"""``el`` for the http://schemas.openxmlformats.org/drawingml/2006/chartDrawing namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/dml_chart_drawing.json``, which a human reviews.

    >>> from docx4j_py.dml.chart_drawing import el
    >>> el.absSizeAnchor()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.chart_drawing import (
    CTAbsSizeAnchor,
    CTConnector,
    CTConnectorNonVisual,
    CTGraphicFrame,
    CTGraphicFrameNonVisual,
    CTGroupShape,
    CTGroupShapeNonVisual,
    CTMarker,
    CTPicture,
    CTPictureNonVisual,
    CTRelSizeAnchor,
    CTShape,
    CTShapeNonVisual,
)
from docx4j_py.dml.main import (
    CTBlipFillProperties,
    CTGroupShapeProperties,
    CTNonVisualConnectorProperties,
    CTNonVisualDrawingProps,
    CTNonVisualDrawingShapeProps,
    CTNonVisualGraphicFrameProperties,
    CTNonVisualGroupDrawingShapeProps,
    CTNonVisualPictureProperties,
    CTPositiveSize2D,
    CTShapeProperties,
    CTShapeStyle,
    CTTextBody,
    CTTransform2D,
)

__NAMESPACE__ = "http://schemas.openxmlformats.org/drawingml/2006/chartDrawing"

def absSizeAnchor(**kwargs: Any) -> CTAbsSizeAnchor:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}absSizeAnchor`` -> :class:`docx4j_py.dml.chart_drawing.CTAbsSizeAnchor`."""
    return CTAbsSizeAnchor(**kwargs)

def blipFill(**kwargs: Any) -> CTBlipFillProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}blipFill`` -> :class:`docx4j_py.dml.main.CTBlipFillProperties`."""
    return CTBlipFillProperties(**kwargs)

def cNvCxnSpPr(**kwargs: Any) -> CTNonVisualConnectorProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvCxnSpPr`` -> :class:`docx4j_py.dml.main.CTNonVisualConnectorProperties`."""
    return CTNonVisualConnectorProperties(**kwargs)

def cNvGraphicFramePr(**kwargs: Any) -> CTNonVisualGraphicFrameProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvGraphicFramePr`` -> :class:`docx4j_py.dml.main.CTNonVisualGraphicFrameProperties`."""
    return CTNonVisualGraphicFrameProperties(**kwargs)

def cNvGrpSpPr(**kwargs: Any) -> CTNonVisualGroupDrawingShapeProps:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvGrpSpPr`` -> :class:`docx4j_py.dml.main.CTNonVisualGroupDrawingShapeProps`."""
    return CTNonVisualGroupDrawingShapeProps(**kwargs)

def cNvPicPr(**kwargs: Any) -> CTNonVisualPictureProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvPicPr`` -> :class:`docx4j_py.dml.main.CTNonVisualPictureProperties`."""
    return CTNonVisualPictureProperties(**kwargs)

def cNvPr(**kwargs: Any) -> CTNonVisualDrawingProps:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingProps`."""
    return CTNonVisualDrawingProps(**kwargs)

def cNvSpPr(**kwargs: Any) -> CTNonVisualDrawingShapeProps:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvSpPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingShapeProps`."""
    return CTNonVisualDrawingShapeProps(**kwargs)

def cxnSp(**kwargs: Any) -> CTConnector:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cxnSp`` -> :class:`docx4j_py.dml.chart_drawing.CTConnector`."""
    return CTConnector(**kwargs)

def ext(**kwargs: Any) -> CTPositiveSize2D:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}ext`` -> :class:`docx4j_py.dml.main.CTPositiveSize2D`."""
    return CTPositiveSize2D(**kwargs)

def from_(**kwargs: Any) -> CTMarker:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}from`` -> :class:`docx4j_py.dml.chart_drawing.CTMarker`."""
    return CTMarker(**kwargs)

def graphicFrame(**kwargs: Any) -> CTGraphicFrame:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}graphicFrame`` -> :class:`docx4j_py.dml.chart_drawing.CTGraphicFrame`."""
    return CTGraphicFrame(**kwargs)

def grpSp(**kwargs: Any) -> CTGroupShape:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}grpSp`` -> :class:`docx4j_py.dml.chart_drawing.CTGroupShape`."""
    return CTGroupShape(**kwargs)

def grpSpPr(**kwargs: Any) -> CTGroupShapeProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}grpSpPr`` -> :class:`docx4j_py.dml.main.CTGroupShapeProperties`."""
    return CTGroupShapeProperties(**kwargs)

def nvCxnSpPr(**kwargs: Any) -> CTConnectorNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvCxnSpPr`` -> :class:`docx4j_py.dml.chart_drawing.CTConnectorNonVisual`."""
    return CTConnectorNonVisual(**kwargs)

def nvGraphicFramePr(**kwargs: Any) -> CTGraphicFrameNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvGraphicFramePr`` -> :class:`docx4j_py.dml.chart_drawing.CTGraphicFrameNonVisual`."""
    return CTGraphicFrameNonVisual(**kwargs)

def nvGrpSpPr(**kwargs: Any) -> CTGroupShapeNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvGrpSpPr`` -> :class:`docx4j_py.dml.chart_drawing.CTGroupShapeNonVisual`."""
    return CTGroupShapeNonVisual(**kwargs)

def nvPicPr(**kwargs: Any) -> CTPictureNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvPicPr`` -> :class:`docx4j_py.dml.chart_drawing.CTPictureNonVisual`."""
    return CTPictureNonVisual(**kwargs)

def nvSpPr(**kwargs: Any) -> CTShapeNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvSpPr`` -> :class:`docx4j_py.dml.chart_drawing.CTShapeNonVisual`."""
    return CTShapeNonVisual(**kwargs)

def pic(**kwargs: Any) -> CTPicture:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}pic`` -> :class:`docx4j_py.dml.chart_drawing.CTPicture`."""
    return CTPicture(**kwargs)

def relSizeAnchor(**kwargs: Any) -> CTRelSizeAnchor:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}relSizeAnchor`` -> :class:`docx4j_py.dml.chart_drawing.CTRelSizeAnchor`."""
    return CTRelSizeAnchor(**kwargs)

def sp(**kwargs: Any) -> CTShape:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}sp`` -> :class:`docx4j_py.dml.chart_drawing.CTShape`."""
    return CTShape(**kwargs)

def spPr(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}spPr`` -> :class:`docx4j_py.dml.main.CTShapeProperties`."""
    return CTShapeProperties(**kwargs)

def style(**kwargs: Any) -> CTShapeStyle:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}style`` -> :class:`docx4j_py.dml.main.CTShapeStyle`."""
    return CTShapeStyle(**kwargs)

def to(**kwargs: Any) -> CTMarker:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}to`` -> :class:`docx4j_py.dml.chart_drawing.CTMarker`."""
    return CTMarker(**kwargs)

def txBody(**kwargs: Any) -> CTTextBody:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}txBody`` -> :class:`docx4j_py.dml.main.CTTextBody`."""
    return CTTextBody(**kwargs)

def xfrm(**kwargs: Any) -> CTTransform2D:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}xfrm`` -> :class:`docx4j_py.dml.main.CTTransform2D`."""
    return CTTransform2D(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}absSizeAnchor": CTAbsSizeAnchor,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}blipFill": CTBlipFillProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvCxnSpPr": CTNonVisualConnectorProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvGraphicFramePr": CTNonVisualGraphicFrameProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvGrpSpPr": CTNonVisualGroupDrawingShapeProps,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvPicPr": CTNonVisualPictureProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvPr": CTNonVisualDrawingProps,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvSpPr": CTNonVisualDrawingShapeProps,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cxnSp": CTConnector,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}ext": CTPositiveSize2D,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}from": CTMarker,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}graphicFrame": CTGraphicFrame,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}grpSp": CTGroupShape,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}grpSpPr": CTGroupShapeProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvCxnSpPr": CTConnectorNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvGraphicFramePr": CTGraphicFrameNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvGrpSpPr": CTGroupShapeNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvPicPr": CTPictureNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvSpPr": CTShapeNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}pic": CTPicture,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}relSizeAnchor": CTRelSizeAnchor,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}sp": CTShape,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}spPr": CTShapeProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}style": CTShapeStyle,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}to": CTMarker,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}txBody": CTTextBody,
    "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}xfrm": CTTransform2D,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "absSizeAnchor": CTAbsSizeAnchor,
    "blipFill": CTBlipFillProperties,
    "cNvCxnSpPr": CTNonVisualConnectorProperties,
    "cNvGraphicFramePr": CTNonVisualGraphicFrameProperties,
    "cNvGrpSpPr": CTNonVisualGroupDrawingShapeProps,
    "cNvPicPr": CTNonVisualPictureProperties,
    "cNvPr": CTNonVisualDrawingProps,
    "cNvSpPr": CTNonVisualDrawingShapeProps,
    "cxnSp": CTConnector,
    "ext": CTPositiveSize2D,
    "from": CTMarker,
    "graphicFrame": CTGraphicFrame,
    "grpSp": CTGroupShape,
    "grpSpPr": CTGroupShapeProperties,
    "nvCxnSpPr": CTConnectorNonVisual,
    "nvGraphicFramePr": CTGraphicFrameNonVisual,
    "nvGrpSpPr": CTGroupShapeNonVisual,
    "nvPicPr": CTPictureNonVisual,
    "nvSpPr": CTShapeNonVisual,
    "pic": CTPicture,
    "relSizeAnchor": CTRelSizeAnchor,
    "sp": CTShape,
    "spPr": CTShapeProperties,
    "style": CTShapeStyle,
    "to": CTMarker,
    "txBody": CTTextBody,
    "xfrm": CTTransform2D,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTAbsSizeAnchor: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}absSizeAnchor",
    CTBlipFillProperties: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}blipFill",
    CTConnector: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cxnSp",
    CTConnectorNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvCxnSpPr",
    CTGraphicFrame: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}graphicFrame",
    CTGraphicFrameNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvGraphicFramePr",
    CTGroupShape: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}grpSp",
    CTGroupShapeNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvGrpSpPr",
    CTGroupShapeProperties: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}grpSpPr",
    CTNonVisualConnectorProperties: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvCxnSpPr",
    CTNonVisualDrawingProps: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvPr",
    CTNonVisualDrawingShapeProps: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvSpPr",
    CTNonVisualGraphicFrameProperties: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvGraphicFramePr",
    CTNonVisualGroupDrawingShapeProps: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvGrpSpPr",
    CTNonVisualPictureProperties: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}cNvPicPr",
    CTPicture: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}pic",
    CTPictureNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvPicPr",
    CTPositiveSize2D: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}ext",
    CTRelSizeAnchor: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}relSizeAnchor",
    CTShape: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}sp",
    CTShapeNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}nvSpPr",
    CTShapeProperties: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}spPr",
    CTShapeStyle: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}style",
    CTTextBody: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}txBody",
    CTTransform2D: "{http://schemas.openxmlformats.org/drawingml/2006/chartDrawing}xfrm",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "absSizeAnchor",
    "blipFill",
    "cNvCxnSpPr",
    "cNvGraphicFramePr",
    "cNvGrpSpPr",
    "cNvPicPr",
    "cNvPr",
    "cNvSpPr",
    "cxnSp",
    "ext",
    "from_",
    "graphicFrame",
    "grpSp",
    "grpSpPr",
    "nvCxnSpPr",
    "nvGraphicFramePr",
    "nvGrpSpPr",
    "nvPicPr",
    "nvSpPr",
    "pic",
    "relSizeAnchor",
    "sp",
    "spPr",
    "style",
    "to",
    "txBody",
    "xfrm",
]
