from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from docx4j_py.dml.chart import (
        Chart,
        ChartSpace,
        CTArea3DChart,
        CTAreaChart,
        CTAreaSer,
        CTAxDataSource,
        CTAxisUnit,
        CTAxPos,
        CTBandFmt,
        CTBandFmts,
        CTBar3DChart,
        CTBarChart,
        CTBarDir,
        CTBarGrouping,
        CTBarSer,
        CTBoolean,
        CTBubbleChart,
        CTBubbleScale,
        CTBubbleSer,
        CTBuiltInUnit,
        CTCatAx,
        CTChart,
        CTChartLines,
        CTChartSpace,
        CTCrossBetween,
        CTCrosses,
        CTCustSplit,
        CTDateAx,
        CTDepthPercent,
        CTDispBlanksAs,
        CTDispUnits,
        CTDispUnitsLbl,
        CTDLbl,
        CTDLblPos,
        CTDLbls,
        CTDouble,
        CTDoughnutChart,
        CTDPt,
        CTDTable,
        CTErrBars,
        CTErrBarType,
        CTErrDir,
        CTErrValType,
        CTExtension,
        CTExtensionList,
        CTExternalData,
        CTFirstSliceAng,
        CTGapAmount,
        CTGrouping,
        CTHeaderFooter,
        CTHoleSize,
        CTHPercent,
        CTLayout,
        CTLayoutMode,
        CTLayoutTarget,
        CTLblAlgn,
        CTLblOffset,
        CTLegend,
        CTLegendEntry,
        CTLegendPos,
        CTLine3DChart,
        CTLineChart,
        CTLineSer,
        CTLogBase,
        CTLvl,
        CTManualLayout,
        CTMarkerSize,
        CTMarkerStyle,
        CTMultiLvlStrData,
        CTMultiLvlStrRef,
        CTNumData,
        CTNumDataSource,
        CTNumFmt,
        CTNumRef,
        CTNumVal,
        CTOfPieChart,
        CTOfPieType,
        CTOrder,
        CTOrientation,
        CTOverlap,
        CTPageMargins,
        CTPageSetup,
        CTPeriod,
        CTPerspective,
        CTPictureFormat,
        CTPictureOptions,
        CTPictureStackUnit,
        CTPie3DChart,
        CTPieChart,
        CTPieSer,
        CTPivotFmt,
        CTPivotFmts,
        CTPivotSource,
        CTPlotArea,
        CTPrintSettings,
        CTProtection,
        CTRadarChart,
        CTRadarSer,
        CTRadarStyle,
        CTRelId,
        CTRotX,
        CTRotY,
        CTScaling,
        CTScatterChart,
        CTScatterSer,
        CTScatterStyle,
        CTSecondPieSize,
        CTSerAx,
        CTSerTx,
        CTSizeRepresents,
        CTSkip,
        CTSplitType,
        CTStockChart,
        CTStrData,
        CTStrRef,
        CTStrVal,
        CTStyle,
        CTSurface,
        CTSurface3DChart,
        CTSurfaceChart,
        CTSurfaceSer,
        CTTextLanguageID,
        CTTickLblPos,
        CTTickMark,
        CTTimeUnit,
        CTTitle,
        CTTrendline,
        CTTrendlineLbl,
        CTTrendlineType,
        CTTx,
        CTUnsignedInt,
        CTUpDownBar,
        CTUpDownBars,
        CTValAx,
        CTView3D,
        Delete,
        ShowBubbleSize,
        ShowCatName,
        ShowLeaderLines,
        ShowLegendKey,
        ShowPercent,
        ShowSerName,
        ShowVal,
        STAxPos,
        STBarDir,
        STBarGrouping,
        STBuiltInUnit,
        STCrossBetween,
        STCrosses,
        STDispBlanksAs,
        STDLblPos,
        STErrBarType,
        STErrDir,
        STErrValType,
        STGrouping,
        STLayoutMode,
        STLayoutTarget,
        STLblAlgn,
        STLegendPos,
        STMarkerStyle,
        STOfPieType,
        STOrientation,
        STPageSetupOrientation,
        STPictureFormat,
        STRadarStyle,
        STScatterStyle,
        STShape,
        STSizeRepresents,
        STSplitType,
        STTickLblPos,
        STTickMark,
        STTimeUnit,
        STTrendlineType,
    )
    from docx4j_py.dml.chart import (
        CTDrawing as ChartCtdrawing,
    )
    from docx4j_py.dml.chart import (
        CTMarker as Ctmarker,
    )
    from docx4j_py.dml.chart import (
        CTShape as Ctshape,
    )
    from docx4j_py.dml.chart_drawing import (
        CTAbsSizeAnchor,
        CTGraphicFrame,
        CTGraphicFrameNonVisual,
        CTRelSizeAnchor,
    )
    from docx4j_py.dml.chart_drawing import (
        CTConnector as ChartCtconnector,
    )
    from docx4j_py.dml.chart_drawing import (
        CTConnectorNonVisual as ChartCtconnectorNonVisual,
    )
    from docx4j_py.dml.chart_drawing import (
        CTDrawing as ChartCtdrawing,
    )
    from docx4j_py.dml.chart_drawing import (
        CTGroupShape as ChartCtgroupShape,
    )
    from docx4j_py.dml.chart_drawing import (
        CTGroupShapeNonVisual as ChartCtgroupShapeNonVisual,
    )
    from docx4j_py.dml.chart_drawing import (
        CTMarker as DrawingCtmarker,
    )
    from docx4j_py.dml.chart_drawing import (
        CTPicture as ChartCtpicture,
    )
    from docx4j_py.dml.chart_drawing import (
        CTPictureNonVisual as ChartDrawingCtpictureNonVisual,
    )
    from docx4j_py.dml.chart_drawing import (
        CTShape as DrawingCtshape,
    )
    from docx4j_py.dml.chart_drawing import (
        CTShapeNonVisual as ChartCtshapeNonVisual,
    )
    from docx4j_py.dml.compatibility import (
        CTCompat,
        LegacyDrawing,
    )
    from docx4j_py.dml.diagram import (
        ColorsDef,
        ColorsDefHdr,
        ColorsDefHdrLst,
        CTAdj,
        CTAdjLst,
        CTAlgorithm,
        CTAnimLvl,
        CTAnimOne,
        CTBulletEnabled,
        CTCategories,
        CTCategory,
        CTChildMax,
        CTChildPref,
        CTChoose,
        CTColors,
        CTColorTransform,
        CTColorTransformHeader,
        CTColorTransformHeaderLst,
        CTConstraint,
        CTConstraints,
        CTCTCategories,
        CTCTCategory,
        CTCTDescription,
        CTCTName,
        CTCTStyleLabel,
        CTCxn,
        CTCxnList,
        CTDataModel,
        CTDescription,
        CTDiagramDefinition,
        CTDiagramDefinitionHeader,
        CTDiagramDefinitionHeaderLst,
        CTDirection,
        CTElemPropSet,
        CTForEach,
        CTHierBranchStyle,
        CTLayoutNode,
        CTLayoutVariablePropertySet,
        CTName,
        CTNumericRule,
        CTOrgChart,
        CTOtherwise,
        CTParameter,
        CTPresentationOf,
        CTPt,
        CTPtList,
        CTRelIds,
        CTResizeHandles,
        CTRules,
        CTSampleData,
        CTSDCategories,
        CTSDCategory,
        CTSDDescription,
        CTSDName,
        CTStyleDefinition,
        CTStyleDefinitionHeader,
        CTStyleDefinitionHeaderLst,
        CTStyleLabel,
        CTTextProps,
        CTWhen,
        DataModel,
        LayoutDef,
        LayoutDefHdr,
        LayoutDefHdrLst,
        RelIds,
        STAlgorithmType,
        STAnimLvlStr,
        STAnimOneStr,
        STArrowheadStyle,
        STAutoTextRotation,
        STAxisType,
        STBendPoint,
        STBoolOperator,
        STBreakpoint,
        STCenterShapeMapping,
        STChildAlignment,
        STChildDirection,
        STChildOrderType,
        STClrAppMethod,
        StConnectorDimension,
        STConnectorPoint,
        STConnectorRouting,
        STConstraintRelationship,
        STConstraintType,
        STContinueDirection,
        STCxnType,
        STDirection,
        STElementType,
        StFallbackDimension,
        STFlowDirection,
        StFunctionArgument,
        STFunctionOperator,
        STFunctionType,
        STGrowDirection,
        STHierarchyAlignment,
        STHierBranchStyle,
        STHorizontalAlignment,
        STHueDir,
        StLayoutShapeType,
        STLinearDirection,
        STNodeHorizontalAlignment,
        STNodeVerticalAlignment,
        STOffset,
        STParameterId,
        STPtType,
        STPyramidAccentPosition,
        STPyramidAccentTextMargin,
        STResizeHandlesStr,
        STRotationPath,
        STSecondaryChildAlignment,
        STSecondaryLinearDirection,
        STStartingElement,
        STTextAlignment,
        STTextAnchorHorizontal,
        STTextAnchorVertical,
        STTextBlockDirection,
        STTextDirection,
        STVerticalAlignment,
        StyleDef,
        StyleDefHdr,
        StyleDefHdrLst,
    )
    from docx4j_py.dml.diagram import (
        CTShape as DiagramCtshape,
    )
    from docx4j_py.dml.diagram import (
        CTTextBody as DiagramCttextBody,
    )
    from docx4j_py.dml.locked_canvas import LockedCanvas
    from docx4j_py.dml.main import (
        Alpha1,
        Alpha2,
        AlphaMod1,
        AlphaMod2,
        BaseStyles,
        Blip,
        Blue1,
        Blue2,
        BlueMod1,
        BlueMod2,
        BlueOff1,
        BlueOff2,
        CTAdjPoint2D,
        CTAdjustHandleList,
        CTAlphaBiLevelEffect,
        CTAlphaCeilingEffect,
        CTAlphaFloorEffect,
        CTAlphaInverseEffect,
        CTAlphaModulateEffect,
        CTAlphaModulateFixedEffect,
        CTAlphaOutsetEffect,
        CTAlphaReplaceEffect,
        CTAngle,
        CTAnimationChartBuildProperties,
        CTAnimationChartElement,
        CTAnimationDgmBuildProperties,
        CTAnimationDgmElement,
        CTAnimationElementChoice,
        CTAnimationGraphicalObjectBuildProperties,
        CTAudioCD,
        CTAudioCDTime,
        CTAudioFile,
        CTBackdrop,
        CTBackgroundFillStyleList,
        CTBackgroundFormatting,
        CtBaseStylesFontScheme,
        CTBaseStylesOverride,
        CtBaseStylesOverrideFontScheme,
        CTBevel,
        CTBiLevelEffect,
        CTBlendEffect,
        CTBlip,
        CTBlipFillProperties,
        CTBlurEffect,
        CTCamera,
        CTCell3D,
        CTClipboardStyleSheet,
        CTColor,
        CTColorChangeEffect,
        CTColorMapping,
        CTColorMappingOverride,
        CTColorMRU,
        CTColorReplaceEffect,
        CTColorScheme,
        CTColorSchemeAndMapping,
        CTColorSchemeList,
        CTComplementTransform,
        CTConnection,
        CTConnectionSite,
        CTConnectionSiteList,
        CTConnectorLocking,
        CTCustomColor,
        CTCustomColorList,
        CTCustomGeometry2D,
        CTDashStop,
        CTDashStopList,
        CTDefaultShapeDefinition,
        CTDuotoneEffect,
        CTEffectContainer,
        CTEffectList,
        CTEffectProperties,
        CTEffectReference,
        CTEffectStyleItem,
        CTEffectStyleList,
        CTEmbeddedWAVAudioFile,
        CTEmptyElement,
        CTFillEffect,
        CTFillOverlayEffect,
        CTFillProperties,
        CTFillStyleList,
        CTFixedPercentage,
        CTFlatText,
        CtFontCollectionFont,
        CTFontReference,
        CTGammaTransform,
        CTGeomGuide,
        CTGeomGuideList,
        CTGeomRect,
        CTGlowEffect,
        CTGradientFillProperties,
        CTGradientStop,
        CTGradientStopList,
        CTGraphicalObjectFrameLocking,
        CTGrayscaleEffect,
        CTGrayscaleTransform,
        CTGroupFillProperties,
        CTGroupLocking,
        CTGroupShapeProperties,
        CTGroupTransform2D,
        CTGvmlConnector,
        CTGvmlConnectorNonVisual,
        CTGvmlGraphicalObjectFrame,
        CTGvmlGraphicFrameNonVisual,
        CTGvmlGroupShape,
        CTGvmlGroupShapeNonVisual,
        CTGvmlPicture,
        CTGvmlPictureNonVisual,
        CTGvmlShape,
        CTGvmlShapeNonVisual,
        CTGvmlTextShape,
        CTGvmlUseShapeRectangle,
        CTHslColor,
        CTHSLEffect,
        CTHyperlink,
        CTInnerShadowEffect,
        CTInverseGammaTransform,
        CTInverseTransform,
        CTLightRig,
        CTLinearShadeProperties,
        CTLineEndProperties,
        CTLineJoinBevel,
        CTLineJoinMiterProperties,
        CTLineJoinRound,
        CTLineProperties,
        CTLineStyleList,
        CTLuminanceEffect,
        CTNoFillProperties,
        CTNonVisualConnectorProperties,
        CTNonVisualDrawingProps,
        CTNonVisualDrawingShapeProps,
        CTNonVisualGraphicFrameProperties,
        CTNonVisualGroupDrawingShapeProps,
        CTNonVisualPictureProperties,
        CTObjectStyleDefaults,
        CTOfficeArtExtension,
        CTOfficeArtExtensionList,
        CTOuterShadowEffect,
        CTPath2D,
        CTPath2DArcTo,
        CTPath2DClose,
        CTPath2DCubicBezierTo,
        CTPath2DLineTo,
        CTPath2DList,
        CTPath2DMoveTo,
        CTPath2DQuadBezierTo,
        CTPathShadeProperties,
        CTPatternFillProperties,
        CTPercentage,
        CTPictureLocking,
        CTPoint2D,
        CTPoint3D,
        CTPolarAdjustHandle,
        CTPositiveFixedAngle,
        CTPositiveFixedPercentage,
        CTPositivePercentage,
        CTPositiveSize2D,
        CTPresetColor,
        CTPresetGeometry2D,
        CTPresetLineDashProperties,
        CTPresetShadowEffect,
        CTPresetTextShape,
        CTQuickTimeFile,
        CTRatio,
        CTReflectionEffect,
        CTRegularTextRun,
        CTRelativeOffsetEffect,
        CTRelativeRect,
        CTScale2D,
        CTScene3D,
        CTSchemeColor,
        CTScRgbColor,
        CTShape3D,
        CTShapeLocking,
        CTShapeProperties,
        CTShapeStyle,
        CTSoftEdgesEffect,
        CTSolidColorFillProperties,
        CTSphereCoords,
        CTSRgbColor,
        CTStretchInfoProperties,
        CTStyleMatrix,
        CTStyleMatrixReference,
        CTSystemColor,
        CTTable,
        CTTableBackgroundStyle,
        CTTableCell,
        CTTableCellBorderStyle,
        CTTableCellProperties,
        CTTableCol,
        CTTableGrid,
        CTTablePartStyle,
        CTTableProperties,
        CTTableRow,
        CTTableStyle,
        CTTableStyleCellStyle,
        CTTableStyleList,
        CTTableStyleTextStyle,
        CTTextAutonumberBullet,
        CTTextBlipBullet,
        CTTextBodyProperties,
        CTTextBulletColorFollowText,
        CTTextBulletSizeFollowText,
        CTTextBulletSizePercent,
        CTTextBulletSizePoint,
        CTTextBulletTypefaceFollowText,
        CTTextCharacterProperties,
        CTTextCharBullet,
        CTTextField,
        CTTextLineBreak,
        CTTextListStyle,
        CTTextNoAutofit,
        CTTextNoBullet,
        CTTextNormalAutofit,
        CTTextParagraph,
        CTTextParagraphProperties,
        CTTextShapeAutofit,
        CTTextSpacing,
        CTTextSpacingPercent,
        CTTextSpacingPoint,
        CTTextTabStop,
        CTTextTabStopList,
        CTTextUnderlineFillFollowText,
        CTTextUnderlineFillGroupWrapper,
        CTTextUnderlineLineFollowText,
        CTThemeableLineStyle,
        CTTileInfoProperties,
        CTTintEffect,
        CTTransform2D,
        CTTransformEffect,
        CTVector3D,
        CTVideoFile,
        CTWholeE2OFormatting,
        CTXYAdjustHandle,
        FontCollection,
        Graphic,
        Graphic1,
        GraphicData,
        Green1,
        Green2,
        GreenMod1,
        GreenMod2,
        GreenOff1,
        GreenOff2,
        HueMod1,
        HueMod2,
        Lum1,
        Lum2,
        LumMod1,
        LumMod2,
        LumOff1,
        LumOff2,
        Red1,
        Red2,
        RedMod1,
        RedMod2,
        RedOff1,
        RedOff2,
        Sat1,
        Sat2,
        SatMod1,
        SatMod2,
        SatOff1,
        SatOff2,
        Shade1,
        Shade2,
        StAnimationChartBuildType,
        StAnimationDgmBuildType,
        STBevelPresetType,
        STBlackWhiteMode,
        STBlendMode,
        STBlipCompression,
        STChartBuildStep,
        STColorSchemeIndex,
        STCompoundLine,
        STDgmBuildStep,
        STEffectContainerType,
        STFontCollectionIndex,
        STLightRigDirection,
        STLightRigType,
        STLineCap,
        STLineEndLength,
        STLineEndType,
        STLineEndWidth,
        STOnOffStyleType,
        STPathFillMode,
        STPathShadeType,
        STPenAlignment,
        STPresetCameraType,
        STPresetColorVal,
        STPresetLineDashVal,
        STPresetMaterialType,
        STPresetPatternVal,
        STPresetShadowVal,
        STRectAlignment,
        STSchemeColorVal,
        STShapeType,
        StSystemColorVal,
        STTextAlignType,
        STTextAnchoringType,
        STTextAutonumberScheme,
        STTextCapsType,
        STTextFontAlignType,
        STTextHorzOverflowType,
        STTextShapeType,
        STTextStrikeType,
        STTextTabAlignType,
        STTextUnderlineType,
        STTextVerticalType,
        STTextVertOverflowType,
        STTextWrappingType,
        STTileFlipMode,
        Tbl,
        TblStyleLst,
        TextFont,
        Theme,
        ThemeManager,
        ThemeOverride,
        Tint1,
        Tint2,
    )
    from docx4j_py.dml.main import (
        CTTextBody as MainCttextBody,
    )
    from docx4j_py.dml.picture import (
        CTPictureNonVisual as PictureCtpictureNonVisual,
    )
    from docx4j_py.dml.picture import (
        Pic,
        Pic1,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTAbsoluteAnchor,
        CTAnchorClientData,
        CTGraphicalObjectFrame,
        CTGraphicalObjectFrameNonVisual,
        CTOneCellAnchor,
        CTTwoCellAnchor,
        From,
        STEditAs,
        To,
        WsDr,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTConnector as SpreadsheetCtconnector,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTConnectorNonVisual as SpreadsheetCtconnectorNonVisual,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTDrawing as SpreadsheetCtdrawing,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTGroupShape as SpreadsheetCtgroupShape,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTGroupShapeNonVisual as SpreadsheetCtgroupShapeNonVisual,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTMarker as SpreadsheetDrawingCtmarker,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTPicture as SpreadsheetCtpicture,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTPictureNonVisual as SpreadsheetDrawingCtpictureNonVisual,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTShape as SpreadsheetDrawingCtshape,
    )
    from docx4j_py.dml.spreadsheet_drawing import (
        CTShapeNonVisual as SpreadsheetCtshapeNonVisual,
    )
    from docx4j_py.dml.wordprocessing_drawing import (
        Anchor,
        Anchor1,
        CTEffectExtent,
        CTPosH,
        CTPosV,
        CTWrapNone,
        CTWrapPath,
        CTWrapSquare,
        CTWrapThrough,
        CTWrapTight,
        CTWrapTopBottom,
        Inline,
        Inline1,
        STAlignH,
        STAlignV,
        STRelFromH,
        STRelFromV,
        STWrapText,
    )

__all__ = [
    "CTArea3DChart",
    "CTAreaChart",
    "CTAreaSer",
    "CTAxDataSource",
    "CTAxPos",
    "CTAxisUnit",
    "CTBandFmt",
    "CTBandFmts",
    "CTBar3DChart",
    "CTBarChart",
    "CTBarDir",
    "CTBarGrouping",
    "CTBarSer",
    "CTBoolean",
    "CTBubbleChart",
    "CTBubbleScale",
    "CTBubbleSer",
    "CTBuiltInUnit",
    "CTCatAx",
    "CTChart",
    "CTChartLines",
    "CTChartSpace",
    "CTCrossBetween",
    "CTCrosses",
    "CTCustSplit",
    "CTDLbl",
    "CTDLblPos",
    "CTDLbls",
    "CTDPt",
    "CTDTable",
    "CTDateAx",
    "CTDepthPercent",
    "CTDispBlanksAs",
    "CTDispUnits",
    "CTDispUnitsLbl",
    "CTDouble",
    "CTDoughnutChart",
    "ChartCtdrawing",
    "CTErrBarType",
    "CTErrBars",
    "CTErrDir",
    "CTErrValType",
    "CTExtension",
    "CTExtensionList",
    "CTExternalData",
    "CTFirstSliceAng",
    "CTGapAmount",
    "CTGrouping",
    "CTHPercent",
    "CTHeaderFooter",
    "CTHoleSize",
    "CTLayout",
    "CTLayoutMode",
    "CTLayoutTarget",
    "CTLblAlgn",
    "CTLblOffset",
    "CTLegend",
    "CTLegendEntry",
    "CTLegendPos",
    "CTLine3DChart",
    "CTLineChart",
    "CTLineSer",
    "CTLogBase",
    "CTLvl",
    "CTManualLayout",
    "Ctmarker",
    "CTMarkerSize",
    "CTMarkerStyle",
    "CTMultiLvlStrData",
    "CTMultiLvlStrRef",
    "CTNumData",
    "CTNumDataSource",
    "CTNumFmt",
    "CTNumRef",
    "CTNumVal",
    "CTOfPieChart",
    "CTOfPieType",
    "CTOrder",
    "CTOrientation",
    "CTOverlap",
    "CTPageMargins",
    "CTPageSetup",
    "CTPeriod",
    "CTPerspective",
    "CTPictureFormat",
    "CTPictureOptions",
    "CTPictureStackUnit",
    "CTPie3DChart",
    "CTPieChart",
    "CTPieSer",
    "CTPivotFmt",
    "CTPivotFmts",
    "CTPivotSource",
    "CTPlotArea",
    "CTPrintSettings",
    "CTProtection",
    "CTRadarChart",
    "CTRadarSer",
    "CTRadarStyle",
    "CTRelId",
    "CTRotX",
    "CTRotY",
    "CTScaling",
    "CTScatterChart",
    "CTScatterSer",
    "CTScatterStyle",
    "CTSecondPieSize",
    "CTSerAx",
    "CTSerTx",
    "Ctshape",
    "CTSizeRepresents",
    "CTSkip",
    "CTSplitType",
    "CTStockChart",
    "CTStrData",
    "CTStrRef",
    "CTStrVal",
    "CTStyle",
    "CTSurface",
    "CTSurface3DChart",
    "CTSurfaceChart",
    "CTSurfaceSer",
    "CTTextLanguageID",
    "CTTickLblPos",
    "CTTickMark",
    "CTTimeUnit",
    "CTTitle",
    "CTTrendline",
    "CTTrendlineLbl",
    "CTTrendlineType",
    "CTTx",
    "CTUnsignedInt",
    "CTUpDownBar",
    "CTUpDownBars",
    "CTValAx",
    "CTView3D",
    "STAxPos",
    "STBarDir",
    "STBarGrouping",
    "STBuiltInUnit",
    "STCrossBetween",
    "STCrosses",
    "STDLblPos",
    "STDispBlanksAs",
    "STErrBarType",
    "STErrDir",
    "STErrValType",
    "STGrouping",
    "STLayoutMode",
    "STLayoutTarget",
    "STLblAlgn",
    "STLegendPos",
    "STMarkerStyle",
    "STOfPieType",
    "STOrientation",
    "STPageSetupOrientation",
    "STPictureFormat",
    "STRadarStyle",
    "STScatterStyle",
    "STShape",
    "STSizeRepresents",
    "STSplitType",
    "STTickLblPos",
    "STTickMark",
    "STTimeUnit",
    "STTrendlineType",
    "Chart",
    "ChartSpace",
    "Delete",
    "ShowBubbleSize",
    "ShowCatName",
    "ShowLeaderLines",
    "ShowLegendKey",
    "ShowPercent",
    "ShowSerName",
    "ShowVal",
    "CTAbsSizeAnchor",
    "ChartCtconnector",
    "ChartCtconnectorNonVisual",
    "ChartCtdrawing",
    "CTGraphicFrame",
    "CTGraphicFrameNonVisual",
    "ChartCtgroupShape",
    "ChartCtgroupShapeNonVisual",
    "DrawingCtmarker",
    "ChartCtpicture",
    "ChartDrawingCtpictureNonVisual",
    "CTRelSizeAnchor",
    "DrawingCtshape",
    "ChartCtshapeNonVisual",
    "CTCompat",
    "LegacyDrawing",
    "CTAdj",
    "CTAdjLst",
    "CTAlgorithm",
    "CTAnimLvl",
    "CTAnimOne",
    "CTBulletEnabled",
    "CTCTCategories",
    "CTCTCategory",
    "CTCTDescription",
    "CTCTName",
    "CTCTStyleLabel",
    "CTCategories",
    "CTCategory",
    "CTChildMax",
    "CTChildPref",
    "CTChoose",
    "CTColorTransform",
    "CTColorTransformHeader",
    "CTColorTransformHeaderLst",
    "CTColors",
    "CTConstraint",
    "CTConstraints",
    "CTCxn",
    "CTCxnList",
    "CTDataModel",
    "CTDescription",
    "CTDiagramDefinition",
    "CTDiagramDefinitionHeader",
    "CTDiagramDefinitionHeaderLst",
    "CTDirection",
    "CTElemPropSet",
    "CTForEach",
    "CTHierBranchStyle",
    "CTLayoutNode",
    "CTLayoutVariablePropertySet",
    "CTName",
    "CTNumericRule",
    "CTOrgChart",
    "CTOtherwise",
    "CTParameter",
    "CTPresentationOf",
    "CTPt",
    "CTPtList",
    "CTRelIds",
    "CTResizeHandles",
    "CTRules",
    "CTSDCategories",
    "CTSDCategory",
    "CTSDDescription",
    "CTSDName",
    "CTSampleData",
    "DiagramCtshape",
    "CTStyleDefinition",
    "CTStyleDefinitionHeader",
    "CTStyleDefinitionHeaderLst",
    "CTStyleLabel",
    "DiagramCttextBody",
    "CTTextProps",
    "CTWhen",
    "STAlgorithmType",
    "STAnimLvlStr",
    "STAnimOneStr",
    "STArrowheadStyle",
    "STAutoTextRotation",
    "STAxisType",
    "STBendPoint",
    "STBoolOperator",
    "STBreakpoint",
    "STCenterShapeMapping",
    "STChildAlignment",
    "STChildDirection",
    "STChildOrderType",
    "STClrAppMethod",
    "STConnectorPoint",
    "STConnectorRouting",
    "STConstraintRelationship",
    "STConstraintType",
    "STContinueDirection",
    "STCxnType",
    "STDirection",
    "STElementType",
    "STFlowDirection",
    "STFunctionOperator",
    "STFunctionType",
    "STGrowDirection",
    "STHierBranchStyle",
    "STHierarchyAlignment",
    "STHorizontalAlignment",
    "STHueDir",
    "STLinearDirection",
    "STNodeHorizontalAlignment",
    "STNodeVerticalAlignment",
    "STOffset",
    "STParameterId",
    "STPtType",
    "STPyramidAccentPosition",
    "STPyramidAccentTextMargin",
    "STResizeHandlesStr",
    "STRotationPath",
    "STSecondaryChildAlignment",
    "STSecondaryLinearDirection",
    "STStartingElement",
    "STTextAlignment",
    "STTextAnchorHorizontal",
    "STTextAnchorVertical",
    "STTextBlockDirection",
    "STTextDirection",
    "STVerticalAlignment",
    "StConnectorDimension",
    "StFallbackDimension",
    "StFunctionArgument",
    "StLayoutShapeType",
    "ColorsDef",
    "ColorsDefHdr",
    "ColorsDefHdrLst",
    "DataModel",
    "LayoutDef",
    "LayoutDefHdr",
    "LayoutDefHdrLst",
    "RelIds",
    "StyleDef",
    "StyleDefHdr",
    "StyleDefHdrLst",
    "LockedCanvas",
    "BaseStyles",
    "CTAdjPoint2D",
    "CTAdjustHandleList",
    "CTAlphaBiLevelEffect",
    "CTAlphaCeilingEffect",
    "CTAlphaFloorEffect",
    "CTAlphaInverseEffect",
    "CTAlphaModulateEffect",
    "CTAlphaModulateFixedEffect",
    "CTAlphaOutsetEffect",
    "CTAlphaReplaceEffect",
    "CTAngle",
    "CTAnimationChartBuildProperties",
    "CTAnimationChartElement",
    "CTAnimationDgmBuildProperties",
    "CTAnimationDgmElement",
    "CTAnimationElementChoice",
    "CTAnimationGraphicalObjectBuildProperties",
    "CTAudioCD",
    "CTAudioCDTime",
    "CTAudioFile",
    "CTBackdrop",
    "CTBackgroundFillStyleList",
    "CTBackgroundFormatting",
    "CTBaseStylesOverride",
    "CTBevel",
    "CTBiLevelEffect",
    "CTBlendEffect",
    "CTBlip",
    "CTBlipFillProperties",
    "CTBlurEffect",
    "CTCamera",
    "CTCell3D",
    "CTClipboardStyleSheet",
    "CTColor",
    "CTColorChangeEffect",
    "CTColorMRU",
    "CTColorMapping",
    "CTColorMappingOverride",
    "CTColorReplaceEffect",
    "CTColorScheme",
    "CTColorSchemeAndMapping",
    "CTColorSchemeList",
    "CTComplementTransform",
    "CTConnection",
    "CTConnectionSite",
    "CTConnectionSiteList",
    "CTConnectorLocking",
    "CTCustomColor",
    "CTCustomColorList",
    "CTCustomGeometry2D",
    "CTDashStop",
    "CTDashStopList",
    "CTDefaultShapeDefinition",
    "CTDuotoneEffect",
    "CTEffectContainer",
    "CTEffectList",
    "CTEffectProperties",
    "CTEffectReference",
    "CTEffectStyleItem",
    "CTEffectStyleList",
    "CTEmbeddedWAVAudioFile",
    "CTEmptyElement",
    "CTFillEffect",
    "CTFillOverlayEffect",
    "CTFillProperties",
    "CTFillStyleList",
    "CTFixedPercentage",
    "CTFlatText",
    "CTFontReference",
    "CTGammaTransform",
    "CTGeomGuide",
    "CTGeomGuideList",
    "CTGeomRect",
    "CTGlowEffect",
    "CTGradientFillProperties",
    "CTGradientStop",
    "CTGradientStopList",
    "CTGraphicalObjectFrameLocking",
    "CTGrayscaleEffect",
    "CTGrayscaleTransform",
    "CTGroupFillProperties",
    "CTGroupLocking",
    "CTGroupShapeProperties",
    "CTGroupTransform2D",
    "CTGvmlConnector",
    "CTGvmlConnectorNonVisual",
    "CTGvmlGraphicFrameNonVisual",
    "CTGvmlGraphicalObjectFrame",
    "CTGvmlGroupShape",
    "CTGvmlGroupShapeNonVisual",
    "CTGvmlPicture",
    "CTGvmlPictureNonVisual",
    "CTGvmlShape",
    "CTGvmlShapeNonVisual",
    "CTGvmlTextShape",
    "CTGvmlUseShapeRectangle",
    "CTHSLEffect",
    "CTHslColor",
    "CTHyperlink",
    "CTInnerShadowEffect",
    "CTInverseGammaTransform",
    "CTInverseTransform",
    "CTLightRig",
    "CTLineEndProperties",
    "CTLineJoinBevel",
    "CTLineJoinMiterProperties",
    "CTLineJoinRound",
    "CTLineProperties",
    "CTLineStyleList",
    "CTLinearShadeProperties",
    "CTLuminanceEffect",
    "CTNoFillProperties",
    "CTNonVisualConnectorProperties",
    "CTNonVisualDrawingProps",
    "CTNonVisualDrawingShapeProps",
    "CTNonVisualGraphicFrameProperties",
    "CTNonVisualGroupDrawingShapeProps",
    "CTNonVisualPictureProperties",
    "CTObjectStyleDefaults",
    "CTOfficeArtExtension",
    "CTOfficeArtExtensionList",
    "CTOuterShadowEffect",
    "CTPath2D",
    "CTPath2DArcTo",
    "CTPath2DClose",
    "CTPath2DCubicBezierTo",
    "CTPath2DLineTo",
    "CTPath2DList",
    "CTPath2DMoveTo",
    "CTPath2DQuadBezierTo",
    "CTPathShadeProperties",
    "CTPatternFillProperties",
    "CTPercentage",
    "CTPictureLocking",
    "CTPoint2D",
    "CTPoint3D",
    "CTPolarAdjustHandle",
    "CTPositiveFixedAngle",
    "CTPositiveFixedPercentage",
    "CTPositivePercentage",
    "CTPositiveSize2D",
    "CTPresetColor",
    "CTPresetGeometry2D",
    "CTPresetLineDashProperties",
    "CTPresetShadowEffect",
    "CTPresetTextShape",
    "CTQuickTimeFile",
    "CTRatio",
    "CTReflectionEffect",
    "CTRegularTextRun",
    "CTRelativeOffsetEffect",
    "CTRelativeRect",
    "CTSRgbColor",
    "CTScRgbColor",
    "CTScale2D",
    "CTScene3D",
    "CTSchemeColor",
    "CTShape3D",
    "CTShapeLocking",
    "CTShapeProperties",
    "CTShapeStyle",
    "CTSoftEdgesEffect",
    "CTSolidColorFillProperties",
    "CTSphereCoords",
    "CTStretchInfoProperties",
    "CTStyleMatrix",
    "CTStyleMatrixReference",
    "CTSystemColor",
    "CTTable",
    "CTTableBackgroundStyle",
    "CTTableCell",
    "CTTableCellBorderStyle",
    "CTTableCellProperties",
    "CTTableCol",
    "CTTableGrid",
    "CTTablePartStyle",
    "CTTableProperties",
    "CTTableRow",
    "CTTableStyle",
    "CTTableStyleCellStyle",
    "CTTableStyleList",
    "CTTableStyleTextStyle",
    "CTTextAutonumberBullet",
    "CTTextBlipBullet",
    "MainCttextBody",
    "CTTextBodyProperties",
    "CTTextBulletColorFollowText",
    "CTTextBulletSizeFollowText",
    "CTTextBulletSizePercent",
    "CTTextBulletSizePoint",
    "CTTextBulletTypefaceFollowText",
    "CTTextCharBullet",
    "CTTextCharacterProperties",
    "CTTextField",
    "CTTextLineBreak",
    "CTTextListStyle",
    "CTTextNoAutofit",
    "CTTextNoBullet",
    "CTTextNormalAutofit",
    "CTTextParagraph",
    "CTTextParagraphProperties",
    "CTTextShapeAutofit",
    "CTTextSpacing",
    "CTTextSpacingPercent",
    "CTTextSpacingPoint",
    "CTTextTabStop",
    "CTTextTabStopList",
    "CTTextUnderlineFillFollowText",
    "CTTextUnderlineFillGroupWrapper",
    "CTTextUnderlineLineFollowText",
    "CTThemeableLineStyle",
    "CTTileInfoProperties",
    "CTTintEffect",
    "CTTransform2D",
    "CTTransformEffect",
    "CTVector3D",
    "CTVideoFile",
    "CTWholeE2OFormatting",
    "CTXYAdjustHandle",
    "CtBaseStylesOverrideFontScheme",
    "CtBaseStylesFontScheme",
    "CtFontCollectionFont",
    "FontCollection",
    "GraphicData",
    "Graphic1",
    "STBevelPresetType",
    "STBlackWhiteMode",
    "STBlendMode",
    "STBlipCompression",
    "STChartBuildStep",
    "STColorSchemeIndex",
    "STCompoundLine",
    "STDgmBuildStep",
    "STEffectContainerType",
    "STFontCollectionIndex",
    "STLightRigDirection",
    "STLightRigType",
    "STLineCap",
    "STLineEndLength",
    "STLineEndType",
    "STLineEndWidth",
    "STOnOffStyleType",
    "STPathFillMode",
    "STPathShadeType",
    "STPenAlignment",
    "STPresetCameraType",
    "STPresetColorVal",
    "STPresetLineDashVal",
    "STPresetMaterialType",
    "STPresetPatternVal",
    "STPresetShadowVal",
    "STRectAlignment",
    "STSchemeColorVal",
    "STShapeType",
    "STTextAlignType",
    "STTextAnchoringType",
    "STTextAutonumberScheme",
    "STTextCapsType",
    "STTextFontAlignType",
    "STTextHorzOverflowType",
    "STTextShapeType",
    "STTextStrikeType",
    "STTextTabAlignType",
    "STTextUnderlineType",
    "STTextVertOverflowType",
    "STTextVerticalType",
    "STTextWrappingType",
    "STTileFlipMode",
    "StAnimationChartBuildType",
    "StAnimationDgmBuildType",
    "StSystemColorVal",
    "TextFont",
    "Theme",
    "AlphaMod1",
    "AlphaMod2",
    "Alpha1",
    "Alpha2",
    "Blip",
    "BlueMod1",
    "BlueMod2",
    "BlueOff1",
    "BlueOff2",
    "Blue1",
    "Blue2",
    "Graphic",
    "GreenMod1",
    "GreenMod2",
    "GreenOff1",
    "GreenOff2",
    "Green1",
    "Green2",
    "HueMod1",
    "HueMod2",
    "LumMod1",
    "LumMod2",
    "LumOff1",
    "LumOff2",
    "Lum1",
    "Lum2",
    "RedMod1",
    "RedMod2",
    "RedOff1",
    "RedOff2",
    "Red1",
    "Red2",
    "SatMod1",
    "SatMod2",
    "SatOff1",
    "SatOff2",
    "Sat1",
    "Sat2",
    "Shade1",
    "Shade2",
    "Tbl",
    "TblStyleLst",
    "ThemeManager",
    "ThemeOverride",
    "Tint1",
    "Tint2",
    "PictureCtpictureNonVisual",
    "Pic1",
    "Pic",
    "CTAbsoluteAnchor",
    "CTAnchorClientData",
    "SpreadsheetCtconnector",
    "SpreadsheetCtconnectorNonVisual",
    "SpreadsheetCtdrawing",
    "CTGraphicalObjectFrame",
    "CTGraphicalObjectFrameNonVisual",
    "SpreadsheetCtgroupShape",
    "SpreadsheetCtgroupShapeNonVisual",
    "SpreadsheetDrawingCtmarker",
    "CTOneCellAnchor",
    "SpreadsheetCtpicture",
    "SpreadsheetDrawingCtpictureNonVisual",
    "SpreadsheetDrawingCtshape",
    "SpreadsheetCtshapeNonVisual",
    "CTTwoCellAnchor",
    "STEditAs",
    "From",
    "To",
    "WsDr",
    "Anchor1",
    "CTEffectExtent",
    "CTPosH",
    "CTPosV",
    "CTWrapNone",
    "CTWrapPath",
    "CTWrapSquare",
    "CTWrapThrough",
    "CTWrapTight",
    "CTWrapTopBottom",
    "Inline1",
    "STAlignH",
    "STAlignV",
    "STRelFromH",
    "STRelFromV",
    "STWrapText",
    "Anchor",
    "Inline",
]

# The re-exports above are resolved on first use, so that importing this
# package never forces a module of it to be imported before the modules it
# depends on.
__lazy_imports__ = {
    "CTArea3DChart": ("docx4j_py.dml.chart", "CTArea3DChart"),
    "CTAreaChart": ("docx4j_py.dml.chart", "CTAreaChart"),
    "CTAreaSer": ("docx4j_py.dml.chart", "CTAreaSer"),
    "CTAxDataSource": ("docx4j_py.dml.chart", "CTAxDataSource"),
    "CTAxPos": ("docx4j_py.dml.chart", "CTAxPos"),
    "CTAxisUnit": ("docx4j_py.dml.chart", "CTAxisUnit"),
    "CTBandFmt": ("docx4j_py.dml.chart", "CTBandFmt"),
    "CTBandFmts": ("docx4j_py.dml.chart", "CTBandFmts"),
    "CTBar3DChart": ("docx4j_py.dml.chart", "CTBar3DChart"),
    "CTBarChart": ("docx4j_py.dml.chart", "CTBarChart"),
    "CTBarDir": ("docx4j_py.dml.chart", "CTBarDir"),
    "CTBarGrouping": ("docx4j_py.dml.chart", "CTBarGrouping"),
    "CTBarSer": ("docx4j_py.dml.chart", "CTBarSer"),
    "CTBoolean": ("docx4j_py.dml.chart", "CTBoolean"),
    "CTBubbleChart": ("docx4j_py.dml.chart", "CTBubbleChart"),
    "CTBubbleScale": ("docx4j_py.dml.chart", "CTBubbleScale"),
    "CTBubbleSer": ("docx4j_py.dml.chart", "CTBubbleSer"),
    "CTBuiltInUnit": ("docx4j_py.dml.chart", "CTBuiltInUnit"),
    "CTCatAx": ("docx4j_py.dml.chart", "CTCatAx"),
    "CTChart": ("docx4j_py.dml.chart", "CTChart"),
    "CTChartLines": ("docx4j_py.dml.chart", "CTChartLines"),
    "CTChartSpace": ("docx4j_py.dml.chart", "CTChartSpace"),
    "CTCrossBetween": ("docx4j_py.dml.chart", "CTCrossBetween"),
    "CTCrosses": ("docx4j_py.dml.chart", "CTCrosses"),
    "CTCustSplit": ("docx4j_py.dml.chart", "CTCustSplit"),
    "CTDLbl": ("docx4j_py.dml.chart", "CTDLbl"),
    "CTDLblPos": ("docx4j_py.dml.chart", "CTDLblPos"),
    "CTDLbls": ("docx4j_py.dml.chart", "CTDLbls"),
    "CTDPt": ("docx4j_py.dml.chart", "CTDPt"),
    "CTDTable": ("docx4j_py.dml.chart", "CTDTable"),
    "CTDateAx": ("docx4j_py.dml.chart", "CTDateAx"),
    "CTDepthPercent": ("docx4j_py.dml.chart", "CTDepthPercent"),
    "CTDispBlanksAs": ("docx4j_py.dml.chart", "CTDispBlanksAs"),
    "CTDispUnits": ("docx4j_py.dml.chart", "CTDispUnits"),
    "CTDispUnitsLbl": ("docx4j_py.dml.chart", "CTDispUnitsLbl"),
    "CTDouble": ("docx4j_py.dml.chart", "CTDouble"),
    "CTDoughnutChart": ("docx4j_py.dml.chart", "CTDoughnutChart"),
    "ChartCtdrawing": ("docx4j_py.dml.chart", "CTDrawing"),
    "CTErrBarType": ("docx4j_py.dml.chart", "CTErrBarType"),
    "CTErrBars": ("docx4j_py.dml.chart", "CTErrBars"),
    "CTErrDir": ("docx4j_py.dml.chart", "CTErrDir"),
    "CTErrValType": ("docx4j_py.dml.chart", "CTErrValType"),
    "CTExtension": ("docx4j_py.dml.chart", "CTExtension"),
    "CTExtensionList": ("docx4j_py.dml.chart", "CTExtensionList"),
    "CTExternalData": ("docx4j_py.dml.chart", "CTExternalData"),
    "CTFirstSliceAng": ("docx4j_py.dml.chart", "CTFirstSliceAng"),
    "CTGapAmount": ("docx4j_py.dml.chart", "CTGapAmount"),
    "CTGrouping": ("docx4j_py.dml.chart", "CTGrouping"),
    "CTHPercent": ("docx4j_py.dml.chart", "CTHPercent"),
    "CTHeaderFooter": ("docx4j_py.dml.chart", "CTHeaderFooter"),
    "CTHoleSize": ("docx4j_py.dml.chart", "CTHoleSize"),
    "CTLayout": ("docx4j_py.dml.chart", "CTLayout"),
    "CTLayoutMode": ("docx4j_py.dml.chart", "CTLayoutMode"),
    "CTLayoutTarget": ("docx4j_py.dml.chart", "CTLayoutTarget"),
    "CTLblAlgn": ("docx4j_py.dml.chart", "CTLblAlgn"),
    "CTLblOffset": ("docx4j_py.dml.chart", "CTLblOffset"),
    "CTLegend": ("docx4j_py.dml.chart", "CTLegend"),
    "CTLegendEntry": ("docx4j_py.dml.chart", "CTLegendEntry"),
    "CTLegendPos": ("docx4j_py.dml.chart", "CTLegendPos"),
    "CTLine3DChart": ("docx4j_py.dml.chart", "CTLine3DChart"),
    "CTLineChart": ("docx4j_py.dml.chart", "CTLineChart"),
    "CTLineSer": ("docx4j_py.dml.chart", "CTLineSer"),
    "CTLogBase": ("docx4j_py.dml.chart", "CTLogBase"),
    "CTLvl": ("docx4j_py.dml.chart", "CTLvl"),
    "CTManualLayout": ("docx4j_py.dml.chart", "CTManualLayout"),
    "Ctmarker": ("docx4j_py.dml.chart", "CTMarker"),
    "CTMarkerSize": ("docx4j_py.dml.chart", "CTMarkerSize"),
    "CTMarkerStyle": ("docx4j_py.dml.chart", "CTMarkerStyle"),
    "CTMultiLvlStrData": ("docx4j_py.dml.chart", "CTMultiLvlStrData"),
    "CTMultiLvlStrRef": ("docx4j_py.dml.chart", "CTMultiLvlStrRef"),
    "CTNumData": ("docx4j_py.dml.chart", "CTNumData"),
    "CTNumDataSource": ("docx4j_py.dml.chart", "CTNumDataSource"),
    "CTNumFmt": ("docx4j_py.dml.chart", "CTNumFmt"),
    "CTNumRef": ("docx4j_py.dml.chart", "CTNumRef"),
    "CTNumVal": ("docx4j_py.dml.chart", "CTNumVal"),
    "CTOfPieChart": ("docx4j_py.dml.chart", "CTOfPieChart"),
    "CTOfPieType": ("docx4j_py.dml.chart", "CTOfPieType"),
    "CTOrder": ("docx4j_py.dml.chart", "CTOrder"),
    "CTOrientation": ("docx4j_py.dml.chart", "CTOrientation"),
    "CTOverlap": ("docx4j_py.dml.chart", "CTOverlap"),
    "CTPageMargins": ("docx4j_py.dml.chart", "CTPageMargins"),
    "CTPageSetup": ("docx4j_py.dml.chart", "CTPageSetup"),
    "CTPeriod": ("docx4j_py.dml.chart", "CTPeriod"),
    "CTPerspective": ("docx4j_py.dml.chart", "CTPerspective"),
    "CTPictureFormat": ("docx4j_py.dml.chart", "CTPictureFormat"),
    "CTPictureOptions": ("docx4j_py.dml.chart", "CTPictureOptions"),
    "CTPictureStackUnit": ("docx4j_py.dml.chart", "CTPictureStackUnit"),
    "CTPie3DChart": ("docx4j_py.dml.chart", "CTPie3DChart"),
    "CTPieChart": ("docx4j_py.dml.chart", "CTPieChart"),
    "CTPieSer": ("docx4j_py.dml.chart", "CTPieSer"),
    "CTPivotFmt": ("docx4j_py.dml.chart", "CTPivotFmt"),
    "CTPivotFmts": ("docx4j_py.dml.chart", "CTPivotFmts"),
    "CTPivotSource": ("docx4j_py.dml.chart", "CTPivotSource"),
    "CTPlotArea": ("docx4j_py.dml.chart", "CTPlotArea"),
    "CTPrintSettings": ("docx4j_py.dml.chart", "CTPrintSettings"),
    "CTProtection": ("docx4j_py.dml.chart", "CTProtection"),
    "CTRadarChart": ("docx4j_py.dml.chart", "CTRadarChart"),
    "CTRadarSer": ("docx4j_py.dml.chart", "CTRadarSer"),
    "CTRadarStyle": ("docx4j_py.dml.chart", "CTRadarStyle"),
    "CTRelId": ("docx4j_py.dml.chart", "CTRelId"),
    "CTRotX": ("docx4j_py.dml.chart", "CTRotX"),
    "CTRotY": ("docx4j_py.dml.chart", "CTRotY"),
    "CTScaling": ("docx4j_py.dml.chart", "CTScaling"),
    "CTScatterChart": ("docx4j_py.dml.chart", "CTScatterChart"),
    "CTScatterSer": ("docx4j_py.dml.chart", "CTScatterSer"),
    "CTScatterStyle": ("docx4j_py.dml.chart", "CTScatterStyle"),
    "CTSecondPieSize": ("docx4j_py.dml.chart", "CTSecondPieSize"),
    "CTSerAx": ("docx4j_py.dml.chart", "CTSerAx"),
    "CTSerTx": ("docx4j_py.dml.chart", "CTSerTx"),
    "Ctshape": ("docx4j_py.dml.chart", "CTShape"),
    "CTSizeRepresents": ("docx4j_py.dml.chart", "CTSizeRepresents"),
    "CTSkip": ("docx4j_py.dml.chart", "CTSkip"),
    "CTSplitType": ("docx4j_py.dml.chart", "CTSplitType"),
    "CTStockChart": ("docx4j_py.dml.chart", "CTStockChart"),
    "CTStrData": ("docx4j_py.dml.chart", "CTStrData"),
    "CTStrRef": ("docx4j_py.dml.chart", "CTStrRef"),
    "CTStrVal": ("docx4j_py.dml.chart", "CTStrVal"),
    "CTStyle": ("docx4j_py.dml.chart", "CTStyle"),
    "CTSurface": ("docx4j_py.dml.chart", "CTSurface"),
    "CTSurface3DChart": ("docx4j_py.dml.chart", "CTSurface3DChart"),
    "CTSurfaceChart": ("docx4j_py.dml.chart", "CTSurfaceChart"),
    "CTSurfaceSer": ("docx4j_py.dml.chart", "CTSurfaceSer"),
    "CTTextLanguageID": ("docx4j_py.dml.chart", "CTTextLanguageID"),
    "CTTickLblPos": ("docx4j_py.dml.chart", "CTTickLblPos"),
    "CTTickMark": ("docx4j_py.dml.chart", "CTTickMark"),
    "CTTimeUnit": ("docx4j_py.dml.chart", "CTTimeUnit"),
    "CTTitle": ("docx4j_py.dml.chart", "CTTitle"),
    "CTTrendline": ("docx4j_py.dml.chart", "CTTrendline"),
    "CTTrendlineLbl": ("docx4j_py.dml.chart", "CTTrendlineLbl"),
    "CTTrendlineType": ("docx4j_py.dml.chart", "CTTrendlineType"),
    "CTTx": ("docx4j_py.dml.chart", "CTTx"),
    "CTUnsignedInt": ("docx4j_py.dml.chart", "CTUnsignedInt"),
    "CTUpDownBar": ("docx4j_py.dml.chart", "CTUpDownBar"),
    "CTUpDownBars": ("docx4j_py.dml.chart", "CTUpDownBars"),
    "CTValAx": ("docx4j_py.dml.chart", "CTValAx"),
    "CTView3D": ("docx4j_py.dml.chart", "CTView3D"),
    "STAxPos": ("docx4j_py.dml.chart", "STAxPos"),
    "STBarDir": ("docx4j_py.dml.chart", "STBarDir"),
    "STBarGrouping": ("docx4j_py.dml.chart", "STBarGrouping"),
    "STBuiltInUnit": ("docx4j_py.dml.chart", "STBuiltInUnit"),
    "STCrossBetween": ("docx4j_py.dml.chart", "STCrossBetween"),
    "STCrosses": ("docx4j_py.dml.chart", "STCrosses"),
    "STDLblPos": ("docx4j_py.dml.chart", "STDLblPos"),
    "STDispBlanksAs": ("docx4j_py.dml.chart", "STDispBlanksAs"),
    "STErrBarType": ("docx4j_py.dml.chart", "STErrBarType"),
    "STErrDir": ("docx4j_py.dml.chart", "STErrDir"),
    "STErrValType": ("docx4j_py.dml.chart", "STErrValType"),
    "STGrouping": ("docx4j_py.dml.chart", "STGrouping"),
    "STLayoutMode": ("docx4j_py.dml.chart", "STLayoutMode"),
    "STLayoutTarget": ("docx4j_py.dml.chart", "STLayoutTarget"),
    "STLblAlgn": ("docx4j_py.dml.chart", "STLblAlgn"),
    "STLegendPos": ("docx4j_py.dml.chart", "STLegendPos"),
    "STMarkerStyle": ("docx4j_py.dml.chart", "STMarkerStyle"),
    "STOfPieType": ("docx4j_py.dml.chart", "STOfPieType"),
    "STOrientation": ("docx4j_py.dml.chart", "STOrientation"),
    "STPageSetupOrientation": ("docx4j_py.dml.chart", "STPageSetupOrientation"),
    "STPictureFormat": ("docx4j_py.dml.chart", "STPictureFormat"),
    "STRadarStyle": ("docx4j_py.dml.chart", "STRadarStyle"),
    "STScatterStyle": ("docx4j_py.dml.chart", "STScatterStyle"),
    "STShape": ("docx4j_py.dml.chart", "STShape"),
    "STSizeRepresents": ("docx4j_py.dml.chart", "STSizeRepresents"),
    "STSplitType": ("docx4j_py.dml.chart", "STSplitType"),
    "STTickLblPos": ("docx4j_py.dml.chart", "STTickLblPos"),
    "STTickMark": ("docx4j_py.dml.chart", "STTickMark"),
    "STTimeUnit": ("docx4j_py.dml.chart", "STTimeUnit"),
    "STTrendlineType": ("docx4j_py.dml.chart", "STTrendlineType"),
    "Chart": ("docx4j_py.dml.chart", "Chart"),
    "ChartSpace": ("docx4j_py.dml.chart", "ChartSpace"),
    "Delete": ("docx4j_py.dml.chart", "Delete"),
    "ShowBubbleSize": ("docx4j_py.dml.chart", "ShowBubbleSize"),
    "ShowCatName": ("docx4j_py.dml.chart", "ShowCatName"),
    "ShowLeaderLines": ("docx4j_py.dml.chart", "ShowLeaderLines"),
    "ShowLegendKey": ("docx4j_py.dml.chart", "ShowLegendKey"),
    "ShowPercent": ("docx4j_py.dml.chart", "ShowPercent"),
    "ShowSerName": ("docx4j_py.dml.chart", "ShowSerName"),
    "ShowVal": ("docx4j_py.dml.chart", "ShowVal"),
    "CTAbsSizeAnchor": ("docx4j_py.dml.chart_drawing", "CTAbsSizeAnchor"),
    "ChartCtconnector": ("docx4j_py.dml.chart_drawing", "CTConnector"),
    "ChartCtconnectorNonVisual": ("docx4j_py.dml.chart_drawing", "CTConnectorNonVisual"),
    "ChartCtdrawing": ("docx4j_py.dml.chart_drawing", "CTDrawing"),
    "CTGraphicFrame": ("docx4j_py.dml.chart_drawing", "CTGraphicFrame"),
    "CTGraphicFrameNonVisual": ("docx4j_py.dml.chart_drawing", "CTGraphicFrameNonVisual"),
    "ChartCtgroupShape": ("docx4j_py.dml.chart_drawing", "CTGroupShape"),
    "ChartCtgroupShapeNonVisual": ("docx4j_py.dml.chart_drawing", "CTGroupShapeNonVisual"),
    "DrawingCtmarker": ("docx4j_py.dml.chart_drawing", "CTMarker"),
    "ChartCtpicture": ("docx4j_py.dml.chart_drawing", "CTPicture"),
    "ChartDrawingCtpictureNonVisual": ("docx4j_py.dml.chart_drawing", "CTPictureNonVisual"),
    "CTRelSizeAnchor": ("docx4j_py.dml.chart_drawing", "CTRelSizeAnchor"),
    "DrawingCtshape": ("docx4j_py.dml.chart_drawing", "CTShape"),
    "ChartCtshapeNonVisual": ("docx4j_py.dml.chart_drawing", "CTShapeNonVisual"),
    "CTCompat": ("docx4j_py.dml.compatibility", "CTCompat"),
    "LegacyDrawing": ("docx4j_py.dml.compatibility", "LegacyDrawing"),
    "CTAdj": ("docx4j_py.dml.diagram", "CTAdj"),
    "CTAdjLst": ("docx4j_py.dml.diagram", "CTAdjLst"),
    "CTAlgorithm": ("docx4j_py.dml.diagram", "CTAlgorithm"),
    "CTAnimLvl": ("docx4j_py.dml.diagram", "CTAnimLvl"),
    "CTAnimOne": ("docx4j_py.dml.diagram", "CTAnimOne"),
    "CTBulletEnabled": ("docx4j_py.dml.diagram", "CTBulletEnabled"),
    "CTCTCategories": ("docx4j_py.dml.diagram", "CTCTCategories"),
    "CTCTCategory": ("docx4j_py.dml.diagram", "CTCTCategory"),
    "CTCTDescription": ("docx4j_py.dml.diagram", "CTCTDescription"),
    "CTCTName": ("docx4j_py.dml.diagram", "CTCTName"),
    "CTCTStyleLabel": ("docx4j_py.dml.diagram", "CTCTStyleLabel"),
    "CTCategories": ("docx4j_py.dml.diagram", "CTCategories"),
    "CTCategory": ("docx4j_py.dml.diagram", "CTCategory"),
    "CTChildMax": ("docx4j_py.dml.diagram", "CTChildMax"),
    "CTChildPref": ("docx4j_py.dml.diagram", "CTChildPref"),
    "CTChoose": ("docx4j_py.dml.diagram", "CTChoose"),
    "CTColorTransform": ("docx4j_py.dml.diagram", "CTColorTransform"),
    "CTColorTransformHeader": ("docx4j_py.dml.diagram", "CTColorTransformHeader"),
    "CTColorTransformHeaderLst": ("docx4j_py.dml.diagram", "CTColorTransformHeaderLst"),
    "CTColors": ("docx4j_py.dml.diagram", "CTColors"),
    "CTConstraint": ("docx4j_py.dml.diagram", "CTConstraint"),
    "CTConstraints": ("docx4j_py.dml.diagram", "CTConstraints"),
    "CTCxn": ("docx4j_py.dml.diagram", "CTCxn"),
    "CTCxnList": ("docx4j_py.dml.diagram", "CTCxnList"),
    "CTDataModel": ("docx4j_py.dml.diagram", "CTDataModel"),
    "CTDescription": ("docx4j_py.dml.diagram", "CTDescription"),
    "CTDiagramDefinition": ("docx4j_py.dml.diagram", "CTDiagramDefinition"),
    "CTDiagramDefinitionHeader": ("docx4j_py.dml.diagram", "CTDiagramDefinitionHeader"),
    "CTDiagramDefinitionHeaderLst": ("docx4j_py.dml.diagram", "CTDiagramDefinitionHeaderLst"),
    "CTDirection": ("docx4j_py.dml.diagram", "CTDirection"),
    "CTElemPropSet": ("docx4j_py.dml.diagram", "CTElemPropSet"),
    "CTForEach": ("docx4j_py.dml.diagram", "CTForEach"),
    "CTHierBranchStyle": ("docx4j_py.dml.diagram", "CTHierBranchStyle"),
    "CTLayoutNode": ("docx4j_py.dml.diagram", "CTLayoutNode"),
    "CTLayoutVariablePropertySet": ("docx4j_py.dml.diagram", "CTLayoutVariablePropertySet"),
    "CTName": ("docx4j_py.dml.diagram", "CTName"),
    "CTNumericRule": ("docx4j_py.dml.diagram", "CTNumericRule"),
    "CTOrgChart": ("docx4j_py.dml.diagram", "CTOrgChart"),
    "CTOtherwise": ("docx4j_py.dml.diagram", "CTOtherwise"),
    "CTParameter": ("docx4j_py.dml.diagram", "CTParameter"),
    "CTPresentationOf": ("docx4j_py.dml.diagram", "CTPresentationOf"),
    "CTPt": ("docx4j_py.dml.diagram", "CTPt"),
    "CTPtList": ("docx4j_py.dml.diagram", "CTPtList"),
    "CTRelIds": ("docx4j_py.dml.diagram", "CTRelIds"),
    "CTResizeHandles": ("docx4j_py.dml.diagram", "CTResizeHandles"),
    "CTRules": ("docx4j_py.dml.diagram", "CTRules"),
    "CTSDCategories": ("docx4j_py.dml.diagram", "CTSDCategories"),
    "CTSDCategory": ("docx4j_py.dml.diagram", "CTSDCategory"),
    "CTSDDescription": ("docx4j_py.dml.diagram", "CTSDDescription"),
    "CTSDName": ("docx4j_py.dml.diagram", "CTSDName"),
    "CTSampleData": ("docx4j_py.dml.diagram", "CTSampleData"),
    "DiagramCtshape": ("docx4j_py.dml.diagram", "CTShape"),
    "CTStyleDefinition": ("docx4j_py.dml.diagram", "CTStyleDefinition"),
    "CTStyleDefinitionHeader": ("docx4j_py.dml.diagram", "CTStyleDefinitionHeader"),
    "CTStyleDefinitionHeaderLst": ("docx4j_py.dml.diagram", "CTStyleDefinitionHeaderLst"),
    "CTStyleLabel": ("docx4j_py.dml.diagram", "CTStyleLabel"),
    "DiagramCttextBody": ("docx4j_py.dml.diagram", "CTTextBody"),
    "CTTextProps": ("docx4j_py.dml.diagram", "CTTextProps"),
    "CTWhen": ("docx4j_py.dml.diagram", "CTWhen"),
    "STAlgorithmType": ("docx4j_py.dml.diagram", "STAlgorithmType"),
    "STAnimLvlStr": ("docx4j_py.dml.diagram", "STAnimLvlStr"),
    "STAnimOneStr": ("docx4j_py.dml.diagram", "STAnimOneStr"),
    "STArrowheadStyle": ("docx4j_py.dml.diagram", "STArrowheadStyle"),
    "STAutoTextRotation": ("docx4j_py.dml.diagram", "STAutoTextRotation"),
    "STAxisType": ("docx4j_py.dml.diagram", "STAxisType"),
    "STBendPoint": ("docx4j_py.dml.diagram", "STBendPoint"),
    "STBoolOperator": ("docx4j_py.dml.diagram", "STBoolOperator"),
    "STBreakpoint": ("docx4j_py.dml.diagram", "STBreakpoint"),
    "STCenterShapeMapping": ("docx4j_py.dml.diagram", "STCenterShapeMapping"),
    "STChildAlignment": ("docx4j_py.dml.diagram", "STChildAlignment"),
    "STChildDirection": ("docx4j_py.dml.diagram", "STChildDirection"),
    "STChildOrderType": ("docx4j_py.dml.diagram", "STChildOrderType"),
    "STClrAppMethod": ("docx4j_py.dml.diagram", "STClrAppMethod"),
    "STConnectorPoint": ("docx4j_py.dml.diagram", "STConnectorPoint"),
    "STConnectorRouting": ("docx4j_py.dml.diagram", "STConnectorRouting"),
    "STConstraintRelationship": ("docx4j_py.dml.diagram", "STConstraintRelationship"),
    "STConstraintType": ("docx4j_py.dml.diagram", "STConstraintType"),
    "STContinueDirection": ("docx4j_py.dml.diagram", "STContinueDirection"),
    "STCxnType": ("docx4j_py.dml.diagram", "STCxnType"),
    "STDirection": ("docx4j_py.dml.diagram", "STDirection"),
    "STElementType": ("docx4j_py.dml.diagram", "STElementType"),
    "STFlowDirection": ("docx4j_py.dml.diagram", "STFlowDirection"),
    "STFunctionOperator": ("docx4j_py.dml.diagram", "STFunctionOperator"),
    "STFunctionType": ("docx4j_py.dml.diagram", "STFunctionType"),
    "STGrowDirection": ("docx4j_py.dml.diagram", "STGrowDirection"),
    "STHierBranchStyle": ("docx4j_py.dml.diagram", "STHierBranchStyle"),
    "STHierarchyAlignment": ("docx4j_py.dml.diagram", "STHierarchyAlignment"),
    "STHorizontalAlignment": ("docx4j_py.dml.diagram", "STHorizontalAlignment"),
    "STHueDir": ("docx4j_py.dml.diagram", "STHueDir"),
    "STLinearDirection": ("docx4j_py.dml.diagram", "STLinearDirection"),
    "STNodeHorizontalAlignment": ("docx4j_py.dml.diagram", "STNodeHorizontalAlignment"),
    "STNodeVerticalAlignment": ("docx4j_py.dml.diagram", "STNodeVerticalAlignment"),
    "STOffset": ("docx4j_py.dml.diagram", "STOffset"),
    "STParameterId": ("docx4j_py.dml.diagram", "STParameterId"),
    "STPtType": ("docx4j_py.dml.diagram", "STPtType"),
    "STPyramidAccentPosition": ("docx4j_py.dml.diagram", "STPyramidAccentPosition"),
    "STPyramidAccentTextMargin": ("docx4j_py.dml.diagram", "STPyramidAccentTextMargin"),
    "STResizeHandlesStr": ("docx4j_py.dml.diagram", "STResizeHandlesStr"),
    "STRotationPath": ("docx4j_py.dml.diagram", "STRotationPath"),
    "STSecondaryChildAlignment": ("docx4j_py.dml.diagram", "STSecondaryChildAlignment"),
    "STSecondaryLinearDirection": ("docx4j_py.dml.diagram", "STSecondaryLinearDirection"),
    "STStartingElement": ("docx4j_py.dml.diagram", "STStartingElement"),
    "STTextAlignment": ("docx4j_py.dml.diagram", "STTextAlignment"),
    "STTextAnchorHorizontal": ("docx4j_py.dml.diagram", "STTextAnchorHorizontal"),
    "STTextAnchorVertical": ("docx4j_py.dml.diagram", "STTextAnchorVertical"),
    "STTextBlockDirection": ("docx4j_py.dml.diagram", "STTextBlockDirection"),
    "STTextDirection": ("docx4j_py.dml.diagram", "STTextDirection"),
    "STVerticalAlignment": ("docx4j_py.dml.diagram", "STVerticalAlignment"),
    "StConnectorDimension": ("docx4j_py.dml.diagram", "StConnectorDimension"),
    "StFallbackDimension": ("docx4j_py.dml.diagram", "StFallbackDimension"),
    "StFunctionArgument": ("docx4j_py.dml.diagram", "StFunctionArgument"),
    "StLayoutShapeType": ("docx4j_py.dml.diagram", "StLayoutShapeType"),
    "ColorsDef": ("docx4j_py.dml.diagram", "ColorsDef"),
    "ColorsDefHdr": ("docx4j_py.dml.diagram", "ColorsDefHdr"),
    "ColorsDefHdrLst": ("docx4j_py.dml.diagram", "ColorsDefHdrLst"),
    "DataModel": ("docx4j_py.dml.diagram", "DataModel"),
    "LayoutDef": ("docx4j_py.dml.diagram", "LayoutDef"),
    "LayoutDefHdr": ("docx4j_py.dml.diagram", "LayoutDefHdr"),
    "LayoutDefHdrLst": ("docx4j_py.dml.diagram", "LayoutDefHdrLst"),
    "RelIds": ("docx4j_py.dml.diagram", "RelIds"),
    "StyleDef": ("docx4j_py.dml.diagram", "StyleDef"),
    "StyleDefHdr": ("docx4j_py.dml.diagram", "StyleDefHdr"),
    "StyleDefHdrLst": ("docx4j_py.dml.diagram", "StyleDefHdrLst"),
    "LockedCanvas": ("docx4j_py.dml.locked_canvas", "LockedCanvas"),
    "BaseStyles": ("docx4j_py.dml.main", "BaseStyles"),
    "CTAdjPoint2D": ("docx4j_py.dml.main", "CTAdjPoint2D"),
    "CTAdjustHandleList": ("docx4j_py.dml.main", "CTAdjustHandleList"),
    "CTAlphaBiLevelEffect": ("docx4j_py.dml.main", "CTAlphaBiLevelEffect"),
    "CTAlphaCeilingEffect": ("docx4j_py.dml.main", "CTAlphaCeilingEffect"),
    "CTAlphaFloorEffect": ("docx4j_py.dml.main", "CTAlphaFloorEffect"),
    "CTAlphaInverseEffect": ("docx4j_py.dml.main", "CTAlphaInverseEffect"),
    "CTAlphaModulateEffect": ("docx4j_py.dml.main", "CTAlphaModulateEffect"),
    "CTAlphaModulateFixedEffect": ("docx4j_py.dml.main", "CTAlphaModulateFixedEffect"),
    "CTAlphaOutsetEffect": ("docx4j_py.dml.main", "CTAlphaOutsetEffect"),
    "CTAlphaReplaceEffect": ("docx4j_py.dml.main", "CTAlphaReplaceEffect"),
    "CTAngle": ("docx4j_py.dml.main", "CTAngle"),
    "CTAnimationChartBuildProperties": ("docx4j_py.dml.main", "CTAnimationChartBuildProperties"),
    "CTAnimationChartElement": ("docx4j_py.dml.main", "CTAnimationChartElement"),
    "CTAnimationDgmBuildProperties": ("docx4j_py.dml.main", "CTAnimationDgmBuildProperties"),
    "CTAnimationDgmElement": ("docx4j_py.dml.main", "CTAnimationDgmElement"),
    "CTAnimationElementChoice": ("docx4j_py.dml.main", "CTAnimationElementChoice"),
    "CTAnimationGraphicalObjectBuildProperties": (
        "docx4j_py.dml.main",
        "CTAnimationGraphicalObjectBuildProperties",
    ),
    "CTAudioCD": ("docx4j_py.dml.main", "CTAudioCD"),
    "CTAudioCDTime": ("docx4j_py.dml.main", "CTAudioCDTime"),
    "CTAudioFile": ("docx4j_py.dml.main", "CTAudioFile"),
    "CTBackdrop": ("docx4j_py.dml.main", "CTBackdrop"),
    "CTBackgroundFillStyleList": ("docx4j_py.dml.main", "CTBackgroundFillStyleList"),
    "CTBackgroundFormatting": ("docx4j_py.dml.main", "CTBackgroundFormatting"),
    "CTBaseStylesOverride": ("docx4j_py.dml.main", "CTBaseStylesOverride"),
    "CTBevel": ("docx4j_py.dml.main", "CTBevel"),
    "CTBiLevelEffect": ("docx4j_py.dml.main", "CTBiLevelEffect"),
    "CTBlendEffect": ("docx4j_py.dml.main", "CTBlendEffect"),
    "CTBlip": ("docx4j_py.dml.main", "CTBlip"),
    "CTBlipFillProperties": ("docx4j_py.dml.main", "CTBlipFillProperties"),
    "CTBlurEffect": ("docx4j_py.dml.main", "CTBlurEffect"),
    "CTCamera": ("docx4j_py.dml.main", "CTCamera"),
    "CTCell3D": ("docx4j_py.dml.main", "CTCell3D"),
    "CTClipboardStyleSheet": ("docx4j_py.dml.main", "CTClipboardStyleSheet"),
    "CTColor": ("docx4j_py.dml.main", "CTColor"),
    "CTColorChangeEffect": ("docx4j_py.dml.main", "CTColorChangeEffect"),
    "CTColorMRU": ("docx4j_py.dml.main", "CTColorMRU"),
    "CTColorMapping": ("docx4j_py.dml.main", "CTColorMapping"),
    "CTColorMappingOverride": ("docx4j_py.dml.main", "CTColorMappingOverride"),
    "CTColorReplaceEffect": ("docx4j_py.dml.main", "CTColorReplaceEffect"),
    "CTColorScheme": ("docx4j_py.dml.main", "CTColorScheme"),
    "CTColorSchemeAndMapping": ("docx4j_py.dml.main", "CTColorSchemeAndMapping"),
    "CTColorSchemeList": ("docx4j_py.dml.main", "CTColorSchemeList"),
    "CTComplementTransform": ("docx4j_py.dml.main", "CTComplementTransform"),
    "CTConnection": ("docx4j_py.dml.main", "CTConnection"),
    "CTConnectionSite": ("docx4j_py.dml.main", "CTConnectionSite"),
    "CTConnectionSiteList": ("docx4j_py.dml.main", "CTConnectionSiteList"),
    "CTConnectorLocking": ("docx4j_py.dml.main", "CTConnectorLocking"),
    "CTCustomColor": ("docx4j_py.dml.main", "CTCustomColor"),
    "CTCustomColorList": ("docx4j_py.dml.main", "CTCustomColorList"),
    "CTCustomGeometry2D": ("docx4j_py.dml.main", "CTCustomGeometry2D"),
    "CTDashStop": ("docx4j_py.dml.main", "CTDashStop"),
    "CTDashStopList": ("docx4j_py.dml.main", "CTDashStopList"),
    "CTDefaultShapeDefinition": ("docx4j_py.dml.main", "CTDefaultShapeDefinition"),
    "CTDuotoneEffect": ("docx4j_py.dml.main", "CTDuotoneEffect"),
    "CTEffectContainer": ("docx4j_py.dml.main", "CTEffectContainer"),
    "CTEffectList": ("docx4j_py.dml.main", "CTEffectList"),
    "CTEffectProperties": ("docx4j_py.dml.main", "CTEffectProperties"),
    "CTEffectReference": ("docx4j_py.dml.main", "CTEffectReference"),
    "CTEffectStyleItem": ("docx4j_py.dml.main", "CTEffectStyleItem"),
    "CTEffectStyleList": ("docx4j_py.dml.main", "CTEffectStyleList"),
    "CTEmbeddedWAVAudioFile": ("docx4j_py.dml.main", "CTEmbeddedWAVAudioFile"),
    "CTEmptyElement": ("docx4j_py.dml.main", "CTEmptyElement"),
    "CTFillEffect": ("docx4j_py.dml.main", "CTFillEffect"),
    "CTFillOverlayEffect": ("docx4j_py.dml.main", "CTFillOverlayEffect"),
    "CTFillProperties": ("docx4j_py.dml.main", "CTFillProperties"),
    "CTFillStyleList": ("docx4j_py.dml.main", "CTFillStyleList"),
    "CTFixedPercentage": ("docx4j_py.dml.main", "CTFixedPercentage"),
    "CTFlatText": ("docx4j_py.dml.main", "CTFlatText"),
    "CTFontReference": ("docx4j_py.dml.main", "CTFontReference"),
    "CTGammaTransform": ("docx4j_py.dml.main", "CTGammaTransform"),
    "CTGeomGuide": ("docx4j_py.dml.main", "CTGeomGuide"),
    "CTGeomGuideList": ("docx4j_py.dml.main", "CTGeomGuideList"),
    "CTGeomRect": ("docx4j_py.dml.main", "CTGeomRect"),
    "CTGlowEffect": ("docx4j_py.dml.main", "CTGlowEffect"),
    "CTGradientFillProperties": ("docx4j_py.dml.main", "CTGradientFillProperties"),
    "CTGradientStop": ("docx4j_py.dml.main", "CTGradientStop"),
    "CTGradientStopList": ("docx4j_py.dml.main", "CTGradientStopList"),
    "CTGraphicalObjectFrameLocking": ("docx4j_py.dml.main", "CTGraphicalObjectFrameLocking"),
    "CTGrayscaleEffect": ("docx4j_py.dml.main", "CTGrayscaleEffect"),
    "CTGrayscaleTransform": ("docx4j_py.dml.main", "CTGrayscaleTransform"),
    "CTGroupFillProperties": ("docx4j_py.dml.main", "CTGroupFillProperties"),
    "CTGroupLocking": ("docx4j_py.dml.main", "CTGroupLocking"),
    "CTGroupShapeProperties": ("docx4j_py.dml.main", "CTGroupShapeProperties"),
    "CTGroupTransform2D": ("docx4j_py.dml.main", "CTGroupTransform2D"),
    "CTGvmlConnector": ("docx4j_py.dml.main", "CTGvmlConnector"),
    "CTGvmlConnectorNonVisual": ("docx4j_py.dml.main", "CTGvmlConnectorNonVisual"),
    "CTGvmlGraphicFrameNonVisual": ("docx4j_py.dml.main", "CTGvmlGraphicFrameNonVisual"),
    "CTGvmlGraphicalObjectFrame": ("docx4j_py.dml.main", "CTGvmlGraphicalObjectFrame"),
    "CTGvmlGroupShape": ("docx4j_py.dml.main", "CTGvmlGroupShape"),
    "CTGvmlGroupShapeNonVisual": ("docx4j_py.dml.main", "CTGvmlGroupShapeNonVisual"),
    "CTGvmlPicture": ("docx4j_py.dml.main", "CTGvmlPicture"),
    "CTGvmlPictureNonVisual": ("docx4j_py.dml.main", "CTGvmlPictureNonVisual"),
    "CTGvmlShape": ("docx4j_py.dml.main", "CTGvmlShape"),
    "CTGvmlShapeNonVisual": ("docx4j_py.dml.main", "CTGvmlShapeNonVisual"),
    "CTGvmlTextShape": ("docx4j_py.dml.main", "CTGvmlTextShape"),
    "CTGvmlUseShapeRectangle": ("docx4j_py.dml.main", "CTGvmlUseShapeRectangle"),
    "CTHSLEffect": ("docx4j_py.dml.main", "CTHSLEffect"),
    "CTHslColor": ("docx4j_py.dml.main", "CTHslColor"),
    "CTHyperlink": ("docx4j_py.dml.main", "CTHyperlink"),
    "CTInnerShadowEffect": ("docx4j_py.dml.main", "CTInnerShadowEffect"),
    "CTInverseGammaTransform": ("docx4j_py.dml.main", "CTInverseGammaTransform"),
    "CTInverseTransform": ("docx4j_py.dml.main", "CTInverseTransform"),
    "CTLightRig": ("docx4j_py.dml.main", "CTLightRig"),
    "CTLineEndProperties": ("docx4j_py.dml.main", "CTLineEndProperties"),
    "CTLineJoinBevel": ("docx4j_py.dml.main", "CTLineJoinBevel"),
    "CTLineJoinMiterProperties": ("docx4j_py.dml.main", "CTLineJoinMiterProperties"),
    "CTLineJoinRound": ("docx4j_py.dml.main", "CTLineJoinRound"),
    "CTLineProperties": ("docx4j_py.dml.main", "CTLineProperties"),
    "CTLineStyleList": ("docx4j_py.dml.main", "CTLineStyleList"),
    "CTLinearShadeProperties": ("docx4j_py.dml.main", "CTLinearShadeProperties"),
    "CTLuminanceEffect": ("docx4j_py.dml.main", "CTLuminanceEffect"),
    "CTNoFillProperties": ("docx4j_py.dml.main", "CTNoFillProperties"),
    "CTNonVisualConnectorProperties": ("docx4j_py.dml.main", "CTNonVisualConnectorProperties"),
    "CTNonVisualDrawingProps": ("docx4j_py.dml.main", "CTNonVisualDrawingProps"),
    "CTNonVisualDrawingShapeProps": ("docx4j_py.dml.main", "CTNonVisualDrawingShapeProps"),
    "CTNonVisualGraphicFrameProperties": (
        "docx4j_py.dml.main",
        "CTNonVisualGraphicFrameProperties",
    ),
    "CTNonVisualGroupDrawingShapeProps": (
        "docx4j_py.dml.main",
        "CTNonVisualGroupDrawingShapeProps",
    ),
    "CTNonVisualPictureProperties": ("docx4j_py.dml.main", "CTNonVisualPictureProperties"),
    "CTObjectStyleDefaults": ("docx4j_py.dml.main", "CTObjectStyleDefaults"),
    "CTOfficeArtExtension": ("docx4j_py.dml.main", "CTOfficeArtExtension"),
    "CTOfficeArtExtensionList": ("docx4j_py.dml.main", "CTOfficeArtExtensionList"),
    "CTOuterShadowEffect": ("docx4j_py.dml.main", "CTOuterShadowEffect"),
    "CTPath2D": ("docx4j_py.dml.main", "CTPath2D"),
    "CTPath2DArcTo": ("docx4j_py.dml.main", "CTPath2DArcTo"),
    "CTPath2DClose": ("docx4j_py.dml.main", "CTPath2DClose"),
    "CTPath2DCubicBezierTo": ("docx4j_py.dml.main", "CTPath2DCubicBezierTo"),
    "CTPath2DLineTo": ("docx4j_py.dml.main", "CTPath2DLineTo"),
    "CTPath2DList": ("docx4j_py.dml.main", "CTPath2DList"),
    "CTPath2DMoveTo": ("docx4j_py.dml.main", "CTPath2DMoveTo"),
    "CTPath2DQuadBezierTo": ("docx4j_py.dml.main", "CTPath2DQuadBezierTo"),
    "CTPathShadeProperties": ("docx4j_py.dml.main", "CTPathShadeProperties"),
    "CTPatternFillProperties": ("docx4j_py.dml.main", "CTPatternFillProperties"),
    "CTPercentage": ("docx4j_py.dml.main", "CTPercentage"),
    "CTPictureLocking": ("docx4j_py.dml.main", "CTPictureLocking"),
    "CTPoint2D": ("docx4j_py.dml.main", "CTPoint2D"),
    "CTPoint3D": ("docx4j_py.dml.main", "CTPoint3D"),
    "CTPolarAdjustHandle": ("docx4j_py.dml.main", "CTPolarAdjustHandle"),
    "CTPositiveFixedAngle": ("docx4j_py.dml.main", "CTPositiveFixedAngle"),
    "CTPositiveFixedPercentage": ("docx4j_py.dml.main", "CTPositiveFixedPercentage"),
    "CTPositivePercentage": ("docx4j_py.dml.main", "CTPositivePercentage"),
    "CTPositiveSize2D": ("docx4j_py.dml.main", "CTPositiveSize2D"),
    "CTPresetColor": ("docx4j_py.dml.main", "CTPresetColor"),
    "CTPresetGeometry2D": ("docx4j_py.dml.main", "CTPresetGeometry2D"),
    "CTPresetLineDashProperties": ("docx4j_py.dml.main", "CTPresetLineDashProperties"),
    "CTPresetShadowEffect": ("docx4j_py.dml.main", "CTPresetShadowEffect"),
    "CTPresetTextShape": ("docx4j_py.dml.main", "CTPresetTextShape"),
    "CTQuickTimeFile": ("docx4j_py.dml.main", "CTQuickTimeFile"),
    "CTRatio": ("docx4j_py.dml.main", "CTRatio"),
    "CTReflectionEffect": ("docx4j_py.dml.main", "CTReflectionEffect"),
    "CTRegularTextRun": ("docx4j_py.dml.main", "CTRegularTextRun"),
    "CTRelativeOffsetEffect": ("docx4j_py.dml.main", "CTRelativeOffsetEffect"),
    "CTRelativeRect": ("docx4j_py.dml.main", "CTRelativeRect"),
    "CTSRgbColor": ("docx4j_py.dml.main", "CTSRgbColor"),
    "CTScRgbColor": ("docx4j_py.dml.main", "CTScRgbColor"),
    "CTScale2D": ("docx4j_py.dml.main", "CTScale2D"),
    "CTScene3D": ("docx4j_py.dml.main", "CTScene3D"),
    "CTSchemeColor": ("docx4j_py.dml.main", "CTSchemeColor"),
    "CTShape3D": ("docx4j_py.dml.main", "CTShape3D"),
    "CTShapeLocking": ("docx4j_py.dml.main", "CTShapeLocking"),
    "CTShapeProperties": ("docx4j_py.dml.main", "CTShapeProperties"),
    "CTShapeStyle": ("docx4j_py.dml.main", "CTShapeStyle"),
    "CTSoftEdgesEffect": ("docx4j_py.dml.main", "CTSoftEdgesEffect"),
    "CTSolidColorFillProperties": ("docx4j_py.dml.main", "CTSolidColorFillProperties"),
    "CTSphereCoords": ("docx4j_py.dml.main", "CTSphereCoords"),
    "CTStretchInfoProperties": ("docx4j_py.dml.main", "CTStretchInfoProperties"),
    "CTStyleMatrix": ("docx4j_py.dml.main", "CTStyleMatrix"),
    "CTStyleMatrixReference": ("docx4j_py.dml.main", "CTStyleMatrixReference"),
    "CTSystemColor": ("docx4j_py.dml.main", "CTSystemColor"),
    "CTTable": ("docx4j_py.dml.main", "CTTable"),
    "CTTableBackgroundStyle": ("docx4j_py.dml.main", "CTTableBackgroundStyle"),
    "CTTableCell": ("docx4j_py.dml.main", "CTTableCell"),
    "CTTableCellBorderStyle": ("docx4j_py.dml.main", "CTTableCellBorderStyle"),
    "CTTableCellProperties": ("docx4j_py.dml.main", "CTTableCellProperties"),
    "CTTableCol": ("docx4j_py.dml.main", "CTTableCol"),
    "CTTableGrid": ("docx4j_py.dml.main", "CTTableGrid"),
    "CTTablePartStyle": ("docx4j_py.dml.main", "CTTablePartStyle"),
    "CTTableProperties": ("docx4j_py.dml.main", "CTTableProperties"),
    "CTTableRow": ("docx4j_py.dml.main", "CTTableRow"),
    "CTTableStyle": ("docx4j_py.dml.main", "CTTableStyle"),
    "CTTableStyleCellStyle": ("docx4j_py.dml.main", "CTTableStyleCellStyle"),
    "CTTableStyleList": ("docx4j_py.dml.main", "CTTableStyleList"),
    "CTTableStyleTextStyle": ("docx4j_py.dml.main", "CTTableStyleTextStyle"),
    "CTTextAutonumberBullet": ("docx4j_py.dml.main", "CTTextAutonumberBullet"),
    "CTTextBlipBullet": ("docx4j_py.dml.main", "CTTextBlipBullet"),
    "MainCttextBody": ("docx4j_py.dml.main", "CTTextBody"),
    "CTTextBodyProperties": ("docx4j_py.dml.main", "CTTextBodyProperties"),
    "CTTextBulletColorFollowText": ("docx4j_py.dml.main", "CTTextBulletColorFollowText"),
    "CTTextBulletSizeFollowText": ("docx4j_py.dml.main", "CTTextBulletSizeFollowText"),
    "CTTextBulletSizePercent": ("docx4j_py.dml.main", "CTTextBulletSizePercent"),
    "CTTextBulletSizePoint": ("docx4j_py.dml.main", "CTTextBulletSizePoint"),
    "CTTextBulletTypefaceFollowText": ("docx4j_py.dml.main", "CTTextBulletTypefaceFollowText"),
    "CTTextCharBullet": ("docx4j_py.dml.main", "CTTextCharBullet"),
    "CTTextCharacterProperties": ("docx4j_py.dml.main", "CTTextCharacterProperties"),
    "CTTextField": ("docx4j_py.dml.main", "CTTextField"),
    "CTTextLineBreak": ("docx4j_py.dml.main", "CTTextLineBreak"),
    "CTTextListStyle": ("docx4j_py.dml.main", "CTTextListStyle"),
    "CTTextNoAutofit": ("docx4j_py.dml.main", "CTTextNoAutofit"),
    "CTTextNoBullet": ("docx4j_py.dml.main", "CTTextNoBullet"),
    "CTTextNormalAutofit": ("docx4j_py.dml.main", "CTTextNormalAutofit"),
    "CTTextParagraph": ("docx4j_py.dml.main", "CTTextParagraph"),
    "CTTextParagraphProperties": ("docx4j_py.dml.main", "CTTextParagraphProperties"),
    "CTTextShapeAutofit": ("docx4j_py.dml.main", "CTTextShapeAutofit"),
    "CTTextSpacing": ("docx4j_py.dml.main", "CTTextSpacing"),
    "CTTextSpacingPercent": ("docx4j_py.dml.main", "CTTextSpacingPercent"),
    "CTTextSpacingPoint": ("docx4j_py.dml.main", "CTTextSpacingPoint"),
    "CTTextTabStop": ("docx4j_py.dml.main", "CTTextTabStop"),
    "CTTextTabStopList": ("docx4j_py.dml.main", "CTTextTabStopList"),
    "CTTextUnderlineFillFollowText": ("docx4j_py.dml.main", "CTTextUnderlineFillFollowText"),
    "CTTextUnderlineFillGroupWrapper": ("docx4j_py.dml.main", "CTTextUnderlineFillGroupWrapper"),
    "CTTextUnderlineLineFollowText": ("docx4j_py.dml.main", "CTTextUnderlineLineFollowText"),
    "CTThemeableLineStyle": ("docx4j_py.dml.main", "CTThemeableLineStyle"),
    "CTTileInfoProperties": ("docx4j_py.dml.main", "CTTileInfoProperties"),
    "CTTintEffect": ("docx4j_py.dml.main", "CTTintEffect"),
    "CTTransform2D": ("docx4j_py.dml.main", "CTTransform2D"),
    "CTTransformEffect": ("docx4j_py.dml.main", "CTTransformEffect"),
    "CTVector3D": ("docx4j_py.dml.main", "CTVector3D"),
    "CTVideoFile": ("docx4j_py.dml.main", "CTVideoFile"),
    "CTWholeE2OFormatting": ("docx4j_py.dml.main", "CTWholeE2OFormatting"),
    "CTXYAdjustHandle": ("docx4j_py.dml.main", "CTXYAdjustHandle"),
    "CtBaseStylesOverrideFontScheme": ("docx4j_py.dml.main", "CtBaseStylesOverrideFontScheme"),
    "CtBaseStylesFontScheme": ("docx4j_py.dml.main", "CtBaseStylesFontScheme"),
    "CtFontCollectionFont": ("docx4j_py.dml.main", "CtFontCollectionFont"),
    "FontCollection": ("docx4j_py.dml.main", "FontCollection"),
    "GraphicData": ("docx4j_py.dml.main", "GraphicData"),
    "Graphic1": ("docx4j_py.dml.main", "Graphic1"),
    "STBevelPresetType": ("docx4j_py.dml.main", "STBevelPresetType"),
    "STBlackWhiteMode": ("docx4j_py.dml.main", "STBlackWhiteMode"),
    "STBlendMode": ("docx4j_py.dml.main", "STBlendMode"),
    "STBlipCompression": ("docx4j_py.dml.main", "STBlipCompression"),
    "STChartBuildStep": ("docx4j_py.dml.main", "STChartBuildStep"),
    "STColorSchemeIndex": ("docx4j_py.dml.main", "STColorSchemeIndex"),
    "STCompoundLine": ("docx4j_py.dml.main", "STCompoundLine"),
    "STDgmBuildStep": ("docx4j_py.dml.main", "STDgmBuildStep"),
    "STEffectContainerType": ("docx4j_py.dml.main", "STEffectContainerType"),
    "STFontCollectionIndex": ("docx4j_py.dml.main", "STFontCollectionIndex"),
    "STLightRigDirection": ("docx4j_py.dml.main", "STLightRigDirection"),
    "STLightRigType": ("docx4j_py.dml.main", "STLightRigType"),
    "STLineCap": ("docx4j_py.dml.main", "STLineCap"),
    "STLineEndLength": ("docx4j_py.dml.main", "STLineEndLength"),
    "STLineEndType": ("docx4j_py.dml.main", "STLineEndType"),
    "STLineEndWidth": ("docx4j_py.dml.main", "STLineEndWidth"),
    "STOnOffStyleType": ("docx4j_py.dml.main", "STOnOffStyleType"),
    "STPathFillMode": ("docx4j_py.dml.main", "STPathFillMode"),
    "STPathShadeType": ("docx4j_py.dml.main", "STPathShadeType"),
    "STPenAlignment": ("docx4j_py.dml.main", "STPenAlignment"),
    "STPresetCameraType": ("docx4j_py.dml.main", "STPresetCameraType"),
    "STPresetColorVal": ("docx4j_py.dml.main", "STPresetColorVal"),
    "STPresetLineDashVal": ("docx4j_py.dml.main", "STPresetLineDashVal"),
    "STPresetMaterialType": ("docx4j_py.dml.main", "STPresetMaterialType"),
    "STPresetPatternVal": ("docx4j_py.dml.main", "STPresetPatternVal"),
    "STPresetShadowVal": ("docx4j_py.dml.main", "STPresetShadowVal"),
    "STRectAlignment": ("docx4j_py.dml.main", "STRectAlignment"),
    "STSchemeColorVal": ("docx4j_py.dml.main", "STSchemeColorVal"),
    "STShapeType": ("docx4j_py.dml.main", "STShapeType"),
    "STTextAlignType": ("docx4j_py.dml.main", "STTextAlignType"),
    "STTextAnchoringType": ("docx4j_py.dml.main", "STTextAnchoringType"),
    "STTextAutonumberScheme": ("docx4j_py.dml.main", "STTextAutonumberScheme"),
    "STTextCapsType": ("docx4j_py.dml.main", "STTextCapsType"),
    "STTextFontAlignType": ("docx4j_py.dml.main", "STTextFontAlignType"),
    "STTextHorzOverflowType": ("docx4j_py.dml.main", "STTextHorzOverflowType"),
    "STTextShapeType": ("docx4j_py.dml.main", "STTextShapeType"),
    "STTextStrikeType": ("docx4j_py.dml.main", "STTextStrikeType"),
    "STTextTabAlignType": ("docx4j_py.dml.main", "STTextTabAlignType"),
    "STTextUnderlineType": ("docx4j_py.dml.main", "STTextUnderlineType"),
    "STTextVertOverflowType": ("docx4j_py.dml.main", "STTextVertOverflowType"),
    "STTextVerticalType": ("docx4j_py.dml.main", "STTextVerticalType"),
    "STTextWrappingType": ("docx4j_py.dml.main", "STTextWrappingType"),
    "STTileFlipMode": ("docx4j_py.dml.main", "STTileFlipMode"),
    "StAnimationChartBuildType": ("docx4j_py.dml.main", "StAnimationChartBuildType"),
    "StAnimationDgmBuildType": ("docx4j_py.dml.main", "StAnimationDgmBuildType"),
    "StSystemColorVal": ("docx4j_py.dml.main", "StSystemColorVal"),
    "TextFont": ("docx4j_py.dml.main", "TextFont"),
    "Theme": ("docx4j_py.dml.main", "Theme"),
    "AlphaMod1": ("docx4j_py.dml.main", "AlphaMod1"),
    "AlphaMod2": ("docx4j_py.dml.main", "AlphaMod2"),
    "Alpha1": ("docx4j_py.dml.main", "Alpha1"),
    "Alpha2": ("docx4j_py.dml.main", "Alpha2"),
    "Blip": ("docx4j_py.dml.main", "Blip"),
    "BlueMod1": ("docx4j_py.dml.main", "BlueMod1"),
    "BlueMod2": ("docx4j_py.dml.main", "BlueMod2"),
    "BlueOff1": ("docx4j_py.dml.main", "BlueOff1"),
    "BlueOff2": ("docx4j_py.dml.main", "BlueOff2"),
    "Blue1": ("docx4j_py.dml.main", "Blue1"),
    "Blue2": ("docx4j_py.dml.main", "Blue2"),
    "Graphic": ("docx4j_py.dml.main", "Graphic"),
    "GreenMod1": ("docx4j_py.dml.main", "GreenMod1"),
    "GreenMod2": ("docx4j_py.dml.main", "GreenMod2"),
    "GreenOff1": ("docx4j_py.dml.main", "GreenOff1"),
    "GreenOff2": ("docx4j_py.dml.main", "GreenOff2"),
    "Green1": ("docx4j_py.dml.main", "Green1"),
    "Green2": ("docx4j_py.dml.main", "Green2"),
    "HueMod1": ("docx4j_py.dml.main", "HueMod1"),
    "HueMod2": ("docx4j_py.dml.main", "HueMod2"),
    "LumMod1": ("docx4j_py.dml.main", "LumMod1"),
    "LumMod2": ("docx4j_py.dml.main", "LumMod2"),
    "LumOff1": ("docx4j_py.dml.main", "LumOff1"),
    "LumOff2": ("docx4j_py.dml.main", "LumOff2"),
    "Lum1": ("docx4j_py.dml.main", "Lum1"),
    "Lum2": ("docx4j_py.dml.main", "Lum2"),
    "RedMod1": ("docx4j_py.dml.main", "RedMod1"),
    "RedMod2": ("docx4j_py.dml.main", "RedMod2"),
    "RedOff1": ("docx4j_py.dml.main", "RedOff1"),
    "RedOff2": ("docx4j_py.dml.main", "RedOff2"),
    "Red1": ("docx4j_py.dml.main", "Red1"),
    "Red2": ("docx4j_py.dml.main", "Red2"),
    "SatMod1": ("docx4j_py.dml.main", "SatMod1"),
    "SatMod2": ("docx4j_py.dml.main", "SatMod2"),
    "SatOff1": ("docx4j_py.dml.main", "SatOff1"),
    "SatOff2": ("docx4j_py.dml.main", "SatOff2"),
    "Sat1": ("docx4j_py.dml.main", "Sat1"),
    "Sat2": ("docx4j_py.dml.main", "Sat2"),
    "Shade1": ("docx4j_py.dml.main", "Shade1"),
    "Shade2": ("docx4j_py.dml.main", "Shade2"),
    "Tbl": ("docx4j_py.dml.main", "Tbl"),
    "TblStyleLst": ("docx4j_py.dml.main", "TblStyleLst"),
    "ThemeManager": ("docx4j_py.dml.main", "ThemeManager"),
    "ThemeOverride": ("docx4j_py.dml.main", "ThemeOverride"),
    "Tint1": ("docx4j_py.dml.main", "Tint1"),
    "Tint2": ("docx4j_py.dml.main", "Tint2"),
    "PictureCtpictureNonVisual": ("docx4j_py.dml.picture", "CTPictureNonVisual"),
    "Pic1": ("docx4j_py.dml.picture", "Pic1"),
    "Pic": ("docx4j_py.dml.picture", "Pic"),
    "CTAbsoluteAnchor": ("docx4j_py.dml.spreadsheet_drawing", "CTAbsoluteAnchor"),
    "CTAnchorClientData": ("docx4j_py.dml.spreadsheet_drawing", "CTAnchorClientData"),
    "SpreadsheetCtconnector": ("docx4j_py.dml.spreadsheet_drawing", "CTConnector"),
    "SpreadsheetCtconnectorNonVisual": (
        "docx4j_py.dml.spreadsheet_drawing",
        "CTConnectorNonVisual",
    ),
    "SpreadsheetCtdrawing": ("docx4j_py.dml.spreadsheet_drawing", "CTDrawing"),
    "CTGraphicalObjectFrame": ("docx4j_py.dml.spreadsheet_drawing", "CTGraphicalObjectFrame"),
    "CTGraphicalObjectFrameNonVisual": (
        "docx4j_py.dml.spreadsheet_drawing",
        "CTGraphicalObjectFrameNonVisual",
    ),
    "SpreadsheetCtgroupShape": ("docx4j_py.dml.spreadsheet_drawing", "CTGroupShape"),
    "SpreadsheetCtgroupShapeNonVisual": (
        "docx4j_py.dml.spreadsheet_drawing",
        "CTGroupShapeNonVisual",
    ),
    "SpreadsheetDrawingCtmarker": ("docx4j_py.dml.spreadsheet_drawing", "CTMarker"),
    "CTOneCellAnchor": ("docx4j_py.dml.spreadsheet_drawing", "CTOneCellAnchor"),
    "SpreadsheetCtpicture": ("docx4j_py.dml.spreadsheet_drawing", "CTPicture"),
    "SpreadsheetDrawingCtpictureNonVisual": (
        "docx4j_py.dml.spreadsheet_drawing",
        "CTPictureNonVisual",
    ),
    "SpreadsheetDrawingCtshape": ("docx4j_py.dml.spreadsheet_drawing", "CTShape"),
    "SpreadsheetCtshapeNonVisual": ("docx4j_py.dml.spreadsheet_drawing", "CTShapeNonVisual"),
    "CTTwoCellAnchor": ("docx4j_py.dml.spreadsheet_drawing", "CTTwoCellAnchor"),
    "STEditAs": ("docx4j_py.dml.spreadsheet_drawing", "STEditAs"),
    "From": ("docx4j_py.dml.spreadsheet_drawing", "From"),
    "To": ("docx4j_py.dml.spreadsheet_drawing", "To"),
    "WsDr": ("docx4j_py.dml.spreadsheet_drawing", "WsDr"),
    "Anchor1": ("docx4j_py.dml.wordprocessing_drawing", "Anchor1"),
    "CTEffectExtent": ("docx4j_py.dml.wordprocessing_drawing", "CTEffectExtent"),
    "CTPosH": ("docx4j_py.dml.wordprocessing_drawing", "CTPosH"),
    "CTPosV": ("docx4j_py.dml.wordprocessing_drawing", "CTPosV"),
    "CTWrapNone": ("docx4j_py.dml.wordprocessing_drawing", "CTWrapNone"),
    "CTWrapPath": ("docx4j_py.dml.wordprocessing_drawing", "CTWrapPath"),
    "CTWrapSquare": ("docx4j_py.dml.wordprocessing_drawing", "CTWrapSquare"),
    "CTWrapThrough": ("docx4j_py.dml.wordprocessing_drawing", "CTWrapThrough"),
    "CTWrapTight": ("docx4j_py.dml.wordprocessing_drawing", "CTWrapTight"),
    "CTWrapTopBottom": ("docx4j_py.dml.wordprocessing_drawing", "CTWrapTopBottom"),
    "Inline1": ("docx4j_py.dml.wordprocessing_drawing", "Inline1"),
    "STAlignH": ("docx4j_py.dml.wordprocessing_drawing", "STAlignH"),
    "STAlignV": ("docx4j_py.dml.wordprocessing_drawing", "STAlignV"),
    "STRelFromH": ("docx4j_py.dml.wordprocessing_drawing", "STRelFromH"),
    "STRelFromV": ("docx4j_py.dml.wordprocessing_drawing", "STRelFromV"),
    "STWrapText": ("docx4j_py.dml.wordprocessing_drawing", "STWrapText"),
    "Anchor": ("docx4j_py.dml.wordprocessing_drawing", "Anchor"),
    "Inline": ("docx4j_py.dml.wordprocessing_drawing", "Inline"),
}


def __getattr__(name: str) -> object:
    """Import a re-exported class on first use."""
    target = __lazy_imports__.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    value = getattr(import_module(target[0]), target[1])
    globals()[name] = value
    return value
