"""``el`` for the http://schemas.openxmlformats.org/markup-compatibility/2006 namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/mce.json``, which a human reviews.

    >>> from docx4j_py.mce import el
    >>> el.AlternateContent()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.mce import (
    AlternateContent as _AlternateContent,
    AlternateContentChoice,
    AlternateContentFallback,
)

__NAMESPACE__ = "http://schemas.openxmlformats.org/markup-compatibility/2006"

def AlternateContent(**kwargs: Any) -> _AlternateContent:
    """``{http://schemas.openxmlformats.org/markup-compatibility/2006}AlternateContent`` -> :class:`docx4j_py.mce.AlternateContent`."""
    return _AlternateContent(**kwargs)

def Choice(**kwargs: Any) -> AlternateContentChoice:
    """``{http://schemas.openxmlformats.org/markup-compatibility/2006}Choice`` -> :class:`docx4j_py.mce.AlternateContentChoice`."""
    return AlternateContentChoice(**kwargs)

def Fallback(**kwargs: Any) -> AlternateContentFallback:
    """``{http://schemas.openxmlformats.org/markup-compatibility/2006}Fallback`` -> :class:`docx4j_py.mce.AlternateContentFallback`."""
    return AlternateContentFallback(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.openxmlformats.org/markup-compatibility/2006}AlternateContent": _AlternateContent,
    "{http://schemas.openxmlformats.org/markup-compatibility/2006}Choice": AlternateContentChoice,
    "{http://schemas.openxmlformats.org/markup-compatibility/2006}Fallback": AlternateContentFallback,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "AlternateContent": _AlternateContent,
    "Choice": AlternateContentChoice,
    "Fallback": AlternateContentFallback,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    _AlternateContent: "{http://schemas.openxmlformats.org/markup-compatibility/2006}AlternateContent",
    AlternateContentChoice: "{http://schemas.openxmlformats.org/markup-compatibility/2006}Choice",
    AlternateContentFallback: "{http://schemas.openxmlformats.org/markup-compatibility/2006}Fallback",
}

__all__ = [
    "AlternateContent",
    "CLASS_TO_QNAME",
    "Choice",
    "ELEMENTS",
    "Fallback",
    "QNAME_TO_CLASS",
]
