from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from docx4j_py.customxml import (
        SchemaLibrary,
        SchemaLibrarySchema,
    )
    from docx4j_py.inkml import (
        ActiveAreaType,
        AffineType,
        AnnotationType,
        AnnotationXMLType,
        BindType,
        BooleanStrType,
        BrushPropertyType,
        BrushRasterOpType,
        BrushTipType,
        BrushType,
        CanvasTransformType,
        CanvasType,
        ChannelPropertiesType,
        ChannelPropertiesTypeChannelProperty,
        ChannelType,
        ChannelTypeOrientation,
        ChannelTypeType,
        ContextType,
        CTMatrix,
        Definitions,
        DefinitionsType,
        Ink,
        InkSourceType,
        InkType,
        IntermittentChannelsType,
        LatencyType,
        MappingType,
        MappingTypeType,
        SampleRateType,
        SourcePropertyType,
        StandardBrushPropertyNameType,
        StandardChannelNameType,
        StandardChannelPropertyNameType,
        StandardUnitsType,
        StStandardLengthUnits,
        StStandardTimeUnits,
        TableType,
        TableTypeApply,
        TableTypeInterpolation,
        TimestampType,
        Trace,
        TraceFormatType,
        TraceGroupType,
        TraceType,
        TraceTypeContinuation,
        TraceTypeType,
        TraceView,
        TraceViewType,
    )
    from docx4j_py.math import (
        CTD,
        CTF,
        CTM,
        CTMC,
        CTMCS,
        CTMR,
        CTR,
        CTRPR,
        CTAcc,
        CTAccPr,
        CTBar,
        CTBarPr,
        CTBorderBox,
        CTBorderBoxPr,
        CTBox,
        CTBoxPr,
        CTBreakBin,
        CTBreakBinSub,
        CTChar,
        CTCtrlPr,
        CTDPr,
        CTEqArr,
        CTEqArrPr,
        CTFPr,
        CTFType,
        CTFunc,
        CTFuncPr,
        CTGroupChr,
        CTGroupChrPr,
        CTInteger2,
        CTInteger255,
        CTLimLoc,
        CTLimLow,
        CTLimLowPr,
        CTLimUpp,
        CTLimUppPr,
        CTManualBreak,
        CTMathPr,
        CTMCPr,
        CTMPr,
        CTNary,
        CTNaryPr,
        CTOMath,
        CTOMathArg,
        CTOMathArgPr,
        CTOMathJc,
        CTOMathPara,
        CTOMathParaPr,
        CTPhant,
        CTPhantPr,
        CTRad,
        CTRadPr,
        CTScript,
        CTShp,
        CTSpacingRule,
        CTSPre,
        CTSPrePr,
        CTSSub,
        CTSSubPr,
        CTSSubSup,
        CTSSubSupPr,
        CTSSup,
        CTSSupPr,
        CTStyle,
        CTText,
        CTTopBot,
        CTUnSignedInteger,
        CTXAlign,
        CTYAlign,
        MathPr,
        OMath,
        OMathPara,
        STBreakBin,
        StBreakBinSub,
        STFType,
        STJc,
        STLimLoc,
        STScript,
        STShp,
        STStyle,
        STTopBot,
    )
    from docx4j_py.math import (
        CTOnOff as MathCtonOff,
    )
    from docx4j_py.math import (
        CTString as MathCtstring,
    )
    from docx4j_py.math import (
        CTTwipsMeasure as MathCttwipsMeasure,
    )
    from docx4j_py.mathml import (
        Abs,
        And,
        Apply,
        ApplyType,
        Arccos,
        Arcsin,
        Arctan,
        Ceiling,
        Ci,
        CiType,
        Cn,
        CnType,
        CnTypeType,
        ConstantType,
        Cos,
        Degree,
        Divide,
        Eq,
        Exp,
        Exponentiale,
        FalseType,
        Floor,
        Geq,
        Gt,
        Leq,
        Ln,
        Log,
        Logbase,
        Lt,
        Math,
        MathType,
        Max,
        Min,
        Minus,
        Neq,
        Not,
        OperatorType,
        Or,
        Pi,
        Plus,
        Power,
        Product,
        QualifierType,
        Quotient,
        Rem,
        Root,
        Sep,
        SepType,
        Sin,
        Sum,
        Tan,
        Times,
        TrueType,
        Xor,
    )
    from docx4j_py.mce import (
        AlternateContent,
        AlternateContentChoice,
        AlternateContentFallback,
    )
    from docx4j_py.relationships import (
        Relationship,
        Relationships,
        RelationshipTargetMode,
    )
    from docx4j_py.shared_types import (
        StOnOff as SharedTypesStOnOff,
    )
    from docx4j_py.shared_types import (
        StXalign as SharedTypesStXalign,
    )
    from docx4j_py.shared_types import (
        StYalign as SharedTypesStYalign,
    )
    from docx4j_py.w14 import (
        Alpha,
        Bevel,
        Checkbox,
        ConflictMode,
        ContentPart,
        CTBevel,
        CTCamera,
        CTDefaultImageDpi,
        CTFillTextEffect,
        CTGlow,
        CTGradientFillProperties,
        CTGradientStop,
        CTGradientStopList,
        CTLigatures,
        CTLightRig,
        CTLinearShadeProperties,
        CTLineJoinMiterProperties,
        CTNumForm,
        CTNumSpacing,
        CTPathShadeProperties,
        CTPercentage,
        CTPositiveFixedPercentage,
        CTPositivePercentage,
        CTPresetLineDashProperties,
        CTProps3D,
        CTReflection,
        CTRelativeRect,
        CTScene3D,
        CTSchemeColor,
        CTSdtCheckbox,
        CTSdtCheckboxSymbol,
        CTShadow,
        CTSolidColorFillProperties,
        CTSphereCoords,
        CTSRgbColor,
        CTStyleSet,
        CTStylisticSets,
        CTTextOutlineEffect,
        CTWordContentPart,
        CTWordContentPartNonVisual,
        CustomXmlConflictDelRangeEnd,
        CustomXmlConflictDelRangeStart,
        DefaultImageDpi,
        DiscardImageEditingData,
        Lum,
        LumMod,
        LumOff,
        Round,
        Sat,
        SatMod,
        SatOff,
        Shade,
        Shadow,
        STBevelPresetType,
        STCompoundLine,
        STLigatures,
        STLightRigDirection,
        STLightRigType,
        STLineCap,
        STNumForm,
        STNumSpacing,
        STPathShadeType,
        STPenAlignment,
        STPresetCameraType,
        STPresetLineDashVal,
        STPresetMaterialType,
        STRectAlignment,
        STSchemeColorVal,
        Tint,
    )
    from docx4j_py.w14 import (
        CTColor as W14Ctcolor,
    )
    from docx4j_py.w14 import (
        CTEmpty as W14Ctempty,
    )
    from docx4j_py.w14 import (
        CTLongHexNumber as W14CtlongHexNumber,
    )
    from docx4j_py.w14 import (
        CTMarkup as W14Ctmarkup,
    )
    from docx4j_py.w14 import (
        CTOnOff as W14CtonOff,
    )
    from docx4j_py.w14 import (
        CTTrackChange as W14CttrackChange,
    )
    from docx4j_py.w14 import (
        DocId as W14DocId,
    )
    from docx4j_py.w14 import (
        StOnOff as W14StOnOff,
    )
    from docx4j_py.w15 import (
        Appearance,
        Collapsed,
        CommentsEx,
        CTCommentEx,
        CTCommentsEx,
        CTPeople,
        CTPerson,
        CTPresenceInfo,
        CTSdtAppearance,
        CTSdtRepeatedSection,
        People,
        RepeatingSection,
        STSdtAppearance,
        WebExtensionCreated,
        WebExtensionLinked,
    )
    from docx4j_py.w15 import (
        BooleanDefaultTrue as W15BooleanDefaultTrue,
    )
    from docx4j_py.w15 import (
        CTColor as W15Ctcolor,
    )
    from docx4j_py.w15 import (
        CTDataBinding as W15CtdataBinding,
    )
    from docx4j_py.w15 import (
        CTDecimalNumber as W15CtdecimalNumber,
    )
    from docx4j_py.w15 import (
        CTEmpty as W15Ctempty,
    )
    from docx4j_py.w15 import (
        CTGuid as W15Ctguid,
    )
    from docx4j_py.w15 import (
        DocId as W15DocId,
    )
    from docx4j_py.wml import (
        RT,
        Body,
        Body1,
        BooleanDefaultFalse,
        Br,
        CalcOnExit,
        CantSplit,
        CellDel,
        CellIns,
        Color,
        CommentRangeEnd,
        CommentRangeStart,
        Comments,
        CommentsComment,
        CTAltChunk,
        CTAltChunkPr,
        CTAttr,
        CTAutoCaption,
        CTAutoCaptions,
        CTBackground,
        CtBdo,
        CtBdoHyperlink,
        CTBookmark,
        CTBookmarkRange,
        CTBorder,
        CTCalendarType,
        CTCaption,
        CTCaptions,
        CTCellMergeTrackChange,
        CTCharacterSpacing,
        CTCnf,
        CTColorSchemeMapping,
        CTColumn,
        CTColumns,
        CTCompat,
        CTCompatSetting,
        CTControl,
        CTCustomXmlBlock,
        CTCustomXmlCell,
        CTCustomXmlPr,
        CtCustomXmlPrPlaceholder,
        CTCustomXmlRow,
        CTCustomXmlRun,
        CtCustomXmlRunHyperlink,
        CtDir,
        CtDirHyperlink,
        CTDiv,
        CTDivBdr,
        CTDivs,
        CTDocGrid,
        CTDocPart,
        CTDocPartBehavior,
        CTDocPartBehaviors,
        CTDocPartCategory,
        CtDocPartCategoryName,
        CTDocPartGallery,
        CTDocPartName,
        CTDocPartPr,
        CtDocPartPrDescription,
        CtDocPartPrStyle,
        CTDocParts,
        CTDocPartType,
        CTDocPartTypes,
        CTDocProtect,
        CTDocRsids,
        CTDocType,
        CTDocVar,
        CTDocVars,
        CTEastAsianLayout,
        CTEdnDocProps,
        CTEdnPos,
        CTEdnProps,
        CtEdnPropsNumStart,
        CTEm,
        CTEndnotes,
        CTFFCheckBox,
        CTFFData,
        CTFFDDList,
        CtFfddlistDefault,
        CtFfddlistListEntry,
        CtFfddlistResult,
        CTFFHelpText,
        CTFFName,
        CTFFStatusText,
        CTFFTextInput,
        CtFftextInputDefault,
        CtFftextInputFormat,
        CtFftextInputMaxLength,
        CTFFTextType,
        CTFitText,
        CtFontFamilyVal,
        CTFootnotes,
        CTFrame,
        CTFrameLayout,
        CtFrameName,
        CTFramePr,
        CTFrameScrollbar,
        CTFrameset,
        CTFramesetSplitbar,
        CtFramesetSplitbarColor,
        CtFramesetSz,
        CtFrameSz,
        CTFtnDocProps,
        CTFtnEdn,
        CTFtnEdnRef,
        CTFtnEdnSepRef,
        CTFtnPos,
        CTFtnProps,
        CtFtnPropsNumStart,
        CTHeight,
        CTKinsoku,
        CTLang,
        CTLanguage,
        CTLineNumber,
        CTLock,
        CtLvlLegacy,
        CtLvlLvlPicBulletId,
        CtLvlLvlRestart,
        CtLvlLvlText,
        CtLvlPStyle,
        CtLvlStart,
        CtLvlSuff,
        CtLvlSuffVal,
        CTMacroName,
        CTMailMerge,
        CtMailMergeActiveRecord,
        CtMailMergeAddressFieldName,
        CtMailMergeCheckErrors,
        CtMailMergeConnectString,
        CTMailMergeDataType,
        CTMailMergeDest,
        CTMailMergeDocType,
        CtMailMergeMailSubject,
        CTMailMergeOdsoFMDFieldType,
        CtMailMergeQuery,
        CTMailMergeSourceType,
        CTMarkupRange,
        CTMathRunTrackChange,
        CtMathRunTrackChangeAnnotationRef,
        CtMathRunTrackChangeCommentReference,
        CtMathRunTrackChangeContinuationSeparator,
        CtMathRunTrackChangeCr,
        CtMathRunTrackChangeDayLong,
        CtMathRunTrackChangeDayShort,
        CtMathRunTrackChangeEndnoteRef,
        CtMathRunTrackChangeFootnoteRef,
        CtMathRunTrackChangeLastRenderedPageBreak,
        CtMathRunTrackChangeMonthLong,
        CtMathRunTrackChangeMonthShort,
        CtMathRunTrackChangeNoBreakHyphen,
        CtMathRunTrackChangePgNum,
        CtMathRunTrackChangePtab,
        CtMathRunTrackChangeSeparator,
        CtMathRunTrackChangeSoftHyphen,
        CtMathRunTrackChangeSym,
        CtMathRunTrackChangeTab,
        CtMathRunTrackChangeYearLong,
        CtMathRunTrackChangeYearShort,
        CTMoveBookmark,
        CTMoveFromRangeEnd,
        CTMoveToRangeEnd,
        CTNumRestart,
        CTObject,
        CTOdso,
        CtOdsoColDelim,
        CTOdsoFieldMapData,
        CtOdsoFieldMapDataColumn,
        CtOdsoFieldMapDataMappedName,
        CtOdsoFieldMapDataName,
        CtOdsoTable,
        CtOdsoUdl,
        CTPageNumber,
        CTPaperSource,
        CTParaRPrOriginal,
        CTPerm,
        CtPermStartEdGrp,
        CTPictureBase,
        CTPixelsMeasure,
        CTPlaceholder,
        CtPlaceholderDocPart,
        CtPprBaseDivId,
        CtPprBaseInd,
        CtPprBaseNumPr,
        CtPprBaseNumPrIlvl,
        CtPprBaseNumPrNumId,
        CtPprBaseOutlineLvl,
        CtPprBasePBdr,
        CtPprBasePStyle,
        CtPprBaseSpacing,
        CtPprBaseTextAlignment,
        CtPprBaseTextAlignmentVal,
        CTPPrChange,
        CTPPrDefault,
        CTProof,
        CtRAnnotationRef,
        CtRCommentReference,
        CtRContinuationSeparator,
        CtRCr,
        CtRDayLong,
        CtRDayShort,
        CTReadingModeInkLockDown,
        CTRecipientData,
        CtRecipientDataColumn,
        CTRecipients,
        CtREndnoteRef,
        CtRFootnoteRef,
        CtRLastRenderedPageBreak,
        CtRMonthLong,
        CtRMonthShort,
        CtRNoBreakHyphen,
        CtRPgNum,
        CTRPrChange,
        CtRprChangeRPr,
        CTRPrDefault,
        CtRPtab,
        CtRSeparator,
        CtRSoftHyphen,
        CtRSym,
        CtRTab,
        CTRuby,
        CTRubyAlign,
        CTRubyContent,
        CTRubyPr,
        CtRYearLong,
        CtRYearShort,
        CTSaveThroughXslt,
        CTSdtCell,
        CTSdtComboBox,
        CTSdtContentCell,
        CTSdtContentRow,
        CTSdtContentRun,
        CtSdtContentRunHyperlink,
        CTSdtDate,
        CtSdtDateDateFormat,
        CTSdtDateMappingType,
        CTSdtDocPart,
        CtSdtDocPartDocPartCategory,
        CtSdtDocPartDocPartGallery,
        CTSdtDropDownList,
        CTSdtEndPr,
        CTSdtListItem,
        CtSdtPrAlias,
        CtSdtPrBibliography,
        CtSdtPrCitation,
        CtSdtPrEquation,
        CtSdtPrGroup,
        CtSdtPrPicture,
        CtSdtPrRichText,
        CTSdtRow,
        CTSdtText,
        CtSectPrBasePgBorders,
        CtSectPrBasePgMar,
        CtSectPrBasePgSz,
        CtSectPrBaseType,
        CtSectPrBaseTypeVal,
        CTSectPrChange,
        CtSectPrPgBorders,
        CtSectPrPgMar,
        CtSectPrPgSz,
        CtSectPrType,
        CtSectPrTypeVal,
        CTSettings,
        CtSettingsAttachedSchema,
        CtSettingsBookFoldPrintingSheets,
        CtSettingsClickAndTypeStyle,
        CtSettingsConsecutiveHyphenLimit,
        CtSettingsDecimalSymbol,
        CtSettingsDefaultTableStyle,
        CtSettingsDisplayHorizontalDrawingGridEvery,
        CtSettingsDisplayVerticalDrawingGridEvery,
        CtSettingsForceUpgrade,
        CtSettingsListSeparator,
        CtSettingsSummaryLength,
        CTShapeDefaults,
        CTShd,
        CTShortHexNumber,
        CTSignedHpsMeasure,
        CTSignedTwipsMeasure,
        CTSimpleField,
        CtSimpleFieldHyperlink,
        CTSmartTagPr,
        CTSmartTagRun,
        CtSmartTagRunHyperlink,
        CTSmartTagType,
        CTStylePaneFilter,
        CTTabStop,
        CTTargetScreenSz,
        CTTblCellMar,
        CTTblGridChange,
        CTTblLayoutType,
        CTTblLook,
        CTTblOverlap,
        CTTblPPr,
        CTTblPrBase,
        CtTblPrBaseTblStyle,
        CtTblPrBaseTblStyleColBandSize,
        CtTblPrBaseTblStyleRowBandSize,
        CTTblPrChange,
        CTTblPrEx,
        CTTblPrExBase,
        CTTblPrExChange,
        CTTblStylePr,
        CtTblWidthType,
        CTTcPrChange,
        CtTcPrInnerGridSpan,
        CtTcPrInnerHMerge,
        CtTcPrInnerHMergeVal,
        CtTcPrInnerTcBorders,
        CtTcPrInnerVMerge,
        CtTcPrInnerVMergeVal,
        CTTextboxTightWrap,
        CtTextDirectionVal,
        CTTextEffect,
        CTTextScale,
        CTTrackChangeNumbering,
        CTTrackChangeRange,
        CTTrackChangesView,
        CTTrPrBase,
        CtTrPrBaseDivId,
        CtTrPrBaseGridAfter,
        CtTrPrBaseGridBefore,
        CTTrPrChange,
        CTTxbxContent,
        CTUcharHexNumber,
        CTVerticalAlignRun,
        CTVerticalJc,
        CTView,
        CTWebSettings,
        CtWebSettingsEncoding,
        CtWebSettingsPixelsPerInch,
        CTWriteProtection,
        CTWritingStyle,
        CTZoom,
        CustomXmlDelRangeEnd1,
        CustomXmlDelRangeEnd2,
        CustomXmlDelRangeStart1,
        CustomXmlDelRangeStart2,
        CustomXmlInsRangeEnd1,
        CustomXmlInsRangeEnd2,
        CustomXmlInsRangeStart1,
        CustomXmlInsRangeStart2,
        CustomXmlMoveFromRangeEnd1,
        CustomXmlMoveFromRangeEnd2,
        CustomXmlMoveFromRangeStart1,
        CustomXmlMoveFromRangeStart2,
        CustomXmlMoveToRangeEnd1,
        CustomXmlMoveToRangeEnd2,
        CustomXmlMoveToRangeStart1,
        CustomXmlMoveToRangeStart2,
        Del1,
        Del2,
        DelInstrText,
        DelText,
        DocDefaults,
        DocDefaultsPPrDefault,
        DocDefaultsRPrDefault,
        DocPartList,
        DocPartObj,
        Document,
        Drawing,
        Enabled,
        EndnoteReference1,
        EndnoteReference2,
        Endnotes,
        EntryMacro,
        ExitMacro,
        FldChar,
        FontFamily,
        FontPanose,
        FontPitch,
        FontRel,
        Fonts,
        FontsFont,
        FontsFontAltName,
        FontSig,
        FooterReference,
        FootnoteReference1,
        FootnoteReference2,
        Footnotes,
        Ftr,
        GlossaryDocument,
        Hdr,
        HdrFtrRef,
        HeaderReference,
        Hidden,
        Highlight,
        HighlightVal,
        HpsMeasure,
        Id,
        Ins1,
        Ins2,
        InstrText,
        Jc,
        JcEnumeration,
        Lvl,
        MoveFrom1,
        MoveFrom2,
        MoveFromRangeStart1,
        MoveFromRangeStart2,
        MoveTo1,
        MoveTo2,
        MoveToRangeStart1,
        MoveToRangeStart2,
        NumberFormat,
        Numbering,
        NumberingAbstractNum,
        NumberingAbstractNumMultiLevelType,
        NumberingAbstractNumMultiLevelTypeVal,
        NumberingAbstractNumName,
        NumberingAbstractNumNumStyleLink,
        NumberingAbstractNumStyleLink,
        NumberingNum,
        NumberingNumAbstractNumId,
        NumberingNumIdMacAtCleanup,
        NumberingNumLvlOverride,
        NumberingNumLvlOverrideStartOverride,
        NumberingNumPicBullet,
        NumFmt,
        P,
        ParaRPr,
        ParaRPrChange,
        PHyperlink,
        Pict,
        PPr,
        PPrBase,
        ProofErr,
        ProofErrType,
        R,
        RangePermissionStart,
        RAnnotationRef,
        RCommentReference,
        RContinuationSeparator,
        RCr,
        RDayLong,
        RDayShort,
        RDelInstrText,
        Recipients,
        REndnoteRef,
        RFonts,
        RFootnoteRef,
        RInstrText,
        RLastRenderedPageBreak,
        RMonthLong,
        RMonthShort,
        RNoBreakHyphen,
        RPgNum,
        RPr,
        RPtab,
        RSeparator,
        RSoftHyphen,
        RStyle,
        RSym,
        RTab,
        RunDel,
        RunIns,
        RunTrackChange,
        RYearLong,
        RYearShort,
        SdtBlock,
        SdtContentBlock,
        SdtPr,
        SdtRun,
        SectPr,
        SectPrBase,
        Settings,
        ShowingPlcHdr,
        STAlgClass,
        STAlgType,
        STAnnotationVMerge,
        STBorder,
        STBrClear,
        STBrType,
        STCalendarType,
        STCaptionPos,
        STChapterSep,
        STCharacterSpacing,
        STColorSchemeIndex,
        STCombineBrackets,
        STCryptProv,
        STDirection,
        STDisplacedByCustomXml,
        STDocGrid,
        STDocPartBehavior,
        STDocPartGallery,
        STDocPartType,
        STDocProtect,
        STDocType,
        STDropCap,
        STEdnPos,
        STEm,
        STFFTextType,
        STFldCharType,
        STFrameLayout,
        STFrameScrollbar,
        STFtnEdn,
        STFtnPos,
        STHAnchor,
        STHeightRule,
        STHexColorAuto,
        STHint,
        STInfoTextType,
        STLineNumberRestart,
        STLineSpacingRule,
        STLock,
        STMailMergeDataType,
        STMailMergeDest,
        STMailMergeDocType,
        STMailMergeOdsoFMDFieldType,
        STMailMergeSourceType,
        STPageBorderDisplay,
        STPageBorderOffset,
        STPageBorderZOrder,
        STPageOrientation,
        STPitch,
        STProof,
        STPTabAlignment,
        STPTabLeader,
        STPTabRelativeTo,
        STRestartNumber,
        STRubyAlign,
        STSdtDateMappingType,
        STShd,
        STTabJc,
        STTabTlc,
        StTargetScreenSz,
        STTblLayoutType,
        STTblOverlap,
        STTblStyleOverrideType,
        STTextboxTightWrap,
        STTextEffect,
        STTheme,
        STThemeColor,
        STVAnchor,
        STVerticalAlignRun,
        STVerticalJc,
        STView,
        STWrap,
        Style,
        StyleAliases,
        StyleBasedOn,
        StyleLink,
        StyleName,
        StyleNext,
        Styles,
        StylesLatentStyles,
        StylesLatentStylesLsdException,
        StyleType,
        StyleUiPriority,
        STZoom,
        T,
        Tabs,
        Tag,
        Tbl,
        TblBorders,
        TblCellSpacing,
        TblGrid,
        TblGridBase,
        TblGridCol,
        TblHeader,
        TblPr,
        TblWidth,
        Tc,
        TcMar,
        TcPr,
        TcPrInner,
        Temporary,
        Text,
        TextDirection,
        Tr,
        TrPr,
        TxbxContent,
        U,
        UnderlineEnumeration,
        WAfter,
        WBefore,
        WebSettings,
    )
    from docx4j_py.wml import (
        BooleanDefaultTrue as WmlBooleanDefaultTrue,
    )
    from docx4j_py.wml import (
        CTColor as WmlCtcolor,
    )
    from docx4j_py.wml import (
        CTDataBinding as WmlCtdataBinding,
    )
    from docx4j_py.wml import (
        CTDecimalNumber as WmlCtdecimalNumber,
    )
    from docx4j_py.wml import (
        CTEmpty as WmlCtempty,
    )
    from docx4j_py.wml import (
        CTGuid as WmlCtguid,
    )
    from docx4j_py.wml import (
        CTLongHexNumber as WmlCtlongHexNumber,
    )
    from docx4j_py.wml import (
        CTMarkup as WmlCtmarkup,
    )
    from docx4j_py.wml import (
        CTRel as WmlCtrel,
    )
    from docx4j_py.wml import (
        CTString as WmlCtstring,
    )
    from docx4j_py.wml import (
        CTTrackChange as WmlCttrackChange,
    )
    from docx4j_py.wml import (
        CTTwipsMeasure as WmlCttwipsMeasure,
    )
    from docx4j_py.wml import (
        StOnOff as WmlStOnOff,
    )
    from docx4j_py.wml import (
        STXAlign as WmlStxalign,
    )
    from docx4j_py.wml import (
        STYAlign as WmlStyalign,
    )
    from docx4j_py.wne import (
        CTAcd,
        CTAcdKeymap,
        CTAcdManifest,
        CTAcds,
        CTDocEvents,
        CTFci,
        CTKeymap,
        CTKeymaps,
        CTMacroWll,
        CTMcd,
        CTMcds,
        CTTcg,
        CTToolbars,
        CTVbaSuppData,
        Macro,
        Tcg,
        VbaSuppData,
        Wll,
    )
    from docx4j_py.wne import (
        CTLongHexNumber as WneCtlongHexNumber,
    )
    from docx4j_py.wne import (
        CTRel as WneCtrel,
    )
    from docx4j_py.wne import (
        StOnOff as WneStOnOff,
    )
    from docx4j_py.xml_ns import (
        LangValue,
        SpaceValue,
    )

__all__ = [
    "SchemaLibrary",
    "SchemaLibrarySchema",
    "ActiveAreaType",
    "AffineType",
    "AnnotationType",
    "AnnotationXMLType",
    "BindType",
    "BooleanStrType",
    "BrushPropertyType",
    "BrushRasterOpType",
    "BrushTipType",
    "BrushType",
    "CTMatrix",
    "CanvasTransformType",
    "CanvasType",
    "ChannelPropertiesType",
    "ChannelType",
    "ContextType",
    "DefinitionsType",
    "InkSourceType",
    "InkType",
    "IntermittentChannelsType",
    "LatencyType",
    "MappingType",
    "StStandardLengthUnits",
    "StStandardTimeUnits",
    "SampleRateType",
    "SourcePropertyType",
    "StandardBrushPropertyNameType",
    "StandardChannelNameType",
    "StandardChannelPropertyNameType",
    "TableType",
    "TimestampType",
    "TraceFormatType",
    "TraceGroupType",
    "TraceType",
    "TraceViewType",
    "ChannelTypeOrientation",
    "ChannelTypeType",
    "ChannelPropertiesTypeChannelProperty",
    "Definitions",
    "Ink",
    "MappingTypeType",
    "StandardUnitsType",
    "TableTypeApply",
    "TableTypeInterpolation",
    "Trace",
    "TraceTypeContinuation",
    "TraceTypeType",
    "TraceView",
    "CTAcc",
    "CTAccPr",
    "CTBar",
    "CTBarPr",
    "CTBorderBox",
    "CTBorderBoxPr",
    "CTBox",
    "CTBoxPr",
    "CTBreakBin",
    "CTBreakBinSub",
    "CTChar",
    "CTCtrlPr",
    "CTD",
    "CTDPr",
    "CTEqArr",
    "CTEqArrPr",
    "CTF",
    "CTFPr",
    "CTFType",
    "CTFunc",
    "CTFuncPr",
    "CTGroupChr",
    "CTGroupChrPr",
    "CTInteger2",
    "CTInteger255",
    "CTLimLoc",
    "CTLimLow",
    "CTLimLowPr",
    "CTLimUpp",
    "CTLimUppPr",
    "CTM",
    "CTMC",
    "CTMCPr",
    "CTMCS",
    "CTMPr",
    "CTMR",
    "CTManualBreak",
    "CTMathPr",
    "CTNary",
    "CTNaryPr",
    "CTOMath",
    "CTOMathArg",
    "CTOMathArgPr",
    "CTOMathJc",
    "CTOMathPara",
    "CTOMathParaPr",
    "MathCtonOff",
    "CTPhant",
    "CTPhantPr",
    "CTR",
    "CTRPR",
    "CTRad",
    "CTRadPr",
    "CTSPre",
    "CTSPrePr",
    "CTSSub",
    "CTSSubPr",
    "CTSSubSup",
    "CTSSubSupPr",
    "CTSSup",
    "CTSSupPr",
    "CTScript",
    "CTShp",
    "CTSpacingRule",
    "MathCtstring",
    "CTStyle",
    "CTText",
    "CTTopBot",
    "MathCttwipsMeasure",
    "CTUnSignedInteger",
    "CTXAlign",
    "CTYAlign",
    "STBreakBin",
    "STFType",
    "STJc",
    "STLimLoc",
    "STScript",
    "STShp",
    "STStyle",
    "STTopBot",
    "StBreakBinSub",
    "MathPr",
    "OMath",
    "OMathPara",
    "ApplyType",
    "CiType",
    "CnType",
    "ConstantType",
    "MathType",
    "OperatorType",
    "QualifierType",
    "SepType",
    "Abs",
    "And",
    "Apply",
    "Arccos",
    "Arcsin",
    "Arctan",
    "Ceiling",
    "Ci",
    "Cn",
    "CnTypeType",
    "Cos",
    "Degree",
    "Divide",
    "Eq",
    "Exp",
    "Exponentiale",
    "FalseType",
    "Floor",
    "Geq",
    "Gt",
    "Leq",
    "Ln",
    "Log",
    "Logbase",
    "Lt",
    "Math",
    "Max",
    "Min",
    "Minus",
    "Neq",
    "Not",
    "Or",
    "Pi",
    "Plus",
    "Power",
    "Product",
    "Quotient",
    "Rem",
    "Root",
    "Sep",
    "Sin",
    "Sum",
    "Tan",
    "Times",
    "TrueType",
    "Xor",
    "AlternateContent",
    "AlternateContentChoice",
    "AlternateContentFallback",
    "Relationship",
    "RelationshipTargetMode",
    "Relationships",
    "SharedTypesStOnOff",
    "SharedTypesStXalign",
    "SharedTypesStYalign",
    "CTBevel",
    "CTCamera",
    "W14Ctcolor",
    "CTDefaultImageDpi",
    "W14Ctempty",
    "CTFillTextEffect",
    "CTGlow",
    "CTGradientFillProperties",
    "CTGradientStop",
    "CTGradientStopList",
    "CTLigatures",
    "CTLightRig",
    "CTLineJoinMiterProperties",
    "CTLinearShadeProperties",
    "W14CtlongHexNumber",
    "W14Ctmarkup",
    "CTNumForm",
    "CTNumSpacing",
    "W14CtonOff",
    "CTPathShadeProperties",
    "CTPercentage",
    "CTPositiveFixedPercentage",
    "CTPositivePercentage",
    "CTPresetLineDashProperties",
    "CTProps3D",
    "CTReflection",
    "CTRelativeRect",
    "CTSRgbColor",
    "CTScene3D",
    "CTSchemeColor",
    "CTSdtCheckbox",
    "CTSdtCheckboxSymbol",
    "CTShadow",
    "CTSolidColorFillProperties",
    "CTSphereCoords",
    "CTStyleSet",
    "CTStylisticSets",
    "CTTextOutlineEffect",
    "W14CttrackChange",
    "CTWordContentPart",
    "CTWordContentPartNonVisual",
    "STBevelPresetType",
    "STCompoundLine",
    "STLigatures",
    "STLightRigDirection",
    "STLightRigType",
    "STLineCap",
    "STNumForm",
    "STNumSpacing",
    "STPathShadeType",
    "STPenAlignment",
    "STPresetCameraType",
    "STPresetLineDashVal",
    "STPresetMaterialType",
    "STRectAlignment",
    "STSchemeColorVal",
    "W14StOnOff",
    "Alpha",
    "Bevel",
    "Checkbox",
    "ConflictMode",
    "ContentPart",
    "CustomXmlConflictDelRangeEnd",
    "CustomXmlConflictDelRangeStart",
    "DefaultImageDpi",
    "DiscardImageEditingData",
    "W14DocId",
    "Lum",
    "LumMod",
    "LumOff",
    "Round",
    "Sat",
    "SatMod",
    "SatOff",
    "Shade",
    "Shadow",
    "Tint",
    "W15BooleanDefaultTrue",
    "W15Ctcolor",
    "CTCommentEx",
    "CTCommentsEx",
    "W15CtdataBinding",
    "W15CtdecimalNumber",
    "W15Ctempty",
    "W15Ctguid",
    "CTPeople",
    "CTPerson",
    "CTPresenceInfo",
    "CTSdtAppearance",
    "CTSdtRepeatedSection",
    "STSdtAppearance",
    "Appearance",
    "Collapsed",
    "CommentsEx",
    "W15DocId",
    "People",
    "RepeatingSection",
    "WebExtensionCreated",
    "WebExtensionLinked",
    "Body1",
    "BooleanDefaultFalse",
    "WmlBooleanDefaultTrue",
    "Br",
    "CTAltChunk",
    "CTAltChunkPr",
    "CTAttr",
    "CTAutoCaption",
    "CTAutoCaptions",
    "CTBackground",
    "CTBookmark",
    "CTBookmarkRange",
    "CTBorder",
    "CTCalendarType",
    "CTCaption",
    "CTCaptions",
    "CTCellMergeTrackChange",
    "CTCharacterSpacing",
    "CTCnf",
    "WmlCtcolor",
    "CTColorSchemeMapping",
    "CTColumn",
    "CTColumns",
    "CTCompat",
    "CTCompatSetting",
    "CTControl",
    "CTCustomXmlBlock",
    "CTCustomXmlCell",
    "CTCustomXmlPr",
    "CTCustomXmlRow",
    "CTCustomXmlRun",
    "WmlCtdataBinding",
    "WmlCtdecimalNumber",
    "CTDiv",
    "CTDivBdr",
    "CTDivs",
    "CTDocGrid",
    "CTDocPart",
    "CTDocPartBehavior",
    "CTDocPartBehaviors",
    "CTDocPartCategory",
    "CTDocPartGallery",
    "CTDocPartName",
    "CTDocPartPr",
    "CTDocPartType",
    "CTDocPartTypes",
    "CTDocParts",
    "CTDocProtect",
    "CTDocRsids",
    "CTDocType",
    "CTDocVar",
    "CTDocVars",
    "CTEastAsianLayout",
    "CTEdnDocProps",
    "CTEdnPos",
    "CTEdnProps",
    "CTEm",
    "WmlCtempty",
    "CTEndnotes",
    "CTFFCheckBox",
    "CTFFDDList",
    "CTFFData",
    "CTFFHelpText",
    "CTFFName",
    "CTFFStatusText",
    "CTFFTextInput",
    "CTFFTextType",
    "CTFitText",
    "CTFootnotes",
    "CTFrame",
    "CTFrameLayout",
    "CTFramePr",
    "CTFrameScrollbar",
    "CTFrameset",
    "CTFramesetSplitbar",
    "CTFtnDocProps",
    "CTFtnEdn",
    "CTFtnEdnRef",
    "CTFtnEdnSepRef",
    "CTFtnPos",
    "CTFtnProps",
    "WmlCtguid",
    "CTHeight",
    "CTKinsoku",
    "CTLang",
    "CTLanguage",
    "CTLineNumber",
    "CTLock",
    "WmlCtlongHexNumber",
    "CTMacroName",
    "CTMailMerge",
    "CTMailMergeDataType",
    "CTMailMergeDest",
    "CTMailMergeDocType",
    "CTMailMergeOdsoFMDFieldType",
    "CTMailMergeSourceType",
    "WmlCtmarkup",
    "CTMarkupRange",
    "CTMathRunTrackChange",
    "CTMoveBookmark",
    "CTMoveFromRangeEnd",
    "CTMoveToRangeEnd",
    "CTNumRestart",
    "CTObject",
    "CTOdso",
    "CTOdsoFieldMapData",
    "CTPPrChange",
    "CTPPrDefault",
    "CTPageNumber",
    "CTPaperSource",
    "CTParaRPrOriginal",
    "CTPerm",
    "CTPictureBase",
    "CTPixelsMeasure",
    "CTPlaceholder",
    "CTProof",
    "CTRPrChange",
    "CTRPrDefault",
    "CTReadingModeInkLockDown",
    "CTRecipientData",
    "CTRecipients",
    "WmlCtrel",
    "CTRuby",
    "CTRubyAlign",
    "CTRubyContent",
    "CTRubyPr",
    "CTSaveThroughXslt",
    "CTSdtCell",
    "CTSdtComboBox",
    "CTSdtContentCell",
    "CTSdtContentRow",
    "CTSdtContentRun",
    "CTSdtDate",
    "CTSdtDateMappingType",
    "CTSdtDocPart",
    "CTSdtDropDownList",
    "CTSdtEndPr",
    "CTSdtListItem",
    "CTSdtRow",
    "CTSdtText",
    "CTSectPrChange",
    "CTSettings",
    "CTShapeDefaults",
    "CTShd",
    "CTShortHexNumber",
    "CTSignedHpsMeasure",
    "CTSignedTwipsMeasure",
    "CTSimpleField",
    "CTSmartTagPr",
    "CTSmartTagRun",
    "CTSmartTagType",
    "WmlCtstring",
    "CTStylePaneFilter",
    "CTTabStop",
    "CTTargetScreenSz",
    "CTTblCellMar",
    "CTTblGridChange",
    "CTTblLayoutType",
    "CTTblLook",
    "CTTblOverlap",
    "CTTblPPr",
    "CTTblPrBase",
    "CTTblPrChange",
    "CTTblPrEx",
    "CTTblPrExBase",
    "CTTblPrExChange",
    "CTTblStylePr",
    "CTTcPrChange",
    "CTTextEffect",
    "CTTextScale",
    "CTTextboxTightWrap",
    "CTTrPrBase",
    "CTTrPrChange",
    "WmlCttrackChange",
    "CTTrackChangeNumbering",
    "CTTrackChangeRange",
    "CTTrackChangesView",
    "WmlCttwipsMeasure",
    "CTTxbxContent",
    "CTUcharHexNumber",
    "CTVerticalAlignRun",
    "CTVerticalJc",
    "CTView",
    "CTWebSettings",
    "CTWriteProtection",
    "CTWritingStyle",
    "CTZoom",
    "CtBdo",
    "CtBdoHyperlink",
    "CtCustomXmlPrPlaceholder",
    "CtCustomXmlRunHyperlink",
    "CtDir",
    "CtDirHyperlink",
    "CtDocPartCategoryName",
    "CtDocPartPrDescription",
    "CtDocPartPrStyle",
    "CtEdnPropsNumStart",
    "CtFfddlistDefault",
    "CtFfddlistListEntry",
    "CtFfddlistResult",
    "CtFftextInputDefault",
    "CtFftextInputFormat",
    "CtFftextInputMaxLength",
    "CtFontFamilyVal",
    "CtFrameName",
    "CtFrameSz",
    "CtFramesetSplitbarColor",
    "CtFramesetSz",
    "CtFtnPropsNumStart",
    "CtLvlLegacy",
    "CtLvlLvlPicBulletId",
    "CtLvlLvlRestart",
    "CtLvlLvlText",
    "CtLvlPStyle",
    "CtLvlStart",
    "CtLvlSuff",
    "CtLvlSuffVal",
    "CtMailMergeActiveRecord",
    "CtMailMergeAddressFieldName",
    "CtMailMergeCheckErrors",
    "CtMailMergeConnectString",
    "CtMailMergeMailSubject",
    "CtMailMergeQuery",
    "CtMathRunTrackChangeAnnotationRef",
    "CtMathRunTrackChangeCommentReference",
    "CtMathRunTrackChangeContinuationSeparator",
    "CtMathRunTrackChangeCr",
    "CtMathRunTrackChangeDayLong",
    "CtMathRunTrackChangeDayShort",
    "CtMathRunTrackChangeEndnoteRef",
    "CtMathRunTrackChangeFootnoteRef",
    "CtMathRunTrackChangeLastRenderedPageBreak",
    "CtMathRunTrackChangeMonthLong",
    "CtMathRunTrackChangeMonthShort",
    "CtMathRunTrackChangeNoBreakHyphen",
    "CtMathRunTrackChangePgNum",
    "CtMathRunTrackChangePtab",
    "CtMathRunTrackChangeSeparator",
    "CtMathRunTrackChangeSoftHyphen",
    "CtMathRunTrackChangeSym",
    "CtMathRunTrackChangeTab",
    "CtMathRunTrackChangeYearLong",
    "CtMathRunTrackChangeYearShort",
    "CtOdsoFieldMapDataColumn",
    "CtOdsoFieldMapDataMappedName",
    "CtOdsoFieldMapDataName",
    "CtOdsoColDelim",
    "CtOdsoTable",
    "CtOdsoUdl",
    "CtPprBaseDivId",
    "CtPprBaseInd",
    "CtPprBaseNumPr",
    "CtPprBaseNumPrIlvl",
    "CtPprBaseNumPrNumId",
    "CtPprBaseOutlineLvl",
    "CtPprBasePBdr",
    "CtPprBasePStyle",
    "CtPprBaseSpacing",
    "CtPprBaseTextAlignment",
    "CtPprBaseTextAlignmentVal",
    "CtPermStartEdGrp",
    "CtPlaceholderDocPart",
    "CtRprChangeRPr",
    "CtRAnnotationRef",
    "CtRCommentReference",
    "CtRContinuationSeparator",
    "CtRCr",
    "CtRDayLong",
    "CtRDayShort",
    "CtREndnoteRef",
    "CtRFootnoteRef",
    "CtRLastRenderedPageBreak",
    "CtRMonthLong",
    "CtRMonthShort",
    "CtRNoBreakHyphen",
    "CtRPgNum",
    "CtRPtab",
    "CtRSeparator",
    "CtRSoftHyphen",
    "CtRSym",
    "CtRTab",
    "CtRYearLong",
    "CtRYearShort",
    "CtRecipientDataColumn",
    "CtSdtContentRunHyperlink",
    "CtSdtDateDateFormat",
    "CtSdtDocPartDocPartCategory",
    "CtSdtDocPartDocPartGallery",
    "CtSdtPrAlias",
    "CtSdtPrBibliography",
    "CtSdtPrCitation",
    "CtSdtPrEquation",
    "CtSdtPrGroup",
    "CtSdtPrPicture",
    "CtSdtPrRichText",
    "CtSectPrBasePgBorders",
    "CtSectPrBasePgMar",
    "CtSectPrBasePgSz",
    "CtSectPrBaseType",
    "CtSectPrBaseTypeVal",
    "CtSectPrPgBorders",
    "CtSectPrPgMar",
    "CtSectPrPgSz",
    "CtSectPrType",
    "CtSectPrTypeVal",
    "CtSettingsAttachedSchema",
    "CtSettingsBookFoldPrintingSheets",
    "CtSettingsClickAndTypeStyle",
    "CtSettingsConsecutiveHyphenLimit",
    "CtSettingsDecimalSymbol",
    "CtSettingsDefaultTableStyle",
    "CtSettingsDisplayHorizontalDrawingGridEvery",
    "CtSettingsDisplayVerticalDrawingGridEvery",
    "CtSettingsForceUpgrade",
    "CtSettingsListSeparator",
    "CtSettingsSummaryLength",
    "CtSimpleFieldHyperlink",
    "CtSmartTagRunHyperlink",
    "CtTblPrBaseTblStyle",
    "CtTblPrBaseTblStyleColBandSize",
    "CtTblPrBaseTblStyleRowBandSize",
    "CtTblWidthType",
    "CtTcPrInnerGridSpan",
    "CtTcPrInnerHMerge",
    "CtTcPrInnerHMergeVal",
    "CtTcPrInnerTcBorders",
    "CtTcPrInnerVMerge",
    "CtTcPrInnerVMergeVal",
    "CtTextDirectionVal",
    "CtTrPrBaseDivId",
    "CtTrPrBaseGridAfter",
    "CtTrPrBaseGridBefore",
    "CtWebSettingsEncoding",
    "CtWebSettingsPixelsPerInch",
    "Color",
    "CommentRangeEnd",
    "CommentRangeStart",
    "Comments",
    "DelText",
    "DocDefaults",
    "Document",
    "Drawing",
    "FldChar",
    "FontFamily",
    "FontPanose",
    "FontPitch",
    "FontRel",
    "FontSig",
    "Fonts",
    "FooterReference",
    "Ftr",
    "GlossaryDocument",
    "Hdr",
    "HdrFtrRef",
    "HeaderReference",
    "Highlight",
    "HpsMeasure",
    "Id",
    "Jc",
    "JcEnumeration",
    "Lvl",
    "NumFmt",
    "NumberFormat",
    "Numbering",
    "P",
    "PPr",
    "PPrBase",
    "ParaRPr",
    "ParaRPrChange",
    "Pict",
    "ProofErr",
    "R",
    "RDelInstrText",
    "RFonts",
    "RInstrText",
    "RPr",
    "RStyle",
    "RT",
    "RangePermissionStart",
    "RunDel",
    "RunIns",
    "RunTrackChange",
    "STAlgClass",
    "STAlgType",
    "STAnnotationVMerge",
    "STBorder",
    "STBrClear",
    "STBrType",
    "STCalendarType",
    "STCaptionPos",
    "STChapterSep",
    "STCharacterSpacing",
    "STColorSchemeIndex",
    "STCombineBrackets",
    "STCryptProv",
    "STDirection",
    "STDisplacedByCustomXml",
    "STDocGrid",
    "STDocPartBehavior",
    "STDocPartGallery",
    "STDocPartType",
    "STDocProtect",
    "STDocType",
    "STDropCap",
    "STEdnPos",
    "STEm",
    "STFFTextType",
    "STFldCharType",
    "STFrameLayout",
    "STFrameScrollbar",
    "STFtnEdn",
    "STFtnPos",
    "STHAnchor",
    "STHeightRule",
    "STHexColorAuto",
    "STHint",
    "STInfoTextType",
    "STLineNumberRestart",
    "STLineSpacingRule",
    "STLock",
    "STMailMergeDataType",
    "STMailMergeDest",
    "STMailMergeDocType",
    "STMailMergeOdsoFMDFieldType",
    "STMailMergeSourceType",
    "STPTabAlignment",
    "STPTabLeader",
    "STPTabRelativeTo",
    "STPageBorderDisplay",
    "STPageBorderOffset",
    "STPageBorderZOrder",
    "STPageOrientation",
    "STPitch",
    "STProof",
    "STRestartNumber",
    "STRubyAlign",
    "STSdtDateMappingType",
    "STShd",
    "STTabJc",
    "STTabTlc",
    "STTblLayoutType",
    "STTblOverlap",
    "STTblStyleOverrideType",
    "STTextEffect",
    "STTextboxTightWrap",
    "STTheme",
    "STThemeColor",
    "STVAnchor",
    "STVerticalAlignRun",
    "STVerticalJc",
    "STView",
    "STWrap",
    "WmlStxalign",
    "WmlStyalign",
    "STZoom",
    "WmlStOnOff",
    "StTargetScreenSz",
    "SdtBlock",
    "SdtContentBlock",
    "SdtPr",
    "SdtRun",
    "SectPr",
    "SectPrBase",
    "Style",
    "Styles",
    "Tabs",
    "Tag",
    "Tbl",
    "TblBorders",
    "TblGrid",
    "TblGridBase",
    "TblGridCol",
    "TblPr",
    "TblWidth",
    "Tc",
    "TcMar",
    "TcPr",
    "TcPrInner",
    "Text",
    "TextDirection",
    "Tr",
    "TrPr",
    "U",
    "UnderlineEnumeration",
    "Body",
    "CalcOnExit",
    "CantSplit",
    "CellDel",
    "CellIns",
    "CommentsComment",
    "CustomXmlDelRangeEnd1",
    "CustomXmlDelRangeEnd2",
    "CustomXmlDelRangeStart1",
    "CustomXmlDelRangeStart2",
    "CustomXmlInsRangeEnd1",
    "CustomXmlInsRangeEnd2",
    "CustomXmlInsRangeStart1",
    "CustomXmlInsRangeStart2",
    "CustomXmlMoveFromRangeEnd1",
    "CustomXmlMoveFromRangeEnd2",
    "CustomXmlMoveFromRangeStart1",
    "CustomXmlMoveFromRangeStart2",
    "CustomXmlMoveToRangeEnd1",
    "CustomXmlMoveToRangeEnd2",
    "CustomXmlMoveToRangeStart1",
    "CustomXmlMoveToRangeStart2",
    "DelInstrText",
    "Del1",
    "Del2",
    "DocDefaultsPPrDefault",
    "DocDefaultsRPrDefault",
    "DocPartList",
    "DocPartObj",
    "Enabled",
    "EndnoteReference1",
    "EndnoteReference2",
    "Endnotes",
    "EntryMacro",
    "ExitMacro",
    "FontsFont",
    "FontsFontAltName",
    "FootnoteReference1",
    "FootnoteReference2",
    "Footnotes",
    "Hidden",
    "HighlightVal",
    "Ins1",
    "Ins2",
    "InstrText",
    "MoveFromRangeStart1",
    "MoveFromRangeStart2",
    "MoveFrom1",
    "MoveFrom2",
    "MoveToRangeStart1",
    "MoveToRangeStart2",
    "MoveTo1",
    "MoveTo2",
    "NumberingAbstractNum",
    "NumberingAbstractNumMultiLevelType",
    "NumberingAbstractNumMultiLevelTypeVal",
    "NumberingAbstractNumName",
    "NumberingAbstractNumNumStyleLink",
    "NumberingAbstractNumStyleLink",
    "NumberingNum",
    "NumberingNumIdMacAtCleanup",
    "NumberingNumPicBullet",
    "NumberingNumAbstractNumId",
    "NumberingNumLvlOverride",
    "NumberingNumLvlOverrideStartOverride",
    "PHyperlink",
    "ProofErrType",
    "RAnnotationRef",
    "RCommentReference",
    "RContinuationSeparator",
    "RCr",
    "RDayLong",
    "RDayShort",
    "REndnoteRef",
    "RFootnoteRef",
    "RLastRenderedPageBreak",
    "RMonthLong",
    "RMonthShort",
    "RNoBreakHyphen",
    "RPgNum",
    "RPtab",
    "RSeparator",
    "RSoftHyphen",
    "RSym",
    "RTab",
    "RYearLong",
    "RYearShort",
    "Recipients",
    "Settings",
    "ShowingPlcHdr",
    "StyleAliases",
    "StyleBasedOn",
    "StyleLink",
    "StyleName",
    "StyleNext",
    "StyleType",
    "StyleUiPriority",
    "StylesLatentStyles",
    "StylesLatentStylesLsdException",
    "T",
    "TblCellSpacing",
    "TblHeader",
    "Temporary",
    "TxbxContent",
    "WAfter",
    "WBefore",
    "WebSettings",
    "CTAcd",
    "CTAcdKeymap",
    "CTAcdManifest",
    "CTAcds",
    "CTDocEvents",
    "CTFci",
    "CTKeymap",
    "CTKeymaps",
    "WneCtlongHexNumber",
    "CTMacroWll",
    "CTMcd",
    "CTMcds",
    "WneCtrel",
    "CTTcg",
    "CTToolbars",
    "CTVbaSuppData",
    "WneStOnOff",
    "Macro",
    "Tcg",
    "VbaSuppData",
    "Wll",
    "LangValue",
    "SpaceValue",
]

# The re-exports above are resolved on first use, so that importing this
# package never forces a module of it to be imported before the modules it
# depends on.
__lazy_imports__ = {
    "SchemaLibrary": ("docx4j_py.customxml", "SchemaLibrary"),
    "SchemaLibrarySchema": ("docx4j_py.customxml", "SchemaLibrarySchema"),
    "ActiveAreaType": ("docx4j_py.inkml", "ActiveAreaType"),
    "AffineType": ("docx4j_py.inkml", "AffineType"),
    "AnnotationType": ("docx4j_py.inkml", "AnnotationType"),
    "AnnotationXMLType": ("docx4j_py.inkml", "AnnotationXMLType"),
    "BindType": ("docx4j_py.inkml", "BindType"),
    "BooleanStrType": ("docx4j_py.inkml", "BooleanStrType"),
    "BrushPropertyType": ("docx4j_py.inkml", "BrushPropertyType"),
    "BrushRasterOpType": ("docx4j_py.inkml", "BrushRasterOpType"),
    "BrushTipType": ("docx4j_py.inkml", "BrushTipType"),
    "BrushType": ("docx4j_py.inkml", "BrushType"),
    "CTMatrix": ("docx4j_py.inkml", "CTMatrix"),
    "CanvasTransformType": ("docx4j_py.inkml", "CanvasTransformType"),
    "CanvasType": ("docx4j_py.inkml", "CanvasType"),
    "ChannelPropertiesType": ("docx4j_py.inkml", "ChannelPropertiesType"),
    "ChannelType": ("docx4j_py.inkml", "ChannelType"),
    "ContextType": ("docx4j_py.inkml", "ContextType"),
    "DefinitionsType": ("docx4j_py.inkml", "DefinitionsType"),
    "InkSourceType": ("docx4j_py.inkml", "InkSourceType"),
    "InkType": ("docx4j_py.inkml", "InkType"),
    "IntermittentChannelsType": ("docx4j_py.inkml", "IntermittentChannelsType"),
    "LatencyType": ("docx4j_py.inkml", "LatencyType"),
    "MappingType": ("docx4j_py.inkml", "MappingType"),
    "StStandardLengthUnits": ("docx4j_py.inkml", "StStandardLengthUnits"),
    "StStandardTimeUnits": ("docx4j_py.inkml", "StStandardTimeUnits"),
    "SampleRateType": ("docx4j_py.inkml", "SampleRateType"),
    "SourcePropertyType": ("docx4j_py.inkml", "SourcePropertyType"),
    "StandardBrushPropertyNameType": ("docx4j_py.inkml", "StandardBrushPropertyNameType"),
    "StandardChannelNameType": ("docx4j_py.inkml", "StandardChannelNameType"),
    "StandardChannelPropertyNameType": ("docx4j_py.inkml", "StandardChannelPropertyNameType"),
    "TableType": ("docx4j_py.inkml", "TableType"),
    "TimestampType": ("docx4j_py.inkml", "TimestampType"),
    "TraceFormatType": ("docx4j_py.inkml", "TraceFormatType"),
    "TraceGroupType": ("docx4j_py.inkml", "TraceGroupType"),
    "TraceType": ("docx4j_py.inkml", "TraceType"),
    "TraceViewType": ("docx4j_py.inkml", "TraceViewType"),
    "ChannelTypeOrientation": ("docx4j_py.inkml", "ChannelTypeOrientation"),
    "ChannelTypeType": ("docx4j_py.inkml", "ChannelTypeType"),
    "ChannelPropertiesTypeChannelProperty": (
        "docx4j_py.inkml",
        "ChannelPropertiesTypeChannelProperty",
    ),
    "Definitions": ("docx4j_py.inkml", "Definitions"),
    "Ink": ("docx4j_py.inkml", "Ink"),
    "MappingTypeType": ("docx4j_py.inkml", "MappingTypeType"),
    "StandardUnitsType": ("docx4j_py.inkml", "StandardUnitsType"),
    "TableTypeApply": ("docx4j_py.inkml", "TableTypeApply"),
    "TableTypeInterpolation": ("docx4j_py.inkml", "TableTypeInterpolation"),
    "Trace": ("docx4j_py.inkml", "Trace"),
    "TraceTypeContinuation": ("docx4j_py.inkml", "TraceTypeContinuation"),
    "TraceTypeType": ("docx4j_py.inkml", "TraceTypeType"),
    "TraceView": ("docx4j_py.inkml", "TraceView"),
    "CTAcc": ("docx4j_py.math", "CTAcc"),
    "CTAccPr": ("docx4j_py.math", "CTAccPr"),
    "CTBar": ("docx4j_py.math", "CTBar"),
    "CTBarPr": ("docx4j_py.math", "CTBarPr"),
    "CTBorderBox": ("docx4j_py.math", "CTBorderBox"),
    "CTBorderBoxPr": ("docx4j_py.math", "CTBorderBoxPr"),
    "CTBox": ("docx4j_py.math", "CTBox"),
    "CTBoxPr": ("docx4j_py.math", "CTBoxPr"),
    "CTBreakBin": ("docx4j_py.math", "CTBreakBin"),
    "CTBreakBinSub": ("docx4j_py.math", "CTBreakBinSub"),
    "CTChar": ("docx4j_py.math", "CTChar"),
    "CTCtrlPr": ("docx4j_py.math", "CTCtrlPr"),
    "CTD": ("docx4j_py.math", "CTD"),
    "CTDPr": ("docx4j_py.math", "CTDPr"),
    "CTEqArr": ("docx4j_py.math", "CTEqArr"),
    "CTEqArrPr": ("docx4j_py.math", "CTEqArrPr"),
    "CTF": ("docx4j_py.math", "CTF"),
    "CTFPr": ("docx4j_py.math", "CTFPr"),
    "CTFType": ("docx4j_py.math", "CTFType"),
    "CTFunc": ("docx4j_py.math", "CTFunc"),
    "CTFuncPr": ("docx4j_py.math", "CTFuncPr"),
    "CTGroupChr": ("docx4j_py.math", "CTGroupChr"),
    "CTGroupChrPr": ("docx4j_py.math", "CTGroupChrPr"),
    "CTInteger2": ("docx4j_py.math", "CTInteger2"),
    "CTInteger255": ("docx4j_py.math", "CTInteger255"),
    "CTLimLoc": ("docx4j_py.math", "CTLimLoc"),
    "CTLimLow": ("docx4j_py.math", "CTLimLow"),
    "CTLimLowPr": ("docx4j_py.math", "CTLimLowPr"),
    "CTLimUpp": ("docx4j_py.math", "CTLimUpp"),
    "CTLimUppPr": ("docx4j_py.math", "CTLimUppPr"),
    "CTM": ("docx4j_py.math", "CTM"),
    "CTMC": ("docx4j_py.math", "CTMC"),
    "CTMCPr": ("docx4j_py.math", "CTMCPr"),
    "CTMCS": ("docx4j_py.math", "CTMCS"),
    "CTMPr": ("docx4j_py.math", "CTMPr"),
    "CTMR": ("docx4j_py.math", "CTMR"),
    "CTManualBreak": ("docx4j_py.math", "CTManualBreak"),
    "CTMathPr": ("docx4j_py.math", "CTMathPr"),
    "CTNary": ("docx4j_py.math", "CTNary"),
    "CTNaryPr": ("docx4j_py.math", "CTNaryPr"),
    "CTOMath": ("docx4j_py.math", "CTOMath"),
    "CTOMathArg": ("docx4j_py.math", "CTOMathArg"),
    "CTOMathArgPr": ("docx4j_py.math", "CTOMathArgPr"),
    "CTOMathJc": ("docx4j_py.math", "CTOMathJc"),
    "CTOMathPara": ("docx4j_py.math", "CTOMathPara"),
    "CTOMathParaPr": ("docx4j_py.math", "CTOMathParaPr"),
    "MathCtonOff": ("docx4j_py.math", "CTOnOff"),
    "CTPhant": ("docx4j_py.math", "CTPhant"),
    "CTPhantPr": ("docx4j_py.math", "CTPhantPr"),
    "CTR": ("docx4j_py.math", "CTR"),
    "CTRPR": ("docx4j_py.math", "CTRPR"),
    "CTRad": ("docx4j_py.math", "CTRad"),
    "CTRadPr": ("docx4j_py.math", "CTRadPr"),
    "CTSPre": ("docx4j_py.math", "CTSPre"),
    "CTSPrePr": ("docx4j_py.math", "CTSPrePr"),
    "CTSSub": ("docx4j_py.math", "CTSSub"),
    "CTSSubPr": ("docx4j_py.math", "CTSSubPr"),
    "CTSSubSup": ("docx4j_py.math", "CTSSubSup"),
    "CTSSubSupPr": ("docx4j_py.math", "CTSSubSupPr"),
    "CTSSup": ("docx4j_py.math", "CTSSup"),
    "CTSSupPr": ("docx4j_py.math", "CTSSupPr"),
    "CTScript": ("docx4j_py.math", "CTScript"),
    "CTShp": ("docx4j_py.math", "CTShp"),
    "CTSpacingRule": ("docx4j_py.math", "CTSpacingRule"),
    "MathCtstring": ("docx4j_py.math", "CTString"),
    "CTStyle": ("docx4j_py.math", "CTStyle"),
    "CTText": ("docx4j_py.math", "CTText"),
    "CTTopBot": ("docx4j_py.math", "CTTopBot"),
    "MathCttwipsMeasure": ("docx4j_py.math", "CTTwipsMeasure"),
    "CTUnSignedInteger": ("docx4j_py.math", "CTUnSignedInteger"),
    "CTXAlign": ("docx4j_py.math", "CTXAlign"),
    "CTYAlign": ("docx4j_py.math", "CTYAlign"),
    "STBreakBin": ("docx4j_py.math", "STBreakBin"),
    "STFType": ("docx4j_py.math", "STFType"),
    "STJc": ("docx4j_py.math", "STJc"),
    "STLimLoc": ("docx4j_py.math", "STLimLoc"),
    "STScript": ("docx4j_py.math", "STScript"),
    "STShp": ("docx4j_py.math", "STShp"),
    "STStyle": ("docx4j_py.math", "STStyle"),
    "STTopBot": ("docx4j_py.math", "STTopBot"),
    "StBreakBinSub": ("docx4j_py.math", "StBreakBinSub"),
    "MathPr": ("docx4j_py.math", "MathPr"),
    "OMath": ("docx4j_py.math", "OMath"),
    "OMathPara": ("docx4j_py.math", "OMathPara"),
    "ApplyType": ("docx4j_py.mathml", "ApplyType"),
    "CiType": ("docx4j_py.mathml", "CiType"),
    "CnType": ("docx4j_py.mathml", "CnType"),
    "ConstantType": ("docx4j_py.mathml", "ConstantType"),
    "MathType": ("docx4j_py.mathml", "MathType"),
    "OperatorType": ("docx4j_py.mathml", "OperatorType"),
    "QualifierType": ("docx4j_py.mathml", "QualifierType"),
    "SepType": ("docx4j_py.mathml", "SepType"),
    "Abs": ("docx4j_py.mathml", "Abs"),
    "And": ("docx4j_py.mathml", "And"),
    "Apply": ("docx4j_py.mathml", "Apply"),
    "Arccos": ("docx4j_py.mathml", "Arccos"),
    "Arcsin": ("docx4j_py.mathml", "Arcsin"),
    "Arctan": ("docx4j_py.mathml", "Arctan"),
    "Ceiling": ("docx4j_py.mathml", "Ceiling"),
    "Ci": ("docx4j_py.mathml", "Ci"),
    "Cn": ("docx4j_py.mathml", "Cn"),
    "CnTypeType": ("docx4j_py.mathml", "CnTypeType"),
    "Cos": ("docx4j_py.mathml", "Cos"),
    "Degree": ("docx4j_py.mathml", "Degree"),
    "Divide": ("docx4j_py.mathml", "Divide"),
    "Eq": ("docx4j_py.mathml", "Eq"),
    "Exp": ("docx4j_py.mathml", "Exp"),
    "Exponentiale": ("docx4j_py.mathml", "Exponentiale"),
    "FalseType": ("docx4j_py.mathml", "FalseType"),
    "Floor": ("docx4j_py.mathml", "Floor"),
    "Geq": ("docx4j_py.mathml", "Geq"),
    "Gt": ("docx4j_py.mathml", "Gt"),
    "Leq": ("docx4j_py.mathml", "Leq"),
    "Ln": ("docx4j_py.mathml", "Ln"),
    "Log": ("docx4j_py.mathml", "Log"),
    "Logbase": ("docx4j_py.mathml", "Logbase"),
    "Lt": ("docx4j_py.mathml", "Lt"),
    "Math": ("docx4j_py.mathml", "Math"),
    "Max": ("docx4j_py.mathml", "Max"),
    "Min": ("docx4j_py.mathml", "Min"),
    "Minus": ("docx4j_py.mathml", "Minus"),
    "Neq": ("docx4j_py.mathml", "Neq"),
    "Not": ("docx4j_py.mathml", "Not"),
    "Or": ("docx4j_py.mathml", "Or"),
    "Pi": ("docx4j_py.mathml", "Pi"),
    "Plus": ("docx4j_py.mathml", "Plus"),
    "Power": ("docx4j_py.mathml", "Power"),
    "Product": ("docx4j_py.mathml", "Product"),
    "Quotient": ("docx4j_py.mathml", "Quotient"),
    "Rem": ("docx4j_py.mathml", "Rem"),
    "Root": ("docx4j_py.mathml", "Root"),
    "Sep": ("docx4j_py.mathml", "Sep"),
    "Sin": ("docx4j_py.mathml", "Sin"),
    "Sum": ("docx4j_py.mathml", "Sum"),
    "Tan": ("docx4j_py.mathml", "Tan"),
    "Times": ("docx4j_py.mathml", "Times"),
    "TrueType": ("docx4j_py.mathml", "TrueType"),
    "Xor": ("docx4j_py.mathml", "Xor"),
    "AlternateContent": ("docx4j_py.mce", "AlternateContent"),
    "AlternateContentChoice": ("docx4j_py.mce", "AlternateContentChoice"),
    "AlternateContentFallback": ("docx4j_py.mce", "AlternateContentFallback"),
    "Relationship": ("docx4j_py.relationships", "Relationship"),
    "RelationshipTargetMode": ("docx4j_py.relationships", "RelationshipTargetMode"),
    "Relationships": ("docx4j_py.relationships", "Relationships"),
    "SharedTypesStOnOff": ("docx4j_py.shared_types", "StOnOff"),
    "SharedTypesStXalign": ("docx4j_py.shared_types", "StXalign"),
    "SharedTypesStYalign": ("docx4j_py.shared_types", "StYalign"),
    "CTBevel": ("docx4j_py.w14", "CTBevel"),
    "CTCamera": ("docx4j_py.w14", "CTCamera"),
    "W14Ctcolor": ("docx4j_py.w14", "CTColor"),
    "CTDefaultImageDpi": ("docx4j_py.w14", "CTDefaultImageDpi"),
    "W14Ctempty": ("docx4j_py.w14", "CTEmpty"),
    "CTFillTextEffect": ("docx4j_py.w14", "CTFillTextEffect"),
    "CTGlow": ("docx4j_py.w14", "CTGlow"),
    "CTGradientFillProperties": ("docx4j_py.w14", "CTGradientFillProperties"),
    "CTGradientStop": ("docx4j_py.w14", "CTGradientStop"),
    "CTGradientStopList": ("docx4j_py.w14", "CTGradientStopList"),
    "CTLigatures": ("docx4j_py.w14", "CTLigatures"),
    "CTLightRig": ("docx4j_py.w14", "CTLightRig"),
    "CTLineJoinMiterProperties": ("docx4j_py.w14", "CTLineJoinMiterProperties"),
    "CTLinearShadeProperties": ("docx4j_py.w14", "CTLinearShadeProperties"),
    "W14CtlongHexNumber": ("docx4j_py.w14", "CTLongHexNumber"),
    "W14Ctmarkup": ("docx4j_py.w14", "CTMarkup"),
    "CTNumForm": ("docx4j_py.w14", "CTNumForm"),
    "CTNumSpacing": ("docx4j_py.w14", "CTNumSpacing"),
    "W14CtonOff": ("docx4j_py.w14", "CTOnOff"),
    "CTPathShadeProperties": ("docx4j_py.w14", "CTPathShadeProperties"),
    "CTPercentage": ("docx4j_py.w14", "CTPercentage"),
    "CTPositiveFixedPercentage": ("docx4j_py.w14", "CTPositiveFixedPercentage"),
    "CTPositivePercentage": ("docx4j_py.w14", "CTPositivePercentage"),
    "CTPresetLineDashProperties": ("docx4j_py.w14", "CTPresetLineDashProperties"),
    "CTProps3D": ("docx4j_py.w14", "CTProps3D"),
    "CTReflection": ("docx4j_py.w14", "CTReflection"),
    "CTRelativeRect": ("docx4j_py.w14", "CTRelativeRect"),
    "CTSRgbColor": ("docx4j_py.w14", "CTSRgbColor"),
    "CTScene3D": ("docx4j_py.w14", "CTScene3D"),
    "CTSchemeColor": ("docx4j_py.w14", "CTSchemeColor"),
    "CTSdtCheckbox": ("docx4j_py.w14", "CTSdtCheckbox"),
    "CTSdtCheckboxSymbol": ("docx4j_py.w14", "CTSdtCheckboxSymbol"),
    "CTShadow": ("docx4j_py.w14", "CTShadow"),
    "CTSolidColorFillProperties": ("docx4j_py.w14", "CTSolidColorFillProperties"),
    "CTSphereCoords": ("docx4j_py.w14", "CTSphereCoords"),
    "CTStyleSet": ("docx4j_py.w14", "CTStyleSet"),
    "CTStylisticSets": ("docx4j_py.w14", "CTStylisticSets"),
    "CTTextOutlineEffect": ("docx4j_py.w14", "CTTextOutlineEffect"),
    "W14CttrackChange": ("docx4j_py.w14", "CTTrackChange"),
    "CTWordContentPart": ("docx4j_py.w14", "CTWordContentPart"),
    "CTWordContentPartNonVisual": ("docx4j_py.w14", "CTWordContentPartNonVisual"),
    "STBevelPresetType": ("docx4j_py.w14", "STBevelPresetType"),
    "STCompoundLine": ("docx4j_py.w14", "STCompoundLine"),
    "STLigatures": ("docx4j_py.w14", "STLigatures"),
    "STLightRigDirection": ("docx4j_py.w14", "STLightRigDirection"),
    "STLightRigType": ("docx4j_py.w14", "STLightRigType"),
    "STLineCap": ("docx4j_py.w14", "STLineCap"),
    "STNumForm": ("docx4j_py.w14", "STNumForm"),
    "STNumSpacing": ("docx4j_py.w14", "STNumSpacing"),
    "STPathShadeType": ("docx4j_py.w14", "STPathShadeType"),
    "STPenAlignment": ("docx4j_py.w14", "STPenAlignment"),
    "STPresetCameraType": ("docx4j_py.w14", "STPresetCameraType"),
    "STPresetLineDashVal": ("docx4j_py.w14", "STPresetLineDashVal"),
    "STPresetMaterialType": ("docx4j_py.w14", "STPresetMaterialType"),
    "STRectAlignment": ("docx4j_py.w14", "STRectAlignment"),
    "STSchemeColorVal": ("docx4j_py.w14", "STSchemeColorVal"),
    "W14StOnOff": ("docx4j_py.w14", "StOnOff"),
    "Alpha": ("docx4j_py.w14", "Alpha"),
    "Bevel": ("docx4j_py.w14", "Bevel"),
    "Checkbox": ("docx4j_py.w14", "Checkbox"),
    "ConflictMode": ("docx4j_py.w14", "ConflictMode"),
    "ContentPart": ("docx4j_py.w14", "ContentPart"),
    "CustomXmlConflictDelRangeEnd": ("docx4j_py.w14", "CustomXmlConflictDelRangeEnd"),
    "CustomXmlConflictDelRangeStart": ("docx4j_py.w14", "CustomXmlConflictDelRangeStart"),
    "DefaultImageDpi": ("docx4j_py.w14", "DefaultImageDpi"),
    "DiscardImageEditingData": ("docx4j_py.w14", "DiscardImageEditingData"),
    "W14DocId": ("docx4j_py.w14", "DocId"),
    "Lum": ("docx4j_py.w14", "Lum"),
    "LumMod": ("docx4j_py.w14", "LumMod"),
    "LumOff": ("docx4j_py.w14", "LumOff"),
    "Round": ("docx4j_py.w14", "Round"),
    "Sat": ("docx4j_py.w14", "Sat"),
    "SatMod": ("docx4j_py.w14", "SatMod"),
    "SatOff": ("docx4j_py.w14", "SatOff"),
    "Shade": ("docx4j_py.w14", "Shade"),
    "Shadow": ("docx4j_py.w14", "Shadow"),
    "Tint": ("docx4j_py.w14", "Tint"),
    "W15BooleanDefaultTrue": ("docx4j_py.w15", "BooleanDefaultTrue"),
    "W15Ctcolor": ("docx4j_py.w15", "CTColor"),
    "CTCommentEx": ("docx4j_py.w15", "CTCommentEx"),
    "CTCommentsEx": ("docx4j_py.w15", "CTCommentsEx"),
    "W15CtdataBinding": ("docx4j_py.w15", "CTDataBinding"),
    "W15CtdecimalNumber": ("docx4j_py.w15", "CTDecimalNumber"),
    "W15Ctempty": ("docx4j_py.w15", "CTEmpty"),
    "W15Ctguid": ("docx4j_py.w15", "CTGuid"),
    "CTPeople": ("docx4j_py.w15", "CTPeople"),
    "CTPerson": ("docx4j_py.w15", "CTPerson"),
    "CTPresenceInfo": ("docx4j_py.w15", "CTPresenceInfo"),
    "CTSdtAppearance": ("docx4j_py.w15", "CTSdtAppearance"),
    "CTSdtRepeatedSection": ("docx4j_py.w15", "CTSdtRepeatedSection"),
    "STSdtAppearance": ("docx4j_py.w15", "STSdtAppearance"),
    "Appearance": ("docx4j_py.w15", "Appearance"),
    "Collapsed": ("docx4j_py.w15", "Collapsed"),
    "CommentsEx": ("docx4j_py.w15", "CommentsEx"),
    "W15DocId": ("docx4j_py.w15", "DocId"),
    "People": ("docx4j_py.w15", "People"),
    "RepeatingSection": ("docx4j_py.w15", "RepeatingSection"),
    "WebExtensionCreated": ("docx4j_py.w15", "WebExtensionCreated"),
    "WebExtensionLinked": ("docx4j_py.w15", "WebExtensionLinked"),
    "Body1": ("docx4j_py.wml", "Body1"),
    "BooleanDefaultFalse": ("docx4j_py.wml", "BooleanDefaultFalse"),
    "WmlBooleanDefaultTrue": ("docx4j_py.wml", "BooleanDefaultTrue"),
    "Br": ("docx4j_py.wml", "Br"),
    "CTAltChunk": ("docx4j_py.wml", "CTAltChunk"),
    "CTAltChunkPr": ("docx4j_py.wml", "CTAltChunkPr"),
    "CTAttr": ("docx4j_py.wml", "CTAttr"),
    "CTAutoCaption": ("docx4j_py.wml", "CTAutoCaption"),
    "CTAutoCaptions": ("docx4j_py.wml", "CTAutoCaptions"),
    "CTBackground": ("docx4j_py.wml", "CTBackground"),
    "CTBookmark": ("docx4j_py.wml", "CTBookmark"),
    "CTBookmarkRange": ("docx4j_py.wml", "CTBookmarkRange"),
    "CTBorder": ("docx4j_py.wml", "CTBorder"),
    "CTCalendarType": ("docx4j_py.wml", "CTCalendarType"),
    "CTCaption": ("docx4j_py.wml", "CTCaption"),
    "CTCaptions": ("docx4j_py.wml", "CTCaptions"),
    "CTCellMergeTrackChange": ("docx4j_py.wml", "CTCellMergeTrackChange"),
    "CTCharacterSpacing": ("docx4j_py.wml", "CTCharacterSpacing"),
    "CTCnf": ("docx4j_py.wml", "CTCnf"),
    "WmlCtcolor": ("docx4j_py.wml", "CTColor"),
    "CTColorSchemeMapping": ("docx4j_py.wml", "CTColorSchemeMapping"),
    "CTColumn": ("docx4j_py.wml", "CTColumn"),
    "CTColumns": ("docx4j_py.wml", "CTColumns"),
    "CTCompat": ("docx4j_py.wml", "CTCompat"),
    "CTCompatSetting": ("docx4j_py.wml", "CTCompatSetting"),
    "CTControl": ("docx4j_py.wml", "CTControl"),
    "CTCustomXmlBlock": ("docx4j_py.wml", "CTCustomXmlBlock"),
    "CTCustomXmlCell": ("docx4j_py.wml", "CTCustomXmlCell"),
    "CTCustomXmlPr": ("docx4j_py.wml", "CTCustomXmlPr"),
    "CTCustomXmlRow": ("docx4j_py.wml", "CTCustomXmlRow"),
    "CTCustomXmlRun": ("docx4j_py.wml", "CTCustomXmlRun"),
    "WmlCtdataBinding": ("docx4j_py.wml", "CTDataBinding"),
    "WmlCtdecimalNumber": ("docx4j_py.wml", "CTDecimalNumber"),
    "CTDiv": ("docx4j_py.wml", "CTDiv"),
    "CTDivBdr": ("docx4j_py.wml", "CTDivBdr"),
    "CTDivs": ("docx4j_py.wml", "CTDivs"),
    "CTDocGrid": ("docx4j_py.wml", "CTDocGrid"),
    "CTDocPart": ("docx4j_py.wml", "CTDocPart"),
    "CTDocPartBehavior": ("docx4j_py.wml", "CTDocPartBehavior"),
    "CTDocPartBehaviors": ("docx4j_py.wml", "CTDocPartBehaviors"),
    "CTDocPartCategory": ("docx4j_py.wml", "CTDocPartCategory"),
    "CTDocPartGallery": ("docx4j_py.wml", "CTDocPartGallery"),
    "CTDocPartName": ("docx4j_py.wml", "CTDocPartName"),
    "CTDocPartPr": ("docx4j_py.wml", "CTDocPartPr"),
    "CTDocPartType": ("docx4j_py.wml", "CTDocPartType"),
    "CTDocPartTypes": ("docx4j_py.wml", "CTDocPartTypes"),
    "CTDocParts": ("docx4j_py.wml", "CTDocParts"),
    "CTDocProtect": ("docx4j_py.wml", "CTDocProtect"),
    "CTDocRsids": ("docx4j_py.wml", "CTDocRsids"),
    "CTDocType": ("docx4j_py.wml", "CTDocType"),
    "CTDocVar": ("docx4j_py.wml", "CTDocVar"),
    "CTDocVars": ("docx4j_py.wml", "CTDocVars"),
    "CTEastAsianLayout": ("docx4j_py.wml", "CTEastAsianLayout"),
    "CTEdnDocProps": ("docx4j_py.wml", "CTEdnDocProps"),
    "CTEdnPos": ("docx4j_py.wml", "CTEdnPos"),
    "CTEdnProps": ("docx4j_py.wml", "CTEdnProps"),
    "CTEm": ("docx4j_py.wml", "CTEm"),
    "WmlCtempty": ("docx4j_py.wml", "CTEmpty"),
    "CTEndnotes": ("docx4j_py.wml", "CTEndnotes"),
    "CTFFCheckBox": ("docx4j_py.wml", "CTFFCheckBox"),
    "CTFFDDList": ("docx4j_py.wml", "CTFFDDList"),
    "CTFFData": ("docx4j_py.wml", "CTFFData"),
    "CTFFHelpText": ("docx4j_py.wml", "CTFFHelpText"),
    "CTFFName": ("docx4j_py.wml", "CTFFName"),
    "CTFFStatusText": ("docx4j_py.wml", "CTFFStatusText"),
    "CTFFTextInput": ("docx4j_py.wml", "CTFFTextInput"),
    "CTFFTextType": ("docx4j_py.wml", "CTFFTextType"),
    "CTFitText": ("docx4j_py.wml", "CTFitText"),
    "CTFootnotes": ("docx4j_py.wml", "CTFootnotes"),
    "CTFrame": ("docx4j_py.wml", "CTFrame"),
    "CTFrameLayout": ("docx4j_py.wml", "CTFrameLayout"),
    "CTFramePr": ("docx4j_py.wml", "CTFramePr"),
    "CTFrameScrollbar": ("docx4j_py.wml", "CTFrameScrollbar"),
    "CTFrameset": ("docx4j_py.wml", "CTFrameset"),
    "CTFramesetSplitbar": ("docx4j_py.wml", "CTFramesetSplitbar"),
    "CTFtnDocProps": ("docx4j_py.wml", "CTFtnDocProps"),
    "CTFtnEdn": ("docx4j_py.wml", "CTFtnEdn"),
    "CTFtnEdnRef": ("docx4j_py.wml", "CTFtnEdnRef"),
    "CTFtnEdnSepRef": ("docx4j_py.wml", "CTFtnEdnSepRef"),
    "CTFtnPos": ("docx4j_py.wml", "CTFtnPos"),
    "CTFtnProps": ("docx4j_py.wml", "CTFtnProps"),
    "WmlCtguid": ("docx4j_py.wml", "CTGuid"),
    "CTHeight": ("docx4j_py.wml", "CTHeight"),
    "CTKinsoku": ("docx4j_py.wml", "CTKinsoku"),
    "CTLang": ("docx4j_py.wml", "CTLang"),
    "CTLanguage": ("docx4j_py.wml", "CTLanguage"),
    "CTLineNumber": ("docx4j_py.wml", "CTLineNumber"),
    "CTLock": ("docx4j_py.wml", "CTLock"),
    "WmlCtlongHexNumber": ("docx4j_py.wml", "CTLongHexNumber"),
    "CTMacroName": ("docx4j_py.wml", "CTMacroName"),
    "CTMailMerge": ("docx4j_py.wml", "CTMailMerge"),
    "CTMailMergeDataType": ("docx4j_py.wml", "CTMailMergeDataType"),
    "CTMailMergeDest": ("docx4j_py.wml", "CTMailMergeDest"),
    "CTMailMergeDocType": ("docx4j_py.wml", "CTMailMergeDocType"),
    "CTMailMergeOdsoFMDFieldType": ("docx4j_py.wml", "CTMailMergeOdsoFMDFieldType"),
    "CTMailMergeSourceType": ("docx4j_py.wml", "CTMailMergeSourceType"),
    "WmlCtmarkup": ("docx4j_py.wml", "CTMarkup"),
    "CTMarkupRange": ("docx4j_py.wml", "CTMarkupRange"),
    "CTMathRunTrackChange": ("docx4j_py.wml", "CTMathRunTrackChange"),
    "CTMoveBookmark": ("docx4j_py.wml", "CTMoveBookmark"),
    "CTMoveFromRangeEnd": ("docx4j_py.wml", "CTMoveFromRangeEnd"),
    "CTMoveToRangeEnd": ("docx4j_py.wml", "CTMoveToRangeEnd"),
    "CTNumRestart": ("docx4j_py.wml", "CTNumRestart"),
    "CTObject": ("docx4j_py.wml", "CTObject"),
    "CTOdso": ("docx4j_py.wml", "CTOdso"),
    "CTOdsoFieldMapData": ("docx4j_py.wml", "CTOdsoFieldMapData"),
    "CTPPrChange": ("docx4j_py.wml", "CTPPrChange"),
    "CTPPrDefault": ("docx4j_py.wml", "CTPPrDefault"),
    "CTPageNumber": ("docx4j_py.wml", "CTPageNumber"),
    "CTPaperSource": ("docx4j_py.wml", "CTPaperSource"),
    "CTParaRPrOriginal": ("docx4j_py.wml", "CTParaRPrOriginal"),
    "CTPerm": ("docx4j_py.wml", "CTPerm"),
    "CTPictureBase": ("docx4j_py.wml", "CTPictureBase"),
    "CTPixelsMeasure": ("docx4j_py.wml", "CTPixelsMeasure"),
    "CTPlaceholder": ("docx4j_py.wml", "CTPlaceholder"),
    "CTProof": ("docx4j_py.wml", "CTProof"),
    "CTRPrChange": ("docx4j_py.wml", "CTRPrChange"),
    "CTRPrDefault": ("docx4j_py.wml", "CTRPrDefault"),
    "CTReadingModeInkLockDown": ("docx4j_py.wml", "CTReadingModeInkLockDown"),
    "CTRecipientData": ("docx4j_py.wml", "CTRecipientData"),
    "CTRecipients": ("docx4j_py.wml", "CTRecipients"),
    "WmlCtrel": ("docx4j_py.wml", "CTRel"),
    "CTRuby": ("docx4j_py.wml", "CTRuby"),
    "CTRubyAlign": ("docx4j_py.wml", "CTRubyAlign"),
    "CTRubyContent": ("docx4j_py.wml", "CTRubyContent"),
    "CTRubyPr": ("docx4j_py.wml", "CTRubyPr"),
    "CTSaveThroughXslt": ("docx4j_py.wml", "CTSaveThroughXslt"),
    "CTSdtCell": ("docx4j_py.wml", "CTSdtCell"),
    "CTSdtComboBox": ("docx4j_py.wml", "CTSdtComboBox"),
    "CTSdtContentCell": ("docx4j_py.wml", "CTSdtContentCell"),
    "CTSdtContentRow": ("docx4j_py.wml", "CTSdtContentRow"),
    "CTSdtContentRun": ("docx4j_py.wml", "CTSdtContentRun"),
    "CTSdtDate": ("docx4j_py.wml", "CTSdtDate"),
    "CTSdtDateMappingType": ("docx4j_py.wml", "CTSdtDateMappingType"),
    "CTSdtDocPart": ("docx4j_py.wml", "CTSdtDocPart"),
    "CTSdtDropDownList": ("docx4j_py.wml", "CTSdtDropDownList"),
    "CTSdtEndPr": ("docx4j_py.wml", "CTSdtEndPr"),
    "CTSdtListItem": ("docx4j_py.wml", "CTSdtListItem"),
    "CTSdtRow": ("docx4j_py.wml", "CTSdtRow"),
    "CTSdtText": ("docx4j_py.wml", "CTSdtText"),
    "CTSectPrChange": ("docx4j_py.wml", "CTSectPrChange"),
    "CTSettings": ("docx4j_py.wml", "CTSettings"),
    "CTShapeDefaults": ("docx4j_py.wml", "CTShapeDefaults"),
    "CTShd": ("docx4j_py.wml", "CTShd"),
    "CTShortHexNumber": ("docx4j_py.wml", "CTShortHexNumber"),
    "CTSignedHpsMeasure": ("docx4j_py.wml", "CTSignedHpsMeasure"),
    "CTSignedTwipsMeasure": ("docx4j_py.wml", "CTSignedTwipsMeasure"),
    "CTSimpleField": ("docx4j_py.wml", "CTSimpleField"),
    "CTSmartTagPr": ("docx4j_py.wml", "CTSmartTagPr"),
    "CTSmartTagRun": ("docx4j_py.wml", "CTSmartTagRun"),
    "CTSmartTagType": ("docx4j_py.wml", "CTSmartTagType"),
    "WmlCtstring": ("docx4j_py.wml", "CTString"),
    "CTStylePaneFilter": ("docx4j_py.wml", "CTStylePaneFilter"),
    "CTTabStop": ("docx4j_py.wml", "CTTabStop"),
    "CTTargetScreenSz": ("docx4j_py.wml", "CTTargetScreenSz"),
    "CTTblCellMar": ("docx4j_py.wml", "CTTblCellMar"),
    "CTTblGridChange": ("docx4j_py.wml", "CTTblGridChange"),
    "CTTblLayoutType": ("docx4j_py.wml", "CTTblLayoutType"),
    "CTTblLook": ("docx4j_py.wml", "CTTblLook"),
    "CTTblOverlap": ("docx4j_py.wml", "CTTblOverlap"),
    "CTTblPPr": ("docx4j_py.wml", "CTTblPPr"),
    "CTTblPrBase": ("docx4j_py.wml", "CTTblPrBase"),
    "CTTblPrChange": ("docx4j_py.wml", "CTTblPrChange"),
    "CTTblPrEx": ("docx4j_py.wml", "CTTblPrEx"),
    "CTTblPrExBase": ("docx4j_py.wml", "CTTblPrExBase"),
    "CTTblPrExChange": ("docx4j_py.wml", "CTTblPrExChange"),
    "CTTblStylePr": ("docx4j_py.wml", "CTTblStylePr"),
    "CTTcPrChange": ("docx4j_py.wml", "CTTcPrChange"),
    "CTTextEffect": ("docx4j_py.wml", "CTTextEffect"),
    "CTTextScale": ("docx4j_py.wml", "CTTextScale"),
    "CTTextboxTightWrap": ("docx4j_py.wml", "CTTextboxTightWrap"),
    "CTTrPrBase": ("docx4j_py.wml", "CTTrPrBase"),
    "CTTrPrChange": ("docx4j_py.wml", "CTTrPrChange"),
    "WmlCttrackChange": ("docx4j_py.wml", "CTTrackChange"),
    "CTTrackChangeNumbering": ("docx4j_py.wml", "CTTrackChangeNumbering"),
    "CTTrackChangeRange": ("docx4j_py.wml", "CTTrackChangeRange"),
    "CTTrackChangesView": ("docx4j_py.wml", "CTTrackChangesView"),
    "WmlCttwipsMeasure": ("docx4j_py.wml", "CTTwipsMeasure"),
    "CTTxbxContent": ("docx4j_py.wml", "CTTxbxContent"),
    "CTUcharHexNumber": ("docx4j_py.wml", "CTUcharHexNumber"),
    "CTVerticalAlignRun": ("docx4j_py.wml", "CTVerticalAlignRun"),
    "CTVerticalJc": ("docx4j_py.wml", "CTVerticalJc"),
    "CTView": ("docx4j_py.wml", "CTView"),
    "CTWebSettings": ("docx4j_py.wml", "CTWebSettings"),
    "CTWriteProtection": ("docx4j_py.wml", "CTWriteProtection"),
    "CTWritingStyle": ("docx4j_py.wml", "CTWritingStyle"),
    "CTZoom": ("docx4j_py.wml", "CTZoom"),
    "CtBdo": ("docx4j_py.wml", "CtBdo"),
    "CtBdoHyperlink": ("docx4j_py.wml", "CtBdoHyperlink"),
    "CtCustomXmlPrPlaceholder": ("docx4j_py.wml", "CtCustomXmlPrPlaceholder"),
    "CtCustomXmlRunHyperlink": ("docx4j_py.wml", "CtCustomXmlRunHyperlink"),
    "CtDir": ("docx4j_py.wml", "CtDir"),
    "CtDirHyperlink": ("docx4j_py.wml", "CtDirHyperlink"),
    "CtDocPartCategoryName": ("docx4j_py.wml", "CtDocPartCategoryName"),
    "CtDocPartPrDescription": ("docx4j_py.wml", "CtDocPartPrDescription"),
    "CtDocPartPrStyle": ("docx4j_py.wml", "CtDocPartPrStyle"),
    "CtEdnPropsNumStart": ("docx4j_py.wml", "CtEdnPropsNumStart"),
    "CtFfddlistDefault": ("docx4j_py.wml", "CtFfddlistDefault"),
    "CtFfddlistListEntry": ("docx4j_py.wml", "CtFfddlistListEntry"),
    "CtFfddlistResult": ("docx4j_py.wml", "CtFfddlistResult"),
    "CtFftextInputDefault": ("docx4j_py.wml", "CtFftextInputDefault"),
    "CtFftextInputFormat": ("docx4j_py.wml", "CtFftextInputFormat"),
    "CtFftextInputMaxLength": ("docx4j_py.wml", "CtFftextInputMaxLength"),
    "CtFontFamilyVal": ("docx4j_py.wml", "CtFontFamilyVal"),
    "CtFrameName": ("docx4j_py.wml", "CtFrameName"),
    "CtFrameSz": ("docx4j_py.wml", "CtFrameSz"),
    "CtFramesetSplitbarColor": ("docx4j_py.wml", "CtFramesetSplitbarColor"),
    "CtFramesetSz": ("docx4j_py.wml", "CtFramesetSz"),
    "CtFtnPropsNumStart": ("docx4j_py.wml", "CtFtnPropsNumStart"),
    "CtLvlLegacy": ("docx4j_py.wml", "CtLvlLegacy"),
    "CtLvlLvlPicBulletId": ("docx4j_py.wml", "CtLvlLvlPicBulletId"),
    "CtLvlLvlRestart": ("docx4j_py.wml", "CtLvlLvlRestart"),
    "CtLvlLvlText": ("docx4j_py.wml", "CtLvlLvlText"),
    "CtLvlPStyle": ("docx4j_py.wml", "CtLvlPStyle"),
    "CtLvlStart": ("docx4j_py.wml", "CtLvlStart"),
    "CtLvlSuff": ("docx4j_py.wml", "CtLvlSuff"),
    "CtLvlSuffVal": ("docx4j_py.wml", "CtLvlSuffVal"),
    "CtMailMergeActiveRecord": ("docx4j_py.wml", "CtMailMergeActiveRecord"),
    "CtMailMergeAddressFieldName": ("docx4j_py.wml", "CtMailMergeAddressFieldName"),
    "CtMailMergeCheckErrors": ("docx4j_py.wml", "CtMailMergeCheckErrors"),
    "CtMailMergeConnectString": ("docx4j_py.wml", "CtMailMergeConnectString"),
    "CtMailMergeMailSubject": ("docx4j_py.wml", "CtMailMergeMailSubject"),
    "CtMailMergeQuery": ("docx4j_py.wml", "CtMailMergeQuery"),
    "CtMathRunTrackChangeAnnotationRef": ("docx4j_py.wml", "CtMathRunTrackChangeAnnotationRef"),
    "CtMathRunTrackChangeCommentReference": (
        "docx4j_py.wml",
        "CtMathRunTrackChangeCommentReference",
    ),
    "CtMathRunTrackChangeContinuationSeparator": (
        "docx4j_py.wml",
        "CtMathRunTrackChangeContinuationSeparator",
    ),
    "CtMathRunTrackChangeCr": ("docx4j_py.wml", "CtMathRunTrackChangeCr"),
    "CtMathRunTrackChangeDayLong": ("docx4j_py.wml", "CtMathRunTrackChangeDayLong"),
    "CtMathRunTrackChangeDayShort": ("docx4j_py.wml", "CtMathRunTrackChangeDayShort"),
    "CtMathRunTrackChangeEndnoteRef": ("docx4j_py.wml", "CtMathRunTrackChangeEndnoteRef"),
    "CtMathRunTrackChangeFootnoteRef": ("docx4j_py.wml", "CtMathRunTrackChangeFootnoteRef"),
    "CtMathRunTrackChangeLastRenderedPageBreak": (
        "docx4j_py.wml",
        "CtMathRunTrackChangeLastRenderedPageBreak",
    ),
    "CtMathRunTrackChangeMonthLong": ("docx4j_py.wml", "CtMathRunTrackChangeMonthLong"),
    "CtMathRunTrackChangeMonthShort": ("docx4j_py.wml", "CtMathRunTrackChangeMonthShort"),
    "CtMathRunTrackChangeNoBreakHyphen": ("docx4j_py.wml", "CtMathRunTrackChangeNoBreakHyphen"),
    "CtMathRunTrackChangePgNum": ("docx4j_py.wml", "CtMathRunTrackChangePgNum"),
    "CtMathRunTrackChangePtab": ("docx4j_py.wml", "CtMathRunTrackChangePtab"),
    "CtMathRunTrackChangeSeparator": ("docx4j_py.wml", "CtMathRunTrackChangeSeparator"),
    "CtMathRunTrackChangeSoftHyphen": ("docx4j_py.wml", "CtMathRunTrackChangeSoftHyphen"),
    "CtMathRunTrackChangeSym": ("docx4j_py.wml", "CtMathRunTrackChangeSym"),
    "CtMathRunTrackChangeTab": ("docx4j_py.wml", "CtMathRunTrackChangeTab"),
    "CtMathRunTrackChangeYearLong": ("docx4j_py.wml", "CtMathRunTrackChangeYearLong"),
    "CtMathRunTrackChangeYearShort": ("docx4j_py.wml", "CtMathRunTrackChangeYearShort"),
    "CtOdsoFieldMapDataColumn": ("docx4j_py.wml", "CtOdsoFieldMapDataColumn"),
    "CtOdsoFieldMapDataMappedName": ("docx4j_py.wml", "CtOdsoFieldMapDataMappedName"),
    "CtOdsoFieldMapDataName": ("docx4j_py.wml", "CtOdsoFieldMapDataName"),
    "CtOdsoColDelim": ("docx4j_py.wml", "CtOdsoColDelim"),
    "CtOdsoTable": ("docx4j_py.wml", "CtOdsoTable"),
    "CtOdsoUdl": ("docx4j_py.wml", "CtOdsoUdl"),
    "CtPprBaseDivId": ("docx4j_py.wml", "CtPprBaseDivId"),
    "CtPprBaseInd": ("docx4j_py.wml", "CtPprBaseInd"),
    "CtPprBaseNumPr": ("docx4j_py.wml", "CtPprBaseNumPr"),
    "CtPprBaseNumPrIlvl": ("docx4j_py.wml", "CtPprBaseNumPrIlvl"),
    "CtPprBaseNumPrNumId": ("docx4j_py.wml", "CtPprBaseNumPrNumId"),
    "CtPprBaseOutlineLvl": ("docx4j_py.wml", "CtPprBaseOutlineLvl"),
    "CtPprBasePBdr": ("docx4j_py.wml", "CtPprBasePBdr"),
    "CtPprBasePStyle": ("docx4j_py.wml", "CtPprBasePStyle"),
    "CtPprBaseSpacing": ("docx4j_py.wml", "CtPprBaseSpacing"),
    "CtPprBaseTextAlignment": ("docx4j_py.wml", "CtPprBaseTextAlignment"),
    "CtPprBaseTextAlignmentVal": ("docx4j_py.wml", "CtPprBaseTextAlignmentVal"),
    "CtPermStartEdGrp": ("docx4j_py.wml", "CtPermStartEdGrp"),
    "CtPlaceholderDocPart": ("docx4j_py.wml", "CtPlaceholderDocPart"),
    "CtRprChangeRPr": ("docx4j_py.wml", "CtRprChangeRPr"),
    "CtRAnnotationRef": ("docx4j_py.wml", "CtRAnnotationRef"),
    "CtRCommentReference": ("docx4j_py.wml", "CtRCommentReference"),
    "CtRContinuationSeparator": ("docx4j_py.wml", "CtRContinuationSeparator"),
    "CtRCr": ("docx4j_py.wml", "CtRCr"),
    "CtRDayLong": ("docx4j_py.wml", "CtRDayLong"),
    "CtRDayShort": ("docx4j_py.wml", "CtRDayShort"),
    "CtREndnoteRef": ("docx4j_py.wml", "CtREndnoteRef"),
    "CtRFootnoteRef": ("docx4j_py.wml", "CtRFootnoteRef"),
    "CtRLastRenderedPageBreak": ("docx4j_py.wml", "CtRLastRenderedPageBreak"),
    "CtRMonthLong": ("docx4j_py.wml", "CtRMonthLong"),
    "CtRMonthShort": ("docx4j_py.wml", "CtRMonthShort"),
    "CtRNoBreakHyphen": ("docx4j_py.wml", "CtRNoBreakHyphen"),
    "CtRPgNum": ("docx4j_py.wml", "CtRPgNum"),
    "CtRPtab": ("docx4j_py.wml", "CtRPtab"),
    "CtRSeparator": ("docx4j_py.wml", "CtRSeparator"),
    "CtRSoftHyphen": ("docx4j_py.wml", "CtRSoftHyphen"),
    "CtRSym": ("docx4j_py.wml", "CtRSym"),
    "CtRTab": ("docx4j_py.wml", "CtRTab"),
    "CtRYearLong": ("docx4j_py.wml", "CtRYearLong"),
    "CtRYearShort": ("docx4j_py.wml", "CtRYearShort"),
    "CtRecipientDataColumn": ("docx4j_py.wml", "CtRecipientDataColumn"),
    "CtSdtContentRunHyperlink": ("docx4j_py.wml", "CtSdtContentRunHyperlink"),
    "CtSdtDateDateFormat": ("docx4j_py.wml", "CtSdtDateDateFormat"),
    "CtSdtDocPartDocPartCategory": ("docx4j_py.wml", "CtSdtDocPartDocPartCategory"),
    "CtSdtDocPartDocPartGallery": ("docx4j_py.wml", "CtSdtDocPartDocPartGallery"),
    "CtSdtPrAlias": ("docx4j_py.wml", "CtSdtPrAlias"),
    "CtSdtPrBibliography": ("docx4j_py.wml", "CtSdtPrBibliography"),
    "CtSdtPrCitation": ("docx4j_py.wml", "CtSdtPrCitation"),
    "CtSdtPrEquation": ("docx4j_py.wml", "CtSdtPrEquation"),
    "CtSdtPrGroup": ("docx4j_py.wml", "CtSdtPrGroup"),
    "CtSdtPrPicture": ("docx4j_py.wml", "CtSdtPrPicture"),
    "CtSdtPrRichText": ("docx4j_py.wml", "CtSdtPrRichText"),
    "CtSectPrBasePgBorders": ("docx4j_py.wml", "CtSectPrBasePgBorders"),
    "CtSectPrBasePgMar": ("docx4j_py.wml", "CtSectPrBasePgMar"),
    "CtSectPrBasePgSz": ("docx4j_py.wml", "CtSectPrBasePgSz"),
    "CtSectPrBaseType": ("docx4j_py.wml", "CtSectPrBaseType"),
    "CtSectPrBaseTypeVal": ("docx4j_py.wml", "CtSectPrBaseTypeVal"),
    "CtSectPrPgBorders": ("docx4j_py.wml", "CtSectPrPgBorders"),
    "CtSectPrPgMar": ("docx4j_py.wml", "CtSectPrPgMar"),
    "CtSectPrPgSz": ("docx4j_py.wml", "CtSectPrPgSz"),
    "CtSectPrType": ("docx4j_py.wml", "CtSectPrType"),
    "CtSectPrTypeVal": ("docx4j_py.wml", "CtSectPrTypeVal"),
    "CtSettingsAttachedSchema": ("docx4j_py.wml", "CtSettingsAttachedSchema"),
    "CtSettingsBookFoldPrintingSheets": ("docx4j_py.wml", "CtSettingsBookFoldPrintingSheets"),
    "CtSettingsClickAndTypeStyle": ("docx4j_py.wml", "CtSettingsClickAndTypeStyle"),
    "CtSettingsConsecutiveHyphenLimit": ("docx4j_py.wml", "CtSettingsConsecutiveHyphenLimit"),
    "CtSettingsDecimalSymbol": ("docx4j_py.wml", "CtSettingsDecimalSymbol"),
    "CtSettingsDefaultTableStyle": ("docx4j_py.wml", "CtSettingsDefaultTableStyle"),
    "CtSettingsDisplayHorizontalDrawingGridEvery": (
        "docx4j_py.wml",
        "CtSettingsDisplayHorizontalDrawingGridEvery",
    ),
    "CtSettingsDisplayVerticalDrawingGridEvery": (
        "docx4j_py.wml",
        "CtSettingsDisplayVerticalDrawingGridEvery",
    ),
    "CtSettingsForceUpgrade": ("docx4j_py.wml", "CtSettingsForceUpgrade"),
    "CtSettingsListSeparator": ("docx4j_py.wml", "CtSettingsListSeparator"),
    "CtSettingsSummaryLength": ("docx4j_py.wml", "CtSettingsSummaryLength"),
    "CtSimpleFieldHyperlink": ("docx4j_py.wml", "CtSimpleFieldHyperlink"),
    "CtSmartTagRunHyperlink": ("docx4j_py.wml", "CtSmartTagRunHyperlink"),
    "CtTblPrBaseTblStyle": ("docx4j_py.wml", "CtTblPrBaseTblStyle"),
    "CtTblPrBaseTblStyleColBandSize": ("docx4j_py.wml", "CtTblPrBaseTblStyleColBandSize"),
    "CtTblPrBaseTblStyleRowBandSize": ("docx4j_py.wml", "CtTblPrBaseTblStyleRowBandSize"),
    "CtTblWidthType": ("docx4j_py.wml", "CtTblWidthType"),
    "CtTcPrInnerGridSpan": ("docx4j_py.wml", "CtTcPrInnerGridSpan"),
    "CtTcPrInnerHMerge": ("docx4j_py.wml", "CtTcPrInnerHMerge"),
    "CtTcPrInnerHMergeVal": ("docx4j_py.wml", "CtTcPrInnerHMergeVal"),
    "CtTcPrInnerTcBorders": ("docx4j_py.wml", "CtTcPrInnerTcBorders"),
    "CtTcPrInnerVMerge": ("docx4j_py.wml", "CtTcPrInnerVMerge"),
    "CtTcPrInnerVMergeVal": ("docx4j_py.wml", "CtTcPrInnerVMergeVal"),
    "CtTextDirectionVal": ("docx4j_py.wml", "CtTextDirectionVal"),
    "CtTrPrBaseDivId": ("docx4j_py.wml", "CtTrPrBaseDivId"),
    "CtTrPrBaseGridAfter": ("docx4j_py.wml", "CtTrPrBaseGridAfter"),
    "CtTrPrBaseGridBefore": ("docx4j_py.wml", "CtTrPrBaseGridBefore"),
    "CtWebSettingsEncoding": ("docx4j_py.wml", "CtWebSettingsEncoding"),
    "CtWebSettingsPixelsPerInch": ("docx4j_py.wml", "CtWebSettingsPixelsPerInch"),
    "Color": ("docx4j_py.wml", "Color"),
    "CommentRangeEnd": ("docx4j_py.wml", "CommentRangeEnd"),
    "CommentRangeStart": ("docx4j_py.wml", "CommentRangeStart"),
    "Comments": ("docx4j_py.wml", "Comments"),
    "DelText": ("docx4j_py.wml", "DelText"),
    "DocDefaults": ("docx4j_py.wml", "DocDefaults"),
    "Document": ("docx4j_py.wml", "Document"),
    "Drawing": ("docx4j_py.wml", "Drawing"),
    "FldChar": ("docx4j_py.wml", "FldChar"),
    "FontFamily": ("docx4j_py.wml", "FontFamily"),
    "FontPanose": ("docx4j_py.wml", "FontPanose"),
    "FontPitch": ("docx4j_py.wml", "FontPitch"),
    "FontRel": ("docx4j_py.wml", "FontRel"),
    "FontSig": ("docx4j_py.wml", "FontSig"),
    "Fonts": ("docx4j_py.wml", "Fonts"),
    "FooterReference": ("docx4j_py.wml", "FooterReference"),
    "Ftr": ("docx4j_py.wml", "Ftr"),
    "GlossaryDocument": ("docx4j_py.wml", "GlossaryDocument"),
    "Hdr": ("docx4j_py.wml", "Hdr"),
    "HdrFtrRef": ("docx4j_py.wml", "HdrFtrRef"),
    "HeaderReference": ("docx4j_py.wml", "HeaderReference"),
    "Highlight": ("docx4j_py.wml", "Highlight"),
    "HpsMeasure": ("docx4j_py.wml", "HpsMeasure"),
    "Id": ("docx4j_py.wml", "Id"),
    "Jc": ("docx4j_py.wml", "Jc"),
    "JcEnumeration": ("docx4j_py.wml", "JcEnumeration"),
    "Lvl": ("docx4j_py.wml", "Lvl"),
    "NumFmt": ("docx4j_py.wml", "NumFmt"),
    "NumberFormat": ("docx4j_py.wml", "NumberFormat"),
    "Numbering": ("docx4j_py.wml", "Numbering"),
    "P": ("docx4j_py.wml", "P"),
    "PPr": ("docx4j_py.wml", "PPr"),
    "PPrBase": ("docx4j_py.wml", "PPrBase"),
    "ParaRPr": ("docx4j_py.wml", "ParaRPr"),
    "ParaRPrChange": ("docx4j_py.wml", "ParaRPrChange"),
    "Pict": ("docx4j_py.wml", "Pict"),
    "ProofErr": ("docx4j_py.wml", "ProofErr"),
    "R": ("docx4j_py.wml", "R"),
    "RDelInstrText": ("docx4j_py.wml", "RDelInstrText"),
    "RFonts": ("docx4j_py.wml", "RFonts"),
    "RInstrText": ("docx4j_py.wml", "RInstrText"),
    "RPr": ("docx4j_py.wml", "RPr"),
    "RStyle": ("docx4j_py.wml", "RStyle"),
    "RT": ("docx4j_py.wml", "RT"),
    "RangePermissionStart": ("docx4j_py.wml", "RangePermissionStart"),
    "RunDel": ("docx4j_py.wml", "RunDel"),
    "RunIns": ("docx4j_py.wml", "RunIns"),
    "RunTrackChange": ("docx4j_py.wml", "RunTrackChange"),
    "STAlgClass": ("docx4j_py.wml", "STAlgClass"),
    "STAlgType": ("docx4j_py.wml", "STAlgType"),
    "STAnnotationVMerge": ("docx4j_py.wml", "STAnnotationVMerge"),
    "STBorder": ("docx4j_py.wml", "STBorder"),
    "STBrClear": ("docx4j_py.wml", "STBrClear"),
    "STBrType": ("docx4j_py.wml", "STBrType"),
    "STCalendarType": ("docx4j_py.wml", "STCalendarType"),
    "STCaptionPos": ("docx4j_py.wml", "STCaptionPos"),
    "STChapterSep": ("docx4j_py.wml", "STChapterSep"),
    "STCharacterSpacing": ("docx4j_py.wml", "STCharacterSpacing"),
    "STColorSchemeIndex": ("docx4j_py.wml", "STColorSchemeIndex"),
    "STCombineBrackets": ("docx4j_py.wml", "STCombineBrackets"),
    "STCryptProv": ("docx4j_py.wml", "STCryptProv"),
    "STDirection": ("docx4j_py.wml", "STDirection"),
    "STDisplacedByCustomXml": ("docx4j_py.wml", "STDisplacedByCustomXml"),
    "STDocGrid": ("docx4j_py.wml", "STDocGrid"),
    "STDocPartBehavior": ("docx4j_py.wml", "STDocPartBehavior"),
    "STDocPartGallery": ("docx4j_py.wml", "STDocPartGallery"),
    "STDocPartType": ("docx4j_py.wml", "STDocPartType"),
    "STDocProtect": ("docx4j_py.wml", "STDocProtect"),
    "STDocType": ("docx4j_py.wml", "STDocType"),
    "STDropCap": ("docx4j_py.wml", "STDropCap"),
    "STEdnPos": ("docx4j_py.wml", "STEdnPos"),
    "STEm": ("docx4j_py.wml", "STEm"),
    "STFFTextType": ("docx4j_py.wml", "STFFTextType"),
    "STFldCharType": ("docx4j_py.wml", "STFldCharType"),
    "STFrameLayout": ("docx4j_py.wml", "STFrameLayout"),
    "STFrameScrollbar": ("docx4j_py.wml", "STFrameScrollbar"),
    "STFtnEdn": ("docx4j_py.wml", "STFtnEdn"),
    "STFtnPos": ("docx4j_py.wml", "STFtnPos"),
    "STHAnchor": ("docx4j_py.wml", "STHAnchor"),
    "STHeightRule": ("docx4j_py.wml", "STHeightRule"),
    "STHexColorAuto": ("docx4j_py.wml", "STHexColorAuto"),
    "STHint": ("docx4j_py.wml", "STHint"),
    "STInfoTextType": ("docx4j_py.wml", "STInfoTextType"),
    "STLineNumberRestart": ("docx4j_py.wml", "STLineNumberRestart"),
    "STLineSpacingRule": ("docx4j_py.wml", "STLineSpacingRule"),
    "STLock": ("docx4j_py.wml", "STLock"),
    "STMailMergeDataType": ("docx4j_py.wml", "STMailMergeDataType"),
    "STMailMergeDest": ("docx4j_py.wml", "STMailMergeDest"),
    "STMailMergeDocType": ("docx4j_py.wml", "STMailMergeDocType"),
    "STMailMergeOdsoFMDFieldType": ("docx4j_py.wml", "STMailMergeOdsoFMDFieldType"),
    "STMailMergeSourceType": ("docx4j_py.wml", "STMailMergeSourceType"),
    "STPTabAlignment": ("docx4j_py.wml", "STPTabAlignment"),
    "STPTabLeader": ("docx4j_py.wml", "STPTabLeader"),
    "STPTabRelativeTo": ("docx4j_py.wml", "STPTabRelativeTo"),
    "STPageBorderDisplay": ("docx4j_py.wml", "STPageBorderDisplay"),
    "STPageBorderOffset": ("docx4j_py.wml", "STPageBorderOffset"),
    "STPageBorderZOrder": ("docx4j_py.wml", "STPageBorderZOrder"),
    "STPageOrientation": ("docx4j_py.wml", "STPageOrientation"),
    "STPitch": ("docx4j_py.wml", "STPitch"),
    "STProof": ("docx4j_py.wml", "STProof"),
    "STRestartNumber": ("docx4j_py.wml", "STRestartNumber"),
    "STRubyAlign": ("docx4j_py.wml", "STRubyAlign"),
    "STSdtDateMappingType": ("docx4j_py.wml", "STSdtDateMappingType"),
    "STShd": ("docx4j_py.wml", "STShd"),
    "STTabJc": ("docx4j_py.wml", "STTabJc"),
    "STTabTlc": ("docx4j_py.wml", "STTabTlc"),
    "STTblLayoutType": ("docx4j_py.wml", "STTblLayoutType"),
    "STTblOverlap": ("docx4j_py.wml", "STTblOverlap"),
    "STTblStyleOverrideType": ("docx4j_py.wml", "STTblStyleOverrideType"),
    "STTextEffect": ("docx4j_py.wml", "STTextEffect"),
    "STTextboxTightWrap": ("docx4j_py.wml", "STTextboxTightWrap"),
    "STTheme": ("docx4j_py.wml", "STTheme"),
    "STThemeColor": ("docx4j_py.wml", "STThemeColor"),
    "STVAnchor": ("docx4j_py.wml", "STVAnchor"),
    "STVerticalAlignRun": ("docx4j_py.wml", "STVerticalAlignRun"),
    "STVerticalJc": ("docx4j_py.wml", "STVerticalJc"),
    "STView": ("docx4j_py.wml", "STView"),
    "STWrap": ("docx4j_py.wml", "STWrap"),
    "WmlStxalign": ("docx4j_py.wml", "STXAlign"),
    "WmlStyalign": ("docx4j_py.wml", "STYAlign"),
    "STZoom": ("docx4j_py.wml", "STZoom"),
    "WmlStOnOff": ("docx4j_py.wml", "StOnOff"),
    "StTargetScreenSz": ("docx4j_py.wml", "StTargetScreenSz"),
    "SdtBlock": ("docx4j_py.wml", "SdtBlock"),
    "SdtContentBlock": ("docx4j_py.wml", "SdtContentBlock"),
    "SdtPr": ("docx4j_py.wml", "SdtPr"),
    "SdtRun": ("docx4j_py.wml", "SdtRun"),
    "SectPr": ("docx4j_py.wml", "SectPr"),
    "SectPrBase": ("docx4j_py.wml", "SectPrBase"),
    "Style": ("docx4j_py.wml", "Style"),
    "Styles": ("docx4j_py.wml", "Styles"),
    "Tabs": ("docx4j_py.wml", "Tabs"),
    "Tag": ("docx4j_py.wml", "Tag"),
    "Tbl": ("docx4j_py.wml", "Tbl"),
    "TblBorders": ("docx4j_py.wml", "TblBorders"),
    "TblGrid": ("docx4j_py.wml", "TblGrid"),
    "TblGridBase": ("docx4j_py.wml", "TblGridBase"),
    "TblGridCol": ("docx4j_py.wml", "TblGridCol"),
    "TblPr": ("docx4j_py.wml", "TblPr"),
    "TblWidth": ("docx4j_py.wml", "TblWidth"),
    "Tc": ("docx4j_py.wml", "Tc"),
    "TcMar": ("docx4j_py.wml", "TcMar"),
    "TcPr": ("docx4j_py.wml", "TcPr"),
    "TcPrInner": ("docx4j_py.wml", "TcPrInner"),
    "Text": ("docx4j_py.wml", "Text"),
    "TextDirection": ("docx4j_py.wml", "TextDirection"),
    "Tr": ("docx4j_py.wml", "Tr"),
    "TrPr": ("docx4j_py.wml", "TrPr"),
    "U": ("docx4j_py.wml", "U"),
    "UnderlineEnumeration": ("docx4j_py.wml", "UnderlineEnumeration"),
    "Body": ("docx4j_py.wml", "Body"),
    "CalcOnExit": ("docx4j_py.wml", "CalcOnExit"),
    "CantSplit": ("docx4j_py.wml", "CantSplit"),
    "CellDel": ("docx4j_py.wml", "CellDel"),
    "CellIns": ("docx4j_py.wml", "CellIns"),
    "CommentsComment": ("docx4j_py.wml", "CommentsComment"),
    "CustomXmlDelRangeEnd1": ("docx4j_py.wml", "CustomXmlDelRangeEnd1"),
    "CustomXmlDelRangeEnd2": ("docx4j_py.wml", "CustomXmlDelRangeEnd2"),
    "CustomXmlDelRangeStart1": ("docx4j_py.wml", "CustomXmlDelRangeStart1"),
    "CustomXmlDelRangeStart2": ("docx4j_py.wml", "CustomXmlDelRangeStart2"),
    "CustomXmlInsRangeEnd1": ("docx4j_py.wml", "CustomXmlInsRangeEnd1"),
    "CustomXmlInsRangeEnd2": ("docx4j_py.wml", "CustomXmlInsRangeEnd2"),
    "CustomXmlInsRangeStart1": ("docx4j_py.wml", "CustomXmlInsRangeStart1"),
    "CustomXmlInsRangeStart2": ("docx4j_py.wml", "CustomXmlInsRangeStart2"),
    "CustomXmlMoveFromRangeEnd1": ("docx4j_py.wml", "CustomXmlMoveFromRangeEnd1"),
    "CustomXmlMoveFromRangeEnd2": ("docx4j_py.wml", "CustomXmlMoveFromRangeEnd2"),
    "CustomXmlMoveFromRangeStart1": ("docx4j_py.wml", "CustomXmlMoveFromRangeStart1"),
    "CustomXmlMoveFromRangeStart2": ("docx4j_py.wml", "CustomXmlMoveFromRangeStart2"),
    "CustomXmlMoveToRangeEnd1": ("docx4j_py.wml", "CustomXmlMoveToRangeEnd1"),
    "CustomXmlMoveToRangeEnd2": ("docx4j_py.wml", "CustomXmlMoveToRangeEnd2"),
    "CustomXmlMoveToRangeStart1": ("docx4j_py.wml", "CustomXmlMoveToRangeStart1"),
    "CustomXmlMoveToRangeStart2": ("docx4j_py.wml", "CustomXmlMoveToRangeStart2"),
    "DelInstrText": ("docx4j_py.wml", "DelInstrText"),
    "Del1": ("docx4j_py.wml", "Del1"),
    "Del2": ("docx4j_py.wml", "Del2"),
    "DocDefaultsPPrDefault": ("docx4j_py.wml", "DocDefaultsPPrDefault"),
    "DocDefaultsRPrDefault": ("docx4j_py.wml", "DocDefaultsRPrDefault"),
    "DocPartList": ("docx4j_py.wml", "DocPartList"),
    "DocPartObj": ("docx4j_py.wml", "DocPartObj"),
    "Enabled": ("docx4j_py.wml", "Enabled"),
    "EndnoteReference1": ("docx4j_py.wml", "EndnoteReference1"),
    "EndnoteReference2": ("docx4j_py.wml", "EndnoteReference2"),
    "Endnotes": ("docx4j_py.wml", "Endnotes"),
    "EntryMacro": ("docx4j_py.wml", "EntryMacro"),
    "ExitMacro": ("docx4j_py.wml", "ExitMacro"),
    "FontsFont": ("docx4j_py.wml", "FontsFont"),
    "FontsFontAltName": ("docx4j_py.wml", "FontsFontAltName"),
    "FootnoteReference1": ("docx4j_py.wml", "FootnoteReference1"),
    "FootnoteReference2": ("docx4j_py.wml", "FootnoteReference2"),
    "Footnotes": ("docx4j_py.wml", "Footnotes"),
    "Hidden": ("docx4j_py.wml", "Hidden"),
    "HighlightVal": ("docx4j_py.wml", "HighlightVal"),
    "Ins1": ("docx4j_py.wml", "Ins1"),
    "Ins2": ("docx4j_py.wml", "Ins2"),
    "InstrText": ("docx4j_py.wml", "InstrText"),
    "MoveFromRangeStart1": ("docx4j_py.wml", "MoveFromRangeStart1"),
    "MoveFromRangeStart2": ("docx4j_py.wml", "MoveFromRangeStart2"),
    "MoveFrom1": ("docx4j_py.wml", "MoveFrom1"),
    "MoveFrom2": ("docx4j_py.wml", "MoveFrom2"),
    "MoveToRangeStart1": ("docx4j_py.wml", "MoveToRangeStart1"),
    "MoveToRangeStart2": ("docx4j_py.wml", "MoveToRangeStart2"),
    "MoveTo1": ("docx4j_py.wml", "MoveTo1"),
    "MoveTo2": ("docx4j_py.wml", "MoveTo2"),
    "NumberingAbstractNum": ("docx4j_py.wml", "NumberingAbstractNum"),
    "NumberingAbstractNumMultiLevelType": ("docx4j_py.wml", "NumberingAbstractNumMultiLevelType"),
    "NumberingAbstractNumMultiLevelTypeVal": (
        "docx4j_py.wml",
        "NumberingAbstractNumMultiLevelTypeVal",
    ),
    "NumberingAbstractNumName": ("docx4j_py.wml", "NumberingAbstractNumName"),
    "NumberingAbstractNumNumStyleLink": ("docx4j_py.wml", "NumberingAbstractNumNumStyleLink"),
    "NumberingAbstractNumStyleLink": ("docx4j_py.wml", "NumberingAbstractNumStyleLink"),
    "NumberingNum": ("docx4j_py.wml", "NumberingNum"),
    "NumberingNumIdMacAtCleanup": ("docx4j_py.wml", "NumberingNumIdMacAtCleanup"),
    "NumberingNumPicBullet": ("docx4j_py.wml", "NumberingNumPicBullet"),
    "NumberingNumAbstractNumId": ("docx4j_py.wml", "NumberingNumAbstractNumId"),
    "NumberingNumLvlOverride": ("docx4j_py.wml", "NumberingNumLvlOverride"),
    "NumberingNumLvlOverrideStartOverride": (
        "docx4j_py.wml",
        "NumberingNumLvlOverrideStartOverride",
    ),
    "PHyperlink": ("docx4j_py.wml", "PHyperlink"),
    "ProofErrType": ("docx4j_py.wml", "ProofErrType"),
    "RAnnotationRef": ("docx4j_py.wml", "RAnnotationRef"),
    "RCommentReference": ("docx4j_py.wml", "RCommentReference"),
    "RContinuationSeparator": ("docx4j_py.wml", "RContinuationSeparator"),
    "RCr": ("docx4j_py.wml", "RCr"),
    "RDayLong": ("docx4j_py.wml", "RDayLong"),
    "RDayShort": ("docx4j_py.wml", "RDayShort"),
    "REndnoteRef": ("docx4j_py.wml", "REndnoteRef"),
    "RFootnoteRef": ("docx4j_py.wml", "RFootnoteRef"),
    "RLastRenderedPageBreak": ("docx4j_py.wml", "RLastRenderedPageBreak"),
    "RMonthLong": ("docx4j_py.wml", "RMonthLong"),
    "RMonthShort": ("docx4j_py.wml", "RMonthShort"),
    "RNoBreakHyphen": ("docx4j_py.wml", "RNoBreakHyphen"),
    "RPgNum": ("docx4j_py.wml", "RPgNum"),
    "RPtab": ("docx4j_py.wml", "RPtab"),
    "RSeparator": ("docx4j_py.wml", "RSeparator"),
    "RSoftHyphen": ("docx4j_py.wml", "RSoftHyphen"),
    "RSym": ("docx4j_py.wml", "RSym"),
    "RTab": ("docx4j_py.wml", "RTab"),
    "RYearLong": ("docx4j_py.wml", "RYearLong"),
    "RYearShort": ("docx4j_py.wml", "RYearShort"),
    "Recipients": ("docx4j_py.wml", "Recipients"),
    "Settings": ("docx4j_py.wml", "Settings"),
    "ShowingPlcHdr": ("docx4j_py.wml", "ShowingPlcHdr"),
    "StyleAliases": ("docx4j_py.wml", "StyleAliases"),
    "StyleBasedOn": ("docx4j_py.wml", "StyleBasedOn"),
    "StyleLink": ("docx4j_py.wml", "StyleLink"),
    "StyleName": ("docx4j_py.wml", "StyleName"),
    "StyleNext": ("docx4j_py.wml", "StyleNext"),
    "StyleType": ("docx4j_py.wml", "StyleType"),
    "StyleUiPriority": ("docx4j_py.wml", "StyleUiPriority"),
    "StylesLatentStyles": ("docx4j_py.wml", "StylesLatentStyles"),
    "StylesLatentStylesLsdException": ("docx4j_py.wml", "StylesLatentStylesLsdException"),
    "T": ("docx4j_py.wml", "T"),
    "TblCellSpacing": ("docx4j_py.wml", "TblCellSpacing"),
    "TblHeader": ("docx4j_py.wml", "TblHeader"),
    "Temporary": ("docx4j_py.wml", "Temporary"),
    "TxbxContent": ("docx4j_py.wml", "TxbxContent"),
    "WAfter": ("docx4j_py.wml", "WAfter"),
    "WBefore": ("docx4j_py.wml", "WBefore"),
    "WebSettings": ("docx4j_py.wml", "WebSettings"),
    "CTAcd": ("docx4j_py.wne", "CTAcd"),
    "CTAcdKeymap": ("docx4j_py.wne", "CTAcdKeymap"),
    "CTAcdManifest": ("docx4j_py.wne", "CTAcdManifest"),
    "CTAcds": ("docx4j_py.wne", "CTAcds"),
    "CTDocEvents": ("docx4j_py.wne", "CTDocEvents"),
    "CTFci": ("docx4j_py.wne", "CTFci"),
    "CTKeymap": ("docx4j_py.wne", "CTKeymap"),
    "CTKeymaps": ("docx4j_py.wne", "CTKeymaps"),
    "WneCtlongHexNumber": ("docx4j_py.wne", "CTLongHexNumber"),
    "CTMacroWll": ("docx4j_py.wne", "CTMacroWll"),
    "CTMcd": ("docx4j_py.wne", "CTMcd"),
    "CTMcds": ("docx4j_py.wne", "CTMcds"),
    "WneCtrel": ("docx4j_py.wne", "CTRel"),
    "CTTcg": ("docx4j_py.wne", "CTTcg"),
    "CTToolbars": ("docx4j_py.wne", "CTToolbars"),
    "CTVbaSuppData": ("docx4j_py.wne", "CTVbaSuppData"),
    "WneStOnOff": ("docx4j_py.wne", "StOnOff"),
    "Macro": ("docx4j_py.wne", "Macro"),
    "Tcg": ("docx4j_py.wne", "Tcg"),
    "VbaSuppData": ("docx4j_py.wne", "VbaSuppData"),
    "Wll": ("docx4j_py.wne", "Wll"),
    "LangValue": ("docx4j_py.xml_ns", "LangValue"),
    "SpaceValue": ("docx4j_py.xml_ns", "SpaceValue"),
}


def __getattr__(name: str) -> object:
    """Import a re-exported class on first use."""
    target = __lazy_imports__.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    value = getattr(import_module(target[0]), target[1])
    globals()[name] = value
    return value


# Import order matters here: these modules import each other, and the
# names each of them only needs once its own classes exist are imported
# at the bottom of that module. Importing them in dependency order makes
# every entry point into this package safe.
# isort: off
import docx4j_py.customxml  # noqa: F401
import docx4j_py.dml.main  # noqa: F401
import docx4j_py.dml.chart_drawing  # noqa: F401
import docx4j_py.dml.chart  # noqa: F401
import docx4j_py.dml.compatibility  # noqa: F401
import docx4j_py.dml.diagram  # noqa: F401
import docx4j_py.dml.locked_canvas  # noqa: F401
import docx4j_py.dml.picture  # noqa: F401
import docx4j_py.dml.spreadsheet_drawing  # noqa: F401
import docx4j_py.word.wp14  # noqa: F401
import docx4j_py.dml.wordprocessing_drawing  # noqa: F401
import docx4j_py.docprops.dcmitype  # noqa: F401
import docx4j_py.xml_ns  # noqa: F401
import docx4j_py.docprops.dc  # noqa: F401
import docx4j_py.docprops.dcterms  # noqa: F401
import docx4j_py.docprops.core  # noqa: F401
import docx4j_py.docprops.variant_types  # noqa: F401
import docx4j_py.docprops.custom  # noqa: F401
import docx4j_py.docprops.extended  # noqa: F401
import docx4j_py.mathml  # noqa: F401
import docx4j_py.inkml  # noqa: F401
import docx4j_py.mce  # noqa: F401
import docx4j_py.shared_types  # noqa: F401
import docx4j_py.oart.main_2010  # noqa: F401
import docx4j_py.math  # noqa: F401
import docx4j_py.wml  # noqa: F401
import docx4j_py.w14  # noqa: F401
import docx4j_py.w15  # noqa: F401
import docx4j_py.oart.animation_2018  # noqa: F401
import docx4j_py.oart.animation_model3d_2018  # noqa: F401
import docx4j_py.oart.chart_2007  # noqa: F401
import docx4j_py.oart.chart_2012  # noqa: F401
import docx4j_py.oart.chart_2014  # noqa: F401
import docx4j_py.oart.chart_2017_03  # noqa: F401
import docx4j_py.oart.chart_ac_2014  # noqa: F401
import docx4j_py.oart.chart_drawing_2010  # noqa: F401
import docx4j_py.oart.chart_style_2012  # noqa: F401
import docx4j_py.oart.chartex_2014  # noqa: F401
import docx4j_py.oart.command_2013  # noqa: F401
import docx4j_py.oart.decorative_2017  # noqa: F401
import docx4j_py.oart.diagram_2008  # noqa: F401
import docx4j_py.oart.diagram_2010  # noqa: F401
import docx4j_py.oart.diagram_2016_11  # noqa: F401
import docx4j_py.oart.diagram_2016_12  # noqa: F401
import docx4j_py.oart.hyperlink_color_2018  # noqa: F401
import docx4j_py.oart.ink_action_2014  # noqa: F401
import docx4j_py.oart.main_2012  # noqa: F401
import docx4j_py.oart.main_2014  # noqa: F401
import docx4j_py.oart.main_2016_11  # noqa: F401
import docx4j_py.oart.model3d_2017  # noqa: F401
import docx4j_py.oart.picture_2010  # noqa: F401
import docx4j_py.oart.spreadsheet_drawing_2010  # noqa: F401
import docx4j_py.oart.svg_2016  # noqa: F401
import docx4j_py.oart.theme_2012  # noqa: F401
import docx4j_py.relationships  # noqa: F401
import docx4j_py.wne  # noqa: F401
import docx4j_py.word.msink  # noqa: F401
import docx4j_py.word.wp15  # noqa: F401
import docx4j_py.word.wps  # noqa: F401
import docx4j_py.word.wpg  # noqa: F401
import docx4j_py.word.wpc  # noqa: F401
# isort: on


# CR-002 section 7: the engine, re-exported for the common case.
# Lazily, through a module __getattr__ (PEP 562): the engine imports the model,
# and the model is what this module's manifest above has just finished
# importing, so an eager import here would be a cycle.
_ENGINE: dict[str, str] = {
    "ContentError": "docx4j_py.model.content",
    "DocumentSession": "docx4j_py.model.sessions",
    "Docx4JException": "docx4j_py.openpackaging",
    "Font": "docx4j_py.model.content",
    "LoadOptions": "docx4j_py.openpackaging",
    "OpcPackage": "docx4j_py.openpackaging",
    "Paragraph": "docx4j_py.model.content",
    "PartName": "docx4j_py.openpackaging",
    "Range": "docx4j_py.model.content",
    "WordprocessingMLPackage": "docx4j_py.openpackaging",
    "create_package": "docx4j_py.openpackaging.api",
    "load": "docx4j_py.openpackaging.api"
}

# CR-003 section 5: the content API registers ``body`` on the parts and on the
# package when it is imported, and the parts layer never imports it back. One
# of the two has to move first, and this module -- which is neither layer, and
# has just finished importing the model both rest on -- is where they meet.
# It costs the engine's import, milliseconds on top of the model's.
import docx4j_py.model.content  # noqa: E402, F401


def __getattr__(name: str) -> object:
    """Import an engine name on first use. CR-002 section 7."""
    target = _ENGINE.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    from importlib import import_module

    value = getattr(import_module(target), name)
    globals()[name] = value
    return value
