"""``el`` for the http://schemas.microsoft.com/office/word/2010/wordml namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/w14.json``, which a human reviews.

    >>> from docx4j_py.w14 import el
    >>> el.alpha()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTNonVisualDrawingProps,
    CTOfficeArtExtensionList,
    CTTransform2D,
)
from docx4j_py.oart.main_2010 import (
    CTNonVisualInkContentPartProperties,
)
from docx4j_py.w14 import (
    Alpha,
    Bevel,
    CTBevel,
    CTCamera,
    CTColor,
    CTEmpty,
    CTFillTextEffect,
    CTGlow,
    CTGradientFillProperties,
    CTGradientStop,
    CTGradientStopList,
    CTLigatures,
    CTLightRig,
    CTLineJoinMiterProperties,
    CTLinearShadeProperties,
    CTMarkup,
    CTNumForm,
    CTNumSpacing,
    CTOnOff,
    CTPathShadeProperties,
    CTPositivePercentage,
    CTPresetLineDashProperties,
    CTProps3D,
    CTReflection,
    CTRelativeRect,
    CTSRgbColor,
    CTScene3D,
    CTSchemeColor,
    CTSdtCheckboxSymbol,
    CTSolidColorFillProperties,
    CTSphereCoords,
    CTStyleSet,
    CTStylisticSets,
    CTTextOutlineEffect,
    CTTrackChange,
    CTWordContentPartNonVisual,
    Checkbox,
    ConflictMode,
    ContentPart,
    CustomXmlConflictDelRangeEnd,
    CustomXmlConflictDelRangeStart,
    DefaultImageDpi,
    DiscardImageEditingData,
    DocId,
    Lum,
    LumMod,
    LumOff,
    Round,
    Sat,
    SatMod,
    SatOff,
    Shade,
    Shadow,
    Tint,
)
from docx4j_py.wml import (
    CTEmpty,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/word/2010/wordml"

def alpha(**kwargs: Any) -> Alpha:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}alpha`` -> :class:`docx4j_py.w14.Alpha`."""
    return Alpha(**kwargs)

def bevel(**kwargs: Any) -> Bevel:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}bevel`` -> :class:`docx4j_py.w14.Bevel`."""
    return Bevel(**kwargs)

def bevelB(**kwargs: Any) -> CTBevel:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}bevelB`` -> :class:`docx4j_py.w14.CTBevel`."""
    return CTBevel(**kwargs)

def bevelT(**kwargs: Any) -> CTBevel:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}bevelT`` -> :class:`docx4j_py.w14.CTBevel`."""
    return CTBevel(**kwargs)

def cNvContentPartPr(**kwargs: Any) -> CTNonVisualInkContentPartProperties:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}cNvContentPartPr`` -> :class:`docx4j_py.oart.main_2010.CTNonVisualInkContentPartProperties`."""
    return CTNonVisualInkContentPartProperties(**kwargs)

def cNvPr(**kwargs: Any) -> CTNonVisualDrawingProps:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}cNvPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingProps`."""
    return CTNonVisualDrawingProps(**kwargs)

def camera(**kwargs: Any) -> CTCamera:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}camera`` -> :class:`docx4j_py.w14.CTCamera`."""
    return CTCamera(**kwargs)

def checkbox(**kwargs: Any) -> Checkbox:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}checkbox`` -> :class:`docx4j_py.w14.Checkbox`."""
    return Checkbox(**kwargs)

def checked(**kwargs: Any) -> CTOnOff:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}checked`` -> :class:`docx4j_py.w14.CTOnOff`."""
    return CTOnOff(**kwargs)

def checkedState(**kwargs: Any) -> CTSdtCheckboxSymbol:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}checkedState`` -> :class:`docx4j_py.w14.CTSdtCheckboxSymbol`."""
    return CTSdtCheckboxSymbol(**kwargs)

def cntxtAlts(**kwargs: Any) -> CTOnOff:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}cntxtAlts`` -> :class:`docx4j_py.w14.CTOnOff`."""
    return CTOnOff(**kwargs)

def conflictMode(**kwargs: Any) -> ConflictMode:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}conflictMode`` -> :class:`docx4j_py.w14.ConflictMode`."""
    return ConflictMode(**kwargs)

def contentPart(**kwargs: Any) -> ContentPart:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}contentPart`` -> :class:`docx4j_py.w14.ContentPart`."""
    return ContentPart(**kwargs)

def contourClr(**kwargs: Any) -> CTColor:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}contourClr`` -> :class:`docx4j_py.w14.CTColor`."""
    return CTColor(**kwargs)

def customXmlConflictDelRangeEnd(**kwargs: Any) -> CustomXmlConflictDelRangeEnd:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictDelRangeEnd`` -> :class:`docx4j_py.w14.CustomXmlConflictDelRangeEnd`."""
    return CustomXmlConflictDelRangeEnd(**kwargs)

def customXmlConflictDelRangeStart(**kwargs: Any) -> CustomXmlConflictDelRangeStart:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictDelRangeStart`` -> :class:`docx4j_py.w14.CustomXmlConflictDelRangeStart`."""
    return CustomXmlConflictDelRangeStart(**kwargs)

def customXmlConflictInsRangeEnd(**kwargs: Any) -> CTMarkup:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictInsRangeEnd`` -> :class:`docx4j_py.w14.CTMarkup`."""
    return CTMarkup(**kwargs)

def customXmlConflictInsRangeStart(**kwargs: Any) -> CTTrackChange:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictInsRangeStart`` -> :class:`docx4j_py.w14.CTTrackChange`."""
    return CTTrackChange(**kwargs)

def defaultImageDpi(**kwargs: Any) -> DefaultImageDpi:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}defaultImageDpi`` -> :class:`docx4j_py.w14.DefaultImageDpi`."""
    return DefaultImageDpi(**kwargs)

def discardImageEditingData(**kwargs: Any) -> DiscardImageEditingData:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}discardImageEditingData`` -> :class:`docx4j_py.w14.DiscardImageEditingData`."""
    return DiscardImageEditingData(**kwargs)

def docId(**kwargs: Any) -> DocId:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}docId`` -> :class:`docx4j_py.w14.DocId`."""
    return DocId(**kwargs)

def entityPicker(**kwargs: Any) -> CTEmpty:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}entityPicker`` -> :class:`docx4j_py.w14.CTEmpty`."""
    return CTEmpty(**kwargs)

def extLst(**kwargs: Any) -> CTOfficeArtExtensionList:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}extLst`` -> :class:`docx4j_py.dml.main.CTOfficeArtExtensionList`."""
    return CTOfficeArtExtensionList(**kwargs)

def extrusionClr(**kwargs: Any) -> CTColor:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}extrusionClr`` -> :class:`docx4j_py.w14.CTColor`."""
    return CTColor(**kwargs)

def fillToRect(**kwargs: Any) -> CTRelativeRect:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}fillToRect`` -> :class:`docx4j_py.w14.CTRelativeRect`."""
    return CTRelativeRect(**kwargs)

def glow(**kwargs: Any) -> CTGlow:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}glow`` -> :class:`docx4j_py.w14.CTGlow`."""
    return CTGlow(**kwargs)

def gradFill(**kwargs: Any) -> CTGradientFillProperties:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}gradFill`` -> :class:`docx4j_py.w14.CTGradientFillProperties`."""
    return CTGradientFillProperties(**kwargs)

def gs(**kwargs: Any) -> CTGradientStop:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}gs`` -> :class:`docx4j_py.w14.CTGradientStop`."""
    return CTGradientStop(**kwargs)

def gsLst(**kwargs: Any) -> CTGradientStopList:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}gsLst`` -> :class:`docx4j_py.w14.CTGradientStopList`."""
    return CTGradientStopList(**kwargs)

def hueMod(**kwargs: Any) -> CTPositivePercentage:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}hueMod`` -> :class:`docx4j_py.w14.CTPositivePercentage`."""
    return CTPositivePercentage(**kwargs)

def ligatures(**kwargs: Any) -> CTLigatures:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}ligatures`` -> :class:`docx4j_py.w14.CTLigatures`."""
    return CTLigatures(**kwargs)

def lightRig(**kwargs: Any) -> CTLightRig:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}lightRig`` -> :class:`docx4j_py.w14.CTLightRig`."""
    return CTLightRig(**kwargs)

def lin(**kwargs: Any) -> CTLinearShadeProperties:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}lin`` -> :class:`docx4j_py.w14.CTLinearShadeProperties`."""
    return CTLinearShadeProperties(**kwargs)

def lum(**kwargs: Any) -> Lum:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}lum`` -> :class:`docx4j_py.w14.Lum`."""
    return Lum(**kwargs)

def lumMod(**kwargs: Any) -> LumMod:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}lumMod`` -> :class:`docx4j_py.w14.LumMod`."""
    return LumMod(**kwargs)

def lumOff(**kwargs: Any) -> LumOff:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}lumOff`` -> :class:`docx4j_py.w14.LumOff`."""
    return LumOff(**kwargs)

def miter(**kwargs: Any) -> CTLineJoinMiterProperties:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}miter`` -> :class:`docx4j_py.w14.CTLineJoinMiterProperties`."""
    return CTLineJoinMiterProperties(**kwargs)

def noFill(**kwargs: Any) -> CTEmpty:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}noFill`` -> :class:`docx4j_py.wml.CTEmpty`."""
    return CTEmpty(**kwargs)

def numForm(**kwargs: Any) -> CTNumForm:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}numForm`` -> :class:`docx4j_py.w14.CTNumForm`."""
    return CTNumForm(**kwargs)

def numSpacing(**kwargs: Any) -> CTNumSpacing:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}numSpacing`` -> :class:`docx4j_py.w14.CTNumSpacing`."""
    return CTNumSpacing(**kwargs)

def nvContentPartPr(**kwargs: Any) -> CTWordContentPartNonVisual:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}nvContentPartPr`` -> :class:`docx4j_py.w14.CTWordContentPartNonVisual`."""
    return CTWordContentPartNonVisual(**kwargs)

def path(**kwargs: Any) -> CTPathShadeProperties:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}path`` -> :class:`docx4j_py.w14.CTPathShadeProperties`."""
    return CTPathShadeProperties(**kwargs)

def props3d(**kwargs: Any) -> CTProps3D:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}props3d`` -> :class:`docx4j_py.w14.CTProps3D`."""
    return CTProps3D(**kwargs)

def prstDash(**kwargs: Any) -> CTPresetLineDashProperties:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}prstDash`` -> :class:`docx4j_py.w14.CTPresetLineDashProperties`."""
    return CTPresetLineDashProperties(**kwargs)

def reflection(**kwargs: Any) -> CTReflection:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}reflection`` -> :class:`docx4j_py.w14.CTReflection`."""
    return CTReflection(**kwargs)

def rot(**kwargs: Any) -> CTSphereCoords:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}rot`` -> :class:`docx4j_py.w14.CTSphereCoords`."""
    return CTSphereCoords(**kwargs)

def round_(**kwargs: Any) -> Round:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}round`` -> :class:`docx4j_py.w14.Round`."""
    return Round(**kwargs)

def sat(**kwargs: Any) -> Sat:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}sat`` -> :class:`docx4j_py.w14.Sat`."""
    return Sat(**kwargs)

def satMod(**kwargs: Any) -> SatMod:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}satMod`` -> :class:`docx4j_py.w14.SatMod`."""
    return SatMod(**kwargs)

def satOff(**kwargs: Any) -> SatOff:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}satOff`` -> :class:`docx4j_py.w14.SatOff`."""
    return SatOff(**kwargs)

def scene3d(**kwargs: Any) -> CTScene3D:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}scene3d`` -> :class:`docx4j_py.w14.CTScene3D`."""
    return CTScene3D(**kwargs)

def schemeClr(**kwargs: Any) -> CTSchemeColor:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}schemeClr`` -> :class:`docx4j_py.w14.CTSchemeColor`."""
    return CTSchemeColor(**kwargs)

def shade(**kwargs: Any) -> Shade:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}shade`` -> :class:`docx4j_py.w14.Shade`."""
    return Shade(**kwargs)

def shadow(**kwargs: Any) -> Shadow:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}shadow`` -> :class:`docx4j_py.w14.Shadow`."""
    return Shadow(**kwargs)

def solidFill(**kwargs: Any) -> CTSolidColorFillProperties:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}solidFill`` -> :class:`docx4j_py.w14.CTSolidColorFillProperties`."""
    return CTSolidColorFillProperties(**kwargs)

def srgbClr(**kwargs: Any) -> CTSRgbColor:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}srgbClr`` -> :class:`docx4j_py.w14.CTSRgbColor`."""
    return CTSRgbColor(**kwargs)

def styleSet(**kwargs: Any) -> CTStyleSet:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}styleSet`` -> :class:`docx4j_py.w14.CTStyleSet`."""
    return CTStyleSet(**kwargs)

def stylisticSets(**kwargs: Any) -> CTStylisticSets:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}stylisticSets`` -> :class:`docx4j_py.w14.CTStylisticSets`."""
    return CTStylisticSets(**kwargs)

def textFill(**kwargs: Any) -> CTFillTextEffect:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}textFill`` -> :class:`docx4j_py.w14.CTFillTextEffect`."""
    return CTFillTextEffect(**kwargs)

def textOutline(**kwargs: Any) -> CTTextOutlineEffect:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}textOutline`` -> :class:`docx4j_py.w14.CTTextOutlineEffect`."""
    return CTTextOutlineEffect(**kwargs)

def tint(**kwargs: Any) -> Tint:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}tint`` -> :class:`docx4j_py.w14.Tint`."""
    return Tint(**kwargs)

def uncheckedState(**kwargs: Any) -> CTSdtCheckboxSymbol:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}uncheckedState`` -> :class:`docx4j_py.w14.CTSdtCheckboxSymbol`."""
    return CTSdtCheckboxSymbol(**kwargs)

def xfrm(**kwargs: Any) -> CTTransform2D:
    """``{http://schemas.microsoft.com/office/word/2010/wordml}xfrm`` -> :class:`docx4j_py.dml.main.CTTransform2D`."""
    return CTTransform2D(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/word/2010/wordml}alpha": Alpha,
    "{http://schemas.microsoft.com/office/word/2010/wordml}bevel": Bevel,
    "{http://schemas.microsoft.com/office/word/2010/wordml}bevelB": CTBevel,
    "{http://schemas.microsoft.com/office/word/2010/wordml}bevelT": CTBevel,
    "{http://schemas.microsoft.com/office/word/2010/wordml}cNvContentPartPr": CTNonVisualInkContentPartProperties,
    "{http://schemas.microsoft.com/office/word/2010/wordml}cNvPr": CTNonVisualDrawingProps,
    "{http://schemas.microsoft.com/office/word/2010/wordml}camera": CTCamera,
    "{http://schemas.microsoft.com/office/word/2010/wordml}checkbox": Checkbox,
    "{http://schemas.microsoft.com/office/word/2010/wordml}checked": CTOnOff,
    "{http://schemas.microsoft.com/office/word/2010/wordml}checkedState": CTSdtCheckboxSymbol,
    "{http://schemas.microsoft.com/office/word/2010/wordml}cntxtAlts": CTOnOff,
    "{http://schemas.microsoft.com/office/word/2010/wordml}conflictMode": ConflictMode,
    "{http://schemas.microsoft.com/office/word/2010/wordml}contentPart": ContentPart,
    "{http://schemas.microsoft.com/office/word/2010/wordml}contourClr": CTColor,
    "{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictDelRangeEnd": CustomXmlConflictDelRangeEnd,
    "{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictDelRangeStart": CustomXmlConflictDelRangeStart,
    "{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictInsRangeEnd": CTMarkup,
    "{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictInsRangeStart": CTTrackChange,
    "{http://schemas.microsoft.com/office/word/2010/wordml}defaultImageDpi": DefaultImageDpi,
    "{http://schemas.microsoft.com/office/word/2010/wordml}discardImageEditingData": DiscardImageEditingData,
    "{http://schemas.microsoft.com/office/word/2010/wordml}docId": DocId,
    "{http://schemas.microsoft.com/office/word/2010/wordml}entityPicker": CTEmpty,
    "{http://schemas.microsoft.com/office/word/2010/wordml}extLst": CTOfficeArtExtensionList,
    "{http://schemas.microsoft.com/office/word/2010/wordml}extrusionClr": CTColor,
    "{http://schemas.microsoft.com/office/word/2010/wordml}fillToRect": CTRelativeRect,
    "{http://schemas.microsoft.com/office/word/2010/wordml}glow": CTGlow,
    "{http://schemas.microsoft.com/office/word/2010/wordml}gradFill": CTGradientFillProperties,
    "{http://schemas.microsoft.com/office/word/2010/wordml}gs": CTGradientStop,
    "{http://schemas.microsoft.com/office/word/2010/wordml}gsLst": CTGradientStopList,
    "{http://schemas.microsoft.com/office/word/2010/wordml}hueMod": CTPositivePercentage,
    "{http://schemas.microsoft.com/office/word/2010/wordml}ligatures": CTLigatures,
    "{http://schemas.microsoft.com/office/word/2010/wordml}lightRig": CTLightRig,
    "{http://schemas.microsoft.com/office/word/2010/wordml}lin": CTLinearShadeProperties,
    "{http://schemas.microsoft.com/office/word/2010/wordml}lum": Lum,
    "{http://schemas.microsoft.com/office/word/2010/wordml}lumMod": LumMod,
    "{http://schemas.microsoft.com/office/word/2010/wordml}lumOff": LumOff,
    "{http://schemas.microsoft.com/office/word/2010/wordml}miter": CTLineJoinMiterProperties,
    "{http://schemas.microsoft.com/office/word/2010/wordml}noFill": CTEmpty,
    "{http://schemas.microsoft.com/office/word/2010/wordml}numForm": CTNumForm,
    "{http://schemas.microsoft.com/office/word/2010/wordml}numSpacing": CTNumSpacing,
    "{http://schemas.microsoft.com/office/word/2010/wordml}nvContentPartPr": CTWordContentPartNonVisual,
    "{http://schemas.microsoft.com/office/word/2010/wordml}path": CTPathShadeProperties,
    "{http://schemas.microsoft.com/office/word/2010/wordml}props3d": CTProps3D,
    "{http://schemas.microsoft.com/office/word/2010/wordml}prstDash": CTPresetLineDashProperties,
    "{http://schemas.microsoft.com/office/word/2010/wordml}reflection": CTReflection,
    "{http://schemas.microsoft.com/office/word/2010/wordml}rot": CTSphereCoords,
    "{http://schemas.microsoft.com/office/word/2010/wordml}round": Round,
    "{http://schemas.microsoft.com/office/word/2010/wordml}sat": Sat,
    "{http://schemas.microsoft.com/office/word/2010/wordml}satMod": SatMod,
    "{http://schemas.microsoft.com/office/word/2010/wordml}satOff": SatOff,
    "{http://schemas.microsoft.com/office/word/2010/wordml}scene3d": CTScene3D,
    "{http://schemas.microsoft.com/office/word/2010/wordml}schemeClr": CTSchemeColor,
    "{http://schemas.microsoft.com/office/word/2010/wordml}shade": Shade,
    "{http://schemas.microsoft.com/office/word/2010/wordml}shadow": Shadow,
    "{http://schemas.microsoft.com/office/word/2010/wordml}solidFill": CTSolidColorFillProperties,
    "{http://schemas.microsoft.com/office/word/2010/wordml}srgbClr": CTSRgbColor,
    "{http://schemas.microsoft.com/office/word/2010/wordml}styleSet": CTStyleSet,
    "{http://schemas.microsoft.com/office/word/2010/wordml}stylisticSets": CTStylisticSets,
    "{http://schemas.microsoft.com/office/word/2010/wordml}textFill": CTFillTextEffect,
    "{http://schemas.microsoft.com/office/word/2010/wordml}textOutline": CTTextOutlineEffect,
    "{http://schemas.microsoft.com/office/word/2010/wordml}tint": Tint,
    "{http://schemas.microsoft.com/office/word/2010/wordml}uncheckedState": CTSdtCheckboxSymbol,
    "{http://schemas.microsoft.com/office/word/2010/wordml}xfrm": CTTransform2D,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "alpha": Alpha,
    "bevel": Bevel,
    "bevelB": CTBevel,
    "bevelT": CTBevel,
    "cNvContentPartPr": CTNonVisualInkContentPartProperties,
    "cNvPr": CTNonVisualDrawingProps,
    "camera": CTCamera,
    "checkbox": Checkbox,
    "checked": CTOnOff,
    "checkedState": CTSdtCheckboxSymbol,
    "cntxtAlts": CTOnOff,
    "conflictMode": ConflictMode,
    "contentPart": ContentPart,
    "contourClr": CTColor,
    "customXmlConflictDelRangeEnd": CustomXmlConflictDelRangeEnd,
    "customXmlConflictDelRangeStart": CustomXmlConflictDelRangeStart,
    "customXmlConflictInsRangeEnd": CTMarkup,
    "customXmlConflictInsRangeStart": CTTrackChange,
    "defaultImageDpi": DefaultImageDpi,
    "discardImageEditingData": DiscardImageEditingData,
    "docId": DocId,
    "entityPicker": CTEmpty,
    "extLst": CTOfficeArtExtensionList,
    "extrusionClr": CTColor,
    "fillToRect": CTRelativeRect,
    "glow": CTGlow,
    "gradFill": CTGradientFillProperties,
    "gs": CTGradientStop,
    "gsLst": CTGradientStopList,
    "hueMod": CTPositivePercentage,
    "ligatures": CTLigatures,
    "lightRig": CTLightRig,
    "lin": CTLinearShadeProperties,
    "lum": Lum,
    "lumMod": LumMod,
    "lumOff": LumOff,
    "miter": CTLineJoinMiterProperties,
    "noFill": CTEmpty,
    "numForm": CTNumForm,
    "numSpacing": CTNumSpacing,
    "nvContentPartPr": CTWordContentPartNonVisual,
    "path": CTPathShadeProperties,
    "props3d": CTProps3D,
    "prstDash": CTPresetLineDashProperties,
    "reflection": CTReflection,
    "rot": CTSphereCoords,
    "round": Round,
    "sat": Sat,
    "satMod": SatMod,
    "satOff": SatOff,
    "scene3d": CTScene3D,
    "schemeClr": CTSchemeColor,
    "shade": Shade,
    "shadow": Shadow,
    "solidFill": CTSolidColorFillProperties,
    "srgbClr": CTSRgbColor,
    "styleSet": CTStyleSet,
    "stylisticSets": CTStylisticSets,
    "textFill": CTFillTextEffect,
    "textOutline": CTTextOutlineEffect,
    "tint": Tint,
    "uncheckedState": CTSdtCheckboxSymbol,
    "xfrm": CTTransform2D,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    Alpha: "{http://schemas.microsoft.com/office/word/2010/wordml}alpha",
    Bevel: "{http://schemas.microsoft.com/office/word/2010/wordml}bevel",
    CTCamera: "{http://schemas.microsoft.com/office/word/2010/wordml}camera",
    CTFillTextEffect: "{http://schemas.microsoft.com/office/word/2010/wordml}textFill",
    CTGlow: "{http://schemas.microsoft.com/office/word/2010/wordml}glow",
    CTGradientFillProperties: "{http://schemas.microsoft.com/office/word/2010/wordml}gradFill",
    CTGradientStop: "{http://schemas.microsoft.com/office/word/2010/wordml}gs",
    CTGradientStopList: "{http://schemas.microsoft.com/office/word/2010/wordml}gsLst",
    CTLigatures: "{http://schemas.microsoft.com/office/word/2010/wordml}ligatures",
    CTLightRig: "{http://schemas.microsoft.com/office/word/2010/wordml}lightRig",
    CTLineJoinMiterProperties: "{http://schemas.microsoft.com/office/word/2010/wordml}miter",
    CTLinearShadeProperties: "{http://schemas.microsoft.com/office/word/2010/wordml}lin",
    CTMarkup: "{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictInsRangeEnd",
    CTNonVisualDrawingProps: "{http://schemas.microsoft.com/office/word/2010/wordml}cNvPr",
    CTNonVisualInkContentPartProperties: "{http://schemas.microsoft.com/office/word/2010/wordml}cNvContentPartPr",
    CTNumForm: "{http://schemas.microsoft.com/office/word/2010/wordml}numForm",
    CTNumSpacing: "{http://schemas.microsoft.com/office/word/2010/wordml}numSpacing",
    CTOfficeArtExtensionList: "{http://schemas.microsoft.com/office/word/2010/wordml}extLst",
    CTPathShadeProperties: "{http://schemas.microsoft.com/office/word/2010/wordml}path",
    CTPositivePercentage: "{http://schemas.microsoft.com/office/word/2010/wordml}hueMod",
    CTPresetLineDashProperties: "{http://schemas.microsoft.com/office/word/2010/wordml}prstDash",
    CTProps3D: "{http://schemas.microsoft.com/office/word/2010/wordml}props3d",
    CTReflection: "{http://schemas.microsoft.com/office/word/2010/wordml}reflection",
    CTRelativeRect: "{http://schemas.microsoft.com/office/word/2010/wordml}fillToRect",
    CTSRgbColor: "{http://schemas.microsoft.com/office/word/2010/wordml}srgbClr",
    CTScene3D: "{http://schemas.microsoft.com/office/word/2010/wordml}scene3d",
    CTSchemeColor: "{http://schemas.microsoft.com/office/word/2010/wordml}schemeClr",
    CTSolidColorFillProperties: "{http://schemas.microsoft.com/office/word/2010/wordml}solidFill",
    CTSphereCoords: "{http://schemas.microsoft.com/office/word/2010/wordml}rot",
    CTStyleSet: "{http://schemas.microsoft.com/office/word/2010/wordml}styleSet",
    CTStylisticSets: "{http://schemas.microsoft.com/office/word/2010/wordml}stylisticSets",
    CTTextOutlineEffect: "{http://schemas.microsoft.com/office/word/2010/wordml}textOutline",
    CTTrackChange: "{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictInsRangeStart",
    CTTransform2D: "{http://schemas.microsoft.com/office/word/2010/wordml}xfrm",
    CTWordContentPartNonVisual: "{http://schemas.microsoft.com/office/word/2010/wordml}nvContentPartPr",
    Checkbox: "{http://schemas.microsoft.com/office/word/2010/wordml}checkbox",
    ConflictMode: "{http://schemas.microsoft.com/office/word/2010/wordml}conflictMode",
    ContentPart: "{http://schemas.microsoft.com/office/word/2010/wordml}contentPart",
    CustomXmlConflictDelRangeEnd: "{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictDelRangeEnd",
    CustomXmlConflictDelRangeStart: "{http://schemas.microsoft.com/office/word/2010/wordml}customXmlConflictDelRangeStart",
    DefaultImageDpi: "{http://schemas.microsoft.com/office/word/2010/wordml}defaultImageDpi",
    DiscardImageEditingData: "{http://schemas.microsoft.com/office/word/2010/wordml}discardImageEditingData",
    DocId: "{http://schemas.microsoft.com/office/word/2010/wordml}docId",
    Lum: "{http://schemas.microsoft.com/office/word/2010/wordml}lum",
    LumMod: "{http://schemas.microsoft.com/office/word/2010/wordml}lumMod",
    LumOff: "{http://schemas.microsoft.com/office/word/2010/wordml}lumOff",
    Round: "{http://schemas.microsoft.com/office/word/2010/wordml}round",
    Sat: "{http://schemas.microsoft.com/office/word/2010/wordml}sat",
    SatMod: "{http://schemas.microsoft.com/office/word/2010/wordml}satMod",
    SatOff: "{http://schemas.microsoft.com/office/word/2010/wordml}satOff",
    Shade: "{http://schemas.microsoft.com/office/word/2010/wordml}shade",
    Shadow: "{http://schemas.microsoft.com/office/word/2010/wordml}shadow",
    Tint: "{http://schemas.microsoft.com/office/word/2010/wordml}tint",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "alpha",
    "bevel",
    "bevelB",
    "bevelT",
    "cNvContentPartPr",
    "cNvPr",
    "camera",
    "checkbox",
    "checked",
    "checkedState",
    "cntxtAlts",
    "conflictMode",
    "contentPart",
    "contourClr",
    "customXmlConflictDelRangeEnd",
    "customXmlConflictDelRangeStart",
    "customXmlConflictInsRangeEnd",
    "customXmlConflictInsRangeStart",
    "defaultImageDpi",
    "discardImageEditingData",
    "docId",
    "entityPicker",
    "extLst",
    "extrusionClr",
    "fillToRect",
    "glow",
    "gradFill",
    "gs",
    "gsLst",
    "hueMod",
    "ligatures",
    "lightRig",
    "lin",
    "lum",
    "lumMod",
    "lumOff",
    "miter",
    "noFill",
    "numForm",
    "numSpacing",
    "nvContentPartPr",
    "path",
    "props3d",
    "prstDash",
    "reflection",
    "rot",
    "round_",
    "sat",
    "satMod",
    "satOff",
    "scene3d",
    "schemeClr",
    "shade",
    "shadow",
    "solidFill",
    "srgbClr",
    "styleSet",
    "stylisticSets",
    "textFill",
    "textOutline",
    "tint",
    "uncheckedState",
    "xfrm",
]
