"""``el`` for the http://schemas.microsoft.com/office/drawing/2014/chartex namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_chartex_2014.json``, which a human reviews.

    >>> from docx4j_py.oart.chartex_2014 import el
    >>> el.address()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTColorMapping,
    CTShapeProperties,
    CTSolidColorFillProperties,
    CTTextBody,
)
from docx4j_py.oart.chartex_2014 import (
    CTAddress,
    CTAggregation,
    CTAxis,
    CTAxisId,
    CTAxisTitle,
    CTAxisUnits,
    CTAxisUnitsLabel,
    CTBinning,
    CTCategoryAxisScaling,
    CTChart,
    CTChartData,
    CTChartTitle,
    CTClear,
    CTCopyrights,
    CTData,
    CTDataId,
    CTDataLabel,
    CTDataLabelHidden,
    CTDataLabelVisibilities,
    CTDataLabels,
    CTDataPoint,
    CTExtension,
    CTExtensionList,
    CTExternalData,
    CTExtremeValueColorPosition,
    CTFormatOverride,
    CTFormatOverrides,
    CTFormula,
    CTGeoCache,
    CTGeoChildEntities,
    CTGeoChildEntitiesQuery,
    CTGeoChildEntitiesQueryResult,
    CTGeoChildEntitiesQueryResults,
    CTGeoChildTypes,
    CTGeoData,
    CTGeoDataEntityQuery,
    CTGeoDataEntityQueryResult,
    CTGeoDataEntityQueryResults,
    CTGeoDataPointQuery,
    CTGeoDataPointToEntityQuery,
    CTGeoDataPointToEntityQueryResult,
    CTGeoDataPointToEntityQueryResults,
    CTGeoEntity,
    CTGeoLocation,
    CTGeoLocationQuery,
    CTGeoLocationQueryResult,
    CTGeoLocationQueryResults,
    CTGeoLocations,
    CTGeoParentEntitiesQuery,
    CTGeoParentEntitiesQueryResult,
    CTGeoParentEntitiesQueryResults,
    CTGeoParentEntity,
    CTGeoPolygon,
    CTGeoPolygons,
    CTGeography,
    CTGridlines,
    CTHeaderFooter,
    CTLegend,
    CTNumberColorPosition,
    CTNumberFormat,
    CTNumericDimension,
    CTNumericLevel,
    CTNumericValue,
    CTPageMargins,
    CTPageSetup,
    CTParentLabelLayout,
    CTPercentageColorPosition,
    CTPlotArea,
    CTPlotAreaRegion,
    CTPlotSurface,
    CTPrintSettings,
    CTRegionLabelLayout,
    CTSeries,
    CTSeriesElementVisibilities,
    CTSeriesLayoutProperties,
    CTStatistics,
    CTStringDimension,
    CTStringLevel,
    CTStringValue,
    CTSubtotalIndex,
    CTSubtotals,
    CTText,
    CTTextData,
    CTTickLabels,
    CTTickMarks,
    CTValueAxisScaling,
    CTValueColorEndPosition,
    CTValueColorMiddlePosition,
    CTValueColorPositions,
    CTValueColors,
    Chart,
    ChartSpace,
    F,
    Nf,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2014/chartex"

def address(**kwargs: Any) -> CTAddress:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}address`` -> :class:`docx4j_py.oart.chartex_2014.CTAddress`."""
    return CTAddress(**kwargs)

def aggregation(**kwargs: Any) -> CTAggregation:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}aggregation`` -> :class:`docx4j_py.oart.chartex_2014.CTAggregation`."""
    return CTAggregation(**kwargs)

def axis(**kwargs: Any) -> CTAxis:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}axis`` -> :class:`docx4j_py.oart.chartex_2014.CTAxis`."""
    return CTAxis(**kwargs)

def axisId(**kwargs: Any) -> CTAxisId:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}axisId`` -> :class:`docx4j_py.oart.chartex_2014.CTAxisId`."""
    return CTAxisId(**kwargs)

def binning(**kwargs: Any) -> CTBinning:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}binning`` -> :class:`docx4j_py.oart.chartex_2014.CTBinning`."""
    return CTBinning(**kwargs)

def catScaling(**kwargs: Any) -> CTCategoryAxisScaling:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}catScaling`` -> :class:`docx4j_py.oart.chartex_2014.CTCategoryAxisScaling`."""
    return CTCategoryAxisScaling(**kwargs)

def chart(**kwargs: Any) -> Chart:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}chart`` -> :class:`docx4j_py.oart.chartex_2014.Chart`, the global element declaration of 2 classes this name takes; see ``chart_chart``."""
    return Chart(**kwargs)

def chart_chart(**kwargs: Any) -> CTChart:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}chart`` -> :class:`docx4j_py.oart.chartex_2014.CTChart`, the CTChart form."""
    return CTChart(**kwargs)

def chartData(**kwargs: Any) -> CTChartData:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}chartData`` -> :class:`docx4j_py.oart.chartex_2014.CTChartData`."""
    return CTChartData(**kwargs)

def chartSpace(**kwargs: Any) -> ChartSpace:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}chartSpace`` -> :class:`docx4j_py.oart.chartex_2014.ChartSpace`."""
    return ChartSpace(**kwargs)

def clear(**kwargs: Any) -> CTClear:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}clear`` -> :class:`docx4j_py.oart.chartex_2014.CTClear`."""
    return CTClear(**kwargs)

def clrMapOvr(**kwargs: Any) -> CTColorMapping:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}clrMapOvr`` -> :class:`docx4j_py.dml.main.CTColorMapping`."""
    return CTColorMapping(**kwargs)

def copyrights(**kwargs: Any) -> CTCopyrights:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}copyrights`` -> :class:`docx4j_py.oart.chartex_2014.CTCopyrights`."""
    return CTCopyrights(**kwargs)

def data(**kwargs: Any) -> CTData:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}data`` -> :class:`docx4j_py.oart.chartex_2014.CTData`."""
    return CTData(**kwargs)

def dataId(**kwargs: Any) -> CTDataId:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}dataId`` -> :class:`docx4j_py.oart.chartex_2014.CTDataId`."""
    return CTDataId(**kwargs)

def dataLabel(**kwargs: Any) -> CTDataLabel:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}dataLabel`` -> :class:`docx4j_py.oart.chartex_2014.CTDataLabel`."""
    return CTDataLabel(**kwargs)

def dataLabelHidden(**kwargs: Any) -> CTDataLabelHidden:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}dataLabelHidden`` -> :class:`docx4j_py.oart.chartex_2014.CTDataLabelHidden`."""
    return CTDataLabelHidden(**kwargs)

def dataLabels(**kwargs: Any) -> CTDataLabels:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}dataLabels`` -> :class:`docx4j_py.oart.chartex_2014.CTDataLabels`."""
    return CTDataLabels(**kwargs)

def dataPt(**kwargs: Any) -> CTDataPoint:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}dataPt`` -> :class:`docx4j_py.oart.chartex_2014.CTDataPoint`."""
    return CTDataPoint(**kwargs)

def ext(**kwargs: Any) -> CTExtension:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}ext`` -> :class:`docx4j_py.oart.chartex_2014.CTExtension`."""
    return CTExtension(**kwargs)

def extLst(**kwargs: Any) -> CTExtensionList:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}extLst`` -> :class:`docx4j_py.oart.chartex_2014.CTExtensionList`."""
    return CTExtensionList(**kwargs)

def externalData(**kwargs: Any) -> CTExternalData:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}externalData`` -> :class:`docx4j_py.oart.chartex_2014.CTExternalData`."""
    return CTExternalData(**kwargs)

def extremeValue(**kwargs: Any) -> CTExtremeValueColorPosition:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}extremeValue`` -> :class:`docx4j_py.oart.chartex_2014.CTExtremeValueColorPosition`."""
    return CTExtremeValueColorPosition(**kwargs)

def f(text: str | None = None, /, **kwargs: Any) -> F:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}f`` -> :class:`docx4j_py.oart.chartex_2014.F`, the most reachable scope of 2 classes this name takes; see ``formula``."""
    return text_element(F, text, kwargs, "value", null)

def formula(text: str | None = None, /, **kwargs: Any) -> CTFormula:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}f`` -> :class:`docx4j_py.oart.chartex_2014.CTFormula`, the CTFormula form."""
    return text_element(CTFormula, text, kwargs, "value", null)

def fmtOvr(**kwargs: Any) -> CTFormatOverride:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}fmtOvr`` -> :class:`docx4j_py.oart.chartex_2014.CTFormatOverride`."""
    return CTFormatOverride(**kwargs)

def fmtOvrs(**kwargs: Any) -> CTFormatOverrides:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}fmtOvrs`` -> :class:`docx4j_py.oart.chartex_2014.CTFormatOverrides`."""
    return CTFormatOverrides(**kwargs)

def geoCache(**kwargs: Any) -> CTGeoCache:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoCache`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoCache`."""
    return CTGeoCache(**kwargs)

def geoChildEntities(**kwargs: Any) -> CTGeoChildEntities:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntities`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoChildEntities`."""
    return CTGeoChildEntities(**kwargs)

def geoChildEntitiesQuery(**kwargs: Any) -> CTGeoChildEntitiesQuery:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntitiesQuery`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoChildEntitiesQuery`."""
    return CTGeoChildEntitiesQuery(**kwargs)

def geoChildEntitiesQueryResult(**kwargs: Any) -> CTGeoChildEntitiesQueryResult:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntitiesQueryResult`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoChildEntitiesQueryResult`."""
    return CTGeoChildEntitiesQueryResult(**kwargs)

def geoChildEntitiesQueryResults(**kwargs: Any) -> CTGeoChildEntitiesQueryResults:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntitiesQueryResults`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoChildEntitiesQueryResults`."""
    return CTGeoChildEntitiesQueryResults(**kwargs)

def geoChildTypes(**kwargs: Any) -> CTGeoChildTypes:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildTypes`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoChildTypes`."""
    return CTGeoChildTypes(**kwargs)

def geoData(**kwargs: Any) -> CTGeoData:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoData`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoData`."""
    return CTGeoData(**kwargs)

def geoDataEntityQuery(**kwargs: Any) -> CTGeoDataEntityQuery:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataEntityQuery`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoDataEntityQuery`."""
    return CTGeoDataEntityQuery(**kwargs)

def geoDataEntityQueryResult(**kwargs: Any) -> CTGeoDataEntityQueryResult:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataEntityQueryResult`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoDataEntityQueryResult`."""
    return CTGeoDataEntityQueryResult(**kwargs)

def geoDataEntityQueryResults(**kwargs: Any) -> CTGeoDataEntityQueryResults:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataEntityQueryResults`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoDataEntityQueryResults`."""
    return CTGeoDataEntityQueryResults(**kwargs)

def geoDataPointQuery(**kwargs: Any) -> CTGeoDataPointQuery:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointQuery`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoDataPointQuery`."""
    return CTGeoDataPointQuery(**kwargs)

def geoDataPointToEntityQuery(**kwargs: Any) -> CTGeoDataPointToEntityQuery:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointToEntityQuery`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoDataPointToEntityQuery`."""
    return CTGeoDataPointToEntityQuery(**kwargs)

def geoDataPointToEntityQueryResult(**kwargs: Any) -> CTGeoDataPointToEntityQueryResult:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointToEntityQueryResult`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoDataPointToEntityQueryResult`."""
    return CTGeoDataPointToEntityQueryResult(**kwargs)

def geoDataPointToEntityQueryResults(**kwargs: Any) -> CTGeoDataPointToEntityQueryResults:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointToEntityQueryResults`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoDataPointToEntityQueryResults`."""
    return CTGeoDataPointToEntityQueryResults(**kwargs)

def geoEntity(**kwargs: Any) -> CTGeoEntity:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoEntity`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoEntity`."""
    return CTGeoEntity(**kwargs)

def geoLocation(**kwargs: Any) -> CTGeoLocation:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocation`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoLocation`."""
    return CTGeoLocation(**kwargs)

def geoLocationQuery(**kwargs: Any) -> CTGeoLocationQuery:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocationQuery`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoLocationQuery`."""
    return CTGeoLocationQuery(**kwargs)

def geoLocationQueryResult(**kwargs: Any) -> CTGeoLocationQueryResult:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocationQueryResult`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoLocationQueryResult`."""
    return CTGeoLocationQueryResult(**kwargs)

def geoLocationQueryResults(**kwargs: Any) -> CTGeoLocationQueryResults:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocationQueryResults`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoLocationQueryResults`."""
    return CTGeoLocationQueryResults(**kwargs)

def geoLocations(**kwargs: Any) -> CTGeoLocations:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocations`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoLocations`."""
    return CTGeoLocations(**kwargs)

def geoParentEntitiesQuery(**kwargs: Any) -> CTGeoParentEntitiesQuery:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntitiesQuery`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoParentEntitiesQuery`."""
    return CTGeoParentEntitiesQuery(**kwargs)

def geoParentEntitiesQueryResult(**kwargs: Any) -> CTGeoParentEntitiesQueryResult:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntitiesQueryResult`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoParentEntitiesQueryResult`."""
    return CTGeoParentEntitiesQueryResult(**kwargs)

def geoParentEntitiesQueryResults(**kwargs: Any) -> CTGeoParentEntitiesQueryResults:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntitiesQueryResults`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoParentEntitiesQueryResults`."""
    return CTGeoParentEntitiesQueryResults(**kwargs)

def geoParentEntity(**kwargs: Any) -> CTGeoParentEntity:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntity`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoParentEntity`."""
    return CTGeoParentEntity(**kwargs)

def geoPolygon(**kwargs: Any) -> CTGeoPolygon:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoPolygon`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoPolygon`."""
    return CTGeoPolygon(**kwargs)

def geoPolygons(**kwargs: Any) -> CTGeoPolygons:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geoPolygons`` -> :class:`docx4j_py.oart.chartex_2014.CTGeoPolygons`."""
    return CTGeoPolygons(**kwargs)

def geography(**kwargs: Any) -> CTGeography:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}geography`` -> :class:`docx4j_py.oart.chartex_2014.CTGeography`."""
    return CTGeography(**kwargs)

def headerFooter(**kwargs: Any) -> CTHeaderFooter:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}headerFooter`` -> :class:`docx4j_py.oart.chartex_2014.CTHeaderFooter`."""
    return CTHeaderFooter(**kwargs)

def idx(**kwargs: Any) -> CTSubtotalIndex:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}idx`` -> :class:`docx4j_py.oart.chartex_2014.CTSubtotalIndex`."""
    return CTSubtotalIndex(**kwargs)

def layoutPr(**kwargs: Any) -> CTSeriesLayoutProperties:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}layoutPr`` -> :class:`docx4j_py.oart.chartex_2014.CTSeriesLayoutProperties`."""
    return CTSeriesLayoutProperties(**kwargs)

def legend(**kwargs: Any) -> CTLegend:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}legend`` -> :class:`docx4j_py.oart.chartex_2014.CTLegend`."""
    return CTLegend(**kwargs)

def lvl(**kwargs: Any) -> CTNumericLevel:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}lvl`` -> :class:`docx4j_py.oart.chartex_2014.CTNumericLevel`, the most reachable scope of 2 classes this name takes; see ``string_level``."""
    return CTNumericLevel(**kwargs)

def string_level(**kwargs: Any) -> CTStringLevel:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}lvl`` -> :class:`docx4j_py.oart.chartex_2014.CTStringLevel`, the CTStringLevel form."""
    return CTStringLevel(**kwargs)

def majorGridlines(**kwargs: Any) -> CTGridlines:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}majorGridlines`` -> :class:`docx4j_py.oart.chartex_2014.CTGridlines`."""
    return CTGridlines(**kwargs)

def majorTickMarks(**kwargs: Any) -> CTTickMarks:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}majorTickMarks`` -> :class:`docx4j_py.oart.chartex_2014.CTTickMarks`."""
    return CTTickMarks(**kwargs)

def max_(**kwargs: Any) -> CTValueColorEndPosition:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}max`` -> :class:`docx4j_py.oart.chartex_2014.CTValueColorEndPosition`."""
    return CTValueColorEndPosition(**kwargs)

def maxColor(**kwargs: Any) -> CTSolidColorFillProperties:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}maxColor`` -> :class:`docx4j_py.dml.main.CTSolidColorFillProperties`."""
    return CTSolidColorFillProperties(**kwargs)

def mid(**kwargs: Any) -> CTValueColorMiddlePosition:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}mid`` -> :class:`docx4j_py.oart.chartex_2014.CTValueColorMiddlePosition`."""
    return CTValueColorMiddlePosition(**kwargs)

def midColor(**kwargs: Any) -> CTSolidColorFillProperties:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}midColor`` -> :class:`docx4j_py.dml.main.CTSolidColorFillProperties`."""
    return CTSolidColorFillProperties(**kwargs)

def min_(**kwargs: Any) -> CTValueColorEndPosition:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}min`` -> :class:`docx4j_py.oart.chartex_2014.CTValueColorEndPosition`."""
    return CTValueColorEndPosition(**kwargs)

def minColor(**kwargs: Any) -> CTSolidColorFillProperties:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}minColor`` -> :class:`docx4j_py.dml.main.CTSolidColorFillProperties`."""
    return CTSolidColorFillProperties(**kwargs)

def minorGridlines(**kwargs: Any) -> CTGridlines:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}minorGridlines`` -> :class:`docx4j_py.oart.chartex_2014.CTGridlines`."""
    return CTGridlines(**kwargs)

def minorTickMarks(**kwargs: Any) -> CTTickMarks:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}minorTickMarks`` -> :class:`docx4j_py.oart.chartex_2014.CTTickMarks`."""
    return CTTickMarks(**kwargs)

def nf(text: str | None = None, /, **kwargs: Any) -> Nf:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}nf`` -> :class:`docx4j_py.oart.chartex_2014.Nf`."""
    return text_element(Nf, text, kwargs, "value", null)

def numDim(**kwargs: Any) -> CTNumericDimension:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}numDim`` -> :class:`docx4j_py.oart.chartex_2014.CTNumericDimension`."""
    return CTNumericDimension(**kwargs)

def numFmt(**kwargs: Any) -> CTNumberFormat:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}numFmt`` -> :class:`docx4j_py.oart.chartex_2014.CTNumberFormat`."""
    return CTNumberFormat(**kwargs)

def number(**kwargs: Any) -> CTNumberColorPosition:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}number`` -> :class:`docx4j_py.oart.chartex_2014.CTNumberColorPosition`."""
    return CTNumberColorPosition(**kwargs)

def pageMargins(**kwargs: Any) -> CTPageMargins:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}pageMargins`` -> :class:`docx4j_py.oart.chartex_2014.CTPageMargins`."""
    return CTPageMargins(**kwargs)

def pageSetup(**kwargs: Any) -> CTPageSetup:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}pageSetup`` -> :class:`docx4j_py.oart.chartex_2014.CTPageSetup`."""
    return CTPageSetup(**kwargs)

def parentLabelLayout(**kwargs: Any) -> CTParentLabelLayout:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}parentLabelLayout`` -> :class:`docx4j_py.oart.chartex_2014.CTParentLabelLayout`."""
    return CTParentLabelLayout(**kwargs)

def percent(**kwargs: Any) -> CTPercentageColorPosition:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}percent`` -> :class:`docx4j_py.oart.chartex_2014.CTPercentageColorPosition`."""
    return CTPercentageColorPosition(**kwargs)

def plotArea(**kwargs: Any) -> CTPlotArea:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}plotArea`` -> :class:`docx4j_py.oart.chartex_2014.CTPlotArea`."""
    return CTPlotArea(**kwargs)

def plotAreaRegion(**kwargs: Any) -> CTPlotAreaRegion:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}plotAreaRegion`` -> :class:`docx4j_py.oart.chartex_2014.CTPlotAreaRegion`."""
    return CTPlotAreaRegion(**kwargs)

def plotSurface(**kwargs: Any) -> CTPlotSurface:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}plotSurface`` -> :class:`docx4j_py.oart.chartex_2014.CTPlotSurface`."""
    return CTPlotSurface(**kwargs)

def printSettings(**kwargs: Any) -> CTPrintSettings:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}printSettings`` -> :class:`docx4j_py.oart.chartex_2014.CTPrintSettings`."""
    return CTPrintSettings(**kwargs)

def pt(text: str | None = None, /, **kwargs: Any) -> CTNumericValue:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}pt`` -> :class:`docx4j_py.oart.chartex_2014.CTNumericValue`, the most reachable scope of 2 classes this name takes; see ``string_value``."""
    return text_element(CTNumericValue, text, kwargs, "value", null)

def string_value(text: str | None = None, /, **kwargs: Any) -> CTStringValue:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}pt`` -> :class:`docx4j_py.oart.chartex_2014.CTStringValue`, the CTStringValue form."""
    return text_element(CTStringValue, text, kwargs, "value", null)

def regionLabelLayout(**kwargs: Any) -> CTRegionLabelLayout:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}regionLabelLayout`` -> :class:`docx4j_py.oart.chartex_2014.CTRegionLabelLayout`."""
    return CTRegionLabelLayout(**kwargs)

def rich(**kwargs: Any) -> CTTextBody:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}rich`` -> :class:`docx4j_py.dml.main.CTTextBody`."""
    return CTTextBody(**kwargs)

def series(**kwargs: Any) -> CTSeries:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}series`` -> :class:`docx4j_py.oart.chartex_2014.CTSeries`."""
    return CTSeries(**kwargs)

def spPr(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}spPr`` -> :class:`docx4j_py.dml.main.CTShapeProperties`."""
    return CTShapeProperties(**kwargs)

def statistics(**kwargs: Any) -> CTStatistics:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}statistics`` -> :class:`docx4j_py.oart.chartex_2014.CTStatistics`."""
    return CTStatistics(**kwargs)

def strDim(**kwargs: Any) -> CTStringDimension:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}strDim`` -> :class:`docx4j_py.oart.chartex_2014.CTStringDimension`."""
    return CTStringDimension(**kwargs)

def subtotals(**kwargs: Any) -> CTSubtotals:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}subtotals`` -> :class:`docx4j_py.oart.chartex_2014.CTSubtotals`."""
    return CTSubtotals(**kwargs)

def tickLabels(**kwargs: Any) -> CTTickLabels:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}tickLabels`` -> :class:`docx4j_py.oart.chartex_2014.CTTickLabels`."""
    return CTTickLabels(**kwargs)

def title(**kwargs: Any) -> CTChartTitle:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}title`` -> :class:`docx4j_py.oart.chartex_2014.CTChartTitle`, the most reachable scope of 2 classes this name takes; see ``axis_title``."""
    return CTChartTitle(**kwargs)

def axis_title(**kwargs: Any) -> CTAxisTitle:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}title`` -> :class:`docx4j_py.oart.chartex_2014.CTAxisTitle`, the CTAxisTitle form."""
    return CTAxisTitle(**kwargs)

def tx(**kwargs: Any) -> CTText:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}tx`` -> :class:`docx4j_py.oart.chartex_2014.CTText`."""
    return CTText(**kwargs)

def txData(**kwargs: Any) -> CTTextData:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}txData`` -> :class:`docx4j_py.oart.chartex_2014.CTTextData`."""
    return CTTextData(**kwargs)

def txPr(**kwargs: Any) -> CTTextBody:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}txPr`` -> :class:`docx4j_py.dml.main.CTTextBody`."""
    return CTTextBody(**kwargs)

def units(**kwargs: Any) -> CTAxisUnits:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}units`` -> :class:`docx4j_py.oart.chartex_2014.CTAxisUnits`."""
    return CTAxisUnits(**kwargs)

def unitsLabel(**kwargs: Any) -> CTAxisUnitsLabel:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}unitsLabel`` -> :class:`docx4j_py.oart.chartex_2014.CTAxisUnitsLabel`."""
    return CTAxisUnitsLabel(**kwargs)

def valScaling(**kwargs: Any) -> CTValueAxisScaling:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}valScaling`` -> :class:`docx4j_py.oart.chartex_2014.CTValueAxisScaling`."""
    return CTValueAxisScaling(**kwargs)

def valueColorPositions(**kwargs: Any) -> CTValueColorPositions:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}valueColorPositions`` -> :class:`docx4j_py.oart.chartex_2014.CTValueColorPositions`."""
    return CTValueColorPositions(**kwargs)

def valueColors(**kwargs: Any) -> CTValueColors:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}valueColors`` -> :class:`docx4j_py.oart.chartex_2014.CTValueColors`."""
    return CTValueColors(**kwargs)

def visibility(**kwargs: Any) -> CTDataLabelVisibilities:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}visibility`` -> :class:`docx4j_py.oart.chartex_2014.CTDataLabelVisibilities`, the most reachable scope of 2 classes this name takes; see ``series_element_visibilities``."""
    return CTDataLabelVisibilities(**kwargs)

def series_element_visibilities(**kwargs: Any) -> CTSeriesElementVisibilities:
    """``{http://schemas.microsoft.com/office/drawing/2014/chartex}visibility`` -> :class:`docx4j_py.oart.chartex_2014.CTSeriesElementVisibilities`, the CTSeriesElementVisibilities form."""
    return CTSeriesElementVisibilities(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}address": CTAddress,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}aggregation": CTAggregation,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}axis": CTAxis,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}axisId": CTAxisId,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}binning": CTBinning,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}catScaling": CTCategoryAxisScaling,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}chart": Chart,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}chartData": CTChartData,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}chartSpace": ChartSpace,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}clear": CTClear,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}clrMapOvr": CTColorMapping,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}copyrights": CTCopyrights,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}data": CTData,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}dataId": CTDataId,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}dataLabel": CTDataLabel,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}dataLabelHidden": CTDataLabelHidden,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}dataLabels": CTDataLabels,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}dataPt": CTDataPoint,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}ext": CTExtension,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}extLst": CTExtensionList,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}externalData": CTExternalData,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}extremeValue": CTExtremeValueColorPosition,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}f": F,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}fmtOvr": CTFormatOverride,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}fmtOvrs": CTFormatOverrides,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoCache": CTGeoCache,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntities": CTGeoChildEntities,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntitiesQuery": CTGeoChildEntitiesQuery,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntitiesQueryResult": CTGeoChildEntitiesQueryResult,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntitiesQueryResults": CTGeoChildEntitiesQueryResults,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildTypes": CTGeoChildTypes,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoData": CTGeoData,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataEntityQuery": CTGeoDataEntityQuery,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataEntityQueryResult": CTGeoDataEntityQueryResult,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataEntityQueryResults": CTGeoDataEntityQueryResults,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointQuery": CTGeoDataPointQuery,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointToEntityQuery": CTGeoDataPointToEntityQuery,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointToEntityQueryResult": CTGeoDataPointToEntityQueryResult,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointToEntityQueryResults": CTGeoDataPointToEntityQueryResults,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoEntity": CTGeoEntity,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocation": CTGeoLocation,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocationQuery": CTGeoLocationQuery,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocationQueryResult": CTGeoLocationQueryResult,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocationQueryResults": CTGeoLocationQueryResults,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocations": CTGeoLocations,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntitiesQuery": CTGeoParentEntitiesQuery,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntitiesQueryResult": CTGeoParentEntitiesQueryResult,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntitiesQueryResults": CTGeoParentEntitiesQueryResults,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntity": CTGeoParentEntity,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoPolygon": CTGeoPolygon,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoPolygons": CTGeoPolygons,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}geography": CTGeography,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}headerFooter": CTHeaderFooter,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}idx": CTSubtotalIndex,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}layoutPr": CTSeriesLayoutProperties,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}legend": CTLegend,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}lvl": CTNumericLevel,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}majorGridlines": CTGridlines,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}majorTickMarks": CTTickMarks,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}max": CTValueColorEndPosition,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}maxColor": CTSolidColorFillProperties,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}mid": CTValueColorMiddlePosition,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}midColor": CTSolidColorFillProperties,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}min": CTValueColorEndPosition,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}minColor": CTSolidColorFillProperties,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}minorGridlines": CTGridlines,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}minorTickMarks": CTTickMarks,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}nf": Nf,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}numDim": CTNumericDimension,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}numFmt": CTNumberFormat,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}number": CTNumberColorPosition,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}pageMargins": CTPageMargins,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}pageSetup": CTPageSetup,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}parentLabelLayout": CTParentLabelLayout,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}percent": CTPercentageColorPosition,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}plotArea": CTPlotArea,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}plotAreaRegion": CTPlotAreaRegion,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}plotSurface": CTPlotSurface,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}printSettings": CTPrintSettings,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}pt": CTNumericValue,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}regionLabelLayout": CTRegionLabelLayout,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}rich": CTTextBody,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}series": CTSeries,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}spPr": CTShapeProperties,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}statistics": CTStatistics,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}strDim": CTStringDimension,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}subtotals": CTSubtotals,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}tickLabels": CTTickLabels,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}title": CTChartTitle,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}tx": CTText,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}txData": CTTextData,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}txPr": CTTextBody,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}units": CTAxisUnits,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}unitsLabel": CTAxisUnitsLabel,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}valScaling": CTValueAxisScaling,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}valueColorPositions": CTValueColorPositions,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}valueColors": CTValueColors,
    "{http://schemas.microsoft.com/office/drawing/2014/chartex}visibility": CTDataLabelVisibilities,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "address": CTAddress,
    "aggregation": CTAggregation,
    "axis": CTAxis,
    "axisId": CTAxisId,
    "binning": CTBinning,
    "catScaling": CTCategoryAxisScaling,
    "chart": Chart,
    "chartData": CTChartData,
    "chartSpace": ChartSpace,
    "clear": CTClear,
    "clrMapOvr": CTColorMapping,
    "copyrights": CTCopyrights,
    "data": CTData,
    "dataId": CTDataId,
    "dataLabel": CTDataLabel,
    "dataLabelHidden": CTDataLabelHidden,
    "dataLabels": CTDataLabels,
    "dataPt": CTDataPoint,
    "ext": CTExtension,
    "extLst": CTExtensionList,
    "externalData": CTExternalData,
    "extremeValue": CTExtremeValueColorPosition,
    "f": F,
    "fmtOvr": CTFormatOverride,
    "fmtOvrs": CTFormatOverrides,
    "geoCache": CTGeoCache,
    "geoChildEntities": CTGeoChildEntities,
    "geoChildEntitiesQuery": CTGeoChildEntitiesQuery,
    "geoChildEntitiesQueryResult": CTGeoChildEntitiesQueryResult,
    "geoChildEntitiesQueryResults": CTGeoChildEntitiesQueryResults,
    "geoChildTypes": CTGeoChildTypes,
    "geoData": CTGeoData,
    "geoDataEntityQuery": CTGeoDataEntityQuery,
    "geoDataEntityQueryResult": CTGeoDataEntityQueryResult,
    "geoDataEntityQueryResults": CTGeoDataEntityQueryResults,
    "geoDataPointQuery": CTGeoDataPointQuery,
    "geoDataPointToEntityQuery": CTGeoDataPointToEntityQuery,
    "geoDataPointToEntityQueryResult": CTGeoDataPointToEntityQueryResult,
    "geoDataPointToEntityQueryResults": CTGeoDataPointToEntityQueryResults,
    "geoEntity": CTGeoEntity,
    "geoLocation": CTGeoLocation,
    "geoLocationQuery": CTGeoLocationQuery,
    "geoLocationQueryResult": CTGeoLocationQueryResult,
    "geoLocationQueryResults": CTGeoLocationQueryResults,
    "geoLocations": CTGeoLocations,
    "geoParentEntitiesQuery": CTGeoParentEntitiesQuery,
    "geoParentEntitiesQueryResult": CTGeoParentEntitiesQueryResult,
    "geoParentEntitiesQueryResults": CTGeoParentEntitiesQueryResults,
    "geoParentEntity": CTGeoParentEntity,
    "geoPolygon": CTGeoPolygon,
    "geoPolygons": CTGeoPolygons,
    "geography": CTGeography,
    "headerFooter": CTHeaderFooter,
    "idx": CTSubtotalIndex,
    "layoutPr": CTSeriesLayoutProperties,
    "legend": CTLegend,
    "lvl": CTNumericLevel,
    "majorGridlines": CTGridlines,
    "majorTickMarks": CTTickMarks,
    "max": CTValueColorEndPosition,
    "maxColor": CTSolidColorFillProperties,
    "mid": CTValueColorMiddlePosition,
    "midColor": CTSolidColorFillProperties,
    "min": CTValueColorEndPosition,
    "minColor": CTSolidColorFillProperties,
    "minorGridlines": CTGridlines,
    "minorTickMarks": CTTickMarks,
    "nf": Nf,
    "numDim": CTNumericDimension,
    "numFmt": CTNumberFormat,
    "number": CTNumberColorPosition,
    "pageMargins": CTPageMargins,
    "pageSetup": CTPageSetup,
    "parentLabelLayout": CTParentLabelLayout,
    "percent": CTPercentageColorPosition,
    "plotArea": CTPlotArea,
    "plotAreaRegion": CTPlotAreaRegion,
    "plotSurface": CTPlotSurface,
    "printSettings": CTPrintSettings,
    "pt": CTNumericValue,
    "regionLabelLayout": CTRegionLabelLayout,
    "rich": CTTextBody,
    "series": CTSeries,
    "spPr": CTShapeProperties,
    "statistics": CTStatistics,
    "strDim": CTStringDimension,
    "subtotals": CTSubtotals,
    "tickLabels": CTTickLabels,
    "title": CTChartTitle,
    "tx": CTText,
    "txData": CTTextData,
    "txPr": CTTextBody,
    "units": CTAxisUnits,
    "unitsLabel": CTAxisUnitsLabel,
    "valScaling": CTValueAxisScaling,
    "valueColorPositions": CTValueColorPositions,
    "valueColors": CTValueColors,
    "visibility": CTDataLabelVisibilities,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTAddress: "{http://schemas.microsoft.com/office/drawing/2014/chartex}address",
    CTAggregation: "{http://schemas.microsoft.com/office/drawing/2014/chartex}aggregation",
    CTAxis: "{http://schemas.microsoft.com/office/drawing/2014/chartex}axis",
    CTAxisId: "{http://schemas.microsoft.com/office/drawing/2014/chartex}axisId",
    CTAxisTitle: "{http://schemas.microsoft.com/office/drawing/2014/chartex}title",
    CTAxisUnits: "{http://schemas.microsoft.com/office/drawing/2014/chartex}units",
    CTAxisUnitsLabel: "{http://schemas.microsoft.com/office/drawing/2014/chartex}unitsLabel",
    CTBinning: "{http://schemas.microsoft.com/office/drawing/2014/chartex}binning",
    CTCategoryAxisScaling: "{http://schemas.microsoft.com/office/drawing/2014/chartex}catScaling",
    CTChart: "{http://schemas.microsoft.com/office/drawing/2014/chartex}chart",
    CTChartData: "{http://schemas.microsoft.com/office/drawing/2014/chartex}chartData",
    CTChartTitle: "{http://schemas.microsoft.com/office/drawing/2014/chartex}title",
    CTClear: "{http://schemas.microsoft.com/office/drawing/2014/chartex}clear",
    CTColorMapping: "{http://schemas.microsoft.com/office/drawing/2014/chartex}clrMapOvr",
    CTCopyrights: "{http://schemas.microsoft.com/office/drawing/2014/chartex}copyrights",
    CTData: "{http://schemas.microsoft.com/office/drawing/2014/chartex}data",
    CTDataId: "{http://schemas.microsoft.com/office/drawing/2014/chartex}dataId",
    CTDataLabel: "{http://schemas.microsoft.com/office/drawing/2014/chartex}dataLabel",
    CTDataLabelHidden: "{http://schemas.microsoft.com/office/drawing/2014/chartex}dataLabelHidden",
    CTDataLabelVisibilities: "{http://schemas.microsoft.com/office/drawing/2014/chartex}visibility",
    CTDataLabels: "{http://schemas.microsoft.com/office/drawing/2014/chartex}dataLabels",
    CTDataPoint: "{http://schemas.microsoft.com/office/drawing/2014/chartex}dataPt",
    CTExtension: "{http://schemas.microsoft.com/office/drawing/2014/chartex}ext",
    CTExtensionList: "{http://schemas.microsoft.com/office/drawing/2014/chartex}extLst",
    CTExternalData: "{http://schemas.microsoft.com/office/drawing/2014/chartex}externalData",
    CTExtremeValueColorPosition: "{http://schemas.microsoft.com/office/drawing/2014/chartex}extremeValue",
    CTFormatOverride: "{http://schemas.microsoft.com/office/drawing/2014/chartex}fmtOvr",
    CTFormatOverrides: "{http://schemas.microsoft.com/office/drawing/2014/chartex}fmtOvrs",
    CTFormula: "{http://schemas.microsoft.com/office/drawing/2014/chartex}f",
    CTGeoCache: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoCache",
    CTGeoChildEntities: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntities",
    CTGeoChildEntitiesQuery: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntitiesQuery",
    CTGeoChildEntitiesQueryResult: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntitiesQueryResult",
    CTGeoChildEntitiesQueryResults: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildEntitiesQueryResults",
    CTGeoChildTypes: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoChildTypes",
    CTGeoData: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoData",
    CTGeoDataEntityQuery: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataEntityQuery",
    CTGeoDataEntityQueryResult: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataEntityQueryResult",
    CTGeoDataEntityQueryResults: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataEntityQueryResults",
    CTGeoDataPointQuery: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointQuery",
    CTGeoDataPointToEntityQuery: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointToEntityQuery",
    CTGeoDataPointToEntityQueryResult: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointToEntityQueryResult",
    CTGeoDataPointToEntityQueryResults: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoDataPointToEntityQueryResults",
    CTGeoEntity: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoEntity",
    CTGeoLocation: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocation",
    CTGeoLocationQuery: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocationQuery",
    CTGeoLocationQueryResult: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocationQueryResult",
    CTGeoLocationQueryResults: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocationQueryResults",
    CTGeoLocations: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoLocations",
    CTGeoParentEntitiesQuery: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntitiesQuery",
    CTGeoParentEntitiesQueryResult: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntitiesQueryResult",
    CTGeoParentEntitiesQueryResults: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntitiesQueryResults",
    CTGeoParentEntity: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoParentEntity",
    CTGeoPolygon: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoPolygon",
    CTGeoPolygons: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geoPolygons",
    CTGeography: "{http://schemas.microsoft.com/office/drawing/2014/chartex}geography",
    CTHeaderFooter: "{http://schemas.microsoft.com/office/drawing/2014/chartex}headerFooter",
    CTLegend: "{http://schemas.microsoft.com/office/drawing/2014/chartex}legend",
    CTNumberColorPosition: "{http://schemas.microsoft.com/office/drawing/2014/chartex}number",
    CTNumberFormat: "{http://schemas.microsoft.com/office/drawing/2014/chartex}numFmt",
    CTNumericDimension: "{http://schemas.microsoft.com/office/drawing/2014/chartex}numDim",
    CTNumericLevel: "{http://schemas.microsoft.com/office/drawing/2014/chartex}lvl",
    CTNumericValue: "{http://schemas.microsoft.com/office/drawing/2014/chartex}pt",
    CTPageMargins: "{http://schemas.microsoft.com/office/drawing/2014/chartex}pageMargins",
    CTPageSetup: "{http://schemas.microsoft.com/office/drawing/2014/chartex}pageSetup",
    CTParentLabelLayout: "{http://schemas.microsoft.com/office/drawing/2014/chartex}parentLabelLayout",
    CTPercentageColorPosition: "{http://schemas.microsoft.com/office/drawing/2014/chartex}percent",
    CTPlotArea: "{http://schemas.microsoft.com/office/drawing/2014/chartex}plotArea",
    CTPlotAreaRegion: "{http://schemas.microsoft.com/office/drawing/2014/chartex}plotAreaRegion",
    CTPlotSurface: "{http://schemas.microsoft.com/office/drawing/2014/chartex}plotSurface",
    CTPrintSettings: "{http://schemas.microsoft.com/office/drawing/2014/chartex}printSettings",
    CTRegionLabelLayout: "{http://schemas.microsoft.com/office/drawing/2014/chartex}regionLabelLayout",
    CTSeries: "{http://schemas.microsoft.com/office/drawing/2014/chartex}series",
    CTSeriesElementVisibilities: "{http://schemas.microsoft.com/office/drawing/2014/chartex}visibility",
    CTSeriesLayoutProperties: "{http://schemas.microsoft.com/office/drawing/2014/chartex}layoutPr",
    CTShapeProperties: "{http://schemas.microsoft.com/office/drawing/2014/chartex}spPr",
    CTStatistics: "{http://schemas.microsoft.com/office/drawing/2014/chartex}statistics",
    CTStringDimension: "{http://schemas.microsoft.com/office/drawing/2014/chartex}strDim",
    CTStringLevel: "{http://schemas.microsoft.com/office/drawing/2014/chartex}lvl",
    CTStringValue: "{http://schemas.microsoft.com/office/drawing/2014/chartex}pt",
    CTSubtotalIndex: "{http://schemas.microsoft.com/office/drawing/2014/chartex}idx",
    CTSubtotals: "{http://schemas.microsoft.com/office/drawing/2014/chartex}subtotals",
    CTText: "{http://schemas.microsoft.com/office/drawing/2014/chartex}tx",
    CTTextData: "{http://schemas.microsoft.com/office/drawing/2014/chartex}txData",
    CTTickLabels: "{http://schemas.microsoft.com/office/drawing/2014/chartex}tickLabels",
    CTValueAxisScaling: "{http://schemas.microsoft.com/office/drawing/2014/chartex}valScaling",
    CTValueColorMiddlePosition: "{http://schemas.microsoft.com/office/drawing/2014/chartex}mid",
    CTValueColorPositions: "{http://schemas.microsoft.com/office/drawing/2014/chartex}valueColorPositions",
    CTValueColors: "{http://schemas.microsoft.com/office/drawing/2014/chartex}valueColors",
    Chart: "{http://schemas.microsoft.com/office/drawing/2014/chartex}chart",
    ChartSpace: "{http://schemas.microsoft.com/office/drawing/2014/chartex}chartSpace",
    F: "{http://schemas.microsoft.com/office/drawing/2014/chartex}f",
    Nf: "{http://schemas.microsoft.com/office/drawing/2014/chartex}nf",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "address",
    "aggregation",
    "axis",
    "axisId",
    "axis_title",
    "binning",
    "catScaling",
    "chart",
    "chartData",
    "chartSpace",
    "chart_chart",
    "clear",
    "clrMapOvr",
    "copyrights",
    "data",
    "dataId",
    "dataLabel",
    "dataLabelHidden",
    "dataLabels",
    "dataPt",
    "ext",
    "extLst",
    "externalData",
    "extremeValue",
    "f",
    "fmtOvr",
    "fmtOvrs",
    "formula",
    "geoCache",
    "geoChildEntities",
    "geoChildEntitiesQuery",
    "geoChildEntitiesQueryResult",
    "geoChildEntitiesQueryResults",
    "geoChildTypes",
    "geoData",
    "geoDataEntityQuery",
    "geoDataEntityQueryResult",
    "geoDataEntityQueryResults",
    "geoDataPointQuery",
    "geoDataPointToEntityQuery",
    "geoDataPointToEntityQueryResult",
    "geoDataPointToEntityQueryResults",
    "geoEntity",
    "geoLocation",
    "geoLocationQuery",
    "geoLocationQueryResult",
    "geoLocationQueryResults",
    "geoLocations",
    "geoParentEntitiesQuery",
    "geoParentEntitiesQueryResult",
    "geoParentEntitiesQueryResults",
    "geoParentEntity",
    "geoPolygon",
    "geoPolygons",
    "geography",
    "headerFooter",
    "idx",
    "layoutPr",
    "legend",
    "lvl",
    "majorGridlines",
    "majorTickMarks",
    "maxColor",
    "max_",
    "mid",
    "midColor",
    "minColor",
    "min_",
    "minorGridlines",
    "minorTickMarks",
    "nf",
    "numDim",
    "numFmt",
    "number",
    "pageMargins",
    "pageSetup",
    "parentLabelLayout",
    "percent",
    "plotArea",
    "plotAreaRegion",
    "plotSurface",
    "printSettings",
    "pt",
    "regionLabelLayout",
    "rich",
    "series",
    "series_element_visibilities",
    "spPr",
    "statistics",
    "strDim",
    "string_level",
    "string_value",
    "subtotals",
    "tickLabels",
    "title",
    "tx",
    "txData",
    "txPr",
    "units",
    "unitsLabel",
    "valScaling",
    "valueColorPositions",
    "valueColors",
    "visibility",
]
