"""``el`` for the http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_spreadsheet_drawing_2010.json``, which a human reviews.

    >>> from docx4j_py.oart.spreadsheet_drawing_2010 import el
    >>> el.cNvContentPartPr()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTNonVisualDrawingProps,
    CTOfficeArtExtensionList,
    CTTransform2D,
)
from docx4j_py.oart.main_2010 import (
    CTNonVisualInkContentPartProperties,
)
from docx4j_py.oart.spreadsheet_drawing_2010 import (
    CTApplicationNonVisualDrawingProps,
    CTContentPartNonVisual,
    ContentPart,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing"

def cNvContentPartPr(**kwargs: Any) -> CTNonVisualInkContentPartProperties:
    """``{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}cNvContentPartPr`` -> :class:`docx4j_py.oart.main_2010.CTNonVisualInkContentPartProperties`."""
    return CTNonVisualInkContentPartProperties(**kwargs)

def cNvPr(**kwargs: Any) -> CTNonVisualDrawingProps:
    """``{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}cNvPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingProps`."""
    return CTNonVisualDrawingProps(**kwargs)

def contentPart(**kwargs: Any) -> ContentPart:
    """``{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}contentPart`` -> :class:`docx4j_py.oart.spreadsheet_drawing_2010.ContentPart`."""
    return ContentPart(**kwargs)

def extLst(**kwargs: Any) -> CTOfficeArtExtensionList:
    """``{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}extLst`` -> :class:`docx4j_py.dml.main.CTOfficeArtExtensionList`."""
    return CTOfficeArtExtensionList(**kwargs)

def nvContentPartPr(**kwargs: Any) -> CTContentPartNonVisual:
    """``{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}nvContentPartPr`` -> :class:`docx4j_py.oart.spreadsheet_drawing_2010.CTContentPartNonVisual`."""
    return CTContentPartNonVisual(**kwargs)

def nvPr(**kwargs: Any) -> CTApplicationNonVisualDrawingProps:
    """``{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}nvPr`` -> :class:`docx4j_py.oart.spreadsheet_drawing_2010.CTApplicationNonVisualDrawingProps`."""
    return CTApplicationNonVisualDrawingProps(**kwargs)

def xfrm(**kwargs: Any) -> CTTransform2D:
    """``{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}xfrm`` -> :class:`docx4j_py.dml.main.CTTransform2D`."""
    return CTTransform2D(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}cNvContentPartPr": CTNonVisualInkContentPartProperties,
    "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}cNvPr": CTNonVisualDrawingProps,
    "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}contentPart": ContentPart,
    "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}extLst": CTOfficeArtExtensionList,
    "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}nvContentPartPr": CTContentPartNonVisual,
    "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}nvPr": CTApplicationNonVisualDrawingProps,
    "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}xfrm": CTTransform2D,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "cNvContentPartPr": CTNonVisualInkContentPartProperties,
    "cNvPr": CTNonVisualDrawingProps,
    "contentPart": ContentPart,
    "extLst": CTOfficeArtExtensionList,
    "nvContentPartPr": CTContentPartNonVisual,
    "nvPr": CTApplicationNonVisualDrawingProps,
    "xfrm": CTTransform2D,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTApplicationNonVisualDrawingProps: "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}nvPr",
    CTContentPartNonVisual: "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}nvContentPartPr",
    CTNonVisualDrawingProps: "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}cNvPr",
    CTNonVisualInkContentPartProperties: "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}cNvContentPartPr",
    CTOfficeArtExtensionList: "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}extLst",
    CTTransform2D: "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}xfrm",
    ContentPart: "{http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing}contentPart",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "cNvContentPartPr",
    "cNvPr",
    "contentPart",
    "extLst",
    "nvContentPartPr",
    "nvPr",
    "xfrm",
]
