"""``el`` for the http://schemas.microsoft.com/office/drawing/2010/main namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_main_2010.json``, which a human reviews.

    >>> from docx4j_py.oart.main_2010 import el
    >>> el.artisticBlur()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTNonVisualDrawingProps,
    CTOfficeArtExtensionList,
    CTTransform2D,
)
from docx4j_py.oart.main_2010 import (
    CTContentPartLocking,
    CTEffectProperties,
    CTFillProperties,
    CTGvmlContentPartNonVisual,
    CTLineProperties,
    CTNonVisualInkContentPartProperties,
    CTPictureEffect,
    CTPictureEffectBackgroundRemoval,
    CTPictureEffectBackgroundRemovalBackgroundMark,
    CTPictureEffectBackgroundRemovalForegroundMark,
    CTPictureEffectBlur,
    CTPictureEffectBrightnessContrast,
    CTPictureEffectCement,
    CTPictureEffectChalkSketch,
    CTPictureEffectColorTemperature,
    CTPictureEffectCrisscrossEtching,
    CTPictureEffectCutout,
    CTPictureEffectFilmGrain,
    CTPictureEffectGlass,
    CTPictureEffectGlowDiffused,
    CTPictureEffectGlowEdges,
    CTPictureEffectLightScreen,
    CTPictureEffectLineDrawing,
    CTPictureEffectMarker,
    CTPictureEffectMosiaicBubbles,
    CTPictureEffectPaintBrush,
    CTPictureEffectPaintStrokes,
    CTPictureEffectPastelsSmooth,
    CTPictureEffectPencilGrayscale,
    CTPictureEffectPencilSketch,
    CTPictureEffectPhotocopy,
    CTPictureEffectPlasticWrap,
    CTPictureEffectSaturation,
    CTPictureEffectSharpenSoften,
    CTPictureEffectTexturizer,
    CTPictureEffectWatercolorSponge,
    CTPictureLayer,
    CTScene3D,
    CTShape3D,
    CameraTool,
    CompatExt,
    ContentPart,
    ImgProps,
    IsCanvas,
    M,
    ShadowObscured,
    UseLocalDpi,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2010/main"

def artisticBlur(**kwargs: Any) -> CTPictureEffectBlur:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticBlur`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectBlur`."""
    return CTPictureEffectBlur(**kwargs)

def artisticCement(**kwargs: Any) -> CTPictureEffectCement:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticCement`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectCement`."""
    return CTPictureEffectCement(**kwargs)

def artisticChalkSketch(**kwargs: Any) -> CTPictureEffectChalkSketch:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticChalkSketch`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectChalkSketch`."""
    return CTPictureEffectChalkSketch(**kwargs)

def artisticCrisscrossEtching(**kwargs: Any) -> CTPictureEffectCrisscrossEtching:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticCrisscrossEtching`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectCrisscrossEtching`."""
    return CTPictureEffectCrisscrossEtching(**kwargs)

def artisticCutout(**kwargs: Any) -> CTPictureEffectCutout:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticCutout`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectCutout`."""
    return CTPictureEffectCutout(**kwargs)

def artisticFilmGrain(**kwargs: Any) -> CTPictureEffectFilmGrain:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticFilmGrain`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectFilmGrain`."""
    return CTPictureEffectFilmGrain(**kwargs)

def artisticGlass(**kwargs: Any) -> CTPictureEffectGlass:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticGlass`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectGlass`."""
    return CTPictureEffectGlass(**kwargs)

def artisticGlowDiffused(**kwargs: Any) -> CTPictureEffectGlowDiffused:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticGlowDiffused`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectGlowDiffused`."""
    return CTPictureEffectGlowDiffused(**kwargs)

def artisticGlowEdges(**kwargs: Any) -> CTPictureEffectGlowEdges:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticGlowEdges`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectGlowEdges`."""
    return CTPictureEffectGlowEdges(**kwargs)

def artisticLightScreen(**kwargs: Any) -> CTPictureEffectLightScreen:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticLightScreen`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectLightScreen`."""
    return CTPictureEffectLightScreen(**kwargs)

def artisticLineDrawing(**kwargs: Any) -> CTPictureEffectLineDrawing:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticLineDrawing`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectLineDrawing`."""
    return CTPictureEffectLineDrawing(**kwargs)

def artisticMarker(**kwargs: Any) -> CTPictureEffectMarker:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticMarker`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectMarker`."""
    return CTPictureEffectMarker(**kwargs)

def artisticMosiaicBubbles(**kwargs: Any) -> CTPictureEffectMosiaicBubbles:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticMosiaicBubbles`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectMosiaicBubbles`."""
    return CTPictureEffectMosiaicBubbles(**kwargs)

def artisticPaintBrush(**kwargs: Any) -> CTPictureEffectPaintBrush:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticPaintBrush`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectPaintBrush`."""
    return CTPictureEffectPaintBrush(**kwargs)

def artisticPaintStrokes(**kwargs: Any) -> CTPictureEffectPaintStrokes:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticPaintStrokes`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectPaintStrokes`."""
    return CTPictureEffectPaintStrokes(**kwargs)

def artisticPastelsSmooth(**kwargs: Any) -> CTPictureEffectPastelsSmooth:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticPastelsSmooth`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectPastelsSmooth`."""
    return CTPictureEffectPastelsSmooth(**kwargs)

def artisticPencilGrayscale(**kwargs: Any) -> CTPictureEffectPencilGrayscale:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticPencilGrayscale`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectPencilGrayscale`."""
    return CTPictureEffectPencilGrayscale(**kwargs)

def artisticPencilSketch(**kwargs: Any) -> CTPictureEffectPencilSketch:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticPencilSketch`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectPencilSketch`."""
    return CTPictureEffectPencilSketch(**kwargs)

def artisticPhotocopy(**kwargs: Any) -> CTPictureEffectPhotocopy:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticPhotocopy`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectPhotocopy`."""
    return CTPictureEffectPhotocopy(**kwargs)

def artisticPlasticWrap(**kwargs: Any) -> CTPictureEffectPlasticWrap:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticPlasticWrap`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectPlasticWrap`."""
    return CTPictureEffectPlasticWrap(**kwargs)

def artisticTexturizer(**kwargs: Any) -> CTPictureEffectTexturizer:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticTexturizer`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectTexturizer`."""
    return CTPictureEffectTexturizer(**kwargs)

def artisticWatercolorSponge(**kwargs: Any) -> CTPictureEffectWatercolorSponge:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}artisticWatercolorSponge`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectWatercolorSponge`."""
    return CTPictureEffectWatercolorSponge(**kwargs)

def backgroundMark(**kwargs: Any) -> CTPictureEffectBackgroundRemovalBackgroundMark:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}backgroundMark`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectBackgroundRemovalBackgroundMark`."""
    return CTPictureEffectBackgroundRemovalBackgroundMark(**kwargs)

def backgroundRemoval(**kwargs: Any) -> CTPictureEffectBackgroundRemoval:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}backgroundRemoval`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectBackgroundRemoval`."""
    return CTPictureEffectBackgroundRemoval(**kwargs)

def brightnessContrast(**kwargs: Any) -> CTPictureEffectBrightnessContrast:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}brightnessContrast`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectBrightnessContrast`."""
    return CTPictureEffectBrightnessContrast(**kwargs)

def cNvContentPartPr(**kwargs: Any) -> CTNonVisualInkContentPartProperties:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}cNvContentPartPr`` -> :class:`docx4j_py.oart.main_2010.CTNonVisualInkContentPartProperties`."""
    return CTNonVisualInkContentPartProperties(**kwargs)

def cNvPr(**kwargs: Any) -> CTNonVisualDrawingProps:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}cNvPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingProps`."""
    return CTNonVisualDrawingProps(**kwargs)

def cameraTool(**kwargs: Any) -> CameraTool:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}cameraTool`` -> :class:`docx4j_py.oart.main_2010.CameraTool`."""
    return CameraTool(**kwargs)

def colorTemperature(**kwargs: Any) -> CTPictureEffectColorTemperature:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}colorTemperature`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectColorTemperature`."""
    return CTPictureEffectColorTemperature(**kwargs)

def compatExt(**kwargs: Any) -> CompatExt:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}compatExt`` -> :class:`docx4j_py.oart.main_2010.CompatExt`."""
    return CompatExt(**kwargs)

def contentPart(**kwargs: Any) -> ContentPart:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}contentPart`` -> :class:`docx4j_py.oart.main_2010.ContentPart`."""
    return ContentPart(**kwargs)

def cpLocks(**kwargs: Any) -> CTContentPartLocking:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}cpLocks`` -> :class:`docx4j_py.oart.main_2010.CTContentPartLocking`."""
    return CTContentPartLocking(**kwargs)

def extLst(**kwargs: Any) -> CTOfficeArtExtensionList:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}extLst`` -> :class:`docx4j_py.dml.main.CTOfficeArtExtensionList`."""
    return CTOfficeArtExtensionList(**kwargs)

def foregroundMark(**kwargs: Any) -> CTPictureEffectBackgroundRemovalForegroundMark:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}foregroundMark`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectBackgroundRemovalForegroundMark`."""
    return CTPictureEffectBackgroundRemovalForegroundMark(**kwargs)

def hiddenEffects(**kwargs: Any) -> CTEffectProperties:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}hiddenEffects`` -> :class:`docx4j_py.oart.main_2010.CTEffectProperties`."""
    return CTEffectProperties(**kwargs)

def hiddenFill(**kwargs: Any) -> CTFillProperties:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}hiddenFill`` -> :class:`docx4j_py.oart.main_2010.CTFillProperties`."""
    return CTFillProperties(**kwargs)

def hiddenLine(**kwargs: Any) -> CTLineProperties:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}hiddenLine`` -> :class:`docx4j_py.oart.main_2010.CTLineProperties`."""
    return CTLineProperties(**kwargs)

def hiddenScene3d(**kwargs: Any) -> CTScene3D:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}hiddenScene3d`` -> :class:`docx4j_py.oart.main_2010.CTScene3D`."""
    return CTScene3D(**kwargs)

def hiddenSp3d(**kwargs: Any) -> CTShape3D:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}hiddenSp3d`` -> :class:`docx4j_py.oart.main_2010.CTShape3D`."""
    return CTShape3D(**kwargs)

def imgEffect(**kwargs: Any) -> CTPictureEffect:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}imgEffect`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffect`."""
    return CTPictureEffect(**kwargs)

def imgLayer(**kwargs: Any) -> CTPictureLayer:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}imgLayer`` -> :class:`docx4j_py.oart.main_2010.CTPictureLayer`."""
    return CTPictureLayer(**kwargs)

def imgProps(**kwargs: Any) -> ImgProps:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}imgProps`` -> :class:`docx4j_py.oart.main_2010.ImgProps`."""
    return ImgProps(**kwargs)

def isCanvas(**kwargs: Any) -> IsCanvas:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}isCanvas`` -> :class:`docx4j_py.oart.main_2010.IsCanvas`."""
    return IsCanvas(**kwargs)

def m(**kwargs: Any) -> M:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}m`` -> :class:`docx4j_py.oart.main_2010.M`."""
    return M(**kwargs)

def nvContentPartPr(**kwargs: Any) -> CTGvmlContentPartNonVisual:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}nvContentPartPr`` -> :class:`docx4j_py.oart.main_2010.CTGvmlContentPartNonVisual`."""
    return CTGvmlContentPartNonVisual(**kwargs)

def saturation(**kwargs: Any) -> CTPictureEffectSaturation:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}saturation`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectSaturation`."""
    return CTPictureEffectSaturation(**kwargs)

def shadowObscured(**kwargs: Any) -> ShadowObscured:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}shadowObscured`` -> :class:`docx4j_py.oart.main_2010.ShadowObscured`."""
    return ShadowObscured(**kwargs)

def sharpenSoften(**kwargs: Any) -> CTPictureEffectSharpenSoften:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}sharpenSoften`` -> :class:`docx4j_py.oart.main_2010.CTPictureEffectSharpenSoften`."""
    return CTPictureEffectSharpenSoften(**kwargs)

def useLocalDpi(**kwargs: Any) -> UseLocalDpi:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}useLocalDpi`` -> :class:`docx4j_py.oart.main_2010.UseLocalDpi`."""
    return UseLocalDpi(**kwargs)

def xfrm(**kwargs: Any) -> CTTransform2D:
    """``{http://schemas.microsoft.com/office/drawing/2010/main}xfrm`` -> :class:`docx4j_py.dml.main.CTTransform2D`."""
    return CTTransform2D(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticBlur": CTPictureEffectBlur,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticCement": CTPictureEffectCement,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticChalkSketch": CTPictureEffectChalkSketch,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticCrisscrossEtching": CTPictureEffectCrisscrossEtching,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticCutout": CTPictureEffectCutout,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticFilmGrain": CTPictureEffectFilmGrain,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticGlass": CTPictureEffectGlass,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticGlowDiffused": CTPictureEffectGlowDiffused,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticGlowEdges": CTPictureEffectGlowEdges,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticLightScreen": CTPictureEffectLightScreen,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticLineDrawing": CTPictureEffectLineDrawing,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticMarker": CTPictureEffectMarker,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticMosiaicBubbles": CTPictureEffectMosiaicBubbles,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPaintBrush": CTPictureEffectPaintBrush,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPaintStrokes": CTPictureEffectPaintStrokes,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPastelsSmooth": CTPictureEffectPastelsSmooth,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPencilGrayscale": CTPictureEffectPencilGrayscale,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPencilSketch": CTPictureEffectPencilSketch,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPhotocopy": CTPictureEffectPhotocopy,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPlasticWrap": CTPictureEffectPlasticWrap,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticTexturizer": CTPictureEffectTexturizer,
    "{http://schemas.microsoft.com/office/drawing/2010/main}artisticWatercolorSponge": CTPictureEffectWatercolorSponge,
    "{http://schemas.microsoft.com/office/drawing/2010/main}backgroundMark": CTPictureEffectBackgroundRemovalBackgroundMark,
    "{http://schemas.microsoft.com/office/drawing/2010/main}backgroundRemoval": CTPictureEffectBackgroundRemoval,
    "{http://schemas.microsoft.com/office/drawing/2010/main}brightnessContrast": CTPictureEffectBrightnessContrast,
    "{http://schemas.microsoft.com/office/drawing/2010/main}cNvContentPartPr": CTNonVisualInkContentPartProperties,
    "{http://schemas.microsoft.com/office/drawing/2010/main}cNvPr": CTNonVisualDrawingProps,
    "{http://schemas.microsoft.com/office/drawing/2010/main}cameraTool": CameraTool,
    "{http://schemas.microsoft.com/office/drawing/2010/main}colorTemperature": CTPictureEffectColorTemperature,
    "{http://schemas.microsoft.com/office/drawing/2010/main}compatExt": CompatExt,
    "{http://schemas.microsoft.com/office/drawing/2010/main}contentPart": ContentPart,
    "{http://schemas.microsoft.com/office/drawing/2010/main}cpLocks": CTContentPartLocking,
    "{http://schemas.microsoft.com/office/drawing/2010/main}extLst": CTOfficeArtExtensionList,
    "{http://schemas.microsoft.com/office/drawing/2010/main}foregroundMark": CTPictureEffectBackgroundRemovalForegroundMark,
    "{http://schemas.microsoft.com/office/drawing/2010/main}hiddenEffects": CTEffectProperties,
    "{http://schemas.microsoft.com/office/drawing/2010/main}hiddenFill": CTFillProperties,
    "{http://schemas.microsoft.com/office/drawing/2010/main}hiddenLine": CTLineProperties,
    "{http://schemas.microsoft.com/office/drawing/2010/main}hiddenScene3d": CTScene3D,
    "{http://schemas.microsoft.com/office/drawing/2010/main}hiddenSp3d": CTShape3D,
    "{http://schemas.microsoft.com/office/drawing/2010/main}imgEffect": CTPictureEffect,
    "{http://schemas.microsoft.com/office/drawing/2010/main}imgLayer": CTPictureLayer,
    "{http://schemas.microsoft.com/office/drawing/2010/main}imgProps": ImgProps,
    "{http://schemas.microsoft.com/office/drawing/2010/main}isCanvas": IsCanvas,
    "{http://schemas.microsoft.com/office/drawing/2010/main}m": M,
    "{http://schemas.microsoft.com/office/drawing/2010/main}nvContentPartPr": CTGvmlContentPartNonVisual,
    "{http://schemas.microsoft.com/office/drawing/2010/main}saturation": CTPictureEffectSaturation,
    "{http://schemas.microsoft.com/office/drawing/2010/main}shadowObscured": ShadowObscured,
    "{http://schemas.microsoft.com/office/drawing/2010/main}sharpenSoften": CTPictureEffectSharpenSoften,
    "{http://schemas.microsoft.com/office/drawing/2010/main}useLocalDpi": UseLocalDpi,
    "{http://schemas.microsoft.com/office/drawing/2010/main}xfrm": CTTransform2D,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "artisticBlur": CTPictureEffectBlur,
    "artisticCement": CTPictureEffectCement,
    "artisticChalkSketch": CTPictureEffectChalkSketch,
    "artisticCrisscrossEtching": CTPictureEffectCrisscrossEtching,
    "artisticCutout": CTPictureEffectCutout,
    "artisticFilmGrain": CTPictureEffectFilmGrain,
    "artisticGlass": CTPictureEffectGlass,
    "artisticGlowDiffused": CTPictureEffectGlowDiffused,
    "artisticGlowEdges": CTPictureEffectGlowEdges,
    "artisticLightScreen": CTPictureEffectLightScreen,
    "artisticLineDrawing": CTPictureEffectLineDrawing,
    "artisticMarker": CTPictureEffectMarker,
    "artisticMosiaicBubbles": CTPictureEffectMosiaicBubbles,
    "artisticPaintBrush": CTPictureEffectPaintBrush,
    "artisticPaintStrokes": CTPictureEffectPaintStrokes,
    "artisticPastelsSmooth": CTPictureEffectPastelsSmooth,
    "artisticPencilGrayscale": CTPictureEffectPencilGrayscale,
    "artisticPencilSketch": CTPictureEffectPencilSketch,
    "artisticPhotocopy": CTPictureEffectPhotocopy,
    "artisticPlasticWrap": CTPictureEffectPlasticWrap,
    "artisticTexturizer": CTPictureEffectTexturizer,
    "artisticWatercolorSponge": CTPictureEffectWatercolorSponge,
    "backgroundMark": CTPictureEffectBackgroundRemovalBackgroundMark,
    "backgroundRemoval": CTPictureEffectBackgroundRemoval,
    "brightnessContrast": CTPictureEffectBrightnessContrast,
    "cNvContentPartPr": CTNonVisualInkContentPartProperties,
    "cNvPr": CTNonVisualDrawingProps,
    "cameraTool": CameraTool,
    "colorTemperature": CTPictureEffectColorTemperature,
    "compatExt": CompatExt,
    "contentPart": ContentPart,
    "cpLocks": CTContentPartLocking,
    "extLst": CTOfficeArtExtensionList,
    "foregroundMark": CTPictureEffectBackgroundRemovalForegroundMark,
    "hiddenEffects": CTEffectProperties,
    "hiddenFill": CTFillProperties,
    "hiddenLine": CTLineProperties,
    "hiddenScene3d": CTScene3D,
    "hiddenSp3d": CTShape3D,
    "imgEffect": CTPictureEffect,
    "imgLayer": CTPictureLayer,
    "imgProps": ImgProps,
    "isCanvas": IsCanvas,
    "m": M,
    "nvContentPartPr": CTGvmlContentPartNonVisual,
    "saturation": CTPictureEffectSaturation,
    "shadowObscured": ShadowObscured,
    "sharpenSoften": CTPictureEffectSharpenSoften,
    "useLocalDpi": UseLocalDpi,
    "xfrm": CTTransform2D,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTContentPartLocking: "{http://schemas.microsoft.com/office/drawing/2010/main}cpLocks",
    CTEffectProperties: "{http://schemas.microsoft.com/office/drawing/2010/main}hiddenEffects",
    CTFillProperties: "{http://schemas.microsoft.com/office/drawing/2010/main}hiddenFill",
    CTGvmlContentPartNonVisual: "{http://schemas.microsoft.com/office/drawing/2010/main}nvContentPartPr",
    CTLineProperties: "{http://schemas.microsoft.com/office/drawing/2010/main}hiddenLine",
    CTNonVisualDrawingProps: "{http://schemas.microsoft.com/office/drawing/2010/main}cNvPr",
    CTNonVisualInkContentPartProperties: "{http://schemas.microsoft.com/office/drawing/2010/main}cNvContentPartPr",
    CTOfficeArtExtensionList: "{http://schemas.microsoft.com/office/drawing/2010/main}extLst",
    CTPictureEffect: "{http://schemas.microsoft.com/office/drawing/2010/main}imgEffect",
    CTPictureEffectBackgroundRemoval: "{http://schemas.microsoft.com/office/drawing/2010/main}backgroundRemoval",
    CTPictureEffectBackgroundRemovalBackgroundMark: "{http://schemas.microsoft.com/office/drawing/2010/main}backgroundMark",
    CTPictureEffectBackgroundRemovalForegroundMark: "{http://schemas.microsoft.com/office/drawing/2010/main}foregroundMark",
    CTPictureEffectBlur: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticBlur",
    CTPictureEffectBrightnessContrast: "{http://schemas.microsoft.com/office/drawing/2010/main}brightnessContrast",
    CTPictureEffectCement: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticCement",
    CTPictureEffectChalkSketch: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticChalkSketch",
    CTPictureEffectColorTemperature: "{http://schemas.microsoft.com/office/drawing/2010/main}colorTemperature",
    CTPictureEffectCrisscrossEtching: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticCrisscrossEtching",
    CTPictureEffectCutout: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticCutout",
    CTPictureEffectFilmGrain: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticFilmGrain",
    CTPictureEffectGlass: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticGlass",
    CTPictureEffectGlowDiffused: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticGlowDiffused",
    CTPictureEffectGlowEdges: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticGlowEdges",
    CTPictureEffectLightScreen: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticLightScreen",
    CTPictureEffectLineDrawing: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticLineDrawing",
    CTPictureEffectMarker: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticMarker",
    CTPictureEffectMosiaicBubbles: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticMosiaicBubbles",
    CTPictureEffectPaintBrush: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPaintBrush",
    CTPictureEffectPaintStrokes: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPaintStrokes",
    CTPictureEffectPastelsSmooth: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPastelsSmooth",
    CTPictureEffectPencilGrayscale: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPencilGrayscale",
    CTPictureEffectPencilSketch: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPencilSketch",
    CTPictureEffectPhotocopy: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPhotocopy",
    CTPictureEffectPlasticWrap: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticPlasticWrap",
    CTPictureEffectSaturation: "{http://schemas.microsoft.com/office/drawing/2010/main}saturation",
    CTPictureEffectSharpenSoften: "{http://schemas.microsoft.com/office/drawing/2010/main}sharpenSoften",
    CTPictureEffectTexturizer: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticTexturizer",
    CTPictureEffectWatercolorSponge: "{http://schemas.microsoft.com/office/drawing/2010/main}artisticWatercolorSponge",
    CTPictureLayer: "{http://schemas.microsoft.com/office/drawing/2010/main}imgLayer",
    CTScene3D: "{http://schemas.microsoft.com/office/drawing/2010/main}hiddenScene3d",
    CTShape3D: "{http://schemas.microsoft.com/office/drawing/2010/main}hiddenSp3d",
    CTTransform2D: "{http://schemas.microsoft.com/office/drawing/2010/main}xfrm",
    CameraTool: "{http://schemas.microsoft.com/office/drawing/2010/main}cameraTool",
    CompatExt: "{http://schemas.microsoft.com/office/drawing/2010/main}compatExt",
    ContentPart: "{http://schemas.microsoft.com/office/drawing/2010/main}contentPart",
    ImgProps: "{http://schemas.microsoft.com/office/drawing/2010/main}imgProps",
    IsCanvas: "{http://schemas.microsoft.com/office/drawing/2010/main}isCanvas",
    M: "{http://schemas.microsoft.com/office/drawing/2010/main}m",
    ShadowObscured: "{http://schemas.microsoft.com/office/drawing/2010/main}shadowObscured",
    UseLocalDpi: "{http://schemas.microsoft.com/office/drawing/2010/main}useLocalDpi",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "artisticBlur",
    "artisticCement",
    "artisticChalkSketch",
    "artisticCrisscrossEtching",
    "artisticCutout",
    "artisticFilmGrain",
    "artisticGlass",
    "artisticGlowDiffused",
    "artisticGlowEdges",
    "artisticLightScreen",
    "artisticLineDrawing",
    "artisticMarker",
    "artisticMosiaicBubbles",
    "artisticPaintBrush",
    "artisticPaintStrokes",
    "artisticPastelsSmooth",
    "artisticPencilGrayscale",
    "artisticPencilSketch",
    "artisticPhotocopy",
    "artisticPlasticWrap",
    "artisticTexturizer",
    "artisticWatercolorSponge",
    "backgroundMark",
    "backgroundRemoval",
    "brightnessContrast",
    "cNvContentPartPr",
    "cNvPr",
    "cameraTool",
    "colorTemperature",
    "compatExt",
    "contentPart",
    "cpLocks",
    "extLst",
    "foregroundMark",
    "hiddenEffects",
    "hiddenFill",
    "hiddenLine",
    "hiddenScene3d",
    "hiddenSp3d",
    "imgEffect",
    "imgLayer",
    "imgProps",
    "isCanvas",
    "m",
    "nvContentPartPr",
    "saturation",
    "shadowObscured",
    "sharpenSoften",
    "useLocalDpi",
    "xfrm",
]
