"""``el`` for the http://schemas.microsoft.com/office/drawing/2018/animation/model3d namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_animation_model3d_2018.json``, which a human reviews.

    >>> from docx4j_py.oart.animation_model3d_2018 import el
    >>> el.animPr()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTOfficeArtExtensionList,
)
from docx4j_py.oart.animation_2018 import (
    CTAnimationProperties,
)
from docx4j_py.oart.animation_model3d_2018 import (
    EmbedAnim,
    PosterFrame,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2018/animation/model3d"

def animPr(**kwargs: Any) -> CTAnimationProperties:
    """``{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}animPr`` -> :class:`docx4j_py.oart.animation_2018.CTAnimationProperties`."""
    return CTAnimationProperties(**kwargs)

def embedAnim(**kwargs: Any) -> EmbedAnim:
    """``{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}embedAnim`` -> :class:`docx4j_py.oart.animation_model3d_2018.EmbedAnim`."""
    return EmbedAnim(**kwargs)

def extLst(**kwargs: Any) -> CTOfficeArtExtensionList:
    """``{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}extLst`` -> :class:`docx4j_py.dml.main.CTOfficeArtExtensionList`."""
    return CTOfficeArtExtensionList(**kwargs)

def posterFrame(**kwargs: Any) -> PosterFrame:
    """``{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}posterFrame`` -> :class:`docx4j_py.oart.animation_model3d_2018.PosterFrame`."""
    return PosterFrame(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}animPr": CTAnimationProperties,
    "{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}embedAnim": EmbedAnim,
    "{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}extLst": CTOfficeArtExtensionList,
    "{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}posterFrame": PosterFrame,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "animPr": CTAnimationProperties,
    "embedAnim": EmbedAnim,
    "extLst": CTOfficeArtExtensionList,
    "posterFrame": PosterFrame,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTAnimationProperties: "{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}animPr",
    CTOfficeArtExtensionList: "{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}extLst",
    EmbedAnim: "{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}embedAnim",
    PosterFrame: "{http://schemas.microsoft.com/office/drawing/2018/animation/model3d}posterFrame",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "animPr",
    "embedAnim",
    "extLst",
    "posterFrame",
]
