"""``el`` for the http://schemas.microsoft.com/ink/2010/main namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/word_msink.json``, which a human reviews.

    >>> from docx4j_py.word.msink import el
    >>> el.context()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.word.msink import (
    CTCtxLink,
    CTProperty,
    Context,
)

__NAMESPACE__ = "http://schemas.microsoft.com/ink/2010/main"

def context(**kwargs: Any) -> Context:
    """``{http://schemas.microsoft.com/ink/2010/main}context`` -> :class:`docx4j_py.word.msink.Context`."""
    return Context(**kwargs)

def destinationLink(**kwargs: Any) -> CTCtxLink:
    """``{http://schemas.microsoft.com/ink/2010/main}destinationLink`` -> :class:`docx4j_py.word.msink.CTCtxLink`."""
    return CTCtxLink(**kwargs)

def property_(text: str | None = None, /, **kwargs: Any) -> CTProperty:
    """``{http://schemas.microsoft.com/ink/2010/main}property`` -> :class:`docx4j_py.word.msink.CTProperty`."""
    return text_element(CTProperty, text, kwargs, "value", null)

def sourceLink(**kwargs: Any) -> CTCtxLink:
    """``{http://schemas.microsoft.com/ink/2010/main}sourceLink`` -> :class:`docx4j_py.word.msink.CTCtxLink`."""
    return CTCtxLink(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/ink/2010/main}context": Context,
    "{http://schemas.microsoft.com/ink/2010/main}destinationLink": CTCtxLink,
    "{http://schemas.microsoft.com/ink/2010/main}property": CTProperty,
    "{http://schemas.microsoft.com/ink/2010/main}sourceLink": CTCtxLink,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "context": Context,
    "destinationLink": CTCtxLink,
    "property": CTProperty,
    "sourceLink": CTCtxLink,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTProperty: "{http://schemas.microsoft.com/ink/2010/main}property",
    Context: "{http://schemas.microsoft.com/ink/2010/main}context",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "context",
    "destinationLink",
    "property_",
    "sourceLink",
]
