"""``el`` for the http://schemas.microsoft.com/office/drawing/2007/8/2/chart namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_chart_2007.json``, which a human reviews.

    >>> from docx4j_py.oart.chart_2007 import el
    >>> el.dropZoneCategories()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTShapeProperties,
)
from docx4j_py.oart.chart_2007 import (
    CTBooleanFalse,
    InvertSolidFillFmt,
    PivotOptions,
    Style,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2007/8/2/chart"

def dropZoneCategories(**kwargs: Any) -> CTBooleanFalse:
    """``{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}dropZoneCategories`` -> :class:`docx4j_py.oart.chart_2007.CTBooleanFalse`."""
    return CTBooleanFalse(**kwargs)

def dropZoneData(**kwargs: Any) -> CTBooleanFalse:
    """``{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}dropZoneData`` -> :class:`docx4j_py.oart.chart_2007.CTBooleanFalse`."""
    return CTBooleanFalse(**kwargs)

def dropZoneFilter(**kwargs: Any) -> CTBooleanFalse:
    """``{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}dropZoneFilter`` -> :class:`docx4j_py.oart.chart_2007.CTBooleanFalse`."""
    return CTBooleanFalse(**kwargs)

def dropZoneSeries(**kwargs: Any) -> CTBooleanFalse:
    """``{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}dropZoneSeries`` -> :class:`docx4j_py.oart.chart_2007.CTBooleanFalse`."""
    return CTBooleanFalse(**kwargs)

def dropZonesVisible(**kwargs: Any) -> CTBooleanFalse:
    """``{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}dropZonesVisible`` -> :class:`docx4j_py.oart.chart_2007.CTBooleanFalse`."""
    return CTBooleanFalse(**kwargs)

def invertSolidFillFmt(**kwargs: Any) -> InvertSolidFillFmt:
    """``{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}invertSolidFillFmt`` -> :class:`docx4j_py.oart.chart_2007.InvertSolidFillFmt`."""
    return InvertSolidFillFmt(**kwargs)

def pivotOptions(**kwargs: Any) -> PivotOptions:
    """``{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}pivotOptions`` -> :class:`docx4j_py.oart.chart_2007.PivotOptions`."""
    return PivotOptions(**kwargs)

def spPr(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}spPr`` -> :class:`docx4j_py.dml.main.CTShapeProperties`."""
    return CTShapeProperties(**kwargs)

def style(**kwargs: Any) -> Style:
    """``{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}style`` -> :class:`docx4j_py.oart.chart_2007.Style`."""
    return Style(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}dropZoneCategories": CTBooleanFalse,
    "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}dropZoneData": CTBooleanFalse,
    "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}dropZoneFilter": CTBooleanFalse,
    "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}dropZoneSeries": CTBooleanFalse,
    "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}dropZonesVisible": CTBooleanFalse,
    "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}invertSolidFillFmt": InvertSolidFillFmt,
    "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}pivotOptions": PivotOptions,
    "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}spPr": CTShapeProperties,
    "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}style": Style,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "dropZoneCategories": CTBooleanFalse,
    "dropZoneData": CTBooleanFalse,
    "dropZoneFilter": CTBooleanFalse,
    "dropZoneSeries": CTBooleanFalse,
    "dropZonesVisible": CTBooleanFalse,
    "invertSolidFillFmt": InvertSolidFillFmt,
    "pivotOptions": PivotOptions,
    "spPr": CTShapeProperties,
    "style": Style,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTShapeProperties: "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}spPr",
    InvertSolidFillFmt: "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}invertSolidFillFmt",
    PivotOptions: "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}pivotOptions",
    Style: "{http://schemas.microsoft.com/office/drawing/2007/8/2/chart}style",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "dropZoneCategories",
    "dropZoneData",
    "dropZoneFilter",
    "dropZoneSeries",
    "dropZonesVisible",
    "invertSolidFillFmt",
    "pivotOptions",
    "spPr",
    "style",
]
