"""``el`` for the http://schemas.microsoft.com/office/drawing/2017/03/chart namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_chart_2017_03.json``, which a human reviews.

    >>> from docx4j_py.oart.chart_2017_03 import el
    >>> el.dataDisplayOptions16()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.oart.chart_2017_03 import (
    CTBooleanFalse,
    DataDisplayOptions16,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2017/03/chart"

def dataDisplayOptions16(**kwargs: Any) -> DataDisplayOptions16:
    """``{http://schemas.microsoft.com/office/drawing/2017/03/chart}dataDisplayOptions16`` -> :class:`docx4j_py.oart.chart_2017_03.DataDisplayOptions16`."""
    return DataDisplayOptions16(**kwargs)

def dispNaAsBlank(**kwargs: Any) -> CTBooleanFalse:
    """``{http://schemas.microsoft.com/office/drawing/2017/03/chart}dispNaAsBlank`` -> :class:`docx4j_py.oart.chart_2017_03.CTBooleanFalse`."""
    return CTBooleanFalse(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2017/03/chart}dataDisplayOptions16": DataDisplayOptions16,
    "{http://schemas.microsoft.com/office/drawing/2017/03/chart}dispNaAsBlank": CTBooleanFalse,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "dataDisplayOptions16": DataDisplayOptions16,
    "dispNaAsBlank": CTBooleanFalse,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTBooleanFalse: "{http://schemas.microsoft.com/office/drawing/2017/03/chart}dispNaAsBlank",
    DataDisplayOptions16: "{http://schemas.microsoft.com/office/drawing/2017/03/chart}dataDisplayOptions16",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "dataDisplayOptions16",
    "dispNaAsBlank",
]
