"""``el`` for the http://schemas.openxmlformats.org/officeDocument/2006/custom-properties namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/docprops_custom.json``, which a human reviews.

    >>> from docx4j_py.docprops.custom import el
    >>> el.Properties()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.docprops.custom import (
    Properties as _Properties,
    PropertiesProperty,
)

__NAMESPACE__ = "http://schemas.openxmlformats.org/officeDocument/2006/custom-properties"

def Properties(**kwargs: Any) -> _Properties:
    """``{http://schemas.openxmlformats.org/officeDocument/2006/custom-properties}Properties`` -> :class:`docx4j_py.docprops.custom.Properties`."""
    return _Properties(**kwargs)

def property_(**kwargs: Any) -> PropertiesProperty:
    """``{http://schemas.openxmlformats.org/officeDocument/2006/custom-properties}property`` -> :class:`docx4j_py.docprops.custom.PropertiesProperty`."""
    return PropertiesProperty(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.openxmlformats.org/officeDocument/2006/custom-properties}Properties": _Properties,
    "{http://schemas.openxmlformats.org/officeDocument/2006/custom-properties}property": PropertiesProperty,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "Properties": _Properties,
    "property": PropertiesProperty,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    _Properties: "{http://schemas.openxmlformats.org/officeDocument/2006/custom-properties}Properties",
    PropertiesProperty: "{http://schemas.openxmlformats.org/officeDocument/2006/custom-properties}property",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "Properties",
    "QNAME_TO_CLASS",
    "property_",
]
