"""``el`` for the http://schemas.microsoft.com/office/word/2012/wordprocessingDrawing namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/word_wp15.json``, which a human reviews.

    >>> from docx4j_py.word.wp15 import el
    >>> el.webVideoPr()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.word.wp15 import (
    WebVideoPr,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/word/2012/wordprocessingDrawing"

def webVideoPr(**kwargs: Any) -> WebVideoPr:
    """``{http://schemas.microsoft.com/office/word/2012/wordprocessingDrawing}webVideoPr`` -> :class:`docx4j_py.word.wp15.WebVideoPr`."""
    return WebVideoPr(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/word/2012/wordprocessingDrawing}webVideoPr": WebVideoPr,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "webVideoPr": WebVideoPr,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    WebVideoPr: "{http://schemas.microsoft.com/office/word/2012/wordprocessingDrawing}webVideoPr",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "webVideoPr",
]
