"""``el`` for the http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/word_wp14.json``, which a human reviews.

    >>> from docx4j_py.word.wp14 import el
    >>> el.pctPosHOffset()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.word.wp14 import (
    PctPosHoffset,
    PctPosVoffset,
    SizeRelH,
    SizeRelV,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing"

def pctPosHOffset(text: str | None = None, /, **kwargs: Any) -> PctPosHoffset:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}pctPosHOffset`` -> :class:`docx4j_py.word.wp14.PctPosHoffset`."""
    return text_element(PctPosHoffset, text, kwargs, "value", null)

def pctPosVOffset(text: str | None = None, /, **kwargs: Any) -> PctPosVoffset:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}pctPosVOffset`` -> :class:`docx4j_py.word.wp14.PctPosVoffset`."""
    return text_element(PctPosVoffset, text, kwargs, "value", null)

def sizeRelH(**kwargs: Any) -> SizeRelH:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}sizeRelH`` -> :class:`docx4j_py.word.wp14.SizeRelH`."""
    return SizeRelH(**kwargs)

def sizeRelV(**kwargs: Any) -> SizeRelV:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}sizeRelV`` -> :class:`docx4j_py.word.wp14.SizeRelV`."""
    return SizeRelV(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}pctPosHOffset": PctPosHoffset,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}pctPosVOffset": PctPosVoffset,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}sizeRelH": SizeRelH,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}sizeRelV": SizeRelV,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "pctPosHOffset": PctPosHoffset,
    "pctPosVOffset": PctPosVoffset,
    "sizeRelH": SizeRelH,
    "sizeRelV": SizeRelV,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    PctPosHoffset: "{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}pctPosHOffset",
    PctPosVoffset: "{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}pctPosVOffset",
    SizeRelH: "{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}sizeRelH",
    SizeRelV: "{http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}sizeRelV",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "pctPosHOffset",
    "pctPosVOffset",
    "sizeRelH",
    "sizeRelV",
]
