"""``el`` for the http://schemas.microsoft.com/office/drawing/2013/main/command namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_command_2013.json``, which a human reviews.

    >>> from docx4j_py.oart.command_2013 import el
    >>> el.chgData()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTOfficeArtExtensionList,
)
from docx4j_py.oart.command_2013 import (
    CTChangesData,
    CTConnectorMonikerList,
    CTGraphicFrameMonikerList,
    CTGroupShapeMonikerList,
    CTInkMonikerList,
    CTPictureMonikerList,
    CTShapeMonikerList,
    CxnSpMkLst,
    GraphicFrameMkLst,
    GrpMkLst,
    InkMkLst,
    PicMkLst,
    SpMkLst,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2013/main/command"

def chgData(**kwargs: Any) -> CTChangesData:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}chgData`` -> :class:`docx4j_py.oart.command_2013.CTChangesData`."""
    return CTChangesData(**kwargs)

def cxnSpMkLst(**kwargs: Any) -> CxnSpMkLst:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}cxnSpMkLst`` -> :class:`docx4j_py.oart.command_2013.CxnSpMkLst`, the global element declaration of 2 classes this name takes; see ``connector_moniker_list``."""
    return CxnSpMkLst(**kwargs)

def connector_moniker_list(**kwargs: Any) -> CTConnectorMonikerList:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}cxnSpMkLst`` -> :class:`docx4j_py.oart.command_2013.CTConnectorMonikerList`, the CTConnectorMonikerList form."""
    return CTConnectorMonikerList(**kwargs)

def extLst(**kwargs: Any) -> CTOfficeArtExtensionList:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}extLst`` -> :class:`docx4j_py.dml.main.CTOfficeArtExtensionList`."""
    return CTOfficeArtExtensionList(**kwargs)

def graphicFrameMkLst(**kwargs: Any) -> GraphicFrameMkLst:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}graphicFrameMkLst`` -> :class:`docx4j_py.oart.command_2013.GraphicFrameMkLst`, the global element declaration of 2 classes this name takes; see ``graphic_frame_moniker_list``."""
    return GraphicFrameMkLst(**kwargs)

def graphic_frame_moniker_list(**kwargs: Any) -> CTGraphicFrameMonikerList:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}graphicFrameMkLst`` -> :class:`docx4j_py.oart.command_2013.CTGraphicFrameMonikerList`, the CTGraphicFrameMonikerList form."""
    return CTGraphicFrameMonikerList(**kwargs)

def grpMkLst(**kwargs: Any) -> GrpMkLst:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}grpMkLst`` -> :class:`docx4j_py.oart.command_2013.GrpMkLst`."""
    return GrpMkLst(**kwargs)

def grpSpMkLst(**kwargs: Any) -> CTGroupShapeMonikerList:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}grpSpMkLst`` -> :class:`docx4j_py.oart.command_2013.CTGroupShapeMonikerList`."""
    return CTGroupShapeMonikerList(**kwargs)

def inkMkLst(**kwargs: Any) -> InkMkLst:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}inkMkLst`` -> :class:`docx4j_py.oart.command_2013.InkMkLst`, the global element declaration of 2 classes this name takes; see ``ink_moniker_list``."""
    return InkMkLst(**kwargs)

def ink_moniker_list(**kwargs: Any) -> CTInkMonikerList:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}inkMkLst`` -> :class:`docx4j_py.oart.command_2013.CTInkMonikerList`, the CTInkMonikerList form."""
    return CTInkMonikerList(**kwargs)

def picMkLst(**kwargs: Any) -> PicMkLst:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}picMkLst`` -> :class:`docx4j_py.oart.command_2013.PicMkLst`, the global element declaration of 2 classes this name takes; see ``picture_moniker_list``."""
    return PicMkLst(**kwargs)

def picture_moniker_list(**kwargs: Any) -> CTPictureMonikerList:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}picMkLst`` -> :class:`docx4j_py.oart.command_2013.CTPictureMonikerList`, the CTPictureMonikerList form."""
    return CTPictureMonikerList(**kwargs)

def spMkLst(**kwargs: Any) -> SpMkLst:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}spMkLst`` -> :class:`docx4j_py.oart.command_2013.SpMkLst`, the global element declaration of 2 classes this name takes; see ``shape_moniker_list``."""
    return SpMkLst(**kwargs)

def shape_moniker_list(**kwargs: Any) -> CTShapeMonikerList:
    """``{http://schemas.microsoft.com/office/drawing/2013/main/command}spMkLst`` -> :class:`docx4j_py.oart.command_2013.CTShapeMonikerList`, the CTShapeMonikerList form."""
    return CTShapeMonikerList(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2013/main/command}chgData": CTChangesData,
    "{http://schemas.microsoft.com/office/drawing/2013/main/command}cxnSpMkLst": CxnSpMkLst,
    "{http://schemas.microsoft.com/office/drawing/2013/main/command}extLst": CTOfficeArtExtensionList,
    "{http://schemas.microsoft.com/office/drawing/2013/main/command}graphicFrameMkLst": GraphicFrameMkLst,
    "{http://schemas.microsoft.com/office/drawing/2013/main/command}grpMkLst": GrpMkLst,
    "{http://schemas.microsoft.com/office/drawing/2013/main/command}grpSpMkLst": CTGroupShapeMonikerList,
    "{http://schemas.microsoft.com/office/drawing/2013/main/command}inkMkLst": InkMkLst,
    "{http://schemas.microsoft.com/office/drawing/2013/main/command}picMkLst": PicMkLst,
    "{http://schemas.microsoft.com/office/drawing/2013/main/command}spMkLst": SpMkLst,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "chgData": CTChangesData,
    "cxnSpMkLst": CxnSpMkLst,
    "extLst": CTOfficeArtExtensionList,
    "graphicFrameMkLst": GraphicFrameMkLst,
    "grpMkLst": GrpMkLst,
    "grpSpMkLst": CTGroupShapeMonikerList,
    "inkMkLst": InkMkLst,
    "picMkLst": PicMkLst,
    "spMkLst": SpMkLst,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTChangesData: "{http://schemas.microsoft.com/office/drawing/2013/main/command}chgData",
    CTConnectorMonikerList: "{http://schemas.microsoft.com/office/drawing/2013/main/command}cxnSpMkLst",
    CTGraphicFrameMonikerList: "{http://schemas.microsoft.com/office/drawing/2013/main/command}graphicFrameMkLst",
    CTGroupShapeMonikerList: "{http://schemas.microsoft.com/office/drawing/2013/main/command}grpSpMkLst",
    CTInkMonikerList: "{http://schemas.microsoft.com/office/drawing/2013/main/command}inkMkLst",
    CTOfficeArtExtensionList: "{http://schemas.microsoft.com/office/drawing/2013/main/command}extLst",
    CTPictureMonikerList: "{http://schemas.microsoft.com/office/drawing/2013/main/command}picMkLst",
    CTShapeMonikerList: "{http://schemas.microsoft.com/office/drawing/2013/main/command}spMkLst",
    CxnSpMkLst: "{http://schemas.microsoft.com/office/drawing/2013/main/command}cxnSpMkLst",
    GraphicFrameMkLst: "{http://schemas.microsoft.com/office/drawing/2013/main/command}graphicFrameMkLst",
    GrpMkLst: "{http://schemas.microsoft.com/office/drawing/2013/main/command}grpMkLst",
    InkMkLst: "{http://schemas.microsoft.com/office/drawing/2013/main/command}inkMkLst",
    PicMkLst: "{http://schemas.microsoft.com/office/drawing/2013/main/command}picMkLst",
    SpMkLst: "{http://schemas.microsoft.com/office/drawing/2013/main/command}spMkLst",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "chgData",
    "connector_moniker_list",
    "cxnSpMkLst",
    "extLst",
    "graphicFrameMkLst",
    "graphic_frame_moniker_list",
    "grpMkLst",
    "grpSpMkLst",
    "inkMkLst",
    "ink_moniker_list",
    "picMkLst",
    "picture_moniker_list",
    "shape_moniker_list",
    "spMkLst",
]
