"""``el`` for the http://purl.org/dc/elements/1.1/ namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/docprops_dc.json``, which a human reviews.

    >>> from docx4j_py.docprops.dc import el
    >>> el.any_()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.docprops.dc import (
    AnyType,
    Contributor,
    Coverage,
    Creator,
    Date,
    Description,
    Format,
    Identifier,
    Language,
    Publisher,
    Relation,
    Rights,
    Source,
    Subject,
    Title,
    Type,
)

__NAMESPACE__ = "http://purl.org/dc/elements/1.1/"

def any_(**kwargs: Any) -> AnyType:
    """``{http://purl.org/dc/elements/1.1/}any`` -> :class:`docx4j_py.docprops.dc.AnyType`."""
    return AnyType(**kwargs)

def contributor(**kwargs: Any) -> Contributor:
    """``{http://purl.org/dc/elements/1.1/}contributor`` -> :class:`docx4j_py.docprops.dc.Contributor`."""
    return Contributor(**kwargs)

def coverage(**kwargs: Any) -> Coverage:
    """``{http://purl.org/dc/elements/1.1/}coverage`` -> :class:`docx4j_py.docprops.dc.Coverage`."""
    return Coverage(**kwargs)

def creator(**kwargs: Any) -> Creator:
    """``{http://purl.org/dc/elements/1.1/}creator`` -> :class:`docx4j_py.docprops.dc.Creator`."""
    return Creator(**kwargs)

def date(**kwargs: Any) -> Date:
    """``{http://purl.org/dc/elements/1.1/}date`` -> :class:`docx4j_py.docprops.dc.Date`."""
    return Date(**kwargs)

def description(**kwargs: Any) -> Description:
    """``{http://purl.org/dc/elements/1.1/}description`` -> :class:`docx4j_py.docprops.dc.Description`."""
    return Description(**kwargs)

def format_(**kwargs: Any) -> Format:
    """``{http://purl.org/dc/elements/1.1/}format`` -> :class:`docx4j_py.docprops.dc.Format`."""
    return Format(**kwargs)

def identifier(**kwargs: Any) -> Identifier:
    """``{http://purl.org/dc/elements/1.1/}identifier`` -> :class:`docx4j_py.docprops.dc.Identifier`."""
    return Identifier(**kwargs)

def language(**kwargs: Any) -> Language:
    """``{http://purl.org/dc/elements/1.1/}language`` -> :class:`docx4j_py.docprops.dc.Language`."""
    return Language(**kwargs)

def publisher(**kwargs: Any) -> Publisher:
    """``{http://purl.org/dc/elements/1.1/}publisher`` -> :class:`docx4j_py.docprops.dc.Publisher`."""
    return Publisher(**kwargs)

def relation(**kwargs: Any) -> Relation:
    """``{http://purl.org/dc/elements/1.1/}relation`` -> :class:`docx4j_py.docprops.dc.Relation`."""
    return Relation(**kwargs)

def rights(**kwargs: Any) -> Rights:
    """``{http://purl.org/dc/elements/1.1/}rights`` -> :class:`docx4j_py.docprops.dc.Rights`."""
    return Rights(**kwargs)

def source(**kwargs: Any) -> Source:
    """``{http://purl.org/dc/elements/1.1/}source`` -> :class:`docx4j_py.docprops.dc.Source`."""
    return Source(**kwargs)

def subject(**kwargs: Any) -> Subject:
    """``{http://purl.org/dc/elements/1.1/}subject`` -> :class:`docx4j_py.docprops.dc.Subject`."""
    return Subject(**kwargs)

def title(**kwargs: Any) -> Title:
    """``{http://purl.org/dc/elements/1.1/}title`` -> :class:`docx4j_py.docprops.dc.Title`."""
    return Title(**kwargs)

def type_(**kwargs: Any) -> Type:
    """``{http://purl.org/dc/elements/1.1/}type`` -> :class:`docx4j_py.docprops.dc.Type`."""
    return Type(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://purl.org/dc/elements/1.1/}any": AnyType,
    "{http://purl.org/dc/elements/1.1/}contributor": Contributor,
    "{http://purl.org/dc/elements/1.1/}coverage": Coverage,
    "{http://purl.org/dc/elements/1.1/}creator": Creator,
    "{http://purl.org/dc/elements/1.1/}date": Date,
    "{http://purl.org/dc/elements/1.1/}description": Description,
    "{http://purl.org/dc/elements/1.1/}format": Format,
    "{http://purl.org/dc/elements/1.1/}identifier": Identifier,
    "{http://purl.org/dc/elements/1.1/}language": Language,
    "{http://purl.org/dc/elements/1.1/}publisher": Publisher,
    "{http://purl.org/dc/elements/1.1/}relation": Relation,
    "{http://purl.org/dc/elements/1.1/}rights": Rights,
    "{http://purl.org/dc/elements/1.1/}source": Source,
    "{http://purl.org/dc/elements/1.1/}subject": Subject,
    "{http://purl.org/dc/elements/1.1/}title": Title,
    "{http://purl.org/dc/elements/1.1/}type": Type,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "any": AnyType,
    "contributor": Contributor,
    "coverage": Coverage,
    "creator": Creator,
    "date": Date,
    "description": Description,
    "format": Format,
    "identifier": Identifier,
    "language": Language,
    "publisher": Publisher,
    "relation": Relation,
    "rights": Rights,
    "source": Source,
    "subject": Subject,
    "title": Title,
    "type": Type,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    AnyType: "{http://purl.org/dc/elements/1.1/}any",
    Contributor: "{http://purl.org/dc/elements/1.1/}contributor",
    Coverage: "{http://purl.org/dc/elements/1.1/}coverage",
    Creator: "{http://purl.org/dc/elements/1.1/}creator",
    Date: "{http://purl.org/dc/elements/1.1/}date",
    Description: "{http://purl.org/dc/elements/1.1/}description",
    Format: "{http://purl.org/dc/elements/1.1/}format",
    Identifier: "{http://purl.org/dc/elements/1.1/}identifier",
    Language: "{http://purl.org/dc/elements/1.1/}language",
    Publisher: "{http://purl.org/dc/elements/1.1/}publisher",
    Relation: "{http://purl.org/dc/elements/1.1/}relation",
    Rights: "{http://purl.org/dc/elements/1.1/}rights",
    Source: "{http://purl.org/dc/elements/1.1/}source",
    Subject: "{http://purl.org/dc/elements/1.1/}subject",
    Title: "{http://purl.org/dc/elements/1.1/}title",
    Type: "{http://purl.org/dc/elements/1.1/}type",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "any_",
    "contributor",
    "coverage",
    "creator",
    "date",
    "description",
    "format_",
    "identifier",
    "language",
    "publisher",
    "relation",
    "rights",
    "source",
    "subject",
    "title",
    "type_",
]
