"""``el`` for the http://schemas.openxmlformats.org/drawingml/2006/picture namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/dml_picture.json``, which a human reviews.

    >>> from docx4j_py.dml.picture import el
    >>> el.blipFill()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTBlipFillProperties,
    CTNonVisualDrawingProps,
    CTNonVisualPictureProperties,
    CTShapeProperties,
)
from docx4j_py.dml.picture import (
    CTPictureNonVisual,
    Pic,
)

__NAMESPACE__ = "http://schemas.openxmlformats.org/drawingml/2006/picture"

def blipFill(**kwargs: Any) -> CTBlipFillProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/picture}blipFill`` -> :class:`docx4j_py.dml.main.CTBlipFillProperties`."""
    return CTBlipFillProperties(**kwargs)

def cNvPicPr(**kwargs: Any) -> CTNonVisualPictureProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/picture}cNvPicPr`` -> :class:`docx4j_py.dml.main.CTNonVisualPictureProperties`."""
    return CTNonVisualPictureProperties(**kwargs)

def cNvPr(**kwargs: Any) -> CTNonVisualDrawingProps:
    """``{http://schemas.openxmlformats.org/drawingml/2006/picture}cNvPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingProps`."""
    return CTNonVisualDrawingProps(**kwargs)

def nvPicPr(**kwargs: Any) -> CTPictureNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/picture}nvPicPr`` -> :class:`docx4j_py.dml.picture.CTPictureNonVisual`."""
    return CTPictureNonVisual(**kwargs)

def pic(**kwargs: Any) -> Pic:
    """``{http://schemas.openxmlformats.org/drawingml/2006/picture}pic`` -> :class:`docx4j_py.dml.picture.Pic`."""
    return Pic(**kwargs)

def spPr(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/picture}spPr`` -> :class:`docx4j_py.dml.main.CTShapeProperties`."""
    return CTShapeProperties(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.openxmlformats.org/drawingml/2006/picture}blipFill": CTBlipFillProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/picture}cNvPicPr": CTNonVisualPictureProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/picture}cNvPr": CTNonVisualDrawingProps,
    "{http://schemas.openxmlformats.org/drawingml/2006/picture}nvPicPr": CTPictureNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/picture}pic": Pic,
    "{http://schemas.openxmlformats.org/drawingml/2006/picture}spPr": CTShapeProperties,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "blipFill": CTBlipFillProperties,
    "cNvPicPr": CTNonVisualPictureProperties,
    "cNvPr": CTNonVisualDrawingProps,
    "nvPicPr": CTPictureNonVisual,
    "pic": Pic,
    "spPr": CTShapeProperties,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTBlipFillProperties: "{http://schemas.openxmlformats.org/drawingml/2006/picture}blipFill",
    CTNonVisualDrawingProps: "{http://schemas.openxmlformats.org/drawingml/2006/picture}cNvPr",
    CTNonVisualPictureProperties: "{http://schemas.openxmlformats.org/drawingml/2006/picture}cNvPicPr",
    CTPictureNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/picture}nvPicPr",
    CTShapeProperties: "{http://schemas.openxmlformats.org/drawingml/2006/picture}spPr",
    Pic: "{http://schemas.openxmlformats.org/drawingml/2006/picture}pic",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "blipFill",
    "cNvPicPr",
    "cNvPr",
    "nvPicPr",
    "pic",
    "spPr",
]
