"""``el`` for the http://schemas.microsoft.com/office/powerpoint/2014/inkAction namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_ink_action_2014.json``, which a human reviews.

    >>> from docx4j_py.oart.ink_action_2014 import el
    >>> el.action()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.inkml import (
    CTMatrix,
)
from docx4j_py.oart.ink_action_2014 import (
    Actions,
    CTAction,
    CTActionData,
    CTActionDataGroup,
    CTActionGroup,
    CTActionProperty,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/powerpoint/2014/inkAction"

def action(**kwargs: Any) -> CTAction:
    """``{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}action`` -> :class:`docx4j_py.oart.ink_action_2014.CTAction`."""
    return CTAction(**kwargs)

def actionData(**kwargs: Any) -> CTActionData:
    """``{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actionData`` -> :class:`docx4j_py.oart.ink_action_2014.CTActionData`."""
    return CTActionData(**kwargs)

def actionDataGroup(**kwargs: Any) -> CTActionDataGroup:
    """``{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actionDataGroup`` -> :class:`docx4j_py.oart.ink_action_2014.CTActionDataGroup`."""
    return CTActionDataGroup(**kwargs)

def actionGroup(**kwargs: Any) -> CTActionGroup:
    """``{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actionGroup`` -> :class:`docx4j_py.oart.ink_action_2014.CTActionGroup`."""
    return CTActionGroup(**kwargs)

def actions(**kwargs: Any) -> Actions:
    """``{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actions`` -> :class:`docx4j_py.oart.ink_action_2014.Actions`."""
    return Actions(**kwargs)

def property_(**kwargs: Any) -> CTActionProperty:
    """``{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}property`` -> :class:`docx4j_py.oart.ink_action_2014.CTActionProperty`."""
    return CTActionProperty(**kwargs)

def transform(text: str | None = None, /, **kwargs: Any) -> CTMatrix:
    """``{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}transform`` -> :class:`docx4j_py.inkml.CTMatrix`."""
    return text_element(CTMatrix, text, kwargs, "value", null)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}action": CTAction,
    "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actionData": CTActionData,
    "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actionDataGroup": CTActionDataGroup,
    "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actionGroup": CTActionGroup,
    "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actions": Actions,
    "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}property": CTActionProperty,
    "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}transform": CTMatrix,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "action": CTAction,
    "actionData": CTActionData,
    "actionDataGroup": CTActionDataGroup,
    "actionGroup": CTActionGroup,
    "actions": Actions,
    "property": CTActionProperty,
    "transform": CTMatrix,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    Actions: "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actions",
    CTAction: "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}action",
    CTActionData: "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actionData",
    CTActionDataGroup: "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actionDataGroup",
    CTActionGroup: "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actionGroup",
    CTActionProperty: "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}property",
    CTMatrix: "{http://schemas.microsoft.com/office/powerpoint/2014/inkAction}transform",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "action",
    "actionData",
    "actionDataGroup",
    "actionGroup",
    "actions",
    "property_",
    "transform",
]
