"""``el`` for the http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/dml_spreadsheet_drawing.json``, which a human reviews.

    >>> from docx4j_py.dml.spreadsheet_drawing import el
    >>> el.absoluteAnchor()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTBlipFillProperties,
    CTGroupShapeProperties,
    CTNonVisualConnectorProperties,
    CTNonVisualDrawingProps,
    CTNonVisualDrawingShapeProps,
    CTNonVisualGraphicFrameProperties,
    CTNonVisualGroupDrawingShapeProps,
    CTNonVisualPictureProperties,
    CTPoint2D,
    CTPositiveSize2D,
    CTShapeProperties,
    CTShapeStyle,
    CTTextBody,
    CTTransform2D,
)
from docx4j_py.dml.spreadsheet_drawing import (
    CTAbsoluteAnchor,
    CTAnchorClientData,
    CTConnector,
    CTConnectorNonVisual,
    CTGraphicalObjectFrame,
    CTGraphicalObjectFrameNonVisual,
    CTGroupShape,
    CTGroupShapeNonVisual,
    CTMarker,
    CTOneCellAnchor,
    CTPicture,
    CTPictureNonVisual,
    CTShape,
    CTShapeNonVisual,
    CTTwoCellAnchor,
    From,
    To,
    WsDr,
)

__NAMESPACE__ = "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing"

def absoluteAnchor(**kwargs: Any) -> CTAbsoluteAnchor:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}absoluteAnchor`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTAbsoluteAnchor`."""
    return CTAbsoluteAnchor(**kwargs)

def blipFill(**kwargs: Any) -> CTBlipFillProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}blipFill`` -> :class:`docx4j_py.dml.main.CTBlipFillProperties`."""
    return CTBlipFillProperties(**kwargs)

def cNvCxnSpPr(**kwargs: Any) -> CTNonVisualConnectorProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvCxnSpPr`` -> :class:`docx4j_py.dml.main.CTNonVisualConnectorProperties`."""
    return CTNonVisualConnectorProperties(**kwargs)

def cNvGraphicFramePr(**kwargs: Any) -> CTNonVisualGraphicFrameProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvGraphicFramePr`` -> :class:`docx4j_py.dml.main.CTNonVisualGraphicFrameProperties`."""
    return CTNonVisualGraphicFrameProperties(**kwargs)

def cNvGrpSpPr(**kwargs: Any) -> CTNonVisualGroupDrawingShapeProps:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvGrpSpPr`` -> :class:`docx4j_py.dml.main.CTNonVisualGroupDrawingShapeProps`."""
    return CTNonVisualGroupDrawingShapeProps(**kwargs)

def cNvPicPr(**kwargs: Any) -> CTNonVisualPictureProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvPicPr`` -> :class:`docx4j_py.dml.main.CTNonVisualPictureProperties`."""
    return CTNonVisualPictureProperties(**kwargs)

def cNvPr(**kwargs: Any) -> CTNonVisualDrawingProps:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingProps`."""
    return CTNonVisualDrawingProps(**kwargs)

def cNvSpPr(**kwargs: Any) -> CTNonVisualDrawingShapeProps:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvSpPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingShapeProps`."""
    return CTNonVisualDrawingShapeProps(**kwargs)

def clientData(**kwargs: Any) -> CTAnchorClientData:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}clientData`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTAnchorClientData`."""
    return CTAnchorClientData(**kwargs)

def cxnSp(**kwargs: Any) -> CTConnector:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cxnSp`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTConnector`."""
    return CTConnector(**kwargs)

def ext(**kwargs: Any) -> CTPositiveSize2D:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}ext`` -> :class:`docx4j_py.dml.main.CTPositiveSize2D`."""
    return CTPositiveSize2D(**kwargs)

def from_(**kwargs: Any) -> From:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}from`` -> :class:`docx4j_py.dml.spreadsheet_drawing.From`, the global element declaration of 2 classes this name takes; see ``from_marker``."""
    return From(**kwargs)

def from_marker(**kwargs: Any) -> CTMarker:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}from`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTMarker`, the CTMarker form."""
    return CTMarker(**kwargs)

def graphicFrame(**kwargs: Any) -> CTGraphicalObjectFrame:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}graphicFrame`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTGraphicalObjectFrame`."""
    return CTGraphicalObjectFrame(**kwargs)

def grpSp(**kwargs: Any) -> CTGroupShape:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}grpSp`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTGroupShape`."""
    return CTGroupShape(**kwargs)

def grpSpPr(**kwargs: Any) -> CTGroupShapeProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}grpSpPr`` -> :class:`docx4j_py.dml.main.CTGroupShapeProperties`."""
    return CTGroupShapeProperties(**kwargs)

def nvCxnSpPr(**kwargs: Any) -> CTConnectorNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvCxnSpPr`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTConnectorNonVisual`."""
    return CTConnectorNonVisual(**kwargs)

def nvGraphicFramePr(**kwargs: Any) -> CTGraphicalObjectFrameNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvGraphicFramePr`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTGraphicalObjectFrameNonVisual`."""
    return CTGraphicalObjectFrameNonVisual(**kwargs)

def nvGrpSpPr(**kwargs: Any) -> CTGroupShapeNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvGrpSpPr`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTGroupShapeNonVisual`."""
    return CTGroupShapeNonVisual(**kwargs)

def nvPicPr(**kwargs: Any) -> CTPictureNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvPicPr`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTPictureNonVisual`."""
    return CTPictureNonVisual(**kwargs)

def nvSpPr(**kwargs: Any) -> CTShapeNonVisual:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvSpPr`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTShapeNonVisual`."""
    return CTShapeNonVisual(**kwargs)

def oneCellAnchor(**kwargs: Any) -> CTOneCellAnchor:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}oneCellAnchor`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTOneCellAnchor`."""
    return CTOneCellAnchor(**kwargs)

def pic(**kwargs: Any) -> CTPicture:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}pic`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTPicture`."""
    return CTPicture(**kwargs)

def pos(**kwargs: Any) -> CTPoint2D:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}pos`` -> :class:`docx4j_py.dml.main.CTPoint2D`."""
    return CTPoint2D(**kwargs)

def sp(**kwargs: Any) -> CTShape:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}sp`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTShape`."""
    return CTShape(**kwargs)

def spPr(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}spPr`` -> :class:`docx4j_py.dml.main.CTShapeProperties`."""
    return CTShapeProperties(**kwargs)

def style(**kwargs: Any) -> CTShapeStyle:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}style`` -> :class:`docx4j_py.dml.main.CTShapeStyle`."""
    return CTShapeStyle(**kwargs)

def to(**kwargs: Any) -> To:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}to`` -> :class:`docx4j_py.dml.spreadsheet_drawing.To`, the global element declaration of 2 classes this name takes; see ``to_marker``."""
    return To(**kwargs)

def to_marker(**kwargs: Any) -> CTMarker:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}to`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTMarker`, the CTMarker form."""
    return CTMarker(**kwargs)

def twoCellAnchor(**kwargs: Any) -> CTTwoCellAnchor:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}twoCellAnchor`` -> :class:`docx4j_py.dml.spreadsheet_drawing.CTTwoCellAnchor`."""
    return CTTwoCellAnchor(**kwargs)

def txBody(**kwargs: Any) -> CTTextBody:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}txBody`` -> :class:`docx4j_py.dml.main.CTTextBody`."""
    return CTTextBody(**kwargs)

def wsDr(**kwargs: Any) -> WsDr:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}wsDr`` -> :class:`docx4j_py.dml.spreadsheet_drawing.WsDr`."""
    return WsDr(**kwargs)

def xfrm(**kwargs: Any) -> CTTransform2D:
    """``{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}xfrm`` -> :class:`docx4j_py.dml.main.CTTransform2D`."""
    return CTTransform2D(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}absoluteAnchor": CTAbsoluteAnchor,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}blipFill": CTBlipFillProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvCxnSpPr": CTNonVisualConnectorProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvGraphicFramePr": CTNonVisualGraphicFrameProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvGrpSpPr": CTNonVisualGroupDrawingShapeProps,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvPicPr": CTNonVisualPictureProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvPr": CTNonVisualDrawingProps,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvSpPr": CTNonVisualDrawingShapeProps,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}clientData": CTAnchorClientData,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cxnSp": CTConnector,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}ext": CTPositiveSize2D,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}from": From,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}graphicFrame": CTGraphicalObjectFrame,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}grpSp": CTGroupShape,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}grpSpPr": CTGroupShapeProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvCxnSpPr": CTConnectorNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvGraphicFramePr": CTGraphicalObjectFrameNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvGrpSpPr": CTGroupShapeNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvPicPr": CTPictureNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvSpPr": CTShapeNonVisual,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}oneCellAnchor": CTOneCellAnchor,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}pic": CTPicture,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}pos": CTPoint2D,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}sp": CTShape,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}spPr": CTShapeProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}style": CTShapeStyle,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}to": To,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}twoCellAnchor": CTTwoCellAnchor,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}txBody": CTTextBody,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}wsDr": WsDr,
    "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}xfrm": CTTransform2D,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "absoluteAnchor": CTAbsoluteAnchor,
    "blipFill": CTBlipFillProperties,
    "cNvCxnSpPr": CTNonVisualConnectorProperties,
    "cNvGraphicFramePr": CTNonVisualGraphicFrameProperties,
    "cNvGrpSpPr": CTNonVisualGroupDrawingShapeProps,
    "cNvPicPr": CTNonVisualPictureProperties,
    "cNvPr": CTNonVisualDrawingProps,
    "cNvSpPr": CTNonVisualDrawingShapeProps,
    "clientData": CTAnchorClientData,
    "cxnSp": CTConnector,
    "ext": CTPositiveSize2D,
    "from": From,
    "graphicFrame": CTGraphicalObjectFrame,
    "grpSp": CTGroupShape,
    "grpSpPr": CTGroupShapeProperties,
    "nvCxnSpPr": CTConnectorNonVisual,
    "nvGraphicFramePr": CTGraphicalObjectFrameNonVisual,
    "nvGrpSpPr": CTGroupShapeNonVisual,
    "nvPicPr": CTPictureNonVisual,
    "nvSpPr": CTShapeNonVisual,
    "oneCellAnchor": CTOneCellAnchor,
    "pic": CTPicture,
    "pos": CTPoint2D,
    "sp": CTShape,
    "spPr": CTShapeProperties,
    "style": CTShapeStyle,
    "to": To,
    "twoCellAnchor": CTTwoCellAnchor,
    "txBody": CTTextBody,
    "wsDr": WsDr,
    "xfrm": CTTransform2D,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTAbsoluteAnchor: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}absoluteAnchor",
    CTAnchorClientData: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}clientData",
    CTBlipFillProperties: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}blipFill",
    CTConnector: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cxnSp",
    CTConnectorNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvCxnSpPr",
    CTGraphicalObjectFrame: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}graphicFrame",
    CTGraphicalObjectFrameNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvGraphicFramePr",
    CTGroupShape: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}grpSp",
    CTGroupShapeNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvGrpSpPr",
    CTGroupShapeProperties: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}grpSpPr",
    CTNonVisualConnectorProperties: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvCxnSpPr",
    CTNonVisualDrawingProps: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvPr",
    CTNonVisualDrawingShapeProps: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvSpPr",
    CTNonVisualGraphicFrameProperties: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvGraphicFramePr",
    CTNonVisualGroupDrawingShapeProps: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvGrpSpPr",
    CTNonVisualPictureProperties: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}cNvPicPr",
    CTOneCellAnchor: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}oneCellAnchor",
    CTPicture: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}pic",
    CTPictureNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvPicPr",
    CTPoint2D: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}pos",
    CTPositiveSize2D: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}ext",
    CTShape: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}sp",
    CTShapeNonVisual: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}nvSpPr",
    CTShapeProperties: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}spPr",
    CTShapeStyle: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}style",
    CTTextBody: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}txBody",
    CTTransform2D: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}xfrm",
    CTTwoCellAnchor: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}twoCellAnchor",
    From: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}from",
    To: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}to",
    WsDr: "{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}wsDr",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "absoluteAnchor",
    "blipFill",
    "cNvCxnSpPr",
    "cNvGraphicFramePr",
    "cNvGrpSpPr",
    "cNvPicPr",
    "cNvPr",
    "cNvSpPr",
    "clientData",
    "cxnSp",
    "ext",
    "from_",
    "from_marker",
    "graphicFrame",
    "grpSp",
    "grpSpPr",
    "nvCxnSpPr",
    "nvGraphicFramePr",
    "nvGrpSpPr",
    "nvPicPr",
    "nvSpPr",
    "oneCellAnchor",
    "pic",
    "pos",
    "sp",
    "spPr",
    "style",
    "to",
    "to_marker",
    "twoCellAnchor",
    "txBody",
    "wsDr",
    "xfrm",
]
