"""``el`` for the http://schemas.microsoft.com/office/drawing/2012/chart namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_chart_2012.json``, which a human reviews.

    >>> from docx4j_py.oart.chart_2012 import el
    >>> el.autoCat()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.chart import (
    CTAreaSer,
    CTAxDataSource,
    CTBarSer,
    CTBoolean,
    CTBubbleSer,
    CTDLbl,
    CTLineSer,
    CTMarker,
    CTPieSer,
    CTRadarSer,
    CTScatterSer,
    CTStrData,
    CTSurfaceSer,
    CTTx,
    CTUnsignedInt,
)
from docx4j_py.dml.main import (
    CTShapeProperties,
)
from docx4j_py.oart.chart_2012 import (
    AutoCat,
    CTBoolean,
    CTCategoryFilterException,
    CTChartLines,
    CTDataLabelFieldTableEntry,
    CTLayout,
    CTNumFmt,
    CTPivotSource,
    CTShapeProperties,
    CTTx,
    CategoryFilterExceptions,
    DatalabelsRange,
    DlblFieldTable,
    FilteredAreaSeries,
    FilteredBarSeries,
    FilteredBubbleSeries,
    FilteredCategoryTitle,
    FilteredLineSeries,
    FilteredPieSeries,
    FilteredRadarSeries,
    FilteredScatterSeries,
    FilteredSeriesTitle,
    FilteredSurfaceSeries,
    FormulaRef,
    FullRef,
    LevelRef,
    ShowDataLabelsRange,
    ShowLeaderLines,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2012/chart"

def autoCat(**kwargs: Any) -> AutoCat:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}autoCat`` -> :class:`docx4j_py.oart.chart_2012.AutoCat`."""
    return AutoCat(**kwargs)

def bubble3D(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}bubble3D`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def cat(**kwargs: Any) -> CTAxDataSource:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}cat`` -> :class:`docx4j_py.dml.chart.CTAxDataSource`."""
    return CTAxDataSource(**kwargs)

def categoryFilterException(**kwargs: Any) -> CTCategoryFilterException:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}categoryFilterException`` -> :class:`docx4j_py.oart.chart_2012.CTCategoryFilterException`."""
    return CTCategoryFilterException(**kwargs)

def categoryFilterExceptions(**kwargs: Any) -> CategoryFilterExceptions:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}categoryFilterExceptions`` -> :class:`docx4j_py.oart.chart_2012.CategoryFilterExceptions`."""
    return CategoryFilterExceptions(**kwargs)

def dLbl(**kwargs: Any) -> CTDLbl:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}dLbl`` -> :class:`docx4j_py.dml.chart.CTDLbl`."""
    return CTDLbl(**kwargs)

def datalabelsRange(**kwargs: Any) -> DatalabelsRange:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}datalabelsRange`` -> :class:`docx4j_py.oart.chart_2012.DatalabelsRange`."""
    return DatalabelsRange(**kwargs)

def dlblFTEntry(**kwargs: Any) -> CTDataLabelFieldTableEntry:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}dlblFTEntry`` -> :class:`docx4j_py.oart.chart_2012.CTDataLabelFieldTableEntry`."""
    return CTDataLabelFieldTableEntry(**kwargs)

def dlblFieldTable(**kwargs: Any) -> DlblFieldTable:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}dlblFieldTable`` -> :class:`docx4j_py.oart.chart_2012.DlblFieldTable`."""
    return DlblFieldTable(**kwargs)

def dlblFieldTableCache(**kwargs: Any) -> CTStrData:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}dlblFieldTableCache`` -> :class:`docx4j_py.dml.chart.CTStrData`."""
    return CTStrData(**kwargs)

def dlblRangeCache(**kwargs: Any) -> CTStrData:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}dlblRangeCache`` -> :class:`docx4j_py.dml.chart.CTStrData`."""
    return CTStrData(**kwargs)

def explosion(**kwargs: Any) -> CTUnsignedInt:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}explosion`` -> :class:`docx4j_py.dml.chart.CTUnsignedInt`."""
    return CTUnsignedInt(**kwargs)

def filteredAreaSeries(**kwargs: Any) -> FilteredAreaSeries:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}filteredAreaSeries`` -> :class:`docx4j_py.oart.chart_2012.FilteredAreaSeries`."""
    return FilteredAreaSeries(**kwargs)

def filteredBarSeries(**kwargs: Any) -> FilteredBarSeries:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}filteredBarSeries`` -> :class:`docx4j_py.oart.chart_2012.FilteredBarSeries`."""
    return FilteredBarSeries(**kwargs)

def filteredBubbleSeries(**kwargs: Any) -> FilteredBubbleSeries:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}filteredBubbleSeries`` -> :class:`docx4j_py.oart.chart_2012.FilteredBubbleSeries`."""
    return FilteredBubbleSeries(**kwargs)

def filteredCategoryTitle(**kwargs: Any) -> FilteredCategoryTitle:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}filteredCategoryTitle`` -> :class:`docx4j_py.oart.chart_2012.FilteredCategoryTitle`."""
    return FilteredCategoryTitle(**kwargs)

def filteredLineSeries(**kwargs: Any) -> FilteredLineSeries:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}filteredLineSeries`` -> :class:`docx4j_py.oart.chart_2012.FilteredLineSeries`."""
    return FilteredLineSeries(**kwargs)

def filteredPieSeries(**kwargs: Any) -> FilteredPieSeries:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}filteredPieSeries`` -> :class:`docx4j_py.oart.chart_2012.FilteredPieSeries`."""
    return FilteredPieSeries(**kwargs)

def filteredRadarSeries(**kwargs: Any) -> FilteredRadarSeries:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}filteredRadarSeries`` -> :class:`docx4j_py.oart.chart_2012.FilteredRadarSeries`."""
    return FilteredRadarSeries(**kwargs)

def filteredScatterSeries(**kwargs: Any) -> FilteredScatterSeries:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}filteredScatterSeries`` -> :class:`docx4j_py.oart.chart_2012.FilteredScatterSeries`."""
    return FilteredScatterSeries(**kwargs)

def filteredSeriesTitle(**kwargs: Any) -> FilteredSeriesTitle:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}filteredSeriesTitle`` -> :class:`docx4j_py.oart.chart_2012.FilteredSeriesTitle`."""
    return FilteredSeriesTitle(**kwargs)

def filteredSurfaceSeries(**kwargs: Any) -> FilteredSurfaceSeries:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}filteredSurfaceSeries`` -> :class:`docx4j_py.oart.chart_2012.FilteredSurfaceSeries`."""
    return FilteredSurfaceSeries(**kwargs)

def formulaRef(**kwargs: Any) -> FormulaRef:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}formulaRef`` -> :class:`docx4j_py.oart.chart_2012.FormulaRef`."""
    return FormulaRef(**kwargs)

def fullRef(**kwargs: Any) -> FullRef:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}fullRef`` -> :class:`docx4j_py.oart.chart_2012.FullRef`."""
    return FullRef(**kwargs)

def invertIfNegative(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}invertIfNegative`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def layout(**kwargs: Any) -> CTLayout:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}layout`` -> :class:`docx4j_py.oart.chart_2012.CTLayout`."""
    return CTLayout(**kwargs)

def leaderLines(**kwargs: Any) -> CTChartLines:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}leaderLines`` -> :class:`docx4j_py.oart.chart_2012.CTChartLines`."""
    return CTChartLines(**kwargs)

def levelRef(**kwargs: Any) -> LevelRef:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}levelRef`` -> :class:`docx4j_py.oart.chart_2012.LevelRef`."""
    return LevelRef(**kwargs)

def marker(**kwargs: Any) -> CTMarker:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}marker`` -> :class:`docx4j_py.dml.chart.CTMarker`."""
    return CTMarker(**kwargs)

def numFmt(**kwargs: Any) -> CTNumFmt:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}numFmt`` -> :class:`docx4j_py.oart.chart_2012.CTNumFmt`."""
    return CTNumFmt(**kwargs)

def pivotSource(**kwargs: Any) -> CTPivotSource:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}pivotSource`` -> :class:`docx4j_py.oart.chart_2012.CTPivotSource`."""
    return CTPivotSource(**kwargs)

def ser(**kwargs: Any) -> CTAreaSer:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}ser`` -> :class:`docx4j_py.dml.chart.CTAreaSer`, the most reachable scope of 8 classes this name takes; see ``bar_ser``, ``bubble_ser``, ``line_ser``, ``pie_ser``, ``radar_ser``, ``scatter_ser``, ``surface_ser``."""
    return CTAreaSer(**kwargs)

def bar_ser(**kwargs: Any) -> CTBarSer:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}ser`` -> :class:`docx4j_py.dml.chart.CTBarSer`, the CTBarSer form."""
    return CTBarSer(**kwargs)

def bubble_ser(**kwargs: Any) -> CTBubbleSer:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}ser`` -> :class:`docx4j_py.dml.chart.CTBubbleSer`, the CTBubbleSer form."""
    return CTBubbleSer(**kwargs)

def line_ser(**kwargs: Any) -> CTLineSer:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}ser`` -> :class:`docx4j_py.dml.chart.CTLineSer`, the CTLineSer form."""
    return CTLineSer(**kwargs)

def pie_ser(**kwargs: Any) -> CTPieSer:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}ser`` -> :class:`docx4j_py.dml.chart.CTPieSer`, the CTPieSer form."""
    return CTPieSer(**kwargs)

def radar_ser(**kwargs: Any) -> CTRadarSer:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}ser`` -> :class:`docx4j_py.dml.chart.CTRadarSer`, the CTRadarSer form."""
    return CTRadarSer(**kwargs)

def scatter_ser(**kwargs: Any) -> CTScatterSer:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}ser`` -> :class:`docx4j_py.dml.chart.CTScatterSer`, the CTScatterSer form."""
    return CTScatterSer(**kwargs)

def surface_ser(**kwargs: Any) -> CTSurfaceSer:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}ser`` -> :class:`docx4j_py.dml.chart.CTSurfaceSer`, the CTSurfaceSer form."""
    return CTSurfaceSer(**kwargs)

def showDataLabelsRange(**kwargs: Any) -> ShowDataLabelsRange:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}showDataLabelsRange`` -> :class:`docx4j_py.oart.chart_2012.ShowDataLabelsRange`."""
    return ShowDataLabelsRange(**kwargs)

def showLeaderLines(**kwargs: Any) -> ShowLeaderLines:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}showLeaderLines`` -> :class:`docx4j_py.oart.chart_2012.ShowLeaderLines`."""
    return ShowLeaderLines(**kwargs)

def spPr(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}spPr`` -> :class:`docx4j_py.oart.chart_2012.CTShapeProperties`, the global element declaration of 2 classes this name takes; see ``shape_properties``."""
    return CTShapeProperties(**kwargs)

def shape_properties(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}spPr`` -> :class:`docx4j_py.dml.main.CTShapeProperties`, the CTShapeProperties form."""
    return CTShapeProperties(**kwargs)

def tx(**kwargs: Any) -> CTTx:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}tx`` -> :class:`docx4j_py.oart.chart_2012.CTTx`, the global element declaration of 2 classes this name takes; see ``tx_tx``."""
    return CTTx(**kwargs)

def tx_tx(**kwargs: Any) -> CTTx:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}tx`` -> :class:`docx4j_py.dml.chart.CTTx`, the CTTx form."""
    return CTTx(**kwargs)

def xForSave(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.microsoft.com/office/drawing/2012/chart}xForSave`` -> :class:`docx4j_py.oart.chart_2012.CTBoolean`."""
    return CTBoolean(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2012/chart}autoCat": AutoCat,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}bubble3D": CTBoolean,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}cat": CTAxDataSource,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}categoryFilterException": CTCategoryFilterException,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}categoryFilterExceptions": CategoryFilterExceptions,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}dLbl": CTDLbl,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}datalabelsRange": DatalabelsRange,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}dlblFTEntry": CTDataLabelFieldTableEntry,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}dlblFieldTable": DlblFieldTable,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}dlblFieldTableCache": CTStrData,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}dlblRangeCache": CTStrData,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}explosion": CTUnsignedInt,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredAreaSeries": FilteredAreaSeries,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredBarSeries": FilteredBarSeries,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredBubbleSeries": FilteredBubbleSeries,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredCategoryTitle": FilteredCategoryTitle,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredLineSeries": FilteredLineSeries,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredPieSeries": FilteredPieSeries,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredRadarSeries": FilteredRadarSeries,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredScatterSeries": FilteredScatterSeries,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredSeriesTitle": FilteredSeriesTitle,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredSurfaceSeries": FilteredSurfaceSeries,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}formulaRef": FormulaRef,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}fullRef": FullRef,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}invertIfNegative": CTBoolean,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}layout": CTLayout,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}leaderLines": CTChartLines,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}levelRef": LevelRef,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}marker": CTMarker,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}numFmt": CTNumFmt,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}pivotSource": CTPivotSource,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}ser": CTAreaSer,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}showDataLabelsRange": ShowDataLabelsRange,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}showLeaderLines": ShowLeaderLines,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}spPr": CTShapeProperties,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}tx": CTTx,
    "{http://schemas.microsoft.com/office/drawing/2012/chart}xForSave": CTBoolean,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "autoCat": AutoCat,
    "bubble3D": CTBoolean,
    "cat": CTAxDataSource,
    "categoryFilterException": CTCategoryFilterException,
    "categoryFilterExceptions": CategoryFilterExceptions,
    "dLbl": CTDLbl,
    "datalabelsRange": DatalabelsRange,
    "dlblFTEntry": CTDataLabelFieldTableEntry,
    "dlblFieldTable": DlblFieldTable,
    "dlblFieldTableCache": CTStrData,
    "dlblRangeCache": CTStrData,
    "explosion": CTUnsignedInt,
    "filteredAreaSeries": FilteredAreaSeries,
    "filteredBarSeries": FilteredBarSeries,
    "filteredBubbleSeries": FilteredBubbleSeries,
    "filteredCategoryTitle": FilteredCategoryTitle,
    "filteredLineSeries": FilteredLineSeries,
    "filteredPieSeries": FilteredPieSeries,
    "filteredRadarSeries": FilteredRadarSeries,
    "filteredScatterSeries": FilteredScatterSeries,
    "filteredSeriesTitle": FilteredSeriesTitle,
    "filteredSurfaceSeries": FilteredSurfaceSeries,
    "formulaRef": FormulaRef,
    "fullRef": FullRef,
    "invertIfNegative": CTBoolean,
    "layout": CTLayout,
    "leaderLines": CTChartLines,
    "levelRef": LevelRef,
    "marker": CTMarker,
    "numFmt": CTNumFmt,
    "pivotSource": CTPivotSource,
    "ser": CTAreaSer,
    "showDataLabelsRange": ShowDataLabelsRange,
    "showLeaderLines": ShowLeaderLines,
    "spPr": CTShapeProperties,
    "tx": CTTx,
    "xForSave": CTBoolean,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    AutoCat: "{http://schemas.microsoft.com/office/drawing/2012/chart}autoCat",
    CTAreaSer: "{http://schemas.microsoft.com/office/drawing/2012/chart}ser",
    CTAxDataSource: "{http://schemas.microsoft.com/office/drawing/2012/chart}cat",
    CTBarSer: "{http://schemas.microsoft.com/office/drawing/2012/chart}ser",
    CTBubbleSer: "{http://schemas.microsoft.com/office/drawing/2012/chart}ser",
    CTCategoryFilterException: "{http://schemas.microsoft.com/office/drawing/2012/chart}categoryFilterException",
    CTChartLines: "{http://schemas.microsoft.com/office/drawing/2012/chart}leaderLines",
    CTDLbl: "{http://schemas.microsoft.com/office/drawing/2012/chart}dLbl",
    CTDataLabelFieldTableEntry: "{http://schemas.microsoft.com/office/drawing/2012/chart}dlblFTEntry",
    CTLayout: "{http://schemas.microsoft.com/office/drawing/2012/chart}layout",
    CTLineSer: "{http://schemas.microsoft.com/office/drawing/2012/chart}ser",
    CTMarker: "{http://schemas.microsoft.com/office/drawing/2012/chart}marker",
    CTNumFmt: "{http://schemas.microsoft.com/office/drawing/2012/chart}numFmt",
    CTPieSer: "{http://schemas.microsoft.com/office/drawing/2012/chart}ser",
    CTPivotSource: "{http://schemas.microsoft.com/office/drawing/2012/chart}pivotSource",
    CTRadarSer: "{http://schemas.microsoft.com/office/drawing/2012/chart}ser",
    CTScatterSer: "{http://schemas.microsoft.com/office/drawing/2012/chart}ser",
    CTShapeProperties: "{http://schemas.microsoft.com/office/drawing/2012/chart}spPr",
    CTSurfaceSer: "{http://schemas.microsoft.com/office/drawing/2012/chart}ser",
    CTTx: "{http://schemas.microsoft.com/office/drawing/2012/chart}tx",
    CTUnsignedInt: "{http://schemas.microsoft.com/office/drawing/2012/chart}explosion",
    CategoryFilterExceptions: "{http://schemas.microsoft.com/office/drawing/2012/chart}categoryFilterExceptions",
    DatalabelsRange: "{http://schemas.microsoft.com/office/drawing/2012/chart}datalabelsRange",
    DlblFieldTable: "{http://schemas.microsoft.com/office/drawing/2012/chart}dlblFieldTable",
    FilteredAreaSeries: "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredAreaSeries",
    FilteredBarSeries: "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredBarSeries",
    FilteredBubbleSeries: "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredBubbleSeries",
    FilteredCategoryTitle: "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredCategoryTitle",
    FilteredLineSeries: "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredLineSeries",
    FilteredPieSeries: "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredPieSeries",
    FilteredRadarSeries: "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredRadarSeries",
    FilteredScatterSeries: "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredScatterSeries",
    FilteredSeriesTitle: "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredSeriesTitle",
    FilteredSurfaceSeries: "{http://schemas.microsoft.com/office/drawing/2012/chart}filteredSurfaceSeries",
    FormulaRef: "{http://schemas.microsoft.com/office/drawing/2012/chart}formulaRef",
    FullRef: "{http://schemas.microsoft.com/office/drawing/2012/chart}fullRef",
    LevelRef: "{http://schemas.microsoft.com/office/drawing/2012/chart}levelRef",
    ShowDataLabelsRange: "{http://schemas.microsoft.com/office/drawing/2012/chart}showDataLabelsRange",
    ShowLeaderLines: "{http://schemas.microsoft.com/office/drawing/2012/chart}showLeaderLines",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "autoCat",
    "bar_ser",
    "bubble3D",
    "bubble_ser",
    "cat",
    "categoryFilterException",
    "categoryFilterExceptions",
    "dLbl",
    "datalabelsRange",
    "dlblFTEntry",
    "dlblFieldTable",
    "dlblFieldTableCache",
    "dlblRangeCache",
    "explosion",
    "filteredAreaSeries",
    "filteredBarSeries",
    "filteredBubbleSeries",
    "filteredCategoryTitle",
    "filteredLineSeries",
    "filteredPieSeries",
    "filteredRadarSeries",
    "filteredScatterSeries",
    "filteredSeriesTitle",
    "filteredSurfaceSeries",
    "formulaRef",
    "fullRef",
    "invertIfNegative",
    "layout",
    "leaderLines",
    "levelRef",
    "line_ser",
    "marker",
    "numFmt",
    "pie_ser",
    "pivotSource",
    "radar_ser",
    "scatter_ser",
    "ser",
    "shape_properties",
    "showDataLabelsRange",
    "showLeaderLines",
    "spPr",
    "surface_ser",
    "tx",
    "tx_tx",
    "xForSave",
]
