"""``el`` for the http://schemas.microsoft.com/office/drawing/2014/chart/ac namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_chart_ac_2014.json``, which a human reviews.

    >>> from docx4j_py.oart.chart_ac_2014 import el
    >>> el.multiLvlStrLit()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.oart.chart_ac_2014 import (
    MultiLvlStrLit,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2014/chart/ac"

def multiLvlStrLit(**kwargs: Any) -> MultiLvlStrLit:
    """``{http://schemas.microsoft.com/office/drawing/2014/chart/ac}multiLvlStrLit`` -> :class:`docx4j_py.oart.chart_ac_2014.MultiLvlStrLit`."""
    return MultiLvlStrLit(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2014/chart/ac}multiLvlStrLit": MultiLvlStrLit,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "multiLvlStrLit": MultiLvlStrLit,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    MultiLvlStrLit: "{http://schemas.microsoft.com/office/drawing/2014/chart/ac}multiLvlStrLit",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "multiLvlStrLit",
]
