"""``el`` for the http://schemas.openxmlformats.org/officeDocument/2006/extended-properties namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/docprops_extended.json``, which a human reviews.

    >>> from docx4j_py.docprops.extended import el
    >>> el.DigSig()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.docprops.extended import (
    Properties as _Properties,
    PropertiesDigSig,
    PropertiesHeadingPairs,
    PropertiesHlinks,
    PropertiesTitlesOfParts,
)

__NAMESPACE__ = "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"

def DigSig(**kwargs: Any) -> PropertiesDigSig:
    """``{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}DigSig`` -> :class:`docx4j_py.docprops.extended.PropertiesDigSig`."""
    return PropertiesDigSig(**kwargs)

def HLinks(**kwargs: Any) -> PropertiesHlinks:
    """``{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}HLinks`` -> :class:`docx4j_py.docprops.extended.PropertiesHlinks`."""
    return PropertiesHlinks(**kwargs)

def HeadingPairs(**kwargs: Any) -> PropertiesHeadingPairs:
    """``{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}HeadingPairs`` -> :class:`docx4j_py.docprops.extended.PropertiesHeadingPairs`."""
    return PropertiesHeadingPairs(**kwargs)

def Properties(**kwargs: Any) -> _Properties:
    """``{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}Properties`` -> :class:`docx4j_py.docprops.extended.Properties`."""
    return _Properties(**kwargs)

def TitlesOfParts(**kwargs: Any) -> PropertiesTitlesOfParts:
    """``{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}TitlesOfParts`` -> :class:`docx4j_py.docprops.extended.PropertiesTitlesOfParts`."""
    return PropertiesTitlesOfParts(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}DigSig": PropertiesDigSig,
    "{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}HLinks": PropertiesHlinks,
    "{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}HeadingPairs": PropertiesHeadingPairs,
    "{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}Properties": _Properties,
    "{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}TitlesOfParts": PropertiesTitlesOfParts,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "DigSig": PropertiesDigSig,
    "HLinks": PropertiesHlinks,
    "HeadingPairs": PropertiesHeadingPairs,
    "Properties": _Properties,
    "TitlesOfParts": PropertiesTitlesOfParts,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    _Properties: "{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}Properties",
    PropertiesDigSig: "{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}DigSig",
    PropertiesHeadingPairs: "{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}HeadingPairs",
    PropertiesHlinks: "{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}HLinks",
    PropertiesTitlesOfParts: "{http://schemas.openxmlformats.org/officeDocument/2006/extended-properties}TitlesOfParts",
}

__all__ = [
    "CLASS_TO_QNAME",
    "DigSig",
    "ELEMENTS",
    "HLinks",
    "HeadingPairs",
    "Properties",
    "QNAME_TO_CLASS",
    "TitlesOfParts",
]
