"""``el`` for the http://schemas.microsoft.com/office/drawing/2014/main namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_main_2014.json``, which a human reviews.

    >>> from docx4j_py.oart.main_2014 import el
    >>> el.colId()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.oart.main_2014 import (
    ColId,
    CreationId,
    CxnDerefs,
    PredDeref,
    RowId,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2014/main"

def colId(**kwargs: Any) -> ColId:
    """``{http://schemas.microsoft.com/office/drawing/2014/main}colId`` -> :class:`docx4j_py.oart.main_2014.ColId`."""
    return ColId(**kwargs)

def creationId(**kwargs: Any) -> CreationId:
    """``{http://schemas.microsoft.com/office/drawing/2014/main}creationId`` -> :class:`docx4j_py.oart.main_2014.CreationId`."""
    return CreationId(**kwargs)

def cxnDERefs(**kwargs: Any) -> CxnDerefs:
    """``{http://schemas.microsoft.com/office/drawing/2014/main}cxnDERefs`` -> :class:`docx4j_py.oart.main_2014.CxnDerefs`."""
    return CxnDerefs(**kwargs)

def predDERef(**kwargs: Any) -> PredDeref:
    """``{http://schemas.microsoft.com/office/drawing/2014/main}predDERef`` -> :class:`docx4j_py.oart.main_2014.PredDeref`."""
    return PredDeref(**kwargs)

def rowId(**kwargs: Any) -> RowId:
    """``{http://schemas.microsoft.com/office/drawing/2014/main}rowId`` -> :class:`docx4j_py.oart.main_2014.RowId`."""
    return RowId(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2014/main}colId": ColId,
    "{http://schemas.microsoft.com/office/drawing/2014/main}creationId": CreationId,
    "{http://schemas.microsoft.com/office/drawing/2014/main}cxnDERefs": CxnDerefs,
    "{http://schemas.microsoft.com/office/drawing/2014/main}predDERef": PredDeref,
    "{http://schemas.microsoft.com/office/drawing/2014/main}rowId": RowId,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "colId": ColId,
    "creationId": CreationId,
    "cxnDERefs": CxnDerefs,
    "predDERef": PredDeref,
    "rowId": RowId,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    ColId: "{http://schemas.microsoft.com/office/drawing/2014/main}colId",
    CreationId: "{http://schemas.microsoft.com/office/drawing/2014/main}creationId",
    CxnDerefs: "{http://schemas.microsoft.com/office/drawing/2014/main}cxnDERefs",
    PredDeref: "{http://schemas.microsoft.com/office/drawing/2014/main}predDERef",
    RowId: "{http://schemas.microsoft.com/office/drawing/2014/main}rowId",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "colId",
    "creationId",
    "cxnDERefs",
    "predDERef",
    "rowId",
]
