"""``el`` for the http://schemas.microsoft.com/office/word/2012/wordml namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/w15.json``, which a human reviews.

    >>> from docx4j_py.w15 import el
    >>> el.appearance()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.w15 import (
    Appearance,
    BooleanDefaultTrue,
    CTColor,
    CTCommentEx,
    CTDataBinding,
    CTDecimalNumber,
    CTEmpty,
    CTPerson,
    CTPresenceInfo,
    Collapsed,
    CommentsEx,
    DocId,
    People,
    RepeatingSection,
    WebExtensionCreated,
    WebExtensionLinked,
)
from docx4j_py.wml import (
    BooleanDefaultTrue,
    CTString,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/word/2012/wordml"

def appearance(**kwargs: Any) -> Appearance:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}appearance`` -> :class:`docx4j_py.w15.Appearance`."""
    return Appearance(**kwargs)

def chartTrackingRefBased(**kwargs: Any) -> BooleanDefaultTrue:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}chartTrackingRefBased`` -> :class:`docx4j_py.w15.BooleanDefaultTrue`."""
    return BooleanDefaultTrue(**kwargs)

def collapsed(**kwargs: Any) -> Collapsed:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}collapsed`` -> :class:`docx4j_py.w15.Collapsed`."""
    return Collapsed(**kwargs)

def color(**kwargs: Any) -> CTColor:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}color`` -> :class:`docx4j_py.w15.CTColor`."""
    return CTColor(**kwargs)

def commentEx(**kwargs: Any) -> CTCommentEx:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}commentEx`` -> :class:`docx4j_py.w15.CTCommentEx`."""
    return CTCommentEx(**kwargs)

def commentsEx(**kwargs: Any) -> CommentsEx:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}commentsEx`` -> :class:`docx4j_py.w15.CommentsEx`."""
    return CommentsEx(**kwargs)

def dataBinding(**kwargs: Any) -> CTDataBinding:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}dataBinding`` -> :class:`docx4j_py.w15.CTDataBinding`."""
    return CTDataBinding(**kwargs)

def doNotAllowInsertDeleteSection(**kwargs: Any) -> BooleanDefaultTrue:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}doNotAllowInsertDeleteSection`` -> :class:`docx4j_py.wml.BooleanDefaultTrue`."""
    return BooleanDefaultTrue(**kwargs)

def docId(**kwargs: Any) -> DocId:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}docId`` -> :class:`docx4j_py.w15.DocId`."""
    return DocId(**kwargs)

def footnoteColumns(**kwargs: Any) -> CTDecimalNumber:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}footnoteColumns`` -> :class:`docx4j_py.w15.CTDecimalNumber`."""
    return CTDecimalNumber(**kwargs)

def people(**kwargs: Any) -> People:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}people`` -> :class:`docx4j_py.w15.People`."""
    return People(**kwargs)

def person(**kwargs: Any) -> CTPerson:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}person`` -> :class:`docx4j_py.w15.CTPerson`."""
    return CTPerson(**kwargs)

def presenceInfo(**kwargs: Any) -> CTPresenceInfo:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}presenceInfo`` -> :class:`docx4j_py.w15.CTPresenceInfo`."""
    return CTPresenceInfo(**kwargs)

def repeatingSection(**kwargs: Any) -> RepeatingSection:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}repeatingSection`` -> :class:`docx4j_py.w15.RepeatingSection`."""
    return RepeatingSection(**kwargs)

def repeatingSectionItem(**kwargs: Any) -> CTEmpty:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}repeatingSectionItem`` -> :class:`docx4j_py.w15.CTEmpty`."""
    return CTEmpty(**kwargs)

def sectionTitle(**kwargs: Any) -> CTString:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}sectionTitle`` -> :class:`docx4j_py.wml.CTString`."""
    return CTString(**kwargs)

def webExtensionCreated(**kwargs: Any) -> WebExtensionCreated:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}webExtensionCreated`` -> :class:`docx4j_py.w15.WebExtensionCreated`."""
    return WebExtensionCreated(**kwargs)

def webExtensionLinked(**kwargs: Any) -> WebExtensionLinked:
    """``{http://schemas.microsoft.com/office/word/2012/wordml}webExtensionLinked`` -> :class:`docx4j_py.w15.WebExtensionLinked`."""
    return WebExtensionLinked(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/word/2012/wordml}appearance": Appearance,
    "{http://schemas.microsoft.com/office/word/2012/wordml}chartTrackingRefBased": BooleanDefaultTrue,
    "{http://schemas.microsoft.com/office/word/2012/wordml}collapsed": Collapsed,
    "{http://schemas.microsoft.com/office/word/2012/wordml}color": CTColor,
    "{http://schemas.microsoft.com/office/word/2012/wordml}commentEx": CTCommentEx,
    "{http://schemas.microsoft.com/office/word/2012/wordml}commentsEx": CommentsEx,
    "{http://schemas.microsoft.com/office/word/2012/wordml}dataBinding": CTDataBinding,
    "{http://schemas.microsoft.com/office/word/2012/wordml}doNotAllowInsertDeleteSection": BooleanDefaultTrue,
    "{http://schemas.microsoft.com/office/word/2012/wordml}docId": DocId,
    "{http://schemas.microsoft.com/office/word/2012/wordml}footnoteColumns": CTDecimalNumber,
    "{http://schemas.microsoft.com/office/word/2012/wordml}people": People,
    "{http://schemas.microsoft.com/office/word/2012/wordml}person": CTPerson,
    "{http://schemas.microsoft.com/office/word/2012/wordml}presenceInfo": CTPresenceInfo,
    "{http://schemas.microsoft.com/office/word/2012/wordml}repeatingSection": RepeatingSection,
    "{http://schemas.microsoft.com/office/word/2012/wordml}repeatingSectionItem": CTEmpty,
    "{http://schemas.microsoft.com/office/word/2012/wordml}sectionTitle": CTString,
    "{http://schemas.microsoft.com/office/word/2012/wordml}webExtensionCreated": WebExtensionCreated,
    "{http://schemas.microsoft.com/office/word/2012/wordml}webExtensionLinked": WebExtensionLinked,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "appearance": Appearance,
    "chartTrackingRefBased": BooleanDefaultTrue,
    "collapsed": Collapsed,
    "color": CTColor,
    "commentEx": CTCommentEx,
    "commentsEx": CommentsEx,
    "dataBinding": CTDataBinding,
    "doNotAllowInsertDeleteSection": BooleanDefaultTrue,
    "docId": DocId,
    "footnoteColumns": CTDecimalNumber,
    "people": People,
    "person": CTPerson,
    "presenceInfo": CTPresenceInfo,
    "repeatingSection": RepeatingSection,
    "repeatingSectionItem": CTEmpty,
    "sectionTitle": CTString,
    "webExtensionCreated": WebExtensionCreated,
    "webExtensionLinked": WebExtensionLinked,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    Appearance: "{http://schemas.microsoft.com/office/word/2012/wordml}appearance",
    CTColor: "{http://schemas.microsoft.com/office/word/2012/wordml}color",
    CTCommentEx: "{http://schemas.microsoft.com/office/word/2012/wordml}commentEx",
    CTDataBinding: "{http://schemas.microsoft.com/office/word/2012/wordml}dataBinding",
    CTDecimalNumber: "{http://schemas.microsoft.com/office/word/2012/wordml}footnoteColumns",
    CTEmpty: "{http://schemas.microsoft.com/office/word/2012/wordml}repeatingSectionItem",
    CTPerson: "{http://schemas.microsoft.com/office/word/2012/wordml}person",
    CTPresenceInfo: "{http://schemas.microsoft.com/office/word/2012/wordml}presenceInfo",
    CTString: "{http://schemas.microsoft.com/office/word/2012/wordml}sectionTitle",
    Collapsed: "{http://schemas.microsoft.com/office/word/2012/wordml}collapsed",
    CommentsEx: "{http://schemas.microsoft.com/office/word/2012/wordml}commentsEx",
    DocId: "{http://schemas.microsoft.com/office/word/2012/wordml}docId",
    People: "{http://schemas.microsoft.com/office/word/2012/wordml}people",
    RepeatingSection: "{http://schemas.microsoft.com/office/word/2012/wordml}repeatingSection",
    WebExtensionCreated: "{http://schemas.microsoft.com/office/word/2012/wordml}webExtensionCreated",
    WebExtensionLinked: "{http://schemas.microsoft.com/office/word/2012/wordml}webExtensionLinked",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "appearance",
    "chartTrackingRefBased",
    "collapsed",
    "color",
    "commentEx",
    "commentsEx",
    "dataBinding",
    "doNotAllowInsertDeleteSection",
    "docId",
    "footnoteColumns",
    "people",
    "person",
    "presenceInfo",
    "repeatingSection",
    "repeatingSectionItem",
    "sectionTitle",
    "webExtensionCreated",
    "webExtensionLinked",
]
