"""``el`` for the http://schemas.microsoft.com/office/word/2010/wordprocessingGroup namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/word_wpg.json``, which a human reviews.

    >>> from docx4j_py.word.wpg import el
    >>> el.cNvFrPr()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTGroupShapeProperties,
    CTNonVisualDrawingProps,
    CTNonVisualGraphicFrameProperties,
    CTNonVisualGroupDrawingShapeProps,
    CTOfficeArtExtensionList,
    CTTransform2D,
)
from docx4j_py.word.wpg import (
    CTGraphicFrame,
    CTWordprocessingGroup,
    Wgp,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/word/2010/wordprocessingGroup"

def cNvFrPr(**kwargs: Any) -> CTNonVisualGraphicFrameProperties:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}cNvFrPr`` -> :class:`docx4j_py.dml.main.CTNonVisualGraphicFrameProperties`."""
    return CTNonVisualGraphicFrameProperties(**kwargs)

def cNvGrpSpPr(**kwargs: Any) -> CTNonVisualGroupDrawingShapeProps:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}cNvGrpSpPr`` -> :class:`docx4j_py.dml.main.CTNonVisualGroupDrawingShapeProps`."""
    return CTNonVisualGroupDrawingShapeProps(**kwargs)

def cNvPr(**kwargs: Any) -> CTNonVisualDrawingProps:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}cNvPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingProps`."""
    return CTNonVisualDrawingProps(**kwargs)

def extLst(**kwargs: Any) -> CTOfficeArtExtensionList:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}extLst`` -> :class:`docx4j_py.dml.main.CTOfficeArtExtensionList`."""
    return CTOfficeArtExtensionList(**kwargs)

def graphicFrame(**kwargs: Any) -> CTGraphicFrame:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}graphicFrame`` -> :class:`docx4j_py.word.wpg.CTGraphicFrame`."""
    return CTGraphicFrame(**kwargs)

def grpSp(**kwargs: Any) -> CTWordprocessingGroup:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}grpSp`` -> :class:`docx4j_py.word.wpg.CTWordprocessingGroup`."""
    return CTWordprocessingGroup(**kwargs)

def grpSpPr(**kwargs: Any) -> CTGroupShapeProperties:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}grpSpPr`` -> :class:`docx4j_py.dml.main.CTGroupShapeProperties`."""
    return CTGroupShapeProperties(**kwargs)

def wgp(**kwargs: Any) -> Wgp:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}wgp`` -> :class:`docx4j_py.word.wpg.Wgp`."""
    return Wgp(**kwargs)

def xfrm(**kwargs: Any) -> CTTransform2D:
    """``{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}xfrm`` -> :class:`docx4j_py.dml.main.CTTransform2D`."""
    return CTTransform2D(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}cNvFrPr": CTNonVisualGraphicFrameProperties,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}cNvGrpSpPr": CTNonVisualGroupDrawingShapeProps,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}cNvPr": CTNonVisualDrawingProps,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}extLst": CTOfficeArtExtensionList,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}graphicFrame": CTGraphicFrame,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}grpSp": CTWordprocessingGroup,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}grpSpPr": CTGroupShapeProperties,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}wgp": Wgp,
    "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}xfrm": CTTransform2D,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "cNvFrPr": CTNonVisualGraphicFrameProperties,
    "cNvGrpSpPr": CTNonVisualGroupDrawingShapeProps,
    "cNvPr": CTNonVisualDrawingProps,
    "extLst": CTOfficeArtExtensionList,
    "graphicFrame": CTGraphicFrame,
    "grpSp": CTWordprocessingGroup,
    "grpSpPr": CTGroupShapeProperties,
    "wgp": Wgp,
    "xfrm": CTTransform2D,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTGraphicFrame: "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}graphicFrame",
    CTGroupShapeProperties: "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}grpSpPr",
    CTNonVisualDrawingProps: "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}cNvPr",
    CTNonVisualGraphicFrameProperties: "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}cNvFrPr",
    CTNonVisualGroupDrawingShapeProps: "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}cNvGrpSpPr",
    CTOfficeArtExtensionList: "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}extLst",
    CTTransform2D: "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}xfrm",
    CTWordprocessingGroup: "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}grpSp",
    Wgp: "{http://schemas.microsoft.com/office/word/2010/wordprocessingGroup}wgp",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "cNvFrPr",
    "cNvGrpSpPr",
    "cNvPr",
    "extLst",
    "graphicFrame",
    "grpSp",
    "grpSpPr",
    "wgp",
    "xfrm",
]
