"""``el`` for the http://schemas.microsoft.com/office/drawing/2012/main namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_main_2012.json``, which a human reviews.

    >>> from docx4j_py.oart.main_2012 import el
    >>> el.backgroundPr()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.oart.main_2012 import (
    BackgroundPr,
    NonVisualGroupProps,
    ObjectPr,
    SignatureLine,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2012/main"

def backgroundPr(**kwargs: Any) -> BackgroundPr:
    """``{http://schemas.microsoft.com/office/drawing/2012/main}backgroundPr`` -> :class:`docx4j_py.oart.main_2012.BackgroundPr`."""
    return BackgroundPr(**kwargs)

def nonVisualGroupProps(**kwargs: Any) -> NonVisualGroupProps:
    """``{http://schemas.microsoft.com/office/drawing/2012/main}nonVisualGroupProps`` -> :class:`docx4j_py.oart.main_2012.NonVisualGroupProps`."""
    return NonVisualGroupProps(**kwargs)

def objectPr(**kwargs: Any) -> ObjectPr:
    """``{http://schemas.microsoft.com/office/drawing/2012/main}objectPr`` -> :class:`docx4j_py.oart.main_2012.ObjectPr`."""
    return ObjectPr(**kwargs)

def signatureLine(**kwargs: Any) -> SignatureLine:
    """``{http://schemas.microsoft.com/office/drawing/2012/main}signatureLine`` -> :class:`docx4j_py.oart.main_2012.SignatureLine`."""
    return SignatureLine(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2012/main}backgroundPr": BackgroundPr,
    "{http://schemas.microsoft.com/office/drawing/2012/main}nonVisualGroupProps": NonVisualGroupProps,
    "{http://schemas.microsoft.com/office/drawing/2012/main}objectPr": ObjectPr,
    "{http://schemas.microsoft.com/office/drawing/2012/main}signatureLine": SignatureLine,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "backgroundPr": BackgroundPr,
    "nonVisualGroupProps": NonVisualGroupProps,
    "objectPr": ObjectPr,
    "signatureLine": SignatureLine,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    BackgroundPr: "{http://schemas.microsoft.com/office/drawing/2012/main}backgroundPr",
    NonVisualGroupProps: "{http://schemas.microsoft.com/office/drawing/2012/main}nonVisualGroupProps",
    ObjectPr: "{http://schemas.microsoft.com/office/drawing/2012/main}objectPr",
    SignatureLine: "{http://schemas.microsoft.com/office/drawing/2012/main}signatureLine",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "backgroundPr",
    "nonVisualGroupProps",
    "objectPr",
    "signatureLine",
]
