"""``el`` for the http://schemas.microsoft.com/office/drawing/2017/model3d namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_model3d_2017.json``, which a human reviews.

    >>> from docx4j_py.oart.model3d_2017 import el
    >>> el.ambientLight()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTBlip,
    CTColor,
    CTOfficeArtExtensionList,
    CTPoint3D,
    CTRatio,
    CTShapeProperties,
    CTVector3D,
)
from docx4j_py.oart.main_2016_11 import (
    CTPictureAttributionSourceURL,
)
from docx4j_py.oart.model3d_2017 import (
    CTAmbientLight,
    CTDirectionalLight,
    CTModel3DCamera,
    CTModel3DRaster,
    CTModel3DTransform,
    CTObjectViewport,
    CTOrthographicProjection,
    CTPerspectiveProjection,
    CTPointLight,
    CTPositiveRatio,
    CTRotate3D,
    CTScale3D,
    CTSpotLight,
    CTUnknownLight,
    CTWindowViewport,
    Model3D,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2017/model3d"

def ambientLight(**kwargs: Any) -> CTAmbientLight:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}ambientLight`` -> :class:`docx4j_py.oart.model3d_2017.CTAmbientLight`."""
    return CTAmbientLight(**kwargs)

def attrSrcUrl(**kwargs: Any) -> CTPictureAttributionSourceURL:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}attrSrcUrl`` -> :class:`docx4j_py.oart.main_2016_11.CTPictureAttributionSourceURL`."""
    return CTPictureAttributionSourceURL(**kwargs)

def blip(**kwargs: Any) -> CTBlip:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}blip`` -> :class:`docx4j_py.dml.main.CTBlip`."""
    return CTBlip(**kwargs)

def camera(**kwargs: Any) -> CTModel3DCamera:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}camera`` -> :class:`docx4j_py.oart.model3d_2017.CTModel3DCamera`."""
    return CTModel3DCamera(**kwargs)

def clr(**kwargs: Any) -> CTColor:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}clr`` -> :class:`docx4j_py.dml.main.CTColor`."""
    return CTColor(**kwargs)

def dirLight(**kwargs: Any) -> CTDirectionalLight:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}dirLight`` -> :class:`docx4j_py.oart.model3d_2017.CTDirectionalLight`."""
    return CTDirectionalLight(**kwargs)

def extLst(**kwargs: Any) -> CTOfficeArtExtensionList:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}extLst`` -> :class:`docx4j_py.dml.main.CTOfficeArtExtensionList`."""
    return CTOfficeArtExtensionList(**kwargs)

def illuminance(**kwargs: Any) -> CTPositiveRatio:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}illuminance`` -> :class:`docx4j_py.oart.model3d_2017.CTPositiveRatio`."""
    return CTPositiveRatio(**kwargs)

def intensity(**kwargs: Any) -> CTPositiveRatio:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}intensity`` -> :class:`docx4j_py.oart.model3d_2017.CTPositiveRatio`."""
    return CTPositiveRatio(**kwargs)

def lookAt(**kwargs: Any) -> CTPoint3D:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}lookAt`` -> :class:`docx4j_py.dml.main.CTPoint3D`."""
    return CTPoint3D(**kwargs)

def meterPerModelUnit(**kwargs: Any) -> CTPositiveRatio:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}meterPerModelUnit`` -> :class:`docx4j_py.oart.model3d_2017.CTPositiveRatio`."""
    return CTPositiveRatio(**kwargs)

def model3D(**kwargs: Any) -> Model3D:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}model3D`` -> :class:`docx4j_py.oart.model3d_2017.Model3D`."""
    return Model3D(**kwargs)

def objViewport(**kwargs: Any) -> CTObjectViewport:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}objViewport`` -> :class:`docx4j_py.oart.model3d_2017.CTObjectViewport`."""
    return CTObjectViewport(**kwargs)

def orthographic(**kwargs: Any) -> CTOrthographicProjection:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}orthographic`` -> :class:`docx4j_py.oart.model3d_2017.CTOrthographicProjection`."""
    return CTOrthographicProjection(**kwargs)

def perspective(**kwargs: Any) -> CTPerspectiveProjection:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}perspective`` -> :class:`docx4j_py.oart.model3d_2017.CTPerspectiveProjection`."""
    return CTPerspectiveProjection(**kwargs)

def pos(**kwargs: Any) -> CTPoint3D:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}pos`` -> :class:`docx4j_py.dml.main.CTPoint3D`."""
    return CTPoint3D(**kwargs)

def postTrans(**kwargs: Any) -> CTVector3D:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}postTrans`` -> :class:`docx4j_py.dml.main.CTVector3D`."""
    return CTVector3D(**kwargs)

def preTrans(**kwargs: Any) -> CTVector3D:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}preTrans`` -> :class:`docx4j_py.dml.main.CTVector3D`."""
    return CTVector3D(**kwargs)

def ptLight(**kwargs: Any) -> CTPointLight:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}ptLight`` -> :class:`docx4j_py.oart.model3d_2017.CTPointLight`."""
    return CTPointLight(**kwargs)

def raster(**kwargs: Any) -> CTModel3DRaster:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}raster`` -> :class:`docx4j_py.oart.model3d_2017.CTModel3DRaster`."""
    return CTModel3DRaster(**kwargs)

def rot(**kwargs: Any) -> CTRotate3D:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}rot`` -> :class:`docx4j_py.oart.model3d_2017.CTRotate3D`."""
    return CTRotate3D(**kwargs)

def scale(**kwargs: Any) -> CTScale3D:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}scale`` -> :class:`docx4j_py.oart.model3d_2017.CTScale3D`."""
    return CTScale3D(**kwargs)

def spPr(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}spPr`` -> :class:`docx4j_py.dml.main.CTShapeProperties`."""
    return CTShapeProperties(**kwargs)

def spotLight(**kwargs: Any) -> CTSpotLight:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}spotLight`` -> :class:`docx4j_py.oart.model3d_2017.CTSpotLight`."""
    return CTSpotLight(**kwargs)

def sx(**kwargs: Any) -> CTRatio:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}sx`` -> :class:`docx4j_py.dml.main.CTRatio`."""
    return CTRatio(**kwargs)

def sy(**kwargs: Any) -> CTRatio:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}sy`` -> :class:`docx4j_py.dml.main.CTRatio`."""
    return CTRatio(**kwargs)

def sz(**kwargs: Any) -> CTPositiveRatio:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}sz`` -> :class:`docx4j_py.oart.model3d_2017.CTPositiveRatio`, the most reachable scope of 2 classes this name takes; see ``ratio``."""
    return CTPositiveRatio(**kwargs)

def ratio(**kwargs: Any) -> CTRatio:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}sz`` -> :class:`docx4j_py.dml.main.CTRatio`, the CTRatio form."""
    return CTRatio(**kwargs)

def trans(**kwargs: Any) -> CTModel3DTransform:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}trans`` -> :class:`docx4j_py.oart.model3d_2017.CTModel3DTransform`."""
    return CTModel3DTransform(**kwargs)

def unkLight(**kwargs: Any) -> CTUnknownLight:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}unkLight`` -> :class:`docx4j_py.oart.model3d_2017.CTUnknownLight`."""
    return CTUnknownLight(**kwargs)

def up(**kwargs: Any) -> CTVector3D:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}up`` -> :class:`docx4j_py.dml.main.CTVector3D`."""
    return CTVector3D(**kwargs)

def winViewport(**kwargs: Any) -> CTWindowViewport:
    """``{http://schemas.microsoft.com/office/drawing/2017/model3d}winViewport`` -> :class:`docx4j_py.oart.model3d_2017.CTWindowViewport`."""
    return CTWindowViewport(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}ambientLight": CTAmbientLight,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}attrSrcUrl": CTPictureAttributionSourceURL,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}blip": CTBlip,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}camera": CTModel3DCamera,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}clr": CTColor,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}dirLight": CTDirectionalLight,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}extLst": CTOfficeArtExtensionList,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}illuminance": CTPositiveRatio,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}intensity": CTPositiveRatio,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}lookAt": CTPoint3D,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}meterPerModelUnit": CTPositiveRatio,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}model3D": Model3D,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}objViewport": CTObjectViewport,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}orthographic": CTOrthographicProjection,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}perspective": CTPerspectiveProjection,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}pos": CTPoint3D,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}postTrans": CTVector3D,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}preTrans": CTVector3D,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}ptLight": CTPointLight,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}raster": CTModel3DRaster,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}rot": CTRotate3D,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}scale": CTScale3D,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}spPr": CTShapeProperties,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}spotLight": CTSpotLight,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}sx": CTRatio,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}sy": CTRatio,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}sz": CTPositiveRatio,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}trans": CTModel3DTransform,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}unkLight": CTUnknownLight,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}up": CTVector3D,
    "{http://schemas.microsoft.com/office/drawing/2017/model3d}winViewport": CTWindowViewport,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "ambientLight": CTAmbientLight,
    "attrSrcUrl": CTPictureAttributionSourceURL,
    "blip": CTBlip,
    "camera": CTModel3DCamera,
    "clr": CTColor,
    "dirLight": CTDirectionalLight,
    "extLst": CTOfficeArtExtensionList,
    "illuminance": CTPositiveRatio,
    "intensity": CTPositiveRatio,
    "lookAt": CTPoint3D,
    "meterPerModelUnit": CTPositiveRatio,
    "model3D": Model3D,
    "objViewport": CTObjectViewport,
    "orthographic": CTOrthographicProjection,
    "perspective": CTPerspectiveProjection,
    "pos": CTPoint3D,
    "postTrans": CTVector3D,
    "preTrans": CTVector3D,
    "ptLight": CTPointLight,
    "raster": CTModel3DRaster,
    "rot": CTRotate3D,
    "scale": CTScale3D,
    "spPr": CTShapeProperties,
    "spotLight": CTSpotLight,
    "sx": CTRatio,
    "sy": CTRatio,
    "sz": CTPositiveRatio,
    "trans": CTModel3DTransform,
    "unkLight": CTUnknownLight,
    "up": CTVector3D,
    "winViewport": CTWindowViewport,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTAmbientLight: "{http://schemas.microsoft.com/office/drawing/2017/model3d}ambientLight",
    CTBlip: "{http://schemas.microsoft.com/office/drawing/2017/model3d}blip",
    CTColor: "{http://schemas.microsoft.com/office/drawing/2017/model3d}clr",
    CTDirectionalLight: "{http://schemas.microsoft.com/office/drawing/2017/model3d}dirLight",
    CTModel3DCamera: "{http://schemas.microsoft.com/office/drawing/2017/model3d}camera",
    CTModel3DRaster: "{http://schemas.microsoft.com/office/drawing/2017/model3d}raster",
    CTModel3DTransform: "{http://schemas.microsoft.com/office/drawing/2017/model3d}trans",
    CTObjectViewport: "{http://schemas.microsoft.com/office/drawing/2017/model3d}objViewport",
    CTOfficeArtExtensionList: "{http://schemas.microsoft.com/office/drawing/2017/model3d}extLst",
    CTOrthographicProjection: "{http://schemas.microsoft.com/office/drawing/2017/model3d}orthographic",
    CTPerspectiveProjection: "{http://schemas.microsoft.com/office/drawing/2017/model3d}perspective",
    CTPictureAttributionSourceURL: "{http://schemas.microsoft.com/office/drawing/2017/model3d}attrSrcUrl",
    CTPointLight: "{http://schemas.microsoft.com/office/drawing/2017/model3d}ptLight",
    CTRotate3D: "{http://schemas.microsoft.com/office/drawing/2017/model3d}rot",
    CTScale3D: "{http://schemas.microsoft.com/office/drawing/2017/model3d}scale",
    CTShapeProperties: "{http://schemas.microsoft.com/office/drawing/2017/model3d}spPr",
    CTSpotLight: "{http://schemas.microsoft.com/office/drawing/2017/model3d}spotLight",
    CTUnknownLight: "{http://schemas.microsoft.com/office/drawing/2017/model3d}unkLight",
    CTWindowViewport: "{http://schemas.microsoft.com/office/drawing/2017/model3d}winViewport",
    Model3D: "{http://schemas.microsoft.com/office/drawing/2017/model3d}model3D",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "ambientLight",
    "attrSrcUrl",
    "blip",
    "camera",
    "clr",
    "dirLight",
    "extLst",
    "illuminance",
    "intensity",
    "lookAt",
    "meterPerModelUnit",
    "model3D",
    "objViewport",
    "orthographic",
    "perspective",
    "pos",
    "postTrans",
    "preTrans",
    "ptLight",
    "raster",
    "ratio",
    "rot",
    "scale",
    "spPr",
    "spotLight",
    "sx",
    "sy",
    "sz",
    "trans",
    "unkLight",
    "up",
    "winViewport",
]
