"""``el`` for the http://schemas.openxmlformats.org/drawingml/2006/diagram namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/dml_diagram.json``, which a human reviews.

    >>> from docx4j_py.dml.diagram import el
    >>> el.adj()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.diagram import (
    CTAdj,
    CTAdjLst,
    CTAlgorithm,
    CTAnimLvl,
    CTAnimOne,
    CTBulletEnabled,
    CTCTCategories,
    CTCTCategory,
    CTCTDescription,
    CTCTName,
    CTCTStyleLabel,
    CTCategories,
    CTCategory,
    CTChildMax,
    CTChildPref,
    CTChoose,
    CTColorTransformHeader,
    CTColors,
    CTConstraint,
    CTConstraints,
    CTCxn,
    CTCxnList,
    CTDataModel,
    CTDescription,
    CTDiagramDefinitionHeader,
    CTDirection,
    CTElemPropSet,
    CTForEach,
    CTHierBranchStyle,
    CTLayoutNode,
    CTLayoutVariablePropertySet,
    CTName,
    CTNumericRule,
    CTOrgChart,
    CTOtherwise,
    CTParameter,
    CTPresentationOf,
    CTPt,
    CTPtList,
    CTResizeHandles,
    CTRules,
    CTSDCategories,
    CTSDCategory,
    CTSDDescription,
    CTSDName,
    CTSampleData,
    CTShape,
    CTStyleDefinitionHeader,
    CTStyleLabel,
    CTTextBody,
    CTTextProps,
    CTWhen,
    ColorsDef,
    ColorsDefHdr,
    ColorsDefHdrLst,
    DataModel,
    LayoutDef,
    LayoutDefHdr,
    LayoutDefHdrLst,
    RelIds,
    StyleDef,
    StyleDefHdr,
    StyleDefHdrLst,
)
from docx4j_py.dml.main import (
    CTBackgroundFormatting,
    CTOfficeArtExtensionList,
    CTScene3D,
    CTShape3D,
    CTShapeProperties,
    CTShapeStyle,
    CTWholeE2OFormatting,
)

__NAMESPACE__ = "http://schemas.openxmlformats.org/drawingml/2006/diagram"

def adj(**kwargs: Any) -> CTAdj:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}adj`` -> :class:`docx4j_py.dml.diagram.CTAdj`."""
    return CTAdj(**kwargs)

def adjLst(**kwargs: Any) -> CTAdjLst:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}adjLst`` -> :class:`docx4j_py.dml.diagram.CTAdjLst`."""
    return CTAdjLst(**kwargs)

def alg(**kwargs: Any) -> CTAlgorithm:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}alg`` -> :class:`docx4j_py.dml.diagram.CTAlgorithm`."""
    return CTAlgorithm(**kwargs)

def animLvl(**kwargs: Any) -> CTAnimLvl:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}animLvl`` -> :class:`docx4j_py.dml.diagram.CTAnimLvl`."""
    return CTAnimLvl(**kwargs)

def animOne(**kwargs: Any) -> CTAnimOne:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}animOne`` -> :class:`docx4j_py.dml.diagram.CTAnimOne`."""
    return CTAnimOne(**kwargs)

def bg(**kwargs: Any) -> CTBackgroundFormatting:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}bg`` -> :class:`docx4j_py.dml.main.CTBackgroundFormatting`."""
    return CTBackgroundFormatting(**kwargs)

def bulletEnabled(**kwargs: Any) -> CTBulletEnabled:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}bulletEnabled`` -> :class:`docx4j_py.dml.diagram.CTBulletEnabled`."""
    return CTBulletEnabled(**kwargs)

def cat(**kwargs: Any) -> CTCTCategory:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}cat`` -> :class:`docx4j_py.dml.diagram.CTCTCategory`, the most reachable scope of 3 classes this name takes; see ``category``, ``sd_category``."""
    return CTCTCategory(**kwargs)

def category(**kwargs: Any) -> CTCategory:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}cat`` -> :class:`docx4j_py.dml.diagram.CTCategory`, the CTCategory form."""
    return CTCategory(**kwargs)

def sd_category(**kwargs: Any) -> CTSDCategory:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}cat`` -> :class:`docx4j_py.dml.diagram.CTSDCategory`, the CTSDCategory form."""
    return CTSDCategory(**kwargs)

def catLst(**kwargs: Any) -> CTCTCategories:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}catLst`` -> :class:`docx4j_py.dml.diagram.CTCTCategories`, the most reachable scope of 3 classes this name takes; see ``categories``, ``sd_categories``."""
    return CTCTCategories(**kwargs)

def categories(**kwargs: Any) -> CTCategories:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}catLst`` -> :class:`docx4j_py.dml.diagram.CTCategories`, the CTCategories form."""
    return CTCategories(**kwargs)

def sd_categories(**kwargs: Any) -> CTSDCategories:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}catLst`` -> :class:`docx4j_py.dml.diagram.CTSDCategories`, the CTSDCategories form."""
    return CTSDCategories(**kwargs)

def chMax(**kwargs: Any) -> CTChildMax:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}chMax`` -> :class:`docx4j_py.dml.diagram.CTChildMax`."""
    return CTChildMax(**kwargs)

def chPref(**kwargs: Any) -> CTChildPref:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}chPref`` -> :class:`docx4j_py.dml.diagram.CTChildPref`."""
    return CTChildPref(**kwargs)

def choose(**kwargs: Any) -> CTChoose:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}choose`` -> :class:`docx4j_py.dml.diagram.CTChoose`."""
    return CTChoose(**kwargs)

def clrData(**kwargs: Any) -> CTSampleData:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}clrData`` -> :class:`docx4j_py.dml.diagram.CTSampleData`."""
    return CTSampleData(**kwargs)

def colorsDef(**kwargs: Any) -> ColorsDef:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDef`` -> :class:`docx4j_py.dml.diagram.ColorsDef`."""
    return ColorsDef(**kwargs)

def colorsDefHdr(**kwargs: Any) -> ColorsDefHdr:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDefHdr`` -> :class:`docx4j_py.dml.diagram.ColorsDefHdr`, the global element declaration of 2 classes this name takes; see ``color_transform_header``."""
    return ColorsDefHdr(**kwargs)

def color_transform_header(**kwargs: Any) -> CTColorTransformHeader:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDefHdr`` -> :class:`docx4j_py.dml.diagram.CTColorTransformHeader`, the CTColorTransformHeader form."""
    return CTColorTransformHeader(**kwargs)

def colorsDefHdrLst(**kwargs: Any) -> ColorsDefHdrLst:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDefHdrLst`` -> :class:`docx4j_py.dml.diagram.ColorsDefHdrLst`."""
    return ColorsDefHdrLst(**kwargs)

def constr(**kwargs: Any) -> CTConstraint:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}constr`` -> :class:`docx4j_py.dml.diagram.CTConstraint`."""
    return CTConstraint(**kwargs)

def constrLst(**kwargs: Any) -> CTConstraints:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}constrLst`` -> :class:`docx4j_py.dml.diagram.CTConstraints`."""
    return CTConstraints(**kwargs)

def cxn(**kwargs: Any) -> CTCxn:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}cxn`` -> :class:`docx4j_py.dml.diagram.CTCxn`."""
    return CTCxn(**kwargs)

def cxnLst(**kwargs: Any) -> CTCxnList:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}cxnLst`` -> :class:`docx4j_py.dml.diagram.CTCxnList`."""
    return CTCxnList(**kwargs)

def dataModel(**kwargs: Any) -> DataModel:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}dataModel`` -> :class:`docx4j_py.dml.diagram.DataModel`, the global element declaration of 2 classes this name takes; see ``data_model``."""
    return DataModel(**kwargs)

def data_model(**kwargs: Any) -> CTDataModel:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}dataModel`` -> :class:`docx4j_py.dml.diagram.CTDataModel`, the CTDataModel form."""
    return CTDataModel(**kwargs)

def desc(**kwargs: Any) -> CTCTDescription:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}desc`` -> :class:`docx4j_py.dml.diagram.CTCTDescription`, the most reachable scope of 3 classes this name takes; see ``description``, ``sd_description``."""
    return CTCTDescription(**kwargs)

def description(**kwargs: Any) -> CTDescription:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}desc`` -> :class:`docx4j_py.dml.diagram.CTDescription`, the CTDescription form."""
    return CTDescription(**kwargs)

def sd_description(**kwargs: Any) -> CTSDDescription:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}desc`` -> :class:`docx4j_py.dml.diagram.CTSDDescription`, the CTSDDescription form."""
    return CTSDDescription(**kwargs)

def dir_(**kwargs: Any) -> CTDirection:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}dir`` -> :class:`docx4j_py.dml.diagram.CTDirection`."""
    return CTDirection(**kwargs)

def effectClrLst(**kwargs: Any) -> CTColors:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}effectClrLst`` -> :class:`docx4j_py.dml.diagram.CTColors`."""
    return CTColors(**kwargs)

def else_(**kwargs: Any) -> CTOtherwise:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}else`` -> :class:`docx4j_py.dml.diagram.CTOtherwise`."""
    return CTOtherwise(**kwargs)

def extLst(**kwargs: Any) -> CTOfficeArtExtensionList:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}extLst`` -> :class:`docx4j_py.dml.main.CTOfficeArtExtensionList`."""
    return CTOfficeArtExtensionList(**kwargs)

def fillClrLst(**kwargs: Any) -> CTColors:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}fillClrLst`` -> :class:`docx4j_py.dml.diagram.CTColors`."""
    return CTColors(**kwargs)

def forEach(**kwargs: Any) -> CTForEach:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}forEach`` -> :class:`docx4j_py.dml.diagram.CTForEach`."""
    return CTForEach(**kwargs)

def hierBranch(**kwargs: Any) -> CTHierBranchStyle:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}hierBranch`` -> :class:`docx4j_py.dml.diagram.CTHierBranchStyle`."""
    return CTHierBranchStyle(**kwargs)

def if_(**kwargs: Any) -> CTWhen:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}if`` -> :class:`docx4j_py.dml.diagram.CTWhen`."""
    return CTWhen(**kwargs)

def layoutDef(**kwargs: Any) -> LayoutDef:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDef`` -> :class:`docx4j_py.dml.diagram.LayoutDef`."""
    return LayoutDef(**kwargs)

def layoutDefHdr(**kwargs: Any) -> LayoutDefHdr:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDefHdr`` -> :class:`docx4j_py.dml.diagram.LayoutDefHdr`, the global element declaration of 2 classes this name takes; see ``diagram_definition_header``."""
    return LayoutDefHdr(**kwargs)

def diagram_definition_header(**kwargs: Any) -> CTDiagramDefinitionHeader:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDefHdr`` -> :class:`docx4j_py.dml.diagram.CTDiagramDefinitionHeader`, the CTDiagramDefinitionHeader form."""
    return CTDiagramDefinitionHeader(**kwargs)

def layoutDefHdrLst(**kwargs: Any) -> LayoutDefHdrLst:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDefHdrLst`` -> :class:`docx4j_py.dml.diagram.LayoutDefHdrLst`."""
    return LayoutDefHdrLst(**kwargs)

def layoutNode(**kwargs: Any) -> CTLayoutNode:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutNode`` -> :class:`docx4j_py.dml.diagram.CTLayoutNode`."""
    return CTLayoutNode(**kwargs)

def linClrLst(**kwargs: Any) -> CTColors:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}linClrLst`` -> :class:`docx4j_py.dml.diagram.CTColors`."""
    return CTColors(**kwargs)

def orgChart(**kwargs: Any) -> CTOrgChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}orgChart`` -> :class:`docx4j_py.dml.diagram.CTOrgChart`."""
    return CTOrgChart(**kwargs)

def param(**kwargs: Any) -> CTParameter:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}param`` -> :class:`docx4j_py.dml.diagram.CTParameter`."""
    return CTParameter(**kwargs)

def prSet(**kwargs: Any) -> CTElemPropSet:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}prSet`` -> :class:`docx4j_py.dml.diagram.CTElemPropSet`."""
    return CTElemPropSet(**kwargs)

def presLayoutVars(**kwargs: Any) -> CTLayoutVariablePropertySet:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}presLayoutVars`` -> :class:`docx4j_py.dml.diagram.CTLayoutVariablePropertySet`."""
    return CTLayoutVariablePropertySet(**kwargs)

def presOf(**kwargs: Any) -> CTPresentationOf:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}presOf`` -> :class:`docx4j_py.dml.diagram.CTPresentationOf`."""
    return CTPresentationOf(**kwargs)

def pt(**kwargs: Any) -> CTPt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}pt`` -> :class:`docx4j_py.dml.diagram.CTPt`."""
    return CTPt(**kwargs)

def ptLst(**kwargs: Any) -> CTPtList:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}ptLst`` -> :class:`docx4j_py.dml.diagram.CTPtList`."""
    return CTPtList(**kwargs)

def relIds(**kwargs: Any) -> RelIds:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}relIds`` -> :class:`docx4j_py.dml.diagram.RelIds`."""
    return RelIds(**kwargs)

def resizeHandles(**kwargs: Any) -> CTResizeHandles:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}resizeHandles`` -> :class:`docx4j_py.dml.diagram.CTResizeHandles`."""
    return CTResizeHandles(**kwargs)

def rule(**kwargs: Any) -> CTNumericRule:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}rule`` -> :class:`docx4j_py.dml.diagram.CTNumericRule`."""
    return CTNumericRule(**kwargs)

def ruleLst(**kwargs: Any) -> CTRules:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}ruleLst`` -> :class:`docx4j_py.dml.diagram.CTRules`."""
    return CTRules(**kwargs)

def sampData(**kwargs: Any) -> CTSampleData:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}sampData`` -> :class:`docx4j_py.dml.diagram.CTSampleData`."""
    return CTSampleData(**kwargs)

def scene3d(**kwargs: Any) -> CTScene3D:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}scene3d`` -> :class:`docx4j_py.dml.main.CTScene3D`."""
    return CTScene3D(**kwargs)

def shape(**kwargs: Any) -> CTShape:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}shape`` -> :class:`docx4j_py.dml.diagram.CTShape`."""
    return CTShape(**kwargs)

def sp3d(**kwargs: Any) -> CTShape3D:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}sp3d`` -> :class:`docx4j_py.dml.main.CTShape3D`."""
    return CTShape3D(**kwargs)

def spPr(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}spPr`` -> :class:`docx4j_py.dml.main.CTShapeProperties`."""
    return CTShapeProperties(**kwargs)

def style(**kwargs: Any) -> CTShapeStyle:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}style`` -> :class:`docx4j_py.dml.main.CTShapeStyle`."""
    return CTShapeStyle(**kwargs)

def styleData(**kwargs: Any) -> CTSampleData:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleData`` -> :class:`docx4j_py.dml.diagram.CTSampleData`."""
    return CTSampleData(**kwargs)

def styleDef(**kwargs: Any) -> StyleDef:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDef`` -> :class:`docx4j_py.dml.diagram.StyleDef`."""
    return StyleDef(**kwargs)

def styleDefHdr(**kwargs: Any) -> StyleDefHdr:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDefHdr`` -> :class:`docx4j_py.dml.diagram.StyleDefHdr`, the global element declaration of 2 classes this name takes; see ``style_definition_header``."""
    return StyleDefHdr(**kwargs)

def style_definition_header(**kwargs: Any) -> CTStyleDefinitionHeader:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDefHdr`` -> :class:`docx4j_py.dml.diagram.CTStyleDefinitionHeader`, the CTStyleDefinitionHeader form."""
    return CTStyleDefinitionHeader(**kwargs)

def styleDefHdrLst(**kwargs: Any) -> StyleDefHdrLst:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDefHdrLst`` -> :class:`docx4j_py.dml.diagram.StyleDefHdrLst`."""
    return StyleDefHdrLst(**kwargs)

def styleLbl(**kwargs: Any) -> CTCTStyleLabel:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleLbl`` -> :class:`docx4j_py.dml.diagram.CTCTStyleLabel`, the most reachable scope of 2 classes this name takes; see ``style_label``."""
    return CTCTStyleLabel(**kwargs)

def style_label(**kwargs: Any) -> CTStyleLabel:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleLbl`` -> :class:`docx4j_py.dml.diagram.CTStyleLabel`, the CTStyleLabel form."""
    return CTStyleLabel(**kwargs)

def t(**kwargs: Any) -> CTTextBody:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}t`` -> :class:`docx4j_py.dml.diagram.CTTextBody`."""
    return CTTextBody(**kwargs)

def title(**kwargs: Any) -> CTCTName:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}title`` -> :class:`docx4j_py.dml.diagram.CTCTName`, the most reachable scope of 3 classes this name takes; see ``name``, ``sd_name``."""
    return CTCTName(**kwargs)

def name(**kwargs: Any) -> CTName:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}title`` -> :class:`docx4j_py.dml.diagram.CTName`, the CTName form."""
    return CTName(**kwargs)

def sd_name(**kwargs: Any) -> CTSDName:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}title`` -> :class:`docx4j_py.dml.diagram.CTSDName`, the CTSDName form."""
    return CTSDName(**kwargs)

def txEffectClrLst(**kwargs: Any) -> CTColors:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}txEffectClrLst`` -> :class:`docx4j_py.dml.diagram.CTColors`."""
    return CTColors(**kwargs)

def txFillClrLst(**kwargs: Any) -> CTColors:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}txFillClrLst`` -> :class:`docx4j_py.dml.diagram.CTColors`."""
    return CTColors(**kwargs)

def txLinClrLst(**kwargs: Any) -> CTColors:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}txLinClrLst`` -> :class:`docx4j_py.dml.diagram.CTColors`."""
    return CTColors(**kwargs)

def txPr(**kwargs: Any) -> CTTextProps:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}txPr`` -> :class:`docx4j_py.dml.diagram.CTTextProps`."""
    return CTTextProps(**kwargs)

def varLst(**kwargs: Any) -> CTLayoutVariablePropertySet:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}varLst`` -> :class:`docx4j_py.dml.diagram.CTLayoutVariablePropertySet`."""
    return CTLayoutVariablePropertySet(**kwargs)

def whole(**kwargs: Any) -> CTWholeE2OFormatting:
    """``{http://schemas.openxmlformats.org/drawingml/2006/diagram}whole`` -> :class:`docx4j_py.dml.main.CTWholeE2OFormatting`."""
    return CTWholeE2OFormatting(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}adj": CTAdj,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}adjLst": CTAdjLst,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}alg": CTAlgorithm,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}animLvl": CTAnimLvl,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}animOne": CTAnimOne,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}bg": CTBackgroundFormatting,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}bulletEnabled": CTBulletEnabled,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}cat": CTCTCategory,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}catLst": CTCTCategories,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}chMax": CTChildMax,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}chPref": CTChildPref,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}choose": CTChoose,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}clrData": CTSampleData,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDef": ColorsDef,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDefHdr": ColorsDefHdr,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDefHdrLst": ColorsDefHdrLst,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}constr": CTConstraint,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}constrLst": CTConstraints,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}cxn": CTCxn,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}cxnLst": CTCxnList,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}dataModel": DataModel,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}desc": CTCTDescription,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}dir": CTDirection,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}effectClrLst": CTColors,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}else": CTOtherwise,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}extLst": CTOfficeArtExtensionList,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}fillClrLst": CTColors,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}forEach": CTForEach,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}hierBranch": CTHierBranchStyle,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}if": CTWhen,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDef": LayoutDef,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDefHdr": LayoutDefHdr,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDefHdrLst": LayoutDefHdrLst,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutNode": CTLayoutNode,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}linClrLst": CTColors,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}orgChart": CTOrgChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}param": CTParameter,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}prSet": CTElemPropSet,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}presLayoutVars": CTLayoutVariablePropertySet,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}presOf": CTPresentationOf,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}pt": CTPt,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}ptLst": CTPtList,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}relIds": RelIds,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}resizeHandles": CTResizeHandles,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}rule": CTNumericRule,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}ruleLst": CTRules,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}sampData": CTSampleData,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}scene3d": CTScene3D,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}shape": CTShape,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}sp3d": CTShape3D,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}spPr": CTShapeProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}style": CTShapeStyle,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleData": CTSampleData,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDef": StyleDef,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDefHdr": StyleDefHdr,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDefHdrLst": StyleDefHdrLst,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleLbl": CTCTStyleLabel,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}t": CTTextBody,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}title": CTCTName,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}txEffectClrLst": CTColors,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}txFillClrLst": CTColors,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}txLinClrLst": CTColors,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}txPr": CTTextProps,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}varLst": CTLayoutVariablePropertySet,
    "{http://schemas.openxmlformats.org/drawingml/2006/diagram}whole": CTWholeE2OFormatting,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "adj": CTAdj,
    "adjLst": CTAdjLst,
    "alg": CTAlgorithm,
    "animLvl": CTAnimLvl,
    "animOne": CTAnimOne,
    "bg": CTBackgroundFormatting,
    "bulletEnabled": CTBulletEnabled,
    "cat": CTCTCategory,
    "catLst": CTCTCategories,
    "chMax": CTChildMax,
    "chPref": CTChildPref,
    "choose": CTChoose,
    "clrData": CTSampleData,
    "colorsDef": ColorsDef,
    "colorsDefHdr": ColorsDefHdr,
    "colorsDefHdrLst": ColorsDefHdrLst,
    "constr": CTConstraint,
    "constrLst": CTConstraints,
    "cxn": CTCxn,
    "cxnLst": CTCxnList,
    "dataModel": DataModel,
    "desc": CTCTDescription,
    "dir": CTDirection,
    "effectClrLst": CTColors,
    "else": CTOtherwise,
    "extLst": CTOfficeArtExtensionList,
    "fillClrLst": CTColors,
    "forEach": CTForEach,
    "hierBranch": CTHierBranchStyle,
    "if": CTWhen,
    "layoutDef": LayoutDef,
    "layoutDefHdr": LayoutDefHdr,
    "layoutDefHdrLst": LayoutDefHdrLst,
    "layoutNode": CTLayoutNode,
    "linClrLst": CTColors,
    "orgChart": CTOrgChart,
    "param": CTParameter,
    "prSet": CTElemPropSet,
    "presLayoutVars": CTLayoutVariablePropertySet,
    "presOf": CTPresentationOf,
    "pt": CTPt,
    "ptLst": CTPtList,
    "relIds": RelIds,
    "resizeHandles": CTResizeHandles,
    "rule": CTNumericRule,
    "ruleLst": CTRules,
    "sampData": CTSampleData,
    "scene3d": CTScene3D,
    "shape": CTShape,
    "sp3d": CTShape3D,
    "spPr": CTShapeProperties,
    "style": CTShapeStyle,
    "styleData": CTSampleData,
    "styleDef": StyleDef,
    "styleDefHdr": StyleDefHdr,
    "styleDefHdrLst": StyleDefHdrLst,
    "styleLbl": CTCTStyleLabel,
    "t": CTTextBody,
    "title": CTCTName,
    "txEffectClrLst": CTColors,
    "txFillClrLst": CTColors,
    "txLinClrLst": CTColors,
    "txPr": CTTextProps,
    "varLst": CTLayoutVariablePropertySet,
    "whole": CTWholeE2OFormatting,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTAdj: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}adj",
    CTAdjLst: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}adjLst",
    CTAlgorithm: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}alg",
    CTAnimLvl: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}animLvl",
    CTAnimOne: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}animOne",
    CTBackgroundFormatting: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}bg",
    CTBulletEnabled: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}bulletEnabled",
    CTCTCategories: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}catLst",
    CTCTCategory: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}cat",
    CTCTDescription: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}desc",
    CTCTName: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}title",
    CTCTStyleLabel: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleLbl",
    CTCategories: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}catLst",
    CTCategory: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}cat",
    CTChildMax: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}chMax",
    CTChildPref: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}chPref",
    CTChoose: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}choose",
    CTColorTransformHeader: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDefHdr",
    CTConstraint: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}constr",
    CTConstraints: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}constrLst",
    CTCxn: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}cxn",
    CTCxnList: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}cxnLst",
    CTDataModel: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}dataModel",
    CTDescription: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}desc",
    CTDiagramDefinitionHeader: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDefHdr",
    CTDirection: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}dir",
    CTElemPropSet: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}prSet",
    CTForEach: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}forEach",
    CTHierBranchStyle: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}hierBranch",
    CTLayoutNode: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutNode",
    CTName: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}title",
    CTNumericRule: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}rule",
    CTOfficeArtExtensionList: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}extLst",
    CTOrgChart: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}orgChart",
    CTOtherwise: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}else",
    CTParameter: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}param",
    CTPresentationOf: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}presOf",
    CTPt: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}pt",
    CTPtList: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}ptLst",
    CTResizeHandles: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}resizeHandles",
    CTRules: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}ruleLst",
    CTSDCategories: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}catLst",
    CTSDCategory: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}cat",
    CTSDDescription: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}desc",
    CTSDName: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}title",
    CTScene3D: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}scene3d",
    CTShape: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}shape",
    CTShape3D: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}sp3d",
    CTShapeProperties: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}spPr",
    CTShapeStyle: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}style",
    CTStyleDefinitionHeader: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDefHdr",
    CTStyleLabel: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleLbl",
    CTTextBody: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}t",
    CTTextProps: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}txPr",
    CTWhen: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}if",
    CTWholeE2OFormatting: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}whole",
    ColorsDef: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDef",
    ColorsDefHdr: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDefHdr",
    ColorsDefHdrLst: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDefHdrLst",
    DataModel: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}dataModel",
    LayoutDef: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDef",
    LayoutDefHdr: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDefHdr",
    LayoutDefHdrLst: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDefHdrLst",
    RelIds: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}relIds",
    StyleDef: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDef",
    StyleDefHdr: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDefHdr",
    StyleDefHdrLst: "{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDefHdrLst",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "adj",
    "adjLst",
    "alg",
    "animLvl",
    "animOne",
    "bg",
    "bulletEnabled",
    "cat",
    "catLst",
    "categories",
    "category",
    "chMax",
    "chPref",
    "choose",
    "clrData",
    "color_transform_header",
    "colorsDef",
    "colorsDefHdr",
    "colorsDefHdrLst",
    "constr",
    "constrLst",
    "cxn",
    "cxnLst",
    "dataModel",
    "data_model",
    "desc",
    "description",
    "diagram_definition_header",
    "dir_",
    "effectClrLst",
    "else_",
    "extLst",
    "fillClrLst",
    "forEach",
    "hierBranch",
    "if_",
    "layoutDef",
    "layoutDefHdr",
    "layoutDefHdrLst",
    "layoutNode",
    "linClrLst",
    "name",
    "orgChart",
    "param",
    "prSet",
    "presLayoutVars",
    "presOf",
    "pt",
    "ptLst",
    "relIds",
    "resizeHandles",
    "rule",
    "ruleLst",
    "sampData",
    "scene3d",
    "sd_categories",
    "sd_category",
    "sd_description",
    "sd_name",
    "shape",
    "sp3d",
    "spPr",
    "style",
    "styleData",
    "styleDef",
    "styleDefHdr",
    "styleDefHdrLst",
    "styleLbl",
    "style_definition_header",
    "style_label",
    "t",
    "title",
    "txEffectClrLst",
    "txFillClrLst",
    "txLinClrLst",
    "txPr",
    "varLst",
    "whole",
]
