from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from docx4j_py.docprops.core import CoreProperties
    from docx4j_py.docprops.custom import (
        Properties as CustomProperties,
    )
    from docx4j_py.docprops.custom import (
        PropertiesProperty,
    )
    from docx4j_py.docprops.dc import (
        AnyType,
        Contributor,
        Coverage,
        Creator,
        Description,
        ElementContainer,
        Format,
        Identifier,
        Language,
        Publisher,
        Relation,
        Rights,
        Source,
        Subject,
        Title,
        Type,
    )
    from docx4j_py.docprops.dc import (
        Date as DcDate,
    )
    from docx4j_py.docprops.dc import (
        SimpleLiteral as DcSimpleLiteral,
    )
    from docx4j_py.docprops.dcmitype import DCMIType as DcmitypeDcmitype
    from docx4j_py.docprops.dcterms import (
        DDC,
        IMT,
        ISO3166,
        ISO6392,
        LCC,
        LCSH,
        MESH,
        RFC1766,
        RFC3066,
        TGN,
        UDC,
        URI,
        W3CDTF,
        Abstract,
        AccessRights,
        Audience,
        Available,
        BibliographicCitation,
        Box,
        ConformsTo,
        Created,
        DateAccepted,
        DateCopyrighted,
        DateSubmitted,
        EducationLevel,
        ElementOrRefinementContainer,
        Extent,
        HasFormat,
        HasPart,
        HasVersion,
        IsFormatOf,
        IsPartOf,
        IsReferencedBy,
        IsReplacedBy,
        IsRequiredBy,
        Issued,
        IsVersionOf,
        Mediator,
        Medium,
        Modified,
        Period,
        Point,
        References,
        Replaces,
        Requires,
        Spatial,
        TableOfContents,
        Temporal,
        Valid,
    )
    from docx4j_py.docprops.dcterms import (
        DCMIType as DctermsDcmitype,
    )
    from docx4j_py.docprops.dcterms import (
        SimpleLiteral as DctermsSimpleLiteral,
    )
    from docx4j_py.docprops.extended import (
        Properties as ExtendedProperties,
    )
    from docx4j_py.docprops.extended import (
        PropertiesDigSig,
        PropertiesHeadingPairs,
        PropertiesHlinks,
        PropertiesTitlesOfParts,
    )
    from docx4j_py.docprops.variant_types import (
        I1,
        I2,
        I4,
        I8,
        R4,
        R8,
        Array,
        Array1,
        Blob,
        Bool,
        Bstr,
        Cf,
        Cf1,
        Clsid,
        CtArrayBaseType,
        CtVectorBaseType,
        Cy,
        DecimalType,
        Empty,
        Empty1,
        Error,
        Filetime,
        Int,
        Lpstr,
        Lpwstr,
        Null,
        Null1,
        Oblob,
        Ostorage,
        Ostream,
        Storage,
        Stream,
        Ui1,
        Ui2,
        Ui4,
        Ui8,
        Uint,
        Variant,
        Variant1,
        Vector,
        Vector1,
        Vstream,
        Vstream1,
    )
    from docx4j_py.docprops.variant_types import (
        Date as VariantTypesDate,
    )

__all__ = [
    "CoreProperties",
    "CustomProperties",
    "PropertiesProperty",
    "ElementContainer",
    "DcSimpleLiteral",
    "AnyType",
    "Contributor",
    "Coverage",
    "Creator",
    "DcDate",
    "Description",
    "Format",
    "Identifier",
    "Language",
    "Publisher",
    "Relation",
    "Rights",
    "Source",
    "Subject",
    "Title",
    "Type",
    "DcmitypeDcmitype",
    "Box",
    "DctermsDcmitype",
    "DDC",
    "ElementOrRefinementContainer",
    "IMT",
    "ISO3166",
    "ISO6392",
    "LCC",
    "LCSH",
    "MESH",
    "Period",
    "Point",
    "RFC1766",
    "RFC3066",
    "DctermsSimpleLiteral",
    "TGN",
    "UDC",
    "URI",
    "W3CDTF",
    "Abstract",
    "AccessRights",
    "Audience",
    "Available",
    "BibliographicCitation",
    "ConformsTo",
    "Created",
    "DateAccepted",
    "DateCopyrighted",
    "DateSubmitted",
    "EducationLevel",
    "Extent",
    "HasFormat",
    "HasPart",
    "HasVersion",
    "IsFormatOf",
    "IsPartOf",
    "IsReferencedBy",
    "IsReplacedBy",
    "IsRequiredBy",
    "IsVersionOf",
    "Issued",
    "Mediator",
    "Medium",
    "Modified",
    "References",
    "Replaces",
    "Requires",
    "Spatial",
    "TableOfContents",
    "Temporal",
    "Valid",
    "ExtendedProperties",
    "PropertiesDigSig",
    "PropertiesHlinks",
    "PropertiesHeadingPairs",
    "PropertiesTitlesOfParts",
    "Array1",
    "CtArrayBaseType",
    "CtVectorBaseType",
    "Cf1",
    "Empty1",
    "Null1",
    "Variant1",
    "Vector1",
    "Vstream1",
    "Array",
    "Blob",
    "Bool",
    "Bstr",
    "Cf",
    "Clsid",
    "Cy",
    "VariantTypesDate",
    "DecimalType",
    "Empty",
    "Error",
    "Filetime",
    "I1",
    "I2",
    "I4",
    "I8",
    "Int",
    "Lpstr",
    "Lpwstr",
    "Null",
    "Oblob",
    "Ostorage",
    "Ostream",
    "R4",
    "R8",
    "Storage",
    "Stream",
    "Ui1",
    "Ui2",
    "Ui4",
    "Ui8",
    "Uint",
    "Variant",
    "Vector",
    "Vstream",
]

# The re-exports above are resolved on first use, so that importing this
# package never forces a module of it to be imported before the modules it
# depends on.
__lazy_imports__ = {
    "CoreProperties": ("docx4j_py.docprops.core", "CoreProperties"),
    "CustomProperties": ("docx4j_py.docprops.custom", "Properties"),
    "PropertiesProperty": ("docx4j_py.docprops.custom", "PropertiesProperty"),
    "ElementContainer": ("docx4j_py.docprops.dc", "ElementContainer"),
    "DcSimpleLiteral": ("docx4j_py.docprops.dc", "SimpleLiteral"),
    "AnyType": ("docx4j_py.docprops.dc", "AnyType"),
    "Contributor": ("docx4j_py.docprops.dc", "Contributor"),
    "Coverage": ("docx4j_py.docprops.dc", "Coverage"),
    "Creator": ("docx4j_py.docprops.dc", "Creator"),
    "DcDate": ("docx4j_py.docprops.dc", "Date"),
    "Description": ("docx4j_py.docprops.dc", "Description"),
    "Format": ("docx4j_py.docprops.dc", "Format"),
    "Identifier": ("docx4j_py.docprops.dc", "Identifier"),
    "Language": ("docx4j_py.docprops.dc", "Language"),
    "Publisher": ("docx4j_py.docprops.dc", "Publisher"),
    "Relation": ("docx4j_py.docprops.dc", "Relation"),
    "Rights": ("docx4j_py.docprops.dc", "Rights"),
    "Source": ("docx4j_py.docprops.dc", "Source"),
    "Subject": ("docx4j_py.docprops.dc", "Subject"),
    "Title": ("docx4j_py.docprops.dc", "Title"),
    "Type": ("docx4j_py.docprops.dc", "Type"),
    "DcmitypeDcmitype": ("docx4j_py.docprops.dcmitype", "DCMIType"),
    "Box": ("docx4j_py.docprops.dcterms", "Box"),
    "DctermsDcmitype": ("docx4j_py.docprops.dcterms", "DCMIType"),
    "DDC": ("docx4j_py.docprops.dcterms", "DDC"),
    "ElementOrRefinementContainer": ("docx4j_py.docprops.dcterms", "ElementOrRefinementContainer"),
    "IMT": ("docx4j_py.docprops.dcterms", "IMT"),
    "ISO3166": ("docx4j_py.docprops.dcterms", "ISO3166"),
    "ISO6392": ("docx4j_py.docprops.dcterms", "ISO6392"),
    "LCC": ("docx4j_py.docprops.dcterms", "LCC"),
    "LCSH": ("docx4j_py.docprops.dcterms", "LCSH"),
    "MESH": ("docx4j_py.docprops.dcterms", "MESH"),
    "Period": ("docx4j_py.docprops.dcterms", "Period"),
    "Point": ("docx4j_py.docprops.dcterms", "Point"),
    "RFC1766": ("docx4j_py.docprops.dcterms", "RFC1766"),
    "RFC3066": ("docx4j_py.docprops.dcterms", "RFC3066"),
    "DctermsSimpleLiteral": ("docx4j_py.docprops.dcterms", "SimpleLiteral"),
    "TGN": ("docx4j_py.docprops.dcterms", "TGN"),
    "UDC": ("docx4j_py.docprops.dcterms", "UDC"),
    "URI": ("docx4j_py.docprops.dcterms", "URI"),
    "W3CDTF": ("docx4j_py.docprops.dcterms", "W3CDTF"),
    "Abstract": ("docx4j_py.docprops.dcterms", "Abstract"),
    "AccessRights": ("docx4j_py.docprops.dcterms", "AccessRights"),
    "Audience": ("docx4j_py.docprops.dcterms", "Audience"),
    "Available": ("docx4j_py.docprops.dcterms", "Available"),
    "BibliographicCitation": ("docx4j_py.docprops.dcterms", "BibliographicCitation"),
    "ConformsTo": ("docx4j_py.docprops.dcterms", "ConformsTo"),
    "Created": ("docx4j_py.docprops.dcterms", "Created"),
    "DateAccepted": ("docx4j_py.docprops.dcterms", "DateAccepted"),
    "DateCopyrighted": ("docx4j_py.docprops.dcterms", "DateCopyrighted"),
    "DateSubmitted": ("docx4j_py.docprops.dcterms", "DateSubmitted"),
    "EducationLevel": ("docx4j_py.docprops.dcterms", "EducationLevel"),
    "Extent": ("docx4j_py.docprops.dcterms", "Extent"),
    "HasFormat": ("docx4j_py.docprops.dcterms", "HasFormat"),
    "HasPart": ("docx4j_py.docprops.dcterms", "HasPart"),
    "HasVersion": ("docx4j_py.docprops.dcterms", "HasVersion"),
    "IsFormatOf": ("docx4j_py.docprops.dcterms", "IsFormatOf"),
    "IsPartOf": ("docx4j_py.docprops.dcterms", "IsPartOf"),
    "IsReferencedBy": ("docx4j_py.docprops.dcterms", "IsReferencedBy"),
    "IsReplacedBy": ("docx4j_py.docprops.dcterms", "IsReplacedBy"),
    "IsRequiredBy": ("docx4j_py.docprops.dcterms", "IsRequiredBy"),
    "IsVersionOf": ("docx4j_py.docprops.dcterms", "IsVersionOf"),
    "Issued": ("docx4j_py.docprops.dcterms", "Issued"),
    "Mediator": ("docx4j_py.docprops.dcterms", "Mediator"),
    "Medium": ("docx4j_py.docprops.dcterms", "Medium"),
    "Modified": ("docx4j_py.docprops.dcterms", "Modified"),
    "References": ("docx4j_py.docprops.dcterms", "References"),
    "Replaces": ("docx4j_py.docprops.dcterms", "Replaces"),
    "Requires": ("docx4j_py.docprops.dcterms", "Requires"),
    "Spatial": ("docx4j_py.docprops.dcterms", "Spatial"),
    "TableOfContents": ("docx4j_py.docprops.dcterms", "TableOfContents"),
    "Temporal": ("docx4j_py.docprops.dcterms", "Temporal"),
    "Valid": ("docx4j_py.docprops.dcterms", "Valid"),
    "ExtendedProperties": ("docx4j_py.docprops.extended", "Properties"),
    "PropertiesDigSig": ("docx4j_py.docprops.extended", "PropertiesDigSig"),
    "PropertiesHlinks": ("docx4j_py.docprops.extended", "PropertiesHlinks"),
    "PropertiesHeadingPairs": ("docx4j_py.docprops.extended", "PropertiesHeadingPairs"),
    "PropertiesTitlesOfParts": ("docx4j_py.docprops.extended", "PropertiesTitlesOfParts"),
    "Array1": ("docx4j_py.docprops.variant_types", "Array1"),
    "CtArrayBaseType": ("docx4j_py.docprops.variant_types", "CtArrayBaseType"),
    "CtVectorBaseType": ("docx4j_py.docprops.variant_types", "CtVectorBaseType"),
    "Cf1": ("docx4j_py.docprops.variant_types", "Cf1"),
    "Empty1": ("docx4j_py.docprops.variant_types", "Empty1"),
    "Null1": ("docx4j_py.docprops.variant_types", "Null1"),
    "Variant1": ("docx4j_py.docprops.variant_types", "Variant1"),
    "Vector1": ("docx4j_py.docprops.variant_types", "Vector1"),
    "Vstream1": ("docx4j_py.docprops.variant_types", "Vstream1"),
    "Array": ("docx4j_py.docprops.variant_types", "Array"),
    "Blob": ("docx4j_py.docprops.variant_types", "Blob"),
    "Bool": ("docx4j_py.docprops.variant_types", "Bool"),
    "Bstr": ("docx4j_py.docprops.variant_types", "Bstr"),
    "Cf": ("docx4j_py.docprops.variant_types", "Cf"),
    "Clsid": ("docx4j_py.docprops.variant_types", "Clsid"),
    "Cy": ("docx4j_py.docprops.variant_types", "Cy"),
    "VariantTypesDate": ("docx4j_py.docprops.variant_types", "Date"),
    "DecimalType": ("docx4j_py.docprops.variant_types", "DecimalType"),
    "Empty": ("docx4j_py.docprops.variant_types", "Empty"),
    "Error": ("docx4j_py.docprops.variant_types", "Error"),
    "Filetime": ("docx4j_py.docprops.variant_types", "Filetime"),
    "I1": ("docx4j_py.docprops.variant_types", "I1"),
    "I2": ("docx4j_py.docprops.variant_types", "I2"),
    "I4": ("docx4j_py.docprops.variant_types", "I4"),
    "I8": ("docx4j_py.docprops.variant_types", "I8"),
    "Int": ("docx4j_py.docprops.variant_types", "Int"),
    "Lpstr": ("docx4j_py.docprops.variant_types", "Lpstr"),
    "Lpwstr": ("docx4j_py.docprops.variant_types", "Lpwstr"),
    "Null": ("docx4j_py.docprops.variant_types", "Null"),
    "Oblob": ("docx4j_py.docprops.variant_types", "Oblob"),
    "Ostorage": ("docx4j_py.docprops.variant_types", "Ostorage"),
    "Ostream": ("docx4j_py.docprops.variant_types", "Ostream"),
    "R4": ("docx4j_py.docprops.variant_types", "R4"),
    "R8": ("docx4j_py.docprops.variant_types", "R8"),
    "Storage": ("docx4j_py.docprops.variant_types", "Storage"),
    "Stream": ("docx4j_py.docprops.variant_types", "Stream"),
    "Ui1": ("docx4j_py.docprops.variant_types", "Ui1"),
    "Ui2": ("docx4j_py.docprops.variant_types", "Ui2"),
    "Ui4": ("docx4j_py.docprops.variant_types", "Ui4"),
    "Ui8": ("docx4j_py.docprops.variant_types", "Ui8"),
    "Uint": ("docx4j_py.docprops.variant_types", "Uint"),
    "Variant": ("docx4j_py.docprops.variant_types", "Variant"),
    "Vector": ("docx4j_py.docprops.variant_types", "Vector"),
    "Vstream": ("docx4j_py.docprops.variant_types", "Vstream"),
}


def __getattr__(name: str) -> object:
    """Import a re-exported class on first use."""
    target = __lazy_imports__.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    value = getattr(import_module(target[0]), target[1])
    globals()[name] = value
    return value
