"""``el`` for the http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/dml_locked_canvas.json``, which a human reviews.

    >>> from docx4j_py.dml.locked_canvas import el
    >>> el.lockedCanvas()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.locked_canvas import (
    LockedCanvas,
)

__NAMESPACE__ = "http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas"

def lockedCanvas(**kwargs: Any) -> LockedCanvas:
    """``{http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas}lockedCanvas`` -> :class:`docx4j_py.dml.locked_canvas.LockedCanvas`."""
    return LockedCanvas(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas}lockedCanvas": LockedCanvas,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "lockedCanvas": LockedCanvas,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    LockedCanvas: "{http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas}lockedCanvas",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "lockedCanvas",
]
