from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from docx4j_py.oart.animation_2018 import (
        CTAnimationProperties,
        STIndefinite,
    )
    from docx4j_py.oart.animation_model3d_2018 import (
        CTEmbeddedAnimation,
        CTPosterFrame,
        EmbedAnim,
        PosterFrame,
    )
    from docx4j_py.oart.chart_2007 import (
        CTBooleanFalse as Type2007CtbooleanFalse,
    )
    from docx4j_py.oart.chart_2007 import (
        CTBooleanTrue,
        CTInvertSolidFillFmt,
        CTPivotOptions,
        CTStyle,
        InvertSolidFillFmt,
        PivotOptions,
    )
    from docx4j_py.oart.chart_2007 import (
        Style as Chart2007Style,
    )
    from docx4j_py.oart.chart_2012 import (
        AutoCat,
        CTChartLines,
        CTDataLabelFieldTable,
        CTDataLabelFieldTableEntry,
        CTFilteredAreaSer,
        CTFilteredBarSer,
        CTFilteredBubbleSer,
        CTFilteredCategoryTitle,
        CTFilteredLineSer,
        CTFilteredPieSer,
        CTFilteredRadarSer,
        CTFilteredScatterSer,
        CTFilteredSeriesTitle,
        CTFilteredSurfaceSer,
        CTFormulaRef,
        CTFullRef,
        CTLayout,
        CTLevelRef,
        CTNumFmt,
        CTPivotSource,
        CTSeriesDataLabelsRange,
        CTTx,
        DatalabelsRange,
        DlblFieldTable,
        FilteredAreaSeries,
        FilteredBarSeries,
        FilteredBubbleSeries,
        FilteredCategoryTitle,
        FilteredLineSeries,
        FilteredPieSeries,
        FilteredRadarSeries,
        FilteredScatterSeries,
        FilteredSeriesTitle,
        FilteredSurfaceSeries,
        FormulaRef,
        FullRef,
        LevelRef,
        ShowDataLabelsRange,
        ShowLeaderLines,
    )
    from docx4j_py.oart.chart_2012 import (
        CategoryFilterExceptions as Type2012CategoryFilterExceptions,
    )
    from docx4j_py.oart.chart_2012 import (
        CTBoolean as Chart2012Ctboolean,
    )
    from docx4j_py.oart.chart_2012 import (
        CTCategoryFilterException as Type2012CtcategoryFilterException,
    )
    from docx4j_py.oart.chart_2012 import (
        CTCategoryFilterExceptions as Type2012CtcategoryFilterExceptions,
    )
    from docx4j_py.oart.chart_2012 import (
        CTShapeProperties as Type2012CtshapeProperties,
    )
    from docx4j_py.oart.chart_2014 import (
        Bubble3D,
        CTChartDataPointUniqueIDMap,
        CTChartDataPointUniqueIDMapEntry,
        CTChartUniqueID,
        CTDLbl,
        CTLiteralDataChart,
        CTMarker,
        CTMultiLvlStrFilteredLiteralCache,
        CTNumFilteredLiteralCache,
        CTPivotOptions16,
        CTStrFilteredLiteralCache,
        CTUnsignedInt,
        Datapointuniqueidmap,
        PivotOptions16,
    )
    from docx4j_py.oart.chart_2014 import (
        CategoryFilterExceptions as Type2014CategoryFilterExceptions,
    )
    from docx4j_py.oart.chart_2014 import (
        CTBoolean as Type2014Ctboolean,
    )
    from docx4j_py.oart.chart_2014 import (
        CTBooleanFalse as Type2014CtbooleanFalse,
    )
    from docx4j_py.oart.chart_2014 import (
        CTCategoryFilterException as Type2014CtcategoryFilterException,
    )
    from docx4j_py.oart.chart_2014 import (
        CTCategoryFilterExceptions as Type2014CtcategoryFilterExceptions,
    )
    from docx4j_py.oart.chart_2014 import (
        CTShapeProperties as Type2014CtshapeProperties,
    )
    from docx4j_py.oart.chart_2017_03 import (
        CTBooleanFalse as Type201703CtbooleanFalse,
    )
    from docx4j_py.oart.chart_2017_03 import (
        CTDataDisplayOptions16,
        DataDisplayOptions16,
    )
    from docx4j_py.oart.chart_ac_2014 import MultiLvlStrLit
    from docx4j_py.oart.chart_drawing_2010 import (
        ContentPart as ChartDrawingContentPart,
    )
    from docx4j_py.oart.chart_drawing_2010 import (
        CTApplicationNonVisualDrawingProps as ChartCtapplicationNonVisualDrawingProps,
    )
    from docx4j_py.oart.chart_drawing_2010 import (
        CTContentPart as ChartCtcontentPart,
    )
    from docx4j_py.oart.chart_drawing_2010 import (
        CTContentPartNonVisual as ChartCtcontentPartNonVisual,
    )
    from docx4j_py.oart.chart_style_2012 import (
        ChartStyle,
        ColorStyle,
        CTChartStyle,
        CTColorStyle,
        CTColorStyleVariation,
        CTFontReference,
        CTMarkerLayout,
        CTStyleColor,
        CTStyleEntry,
        CTStyleReference,
        STColorStyleMethodEnum,
        STMarkerStyle,
        STStyleColorEnum,
        STStyleEntryModifierEnum,
        STStyleReferenceModifierEnum,
    )
    from docx4j_py.oart.chartex_2014 import (
        Chart,
        ChartSpace,
        CTAddress,
        CTAggregation,
        CTAxis,
        CTAxisId,
        CTAxisTitle,
        CTAxisUnits,
        CTAxisUnitsLabel,
        CTBinning,
        CTCategoryAxisScaling,
        CTChart,
        CTChartData,
        CTChartSpace,
        CTChartTitle,
        CTClear,
        CTCopyrights,
        CTData,
        CTDataId,
        CTDataLabel,
        CTDataLabelHidden,
        CTDataLabels,
        CTDataLabelVisibilities,
        CTDataPoint,
        CTExtension,
        CTExtensionList,
        CTExternalData,
        CTExtremeValueColorPosition,
        CTFormatOverride,
        CTFormatOverrides,
        CTFormula,
        CTGeoCache,
        CTGeoChildEntities,
        CTGeoChildEntitiesQuery,
        CTGeoChildEntitiesQueryResult,
        CTGeoChildEntitiesQueryResults,
        CTGeoChildTypes,
        CTGeoData,
        CTGeoDataEntityQuery,
        CTGeoDataEntityQueryResult,
        CTGeoDataEntityQueryResults,
        CTGeoDataPointQuery,
        CTGeoDataPointToEntityQuery,
        CTGeoDataPointToEntityQueryResult,
        CTGeoDataPointToEntityQueryResults,
        CTGeoEntity,
        CTGeography,
        CTGeoHierarchyEntity,
        CTGeoLocation,
        CTGeoLocationQuery,
        CTGeoLocationQueryResult,
        CTGeoLocationQueryResults,
        CTGeoLocations,
        CTGeoParentEntitiesQuery,
        CTGeoParentEntitiesQueryResult,
        CTGeoParentEntitiesQueryResults,
        CTGeoParentEntity,
        CTGeoPolygon,
        CTGeoPolygons,
        CTGridlines,
        CTHeaderFooter,
        CTLegend,
        CTNumberColorPosition,
        CTNumberFormat,
        CTNumericDimension,
        CTNumericLevel,
        CTNumericValue,
        CTPageMargins,
        CTPageSetup,
        CTParentLabelLayout,
        CTPercentageColorPosition,
        CTPlotArea,
        CTPlotAreaRegion,
        CTPlotSurface,
        CTPrintSettings,
        CTRegionLabelLayout,
        CTRelId,
        CTSeries,
        CTSeriesElementVisibilities,
        CTSeriesLayoutProperties,
        CTStatistics,
        CTStringDimension,
        CTStringLevel,
        CTStringValue,
        CTSubtotalIndex,
        CTSubtotals,
        CTText,
        CTTextData,
        CTTickLabels,
        CTTickMarks,
        CTValueAxisScaling,
        CTValueColorEndPosition,
        CTValueColorMiddlePosition,
        CTValueColorPositions,
        CTValueColors,
        F,
        Nf,
        STAxisUnit,
        STDataLabelPos,
        StDoubleOrAutomaticValue,
        STEntityType,
        STFormulaDirection,
        StGapWidthRatioValue,
        STGeoMappingLevel,
        STGeoProjectionType,
        STIntervalClosedSide,
        STNumericDimensionType,
        STPageOrientation,
        STParentLabelLayout,
        STPosAlign,
        STQuartileMethod,
        STRegionLabelLayout,
        STSeriesLayout,
        STSidePos,
        STStringDimensionType,
        STTickMarksType,
        StValueAxisUnitValue,
    )
    from docx4j_py.oart.command_2013 import (
        CTChangesData,
        CTConnectorChanges,
        CTConnectorMoniker,
        CTConnectorMonikerList,
        CTGraphicFrameChanges,
        CTGraphicFrameMoniker,
        CTGraphicFrameMonikerList,
        CTGroupShapeChanges,
        CTGroupShapeMoniker,
        CTGroupShapeMonikerList,
        CTInkChanges,
        CTInkMoniker,
        CTInkMonikerList,
        CTPictureChanges,
        CTPictureMoniker,
        CTPictureMonikerList,
        CTShapeChanges,
        CTShapeMoniker,
        CTShapeMonikerList,
        CxnSpMkLst,
        GraphicFrameMkLst,
        GrpMkLst,
        InkMkLst,
        PicMkLst,
        SpMkLst,
        STConnectorChangeBit,
        STGraphicFrameChangeBit,
        STGroupShapeChangeBit,
        STInkChangeBit,
        STPictureChangeBit,
        STShapeChangeBit,
    )
    from docx4j_py.oart.decorative_2017 import (
        CTDecorative,
        Decorative,
    )
    from docx4j_py.oart.diagram_2008 import (
        CTDataModelExtBlock,
        CTDrawing,
        CTGroupShape,
        CTGroupShapeNonVisual,
        CTShape,
        CTShapeNonVisual,
        DataModelExt,
        Drawing,
    )
    from docx4j_py.oart.diagram_2010 import (
        CTBoolean as Diagram2010Ctboolean,
    )
    from docx4j_py.oart.diagram_2010 import (
        CTNonVisualDrawingProps,
        RecolorImg,
    )
    from docx4j_py.oart.diagram_2016_11 import (
        AutoBuNodeInfoLst,
        CTDiagramAutoBullet,
        CTNumberDiagramInfo,
        CTNumberDiagramInfoList,
        STSTorageType,
    )
    from docx4j_py.oart.diagram_2016_12 import (
        LstStyle,
        SpPr,
    )
    from docx4j_py.oart.hyperlink_color_2018 import (
        CTHyperlinkColor,
        HlinkClr,
        STHyperlinkColor,
    )
    from docx4j_py.oart.ink_action_2014 import (
        Actions,
        CTAction,
        CTActionData,
        CTActionDataGroup,
        CTActionGroup,
        CTActionProperty,
        CTActions,
        STActionTypeReserved,
        STDataNameReserved,
        STPropertyNameReserved,
        STPropertyValueReserved,
    )
    from docx4j_py.oart.main_2010 import (
        CameraTool,
        CompatExt,
        CTCameraTool,
        CTCompatExt,
        CTContentPartLocking,
        CTEffectProperties,
        CTFillProperties,
        CTGvmlContentPart,
        CTGvmlContentPartNonVisual,
        CTIsGvmlCanvas,
        CTLineProperties,
        CTNonVisualInkContentPartProperties,
        CTPhoto,
        CTPictureEffect,
        CTPictureEffectBackgroundRemoval,
        CTPictureEffectBackgroundRemovalBackgroundMark,
        CTPictureEffectBackgroundRemovalForegroundMark,
        CTPictureEffectBlur,
        CTPictureEffectBrightnessContrast,
        CTPictureEffectCement,
        CTPictureEffectChalkSketch,
        CTPictureEffectColorTemperature,
        CTPictureEffectCrisscrossEtching,
        CTPictureEffectCutout,
        CTPictureEffectFilmGrain,
        CTPictureEffectGlass,
        CTPictureEffectGlowDiffused,
        CTPictureEffectGlowEdges,
        CTPictureEffectLightScreen,
        CTPictureEffectLineDrawing,
        CTPictureEffectMarker,
        CTPictureEffectMosiaicBubbles,
        CTPictureEffectPaintBrush,
        CTPictureEffectPaintStrokes,
        CTPictureEffectPastelsSmooth,
        CTPictureEffectPencilGrayscale,
        CTPictureEffectPencilSketch,
        CTPictureEffectPhotocopy,
        CTPictureEffectPlasticWrap,
        CTPictureEffectSaturation,
        CTPictureEffectSharpenSoften,
        CTPictureEffectTexturizer,
        CTPictureEffectWatercolorSponge,
        CTPictureLayer,
        CTScene3D,
        CTShadowObscured,
        CTShape3D,
        CTTextMath,
        CTUseLocalDpi,
        ImgProps,
        IsCanvas,
        M,
        ShadowObscured,
        UseLocalDpi,
    )
    from docx4j_py.oart.main_2010 import (
        ContentPart as MainContentPart,
    )
    from docx4j_py.oart.main_2012 import (
        BackgroundPr,
        CTBackgroundPr,
        CTNonVisualGroupProps,
        CTObjectPr,
        CTSignatureLine,
        NonVisualGroupProps,
        ObjectPr,
        SignatureLine,
        StTargetScreenSz,
    )
    from docx4j_py.oart.main_2014 import (
        ColId,
        CreationId,
        CTConnectableReferences,
        CTCreationId,
        CTIdentifier,
        CTPredecessorDrawingElementReference,
        CxnDerefs,
        PredDeref,
        RowId,
    )
    from docx4j_py.oart.main_2016_11 import (
        CTPictureAttributionSourceURL,
        PicAttrSrcUrl,
    )
    from docx4j_py.oart.model3d_2017 import (
        CTAmbientLight,
        CTDirectionalLight,
        CTModel3D,
        CTModel3DCamera,
        CTModel3DRaster,
        CTModel3DTransform,
        CTObjectViewport,
        CTOrthographicProjection,
        CTPerspectiveProjection,
        CTPointLight,
        CTPositiveRatio,
        CTRotate3D,
        CTScale3D,
        CTSpotLight,
        CTUnknownLight,
        CTWindowViewport,
        Model3D,
    )
    from docx4j_py.oart.picture_2010 import (
        ExtLst,
    )
    from docx4j_py.oart.picture_2010 import (
        Style as Picture2010Style,
    )
    from docx4j_py.oart.spreadsheet_drawing_2010 import (
        ContentPart as SpreadsheetContentPart,
    )
    from docx4j_py.oart.spreadsheet_drawing_2010 import (
        CTApplicationNonVisualDrawingProps as SpreadsheetCtapplicationNonVisualDrawingProps,
    )
    from docx4j_py.oart.spreadsheet_drawing_2010 import (
        CTContentPart as SpreadsheetCtcontentPart,
    )
    from docx4j_py.oart.spreadsheet_drawing_2010 import (
        CTContentPartNonVisual as SpreadsheetCtcontentPartNonVisual,
    )
    from docx4j_py.oart.svg_2016 import (
        CTSVGBlip,
        SvgBlip,
    )
    from docx4j_py.oart.theme_2012 import (
        CTThemeFamily,
        ThemeFamily,
    )

__all__ = [
    "CTAnimationProperties",
    "STIndefinite",
    "CTEmbeddedAnimation",
    "CTPosterFrame",
    "EmbedAnim",
    "PosterFrame",
    "Type2007CtbooleanFalse",
    "CTBooleanTrue",
    "CTInvertSolidFillFmt",
    "CTPivotOptions",
    "CTStyle",
    "InvertSolidFillFmt",
    "PivotOptions",
    "Chart2007Style",
    "Chart2012Ctboolean",
    "Type2012CtcategoryFilterException",
    "Type2012CtcategoryFilterExceptions",
    "CTChartLines",
    "CTDataLabelFieldTable",
    "CTDataLabelFieldTableEntry",
    "CTFilteredAreaSer",
    "CTFilteredBarSer",
    "CTFilteredBubbleSer",
    "CTFilteredCategoryTitle",
    "CTFilteredLineSer",
    "CTFilteredPieSer",
    "CTFilteredRadarSer",
    "CTFilteredScatterSer",
    "CTFilteredSeriesTitle",
    "CTFilteredSurfaceSer",
    "CTFormulaRef",
    "CTFullRef",
    "CTLayout",
    "CTLevelRef",
    "CTNumFmt",
    "CTPivotSource",
    "CTSeriesDataLabelsRange",
    "Type2012CtshapeProperties",
    "CTTx",
    "AutoCat",
    "Type2012CategoryFilterExceptions",
    "DatalabelsRange",
    "DlblFieldTable",
    "FilteredAreaSeries",
    "FilteredBarSeries",
    "FilteredBubbleSeries",
    "FilteredCategoryTitle",
    "FilteredLineSeries",
    "FilteredPieSeries",
    "FilteredRadarSeries",
    "FilteredScatterSeries",
    "FilteredSeriesTitle",
    "FilteredSurfaceSeries",
    "FormulaRef",
    "FullRef",
    "LevelRef",
    "ShowDataLabelsRange",
    "ShowLeaderLines",
    "Type2014Ctboolean",
    "Type2014CtbooleanFalse",
    "Type2014CtcategoryFilterException",
    "Type2014CtcategoryFilterExceptions",
    "CTChartDataPointUniqueIDMap",
    "CTChartDataPointUniqueIDMapEntry",
    "CTChartUniqueID",
    "CTDLbl",
    "CTLiteralDataChart",
    "CTMarker",
    "CTMultiLvlStrFilteredLiteralCache",
    "CTNumFilteredLiteralCache",
    "CTPivotOptions16",
    "Type2014CtshapeProperties",
    "CTStrFilteredLiteralCache",
    "CTUnsignedInt",
    "Bubble3D",
    "Type2014CategoryFilterExceptions",
    "Datapointuniqueidmap",
    "PivotOptions16",
    "Type201703CtbooleanFalse",
    "CTDataDisplayOptions16",
    "DataDisplayOptions16",
    "MultiLvlStrLit",
    "ChartCtapplicationNonVisualDrawingProps",
    "ChartCtcontentPart",
    "ChartCtcontentPartNonVisual",
    "ChartDrawingContentPart",
    "CTChartStyle",
    "CTColorStyle",
    "CTColorStyleVariation",
    "CTFontReference",
    "CTMarkerLayout",
    "CTStyleColor",
    "CTStyleEntry",
    "CTStyleReference",
    "STColorStyleMethodEnum",
    "STMarkerStyle",
    "STStyleColorEnum",
    "STStyleEntryModifierEnum",
    "STStyleReferenceModifierEnum",
    "ChartStyle",
    "ColorStyle",
    "CTAddress",
    "CTAggregation",
    "CTAxis",
    "CTAxisId",
    "CTAxisTitle",
    "CTAxisUnits",
    "CTAxisUnitsLabel",
    "CTBinning",
    "CTCategoryAxisScaling",
    "CTChart",
    "CTChartData",
    "CTChartSpace",
    "CTChartTitle",
    "CTClear",
    "CTCopyrights",
    "CTData",
    "CTDataId",
    "CTDataLabel",
    "CTDataLabelHidden",
    "CTDataLabelVisibilities",
    "CTDataLabels",
    "CTDataPoint",
    "CTExtension",
    "CTExtensionList",
    "CTExternalData",
    "CTExtremeValueColorPosition",
    "CTFormatOverride",
    "CTFormatOverrides",
    "CTFormula",
    "CTGeoCache",
    "CTGeoChildEntities",
    "CTGeoChildEntitiesQuery",
    "CTGeoChildEntitiesQueryResult",
    "CTGeoChildEntitiesQueryResults",
    "CTGeoChildTypes",
    "CTGeoData",
    "CTGeoDataEntityQuery",
    "CTGeoDataEntityQueryResult",
    "CTGeoDataEntityQueryResults",
    "CTGeoDataPointQuery",
    "CTGeoDataPointToEntityQuery",
    "CTGeoDataPointToEntityQueryResult",
    "CTGeoDataPointToEntityQueryResults",
    "CTGeoEntity",
    "CTGeoHierarchyEntity",
    "CTGeoLocation",
    "CTGeoLocationQuery",
    "CTGeoLocationQueryResult",
    "CTGeoLocationQueryResults",
    "CTGeoLocations",
    "CTGeoParentEntitiesQuery",
    "CTGeoParentEntitiesQueryResult",
    "CTGeoParentEntitiesQueryResults",
    "CTGeoParentEntity",
    "CTGeoPolygon",
    "CTGeoPolygons",
    "CTGeography",
    "CTGridlines",
    "CTHeaderFooter",
    "CTLegend",
    "CTNumberColorPosition",
    "CTNumberFormat",
    "CTNumericDimension",
    "CTNumericLevel",
    "CTNumericValue",
    "CTPageMargins",
    "CTPageSetup",
    "CTParentLabelLayout",
    "CTPercentageColorPosition",
    "CTPlotArea",
    "CTPlotAreaRegion",
    "CTPlotSurface",
    "CTPrintSettings",
    "CTRegionLabelLayout",
    "CTRelId",
    "CTSeries",
    "CTSeriesElementVisibilities",
    "CTSeriesLayoutProperties",
    "CTStatistics",
    "CTStringDimension",
    "CTStringLevel",
    "CTStringValue",
    "CTSubtotalIndex",
    "CTSubtotals",
    "CTText",
    "CTTextData",
    "CTTickLabels",
    "CTTickMarks",
    "CTValueAxisScaling",
    "CTValueColorEndPosition",
    "CTValueColorMiddlePosition",
    "CTValueColorPositions",
    "CTValueColors",
    "STAxisUnit",
    "STDataLabelPos",
    "STEntityType",
    "STFormulaDirection",
    "STGeoMappingLevel",
    "STGeoProjectionType",
    "STIntervalClosedSide",
    "STNumericDimensionType",
    "STPageOrientation",
    "STParentLabelLayout",
    "STPosAlign",
    "STQuartileMethod",
    "STRegionLabelLayout",
    "STSeriesLayout",
    "STSidePos",
    "STStringDimensionType",
    "STTickMarksType",
    "StDoubleOrAutomaticValue",
    "StGapWidthRatioValue",
    "StValueAxisUnitValue",
    "Chart",
    "ChartSpace",
    "F",
    "Nf",
    "CTChangesData",
    "CTConnectorChanges",
    "CTConnectorMoniker",
    "CTConnectorMonikerList",
    "CTGraphicFrameChanges",
    "CTGraphicFrameMoniker",
    "CTGraphicFrameMonikerList",
    "CTGroupShapeChanges",
    "CTGroupShapeMoniker",
    "CTGroupShapeMonikerList",
    "CTInkChanges",
    "CTInkMoniker",
    "CTInkMonikerList",
    "CTPictureChanges",
    "CTPictureMoniker",
    "CTPictureMonikerList",
    "CTShapeChanges",
    "CTShapeMoniker",
    "CTShapeMonikerList",
    "STConnectorChangeBit",
    "STGraphicFrameChangeBit",
    "STGroupShapeChangeBit",
    "STInkChangeBit",
    "STPictureChangeBit",
    "STShapeChangeBit",
    "CxnSpMkLst",
    "GraphicFrameMkLst",
    "GrpMkLst",
    "InkMkLst",
    "PicMkLst",
    "SpMkLst",
    "CTDecorative",
    "Decorative",
    "CTDataModelExtBlock",
    "CTDrawing",
    "CTGroupShape",
    "CTGroupShapeNonVisual",
    "CTShape",
    "CTShapeNonVisual",
    "DataModelExt",
    "Drawing",
    "Diagram2010Ctboolean",
    "CTNonVisualDrawingProps",
    "RecolorImg",
    "CTDiagramAutoBullet",
    "CTNumberDiagramInfo",
    "CTNumberDiagramInfoList",
    "STSTorageType",
    "AutoBuNodeInfoLst",
    "LstStyle",
    "SpPr",
    "CTHyperlinkColor",
    "STHyperlinkColor",
    "HlinkClr",
    "CTAction",
    "CTActionData",
    "CTActionDataGroup",
    "CTActionGroup",
    "CTActionProperty",
    "CTActions",
    "STActionTypeReserved",
    "STDataNameReserved",
    "STPropertyNameReserved",
    "STPropertyValueReserved",
    "Actions",
    "CTCameraTool",
    "CTCompatExt",
    "CTContentPartLocking",
    "CTEffectProperties",
    "CTFillProperties",
    "CTGvmlContentPart",
    "CTGvmlContentPartNonVisual",
    "CTIsGvmlCanvas",
    "CTLineProperties",
    "CTNonVisualInkContentPartProperties",
    "CTPhoto",
    "CTPictureEffect",
    "CTPictureEffectBackgroundRemoval",
    "CTPictureEffectBackgroundRemovalBackgroundMark",
    "CTPictureEffectBackgroundRemovalForegroundMark",
    "CTPictureEffectBlur",
    "CTPictureEffectBrightnessContrast",
    "CTPictureEffectCement",
    "CTPictureEffectChalkSketch",
    "CTPictureEffectColorTemperature",
    "CTPictureEffectCrisscrossEtching",
    "CTPictureEffectCutout",
    "CTPictureEffectFilmGrain",
    "CTPictureEffectGlass",
    "CTPictureEffectGlowDiffused",
    "CTPictureEffectGlowEdges",
    "CTPictureEffectLightScreen",
    "CTPictureEffectLineDrawing",
    "CTPictureEffectMarker",
    "CTPictureEffectMosiaicBubbles",
    "CTPictureEffectPaintBrush",
    "CTPictureEffectPaintStrokes",
    "CTPictureEffectPastelsSmooth",
    "CTPictureEffectPencilGrayscale",
    "CTPictureEffectPencilSketch",
    "CTPictureEffectPhotocopy",
    "CTPictureEffectPlasticWrap",
    "CTPictureEffectSaturation",
    "CTPictureEffectSharpenSoften",
    "CTPictureEffectTexturizer",
    "CTPictureEffectWatercolorSponge",
    "CTPictureLayer",
    "CTScene3D",
    "CTShadowObscured",
    "CTShape3D",
    "CTTextMath",
    "CTUseLocalDpi",
    "CameraTool",
    "CompatExt",
    "MainContentPart",
    "ImgProps",
    "IsCanvas",
    "M",
    "ShadowObscured",
    "UseLocalDpi",
    "CTBackgroundPr",
    "CTNonVisualGroupProps",
    "CTObjectPr",
    "CTSignatureLine",
    "StTargetScreenSz",
    "BackgroundPr",
    "NonVisualGroupProps",
    "ObjectPr",
    "SignatureLine",
    "CTConnectableReferences",
    "CTCreationId",
    "CTIdentifier",
    "CTPredecessorDrawingElementReference",
    "ColId",
    "CreationId",
    "CxnDerefs",
    "PredDeref",
    "RowId",
    "CTPictureAttributionSourceURL",
    "PicAttrSrcUrl",
    "CTAmbientLight",
    "CTDirectionalLight",
    "CTModel3D",
    "CTModel3DCamera",
    "CTModel3DRaster",
    "CTModel3DTransform",
    "CTObjectViewport",
    "CTOrthographicProjection",
    "CTPerspectiveProjection",
    "CTPointLight",
    "CTPositiveRatio",
    "CTRotate3D",
    "CTScale3D",
    "CTSpotLight",
    "CTUnknownLight",
    "CTWindowViewport",
    "Model3D",
    "ExtLst",
    "Picture2010Style",
    "SpreadsheetCtapplicationNonVisualDrawingProps",
    "SpreadsheetCtcontentPart",
    "SpreadsheetCtcontentPartNonVisual",
    "SpreadsheetContentPart",
    "CTSVGBlip",
    "SvgBlip",
    "CTThemeFamily",
    "ThemeFamily",
]

# The re-exports above are resolved on first use, so that importing this
# package never forces a module of it to be imported before the modules it
# depends on.
__lazy_imports__ = {
    "CTAnimationProperties": ("docx4j_py.oart.animation_2018", "CTAnimationProperties"),
    "STIndefinite": ("docx4j_py.oart.animation_2018", "STIndefinite"),
    "CTEmbeddedAnimation": ("docx4j_py.oart.animation_model3d_2018", "CTEmbeddedAnimation"),
    "CTPosterFrame": ("docx4j_py.oart.animation_model3d_2018", "CTPosterFrame"),
    "EmbedAnim": ("docx4j_py.oart.animation_model3d_2018", "EmbedAnim"),
    "PosterFrame": ("docx4j_py.oart.animation_model3d_2018", "PosterFrame"),
    "Type2007CtbooleanFalse": ("docx4j_py.oart.chart_2007", "CTBooleanFalse"),
    "CTBooleanTrue": ("docx4j_py.oart.chart_2007", "CTBooleanTrue"),
    "CTInvertSolidFillFmt": ("docx4j_py.oart.chart_2007", "CTInvertSolidFillFmt"),
    "CTPivotOptions": ("docx4j_py.oart.chart_2007", "CTPivotOptions"),
    "CTStyle": ("docx4j_py.oart.chart_2007", "CTStyle"),
    "InvertSolidFillFmt": ("docx4j_py.oart.chart_2007", "InvertSolidFillFmt"),
    "PivotOptions": ("docx4j_py.oart.chart_2007", "PivotOptions"),
    "Chart2007Style": ("docx4j_py.oart.chart_2007", "Style"),
    "Chart2012Ctboolean": ("docx4j_py.oart.chart_2012", "CTBoolean"),
    "Type2012CtcategoryFilterException": (
        "docx4j_py.oart.chart_2012",
        "CTCategoryFilterException",
    ),
    "Type2012CtcategoryFilterExceptions": (
        "docx4j_py.oart.chart_2012",
        "CTCategoryFilterExceptions",
    ),
    "CTChartLines": ("docx4j_py.oart.chart_2012", "CTChartLines"),
    "CTDataLabelFieldTable": ("docx4j_py.oart.chart_2012", "CTDataLabelFieldTable"),
    "CTDataLabelFieldTableEntry": ("docx4j_py.oart.chart_2012", "CTDataLabelFieldTableEntry"),
    "CTFilteredAreaSer": ("docx4j_py.oart.chart_2012", "CTFilteredAreaSer"),
    "CTFilteredBarSer": ("docx4j_py.oart.chart_2012", "CTFilteredBarSer"),
    "CTFilteredBubbleSer": ("docx4j_py.oart.chart_2012", "CTFilteredBubbleSer"),
    "CTFilteredCategoryTitle": ("docx4j_py.oart.chart_2012", "CTFilteredCategoryTitle"),
    "CTFilteredLineSer": ("docx4j_py.oart.chart_2012", "CTFilteredLineSer"),
    "CTFilteredPieSer": ("docx4j_py.oart.chart_2012", "CTFilteredPieSer"),
    "CTFilteredRadarSer": ("docx4j_py.oart.chart_2012", "CTFilteredRadarSer"),
    "CTFilteredScatterSer": ("docx4j_py.oart.chart_2012", "CTFilteredScatterSer"),
    "CTFilteredSeriesTitle": ("docx4j_py.oart.chart_2012", "CTFilteredSeriesTitle"),
    "CTFilteredSurfaceSer": ("docx4j_py.oart.chart_2012", "CTFilteredSurfaceSer"),
    "CTFormulaRef": ("docx4j_py.oart.chart_2012", "CTFormulaRef"),
    "CTFullRef": ("docx4j_py.oart.chart_2012", "CTFullRef"),
    "CTLayout": ("docx4j_py.oart.chart_2012", "CTLayout"),
    "CTLevelRef": ("docx4j_py.oart.chart_2012", "CTLevelRef"),
    "CTNumFmt": ("docx4j_py.oart.chart_2012", "CTNumFmt"),
    "CTPivotSource": ("docx4j_py.oart.chart_2012", "CTPivotSource"),
    "CTSeriesDataLabelsRange": ("docx4j_py.oart.chart_2012", "CTSeriesDataLabelsRange"),
    "Type2012CtshapeProperties": ("docx4j_py.oart.chart_2012", "CTShapeProperties"),
    "CTTx": ("docx4j_py.oart.chart_2012", "CTTx"),
    "AutoCat": ("docx4j_py.oart.chart_2012", "AutoCat"),
    "Type2012CategoryFilterExceptions": ("docx4j_py.oart.chart_2012", "CategoryFilterExceptions"),
    "DatalabelsRange": ("docx4j_py.oart.chart_2012", "DatalabelsRange"),
    "DlblFieldTable": ("docx4j_py.oart.chart_2012", "DlblFieldTable"),
    "FilteredAreaSeries": ("docx4j_py.oart.chart_2012", "FilteredAreaSeries"),
    "FilteredBarSeries": ("docx4j_py.oart.chart_2012", "FilteredBarSeries"),
    "FilteredBubbleSeries": ("docx4j_py.oart.chart_2012", "FilteredBubbleSeries"),
    "FilteredCategoryTitle": ("docx4j_py.oart.chart_2012", "FilteredCategoryTitle"),
    "FilteredLineSeries": ("docx4j_py.oart.chart_2012", "FilteredLineSeries"),
    "FilteredPieSeries": ("docx4j_py.oart.chart_2012", "FilteredPieSeries"),
    "FilteredRadarSeries": ("docx4j_py.oart.chart_2012", "FilteredRadarSeries"),
    "FilteredScatterSeries": ("docx4j_py.oart.chart_2012", "FilteredScatterSeries"),
    "FilteredSeriesTitle": ("docx4j_py.oart.chart_2012", "FilteredSeriesTitle"),
    "FilteredSurfaceSeries": ("docx4j_py.oart.chart_2012", "FilteredSurfaceSeries"),
    "FormulaRef": ("docx4j_py.oart.chart_2012", "FormulaRef"),
    "FullRef": ("docx4j_py.oart.chart_2012", "FullRef"),
    "LevelRef": ("docx4j_py.oart.chart_2012", "LevelRef"),
    "ShowDataLabelsRange": ("docx4j_py.oart.chart_2012", "ShowDataLabelsRange"),
    "ShowLeaderLines": ("docx4j_py.oart.chart_2012", "ShowLeaderLines"),
    "Type2014Ctboolean": ("docx4j_py.oart.chart_2014", "CTBoolean"),
    "Type2014CtbooleanFalse": ("docx4j_py.oart.chart_2014", "CTBooleanFalse"),
    "Type2014CtcategoryFilterException": (
        "docx4j_py.oart.chart_2014",
        "CTCategoryFilterException",
    ),
    "Type2014CtcategoryFilterExceptions": (
        "docx4j_py.oart.chart_2014",
        "CTCategoryFilterExceptions",
    ),
    "CTChartDataPointUniqueIDMap": ("docx4j_py.oart.chart_2014", "CTChartDataPointUniqueIDMap"),
    "CTChartDataPointUniqueIDMapEntry": (
        "docx4j_py.oart.chart_2014",
        "CTChartDataPointUniqueIDMapEntry",
    ),
    "CTChartUniqueID": ("docx4j_py.oart.chart_2014", "CTChartUniqueID"),
    "CTDLbl": ("docx4j_py.oart.chart_2014", "CTDLbl"),
    "CTLiteralDataChart": ("docx4j_py.oart.chart_2014", "CTLiteralDataChart"),
    "CTMarker": ("docx4j_py.oart.chart_2014", "CTMarker"),
    "CTMultiLvlStrFilteredLiteralCache": (
        "docx4j_py.oart.chart_2014",
        "CTMultiLvlStrFilteredLiteralCache",
    ),
    "CTNumFilteredLiteralCache": ("docx4j_py.oart.chart_2014", "CTNumFilteredLiteralCache"),
    "CTPivotOptions16": ("docx4j_py.oart.chart_2014", "CTPivotOptions16"),
    "Type2014CtshapeProperties": ("docx4j_py.oart.chart_2014", "CTShapeProperties"),
    "CTStrFilteredLiteralCache": ("docx4j_py.oart.chart_2014", "CTStrFilteredLiteralCache"),
    "CTUnsignedInt": ("docx4j_py.oart.chart_2014", "CTUnsignedInt"),
    "Bubble3D": ("docx4j_py.oart.chart_2014", "Bubble3D"),
    "Type2014CategoryFilterExceptions": ("docx4j_py.oart.chart_2014", "CategoryFilterExceptions"),
    "Datapointuniqueidmap": ("docx4j_py.oart.chart_2014", "Datapointuniqueidmap"),
    "PivotOptions16": ("docx4j_py.oart.chart_2014", "PivotOptions16"),
    "Type201703CtbooleanFalse": ("docx4j_py.oart.chart_2017_03", "CTBooleanFalse"),
    "CTDataDisplayOptions16": ("docx4j_py.oart.chart_2017_03", "CTDataDisplayOptions16"),
    "DataDisplayOptions16": ("docx4j_py.oart.chart_2017_03", "DataDisplayOptions16"),
    "MultiLvlStrLit": ("docx4j_py.oart.chart_ac_2014", "MultiLvlStrLit"),
    "ChartCtapplicationNonVisualDrawingProps": (
        "docx4j_py.oart.chart_drawing_2010",
        "CTApplicationNonVisualDrawingProps",
    ),
    "ChartCtcontentPart": ("docx4j_py.oart.chart_drawing_2010", "CTContentPart"),
    "ChartCtcontentPartNonVisual": ("docx4j_py.oart.chart_drawing_2010", "CTContentPartNonVisual"),
    "ChartDrawingContentPart": ("docx4j_py.oart.chart_drawing_2010", "ContentPart"),
    "CTChartStyle": ("docx4j_py.oart.chart_style_2012", "CTChartStyle"),
    "CTColorStyle": ("docx4j_py.oart.chart_style_2012", "CTColorStyle"),
    "CTColorStyleVariation": ("docx4j_py.oart.chart_style_2012", "CTColorStyleVariation"),
    "CTFontReference": ("docx4j_py.oart.chart_style_2012", "CTFontReference"),
    "CTMarkerLayout": ("docx4j_py.oart.chart_style_2012", "CTMarkerLayout"),
    "CTStyleColor": ("docx4j_py.oart.chart_style_2012", "CTStyleColor"),
    "CTStyleEntry": ("docx4j_py.oart.chart_style_2012", "CTStyleEntry"),
    "CTStyleReference": ("docx4j_py.oart.chart_style_2012", "CTStyleReference"),
    "STColorStyleMethodEnum": ("docx4j_py.oart.chart_style_2012", "STColorStyleMethodEnum"),
    "STMarkerStyle": ("docx4j_py.oart.chart_style_2012", "STMarkerStyle"),
    "STStyleColorEnum": ("docx4j_py.oart.chart_style_2012", "STStyleColorEnum"),
    "STStyleEntryModifierEnum": ("docx4j_py.oart.chart_style_2012", "STStyleEntryModifierEnum"),
    "STStyleReferenceModifierEnum": (
        "docx4j_py.oart.chart_style_2012",
        "STStyleReferenceModifierEnum",
    ),
    "ChartStyle": ("docx4j_py.oart.chart_style_2012", "ChartStyle"),
    "ColorStyle": ("docx4j_py.oart.chart_style_2012", "ColorStyle"),
    "CTAddress": ("docx4j_py.oart.chartex_2014", "CTAddress"),
    "CTAggregation": ("docx4j_py.oart.chartex_2014", "CTAggregation"),
    "CTAxis": ("docx4j_py.oart.chartex_2014", "CTAxis"),
    "CTAxisId": ("docx4j_py.oart.chartex_2014", "CTAxisId"),
    "CTAxisTitle": ("docx4j_py.oart.chartex_2014", "CTAxisTitle"),
    "CTAxisUnits": ("docx4j_py.oart.chartex_2014", "CTAxisUnits"),
    "CTAxisUnitsLabel": ("docx4j_py.oart.chartex_2014", "CTAxisUnitsLabel"),
    "CTBinning": ("docx4j_py.oart.chartex_2014", "CTBinning"),
    "CTCategoryAxisScaling": ("docx4j_py.oart.chartex_2014", "CTCategoryAxisScaling"),
    "CTChart": ("docx4j_py.oart.chartex_2014", "CTChart"),
    "CTChartData": ("docx4j_py.oart.chartex_2014", "CTChartData"),
    "CTChartSpace": ("docx4j_py.oart.chartex_2014", "CTChartSpace"),
    "CTChartTitle": ("docx4j_py.oart.chartex_2014", "CTChartTitle"),
    "CTClear": ("docx4j_py.oart.chartex_2014", "CTClear"),
    "CTCopyrights": ("docx4j_py.oart.chartex_2014", "CTCopyrights"),
    "CTData": ("docx4j_py.oart.chartex_2014", "CTData"),
    "CTDataId": ("docx4j_py.oart.chartex_2014", "CTDataId"),
    "CTDataLabel": ("docx4j_py.oart.chartex_2014", "CTDataLabel"),
    "CTDataLabelHidden": ("docx4j_py.oart.chartex_2014", "CTDataLabelHidden"),
    "CTDataLabelVisibilities": ("docx4j_py.oart.chartex_2014", "CTDataLabelVisibilities"),
    "CTDataLabels": ("docx4j_py.oart.chartex_2014", "CTDataLabels"),
    "CTDataPoint": ("docx4j_py.oart.chartex_2014", "CTDataPoint"),
    "CTExtension": ("docx4j_py.oart.chartex_2014", "CTExtension"),
    "CTExtensionList": ("docx4j_py.oart.chartex_2014", "CTExtensionList"),
    "CTExternalData": ("docx4j_py.oart.chartex_2014", "CTExternalData"),
    "CTExtremeValueColorPosition": ("docx4j_py.oart.chartex_2014", "CTExtremeValueColorPosition"),
    "CTFormatOverride": ("docx4j_py.oart.chartex_2014", "CTFormatOverride"),
    "CTFormatOverrides": ("docx4j_py.oart.chartex_2014", "CTFormatOverrides"),
    "CTFormula": ("docx4j_py.oart.chartex_2014", "CTFormula"),
    "CTGeoCache": ("docx4j_py.oart.chartex_2014", "CTGeoCache"),
    "CTGeoChildEntities": ("docx4j_py.oart.chartex_2014", "CTGeoChildEntities"),
    "CTGeoChildEntitiesQuery": ("docx4j_py.oart.chartex_2014", "CTGeoChildEntitiesQuery"),
    "CTGeoChildEntitiesQueryResult": (
        "docx4j_py.oart.chartex_2014",
        "CTGeoChildEntitiesQueryResult",
    ),
    "CTGeoChildEntitiesQueryResults": (
        "docx4j_py.oart.chartex_2014",
        "CTGeoChildEntitiesQueryResults",
    ),
    "CTGeoChildTypes": ("docx4j_py.oart.chartex_2014", "CTGeoChildTypes"),
    "CTGeoData": ("docx4j_py.oart.chartex_2014", "CTGeoData"),
    "CTGeoDataEntityQuery": ("docx4j_py.oart.chartex_2014", "CTGeoDataEntityQuery"),
    "CTGeoDataEntityQueryResult": ("docx4j_py.oart.chartex_2014", "CTGeoDataEntityQueryResult"),
    "CTGeoDataEntityQueryResults": ("docx4j_py.oart.chartex_2014", "CTGeoDataEntityQueryResults"),
    "CTGeoDataPointQuery": ("docx4j_py.oart.chartex_2014", "CTGeoDataPointQuery"),
    "CTGeoDataPointToEntityQuery": ("docx4j_py.oart.chartex_2014", "CTGeoDataPointToEntityQuery"),
    "CTGeoDataPointToEntityQueryResult": (
        "docx4j_py.oart.chartex_2014",
        "CTGeoDataPointToEntityQueryResult",
    ),
    "CTGeoDataPointToEntityQueryResults": (
        "docx4j_py.oart.chartex_2014",
        "CTGeoDataPointToEntityQueryResults",
    ),
    "CTGeoEntity": ("docx4j_py.oart.chartex_2014", "CTGeoEntity"),
    "CTGeoHierarchyEntity": ("docx4j_py.oart.chartex_2014", "CTGeoHierarchyEntity"),
    "CTGeoLocation": ("docx4j_py.oart.chartex_2014", "CTGeoLocation"),
    "CTGeoLocationQuery": ("docx4j_py.oart.chartex_2014", "CTGeoLocationQuery"),
    "CTGeoLocationQueryResult": ("docx4j_py.oart.chartex_2014", "CTGeoLocationQueryResult"),
    "CTGeoLocationQueryResults": ("docx4j_py.oart.chartex_2014", "CTGeoLocationQueryResults"),
    "CTGeoLocations": ("docx4j_py.oart.chartex_2014", "CTGeoLocations"),
    "CTGeoParentEntitiesQuery": ("docx4j_py.oart.chartex_2014", "CTGeoParentEntitiesQuery"),
    "CTGeoParentEntitiesQueryResult": (
        "docx4j_py.oart.chartex_2014",
        "CTGeoParentEntitiesQueryResult",
    ),
    "CTGeoParentEntitiesQueryResults": (
        "docx4j_py.oart.chartex_2014",
        "CTGeoParentEntitiesQueryResults",
    ),
    "CTGeoParentEntity": ("docx4j_py.oart.chartex_2014", "CTGeoParentEntity"),
    "CTGeoPolygon": ("docx4j_py.oart.chartex_2014", "CTGeoPolygon"),
    "CTGeoPolygons": ("docx4j_py.oart.chartex_2014", "CTGeoPolygons"),
    "CTGeography": ("docx4j_py.oart.chartex_2014", "CTGeography"),
    "CTGridlines": ("docx4j_py.oart.chartex_2014", "CTGridlines"),
    "CTHeaderFooter": ("docx4j_py.oart.chartex_2014", "CTHeaderFooter"),
    "CTLegend": ("docx4j_py.oart.chartex_2014", "CTLegend"),
    "CTNumberColorPosition": ("docx4j_py.oart.chartex_2014", "CTNumberColorPosition"),
    "CTNumberFormat": ("docx4j_py.oart.chartex_2014", "CTNumberFormat"),
    "CTNumericDimension": ("docx4j_py.oart.chartex_2014", "CTNumericDimension"),
    "CTNumericLevel": ("docx4j_py.oart.chartex_2014", "CTNumericLevel"),
    "CTNumericValue": ("docx4j_py.oart.chartex_2014", "CTNumericValue"),
    "CTPageMargins": ("docx4j_py.oart.chartex_2014", "CTPageMargins"),
    "CTPageSetup": ("docx4j_py.oart.chartex_2014", "CTPageSetup"),
    "CTParentLabelLayout": ("docx4j_py.oart.chartex_2014", "CTParentLabelLayout"),
    "CTPercentageColorPosition": ("docx4j_py.oart.chartex_2014", "CTPercentageColorPosition"),
    "CTPlotArea": ("docx4j_py.oart.chartex_2014", "CTPlotArea"),
    "CTPlotAreaRegion": ("docx4j_py.oart.chartex_2014", "CTPlotAreaRegion"),
    "CTPlotSurface": ("docx4j_py.oart.chartex_2014", "CTPlotSurface"),
    "CTPrintSettings": ("docx4j_py.oart.chartex_2014", "CTPrintSettings"),
    "CTRegionLabelLayout": ("docx4j_py.oart.chartex_2014", "CTRegionLabelLayout"),
    "CTRelId": ("docx4j_py.oart.chartex_2014", "CTRelId"),
    "CTSeries": ("docx4j_py.oart.chartex_2014", "CTSeries"),
    "CTSeriesElementVisibilities": ("docx4j_py.oart.chartex_2014", "CTSeriesElementVisibilities"),
    "CTSeriesLayoutProperties": ("docx4j_py.oart.chartex_2014", "CTSeriesLayoutProperties"),
    "CTStatistics": ("docx4j_py.oart.chartex_2014", "CTStatistics"),
    "CTStringDimension": ("docx4j_py.oart.chartex_2014", "CTStringDimension"),
    "CTStringLevel": ("docx4j_py.oart.chartex_2014", "CTStringLevel"),
    "CTStringValue": ("docx4j_py.oart.chartex_2014", "CTStringValue"),
    "CTSubtotalIndex": ("docx4j_py.oart.chartex_2014", "CTSubtotalIndex"),
    "CTSubtotals": ("docx4j_py.oart.chartex_2014", "CTSubtotals"),
    "CTText": ("docx4j_py.oart.chartex_2014", "CTText"),
    "CTTextData": ("docx4j_py.oart.chartex_2014", "CTTextData"),
    "CTTickLabels": ("docx4j_py.oart.chartex_2014", "CTTickLabels"),
    "CTTickMarks": ("docx4j_py.oart.chartex_2014", "CTTickMarks"),
    "CTValueAxisScaling": ("docx4j_py.oart.chartex_2014", "CTValueAxisScaling"),
    "CTValueColorEndPosition": ("docx4j_py.oart.chartex_2014", "CTValueColorEndPosition"),
    "CTValueColorMiddlePosition": ("docx4j_py.oart.chartex_2014", "CTValueColorMiddlePosition"),
    "CTValueColorPositions": ("docx4j_py.oart.chartex_2014", "CTValueColorPositions"),
    "CTValueColors": ("docx4j_py.oart.chartex_2014", "CTValueColors"),
    "STAxisUnit": ("docx4j_py.oart.chartex_2014", "STAxisUnit"),
    "STDataLabelPos": ("docx4j_py.oart.chartex_2014", "STDataLabelPos"),
    "STEntityType": ("docx4j_py.oart.chartex_2014", "STEntityType"),
    "STFormulaDirection": ("docx4j_py.oart.chartex_2014", "STFormulaDirection"),
    "STGeoMappingLevel": ("docx4j_py.oart.chartex_2014", "STGeoMappingLevel"),
    "STGeoProjectionType": ("docx4j_py.oart.chartex_2014", "STGeoProjectionType"),
    "STIntervalClosedSide": ("docx4j_py.oart.chartex_2014", "STIntervalClosedSide"),
    "STNumericDimensionType": ("docx4j_py.oart.chartex_2014", "STNumericDimensionType"),
    "STPageOrientation": ("docx4j_py.oart.chartex_2014", "STPageOrientation"),
    "STParentLabelLayout": ("docx4j_py.oart.chartex_2014", "STParentLabelLayout"),
    "STPosAlign": ("docx4j_py.oart.chartex_2014", "STPosAlign"),
    "STQuartileMethod": ("docx4j_py.oart.chartex_2014", "STQuartileMethod"),
    "STRegionLabelLayout": ("docx4j_py.oart.chartex_2014", "STRegionLabelLayout"),
    "STSeriesLayout": ("docx4j_py.oart.chartex_2014", "STSeriesLayout"),
    "STSidePos": ("docx4j_py.oart.chartex_2014", "STSidePos"),
    "STStringDimensionType": ("docx4j_py.oart.chartex_2014", "STStringDimensionType"),
    "STTickMarksType": ("docx4j_py.oart.chartex_2014", "STTickMarksType"),
    "StDoubleOrAutomaticValue": ("docx4j_py.oart.chartex_2014", "StDoubleOrAutomaticValue"),
    "StGapWidthRatioValue": ("docx4j_py.oart.chartex_2014", "StGapWidthRatioValue"),
    "StValueAxisUnitValue": ("docx4j_py.oart.chartex_2014", "StValueAxisUnitValue"),
    "Chart": ("docx4j_py.oart.chartex_2014", "Chart"),
    "ChartSpace": ("docx4j_py.oart.chartex_2014", "ChartSpace"),
    "F": ("docx4j_py.oart.chartex_2014", "F"),
    "Nf": ("docx4j_py.oart.chartex_2014", "Nf"),
    "CTChangesData": ("docx4j_py.oart.command_2013", "CTChangesData"),
    "CTConnectorChanges": ("docx4j_py.oart.command_2013", "CTConnectorChanges"),
    "CTConnectorMoniker": ("docx4j_py.oart.command_2013", "CTConnectorMoniker"),
    "CTConnectorMonikerList": ("docx4j_py.oart.command_2013", "CTConnectorMonikerList"),
    "CTGraphicFrameChanges": ("docx4j_py.oart.command_2013", "CTGraphicFrameChanges"),
    "CTGraphicFrameMoniker": ("docx4j_py.oart.command_2013", "CTGraphicFrameMoniker"),
    "CTGraphicFrameMonikerList": ("docx4j_py.oart.command_2013", "CTGraphicFrameMonikerList"),
    "CTGroupShapeChanges": ("docx4j_py.oart.command_2013", "CTGroupShapeChanges"),
    "CTGroupShapeMoniker": ("docx4j_py.oart.command_2013", "CTGroupShapeMoniker"),
    "CTGroupShapeMonikerList": ("docx4j_py.oart.command_2013", "CTGroupShapeMonikerList"),
    "CTInkChanges": ("docx4j_py.oart.command_2013", "CTInkChanges"),
    "CTInkMoniker": ("docx4j_py.oart.command_2013", "CTInkMoniker"),
    "CTInkMonikerList": ("docx4j_py.oart.command_2013", "CTInkMonikerList"),
    "CTPictureChanges": ("docx4j_py.oart.command_2013", "CTPictureChanges"),
    "CTPictureMoniker": ("docx4j_py.oart.command_2013", "CTPictureMoniker"),
    "CTPictureMonikerList": ("docx4j_py.oart.command_2013", "CTPictureMonikerList"),
    "CTShapeChanges": ("docx4j_py.oart.command_2013", "CTShapeChanges"),
    "CTShapeMoniker": ("docx4j_py.oart.command_2013", "CTShapeMoniker"),
    "CTShapeMonikerList": ("docx4j_py.oart.command_2013", "CTShapeMonikerList"),
    "STConnectorChangeBit": ("docx4j_py.oart.command_2013", "STConnectorChangeBit"),
    "STGraphicFrameChangeBit": ("docx4j_py.oart.command_2013", "STGraphicFrameChangeBit"),
    "STGroupShapeChangeBit": ("docx4j_py.oart.command_2013", "STGroupShapeChangeBit"),
    "STInkChangeBit": ("docx4j_py.oart.command_2013", "STInkChangeBit"),
    "STPictureChangeBit": ("docx4j_py.oart.command_2013", "STPictureChangeBit"),
    "STShapeChangeBit": ("docx4j_py.oart.command_2013", "STShapeChangeBit"),
    "CxnSpMkLst": ("docx4j_py.oart.command_2013", "CxnSpMkLst"),
    "GraphicFrameMkLst": ("docx4j_py.oart.command_2013", "GraphicFrameMkLst"),
    "GrpMkLst": ("docx4j_py.oart.command_2013", "GrpMkLst"),
    "InkMkLst": ("docx4j_py.oart.command_2013", "InkMkLst"),
    "PicMkLst": ("docx4j_py.oart.command_2013", "PicMkLst"),
    "SpMkLst": ("docx4j_py.oart.command_2013", "SpMkLst"),
    "CTDecorative": ("docx4j_py.oart.decorative_2017", "CTDecorative"),
    "Decorative": ("docx4j_py.oart.decorative_2017", "Decorative"),
    "CTDataModelExtBlock": ("docx4j_py.oart.diagram_2008", "CTDataModelExtBlock"),
    "CTDrawing": ("docx4j_py.oart.diagram_2008", "CTDrawing"),
    "CTGroupShape": ("docx4j_py.oart.diagram_2008", "CTGroupShape"),
    "CTGroupShapeNonVisual": ("docx4j_py.oart.diagram_2008", "CTGroupShapeNonVisual"),
    "CTShape": ("docx4j_py.oart.diagram_2008", "CTShape"),
    "CTShapeNonVisual": ("docx4j_py.oart.diagram_2008", "CTShapeNonVisual"),
    "DataModelExt": ("docx4j_py.oart.diagram_2008", "DataModelExt"),
    "Drawing": ("docx4j_py.oart.diagram_2008", "Drawing"),
    "Diagram2010Ctboolean": ("docx4j_py.oart.diagram_2010", "CTBoolean"),
    "CTNonVisualDrawingProps": ("docx4j_py.oart.diagram_2010", "CTNonVisualDrawingProps"),
    "RecolorImg": ("docx4j_py.oart.diagram_2010", "RecolorImg"),
    "CTDiagramAutoBullet": ("docx4j_py.oart.diagram_2016_11", "CTDiagramAutoBullet"),
    "CTNumberDiagramInfo": ("docx4j_py.oart.diagram_2016_11", "CTNumberDiagramInfo"),
    "CTNumberDiagramInfoList": ("docx4j_py.oart.diagram_2016_11", "CTNumberDiagramInfoList"),
    "STSTorageType": ("docx4j_py.oart.diagram_2016_11", "STSTorageType"),
    "AutoBuNodeInfoLst": ("docx4j_py.oart.diagram_2016_11", "AutoBuNodeInfoLst"),
    "LstStyle": ("docx4j_py.oart.diagram_2016_12", "LstStyle"),
    "SpPr": ("docx4j_py.oart.diagram_2016_12", "SpPr"),
    "CTHyperlinkColor": ("docx4j_py.oart.hyperlink_color_2018", "CTHyperlinkColor"),
    "STHyperlinkColor": ("docx4j_py.oart.hyperlink_color_2018", "STHyperlinkColor"),
    "HlinkClr": ("docx4j_py.oart.hyperlink_color_2018", "HlinkClr"),
    "CTAction": ("docx4j_py.oart.ink_action_2014", "CTAction"),
    "CTActionData": ("docx4j_py.oart.ink_action_2014", "CTActionData"),
    "CTActionDataGroup": ("docx4j_py.oart.ink_action_2014", "CTActionDataGroup"),
    "CTActionGroup": ("docx4j_py.oart.ink_action_2014", "CTActionGroup"),
    "CTActionProperty": ("docx4j_py.oart.ink_action_2014", "CTActionProperty"),
    "CTActions": ("docx4j_py.oart.ink_action_2014", "CTActions"),
    "STActionTypeReserved": ("docx4j_py.oart.ink_action_2014", "STActionTypeReserved"),
    "STDataNameReserved": ("docx4j_py.oart.ink_action_2014", "STDataNameReserved"),
    "STPropertyNameReserved": ("docx4j_py.oart.ink_action_2014", "STPropertyNameReserved"),
    "STPropertyValueReserved": ("docx4j_py.oart.ink_action_2014", "STPropertyValueReserved"),
    "Actions": ("docx4j_py.oart.ink_action_2014", "Actions"),
    "CTCameraTool": ("docx4j_py.oart.main_2010", "CTCameraTool"),
    "CTCompatExt": ("docx4j_py.oart.main_2010", "CTCompatExt"),
    "CTContentPartLocking": ("docx4j_py.oart.main_2010", "CTContentPartLocking"),
    "CTEffectProperties": ("docx4j_py.oart.main_2010", "CTEffectProperties"),
    "CTFillProperties": ("docx4j_py.oart.main_2010", "CTFillProperties"),
    "CTGvmlContentPart": ("docx4j_py.oart.main_2010", "CTGvmlContentPart"),
    "CTGvmlContentPartNonVisual": ("docx4j_py.oart.main_2010", "CTGvmlContentPartNonVisual"),
    "CTIsGvmlCanvas": ("docx4j_py.oart.main_2010", "CTIsGvmlCanvas"),
    "CTLineProperties": ("docx4j_py.oart.main_2010", "CTLineProperties"),
    "CTNonVisualInkContentPartProperties": (
        "docx4j_py.oart.main_2010",
        "CTNonVisualInkContentPartProperties",
    ),
    "CTPhoto": ("docx4j_py.oart.main_2010", "CTPhoto"),
    "CTPictureEffect": ("docx4j_py.oart.main_2010", "CTPictureEffect"),
    "CTPictureEffectBackgroundRemoval": (
        "docx4j_py.oart.main_2010",
        "CTPictureEffectBackgroundRemoval",
    ),
    "CTPictureEffectBackgroundRemovalBackgroundMark": (
        "docx4j_py.oart.main_2010",
        "CTPictureEffectBackgroundRemovalBackgroundMark",
    ),
    "CTPictureEffectBackgroundRemovalForegroundMark": (
        "docx4j_py.oart.main_2010",
        "CTPictureEffectBackgroundRemovalForegroundMark",
    ),
    "CTPictureEffectBlur": ("docx4j_py.oart.main_2010", "CTPictureEffectBlur"),
    "CTPictureEffectBrightnessContrast": (
        "docx4j_py.oart.main_2010",
        "CTPictureEffectBrightnessContrast",
    ),
    "CTPictureEffectCement": ("docx4j_py.oart.main_2010", "CTPictureEffectCement"),
    "CTPictureEffectChalkSketch": ("docx4j_py.oart.main_2010", "CTPictureEffectChalkSketch"),
    "CTPictureEffectColorTemperature": (
        "docx4j_py.oart.main_2010",
        "CTPictureEffectColorTemperature",
    ),
    "CTPictureEffectCrisscrossEtching": (
        "docx4j_py.oart.main_2010",
        "CTPictureEffectCrisscrossEtching",
    ),
    "CTPictureEffectCutout": ("docx4j_py.oart.main_2010", "CTPictureEffectCutout"),
    "CTPictureEffectFilmGrain": ("docx4j_py.oart.main_2010", "CTPictureEffectFilmGrain"),
    "CTPictureEffectGlass": ("docx4j_py.oart.main_2010", "CTPictureEffectGlass"),
    "CTPictureEffectGlowDiffused": ("docx4j_py.oart.main_2010", "CTPictureEffectGlowDiffused"),
    "CTPictureEffectGlowEdges": ("docx4j_py.oart.main_2010", "CTPictureEffectGlowEdges"),
    "CTPictureEffectLightScreen": ("docx4j_py.oart.main_2010", "CTPictureEffectLightScreen"),
    "CTPictureEffectLineDrawing": ("docx4j_py.oart.main_2010", "CTPictureEffectLineDrawing"),
    "CTPictureEffectMarker": ("docx4j_py.oart.main_2010", "CTPictureEffectMarker"),
    "CTPictureEffectMosiaicBubbles": ("docx4j_py.oart.main_2010", "CTPictureEffectMosiaicBubbles"),
    "CTPictureEffectPaintBrush": ("docx4j_py.oart.main_2010", "CTPictureEffectPaintBrush"),
    "CTPictureEffectPaintStrokes": ("docx4j_py.oart.main_2010", "CTPictureEffectPaintStrokes"),
    "CTPictureEffectPastelsSmooth": ("docx4j_py.oart.main_2010", "CTPictureEffectPastelsSmooth"),
    "CTPictureEffectPencilGrayscale": (
        "docx4j_py.oart.main_2010",
        "CTPictureEffectPencilGrayscale",
    ),
    "CTPictureEffectPencilSketch": ("docx4j_py.oart.main_2010", "CTPictureEffectPencilSketch"),
    "CTPictureEffectPhotocopy": ("docx4j_py.oart.main_2010", "CTPictureEffectPhotocopy"),
    "CTPictureEffectPlasticWrap": ("docx4j_py.oart.main_2010", "CTPictureEffectPlasticWrap"),
    "CTPictureEffectSaturation": ("docx4j_py.oart.main_2010", "CTPictureEffectSaturation"),
    "CTPictureEffectSharpenSoften": ("docx4j_py.oart.main_2010", "CTPictureEffectSharpenSoften"),
    "CTPictureEffectTexturizer": ("docx4j_py.oart.main_2010", "CTPictureEffectTexturizer"),
    "CTPictureEffectWatercolorSponge": (
        "docx4j_py.oart.main_2010",
        "CTPictureEffectWatercolorSponge",
    ),
    "CTPictureLayer": ("docx4j_py.oart.main_2010", "CTPictureLayer"),
    "CTScene3D": ("docx4j_py.oart.main_2010", "CTScene3D"),
    "CTShadowObscured": ("docx4j_py.oart.main_2010", "CTShadowObscured"),
    "CTShape3D": ("docx4j_py.oart.main_2010", "CTShape3D"),
    "CTTextMath": ("docx4j_py.oart.main_2010", "CTTextMath"),
    "CTUseLocalDpi": ("docx4j_py.oart.main_2010", "CTUseLocalDpi"),
    "CameraTool": ("docx4j_py.oart.main_2010", "CameraTool"),
    "CompatExt": ("docx4j_py.oart.main_2010", "CompatExt"),
    "MainContentPart": ("docx4j_py.oart.main_2010", "ContentPart"),
    "ImgProps": ("docx4j_py.oart.main_2010", "ImgProps"),
    "IsCanvas": ("docx4j_py.oart.main_2010", "IsCanvas"),
    "M": ("docx4j_py.oart.main_2010", "M"),
    "ShadowObscured": ("docx4j_py.oart.main_2010", "ShadowObscured"),
    "UseLocalDpi": ("docx4j_py.oart.main_2010", "UseLocalDpi"),
    "CTBackgroundPr": ("docx4j_py.oart.main_2012", "CTBackgroundPr"),
    "CTNonVisualGroupProps": ("docx4j_py.oart.main_2012", "CTNonVisualGroupProps"),
    "CTObjectPr": ("docx4j_py.oart.main_2012", "CTObjectPr"),
    "CTSignatureLine": ("docx4j_py.oart.main_2012", "CTSignatureLine"),
    "StTargetScreenSz": ("docx4j_py.oart.main_2012", "StTargetScreenSz"),
    "BackgroundPr": ("docx4j_py.oart.main_2012", "BackgroundPr"),
    "NonVisualGroupProps": ("docx4j_py.oart.main_2012", "NonVisualGroupProps"),
    "ObjectPr": ("docx4j_py.oart.main_2012", "ObjectPr"),
    "SignatureLine": ("docx4j_py.oart.main_2012", "SignatureLine"),
    "CTConnectableReferences": ("docx4j_py.oart.main_2014", "CTConnectableReferences"),
    "CTCreationId": ("docx4j_py.oart.main_2014", "CTCreationId"),
    "CTIdentifier": ("docx4j_py.oart.main_2014", "CTIdentifier"),
    "CTPredecessorDrawingElementReference": (
        "docx4j_py.oart.main_2014",
        "CTPredecessorDrawingElementReference",
    ),
    "ColId": ("docx4j_py.oart.main_2014", "ColId"),
    "CreationId": ("docx4j_py.oart.main_2014", "CreationId"),
    "CxnDerefs": ("docx4j_py.oart.main_2014", "CxnDerefs"),
    "PredDeref": ("docx4j_py.oart.main_2014", "PredDeref"),
    "RowId": ("docx4j_py.oart.main_2014", "RowId"),
    "CTPictureAttributionSourceURL": (
        "docx4j_py.oart.main_2016_11",
        "CTPictureAttributionSourceURL",
    ),
    "PicAttrSrcUrl": ("docx4j_py.oart.main_2016_11", "PicAttrSrcUrl"),
    "CTAmbientLight": ("docx4j_py.oart.model3d_2017", "CTAmbientLight"),
    "CTDirectionalLight": ("docx4j_py.oart.model3d_2017", "CTDirectionalLight"),
    "CTModel3D": ("docx4j_py.oart.model3d_2017", "CTModel3D"),
    "CTModel3DCamera": ("docx4j_py.oart.model3d_2017", "CTModel3DCamera"),
    "CTModel3DRaster": ("docx4j_py.oart.model3d_2017", "CTModel3DRaster"),
    "CTModel3DTransform": ("docx4j_py.oart.model3d_2017", "CTModel3DTransform"),
    "CTObjectViewport": ("docx4j_py.oart.model3d_2017", "CTObjectViewport"),
    "CTOrthographicProjection": ("docx4j_py.oart.model3d_2017", "CTOrthographicProjection"),
    "CTPerspectiveProjection": ("docx4j_py.oart.model3d_2017", "CTPerspectiveProjection"),
    "CTPointLight": ("docx4j_py.oart.model3d_2017", "CTPointLight"),
    "CTPositiveRatio": ("docx4j_py.oart.model3d_2017", "CTPositiveRatio"),
    "CTRotate3D": ("docx4j_py.oart.model3d_2017", "CTRotate3D"),
    "CTScale3D": ("docx4j_py.oart.model3d_2017", "CTScale3D"),
    "CTSpotLight": ("docx4j_py.oart.model3d_2017", "CTSpotLight"),
    "CTUnknownLight": ("docx4j_py.oart.model3d_2017", "CTUnknownLight"),
    "CTWindowViewport": ("docx4j_py.oart.model3d_2017", "CTWindowViewport"),
    "Model3D": ("docx4j_py.oart.model3d_2017", "Model3D"),
    "ExtLst": ("docx4j_py.oart.picture_2010", "ExtLst"),
    "Picture2010Style": ("docx4j_py.oart.picture_2010", "Style"),
    "SpreadsheetCtapplicationNonVisualDrawingProps": (
        "docx4j_py.oart.spreadsheet_drawing_2010",
        "CTApplicationNonVisualDrawingProps",
    ),
    "SpreadsheetCtcontentPart": ("docx4j_py.oart.spreadsheet_drawing_2010", "CTContentPart"),
    "SpreadsheetCtcontentPartNonVisual": (
        "docx4j_py.oart.spreadsheet_drawing_2010",
        "CTContentPartNonVisual",
    ),
    "SpreadsheetContentPart": ("docx4j_py.oart.spreadsheet_drawing_2010", "ContentPart"),
    "CTSVGBlip": ("docx4j_py.oart.svg_2016", "CTSVGBlip"),
    "SvgBlip": ("docx4j_py.oart.svg_2016", "SvgBlip"),
    "CTThemeFamily": ("docx4j_py.oart.theme_2012", "CTThemeFamily"),
    "ThemeFamily": ("docx4j_py.oart.theme_2012", "ThemeFamily"),
}


def __getattr__(name: str) -> object:
    """Import a re-exported class on first use."""
    target = __lazy_imports__.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    value = getattr(import_module(target[0]), target[1])
    globals()[name] = value
    return value
