"""``el`` for the http://schemas.microsoft.com/office/drawing/2010/picture namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_picture_2010.json``, which a human reviews.

    >>> from docx4j_py.oart.picture_2010 import el
    >>> el.extLst()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.oart.picture_2010 import (
    ExtLst,
    Style,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2010/picture"

def extLst(**kwargs: Any) -> ExtLst:
    """``{http://schemas.microsoft.com/office/drawing/2010/picture}extLst`` -> :class:`docx4j_py.oart.picture_2010.ExtLst`."""
    return ExtLst(**kwargs)

def style(**kwargs: Any) -> Style:
    """``{http://schemas.microsoft.com/office/drawing/2010/picture}style`` -> :class:`docx4j_py.oart.picture_2010.Style`."""
    return Style(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2010/picture}extLst": ExtLst,
    "{http://schemas.microsoft.com/office/drawing/2010/picture}style": Style,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "extLst": ExtLst,
    "style": Style,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    ExtLst: "{http://schemas.microsoft.com/office/drawing/2010/picture}extLst",
    Style: "{http://schemas.microsoft.com/office/drawing/2010/picture}style",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "extLst",
    "style",
]
