"""``el`` for the http://schemas.microsoft.com/office/drawing/2008/diagram namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/oart_diagram_2008.json``, which a human reviews.

    >>> from docx4j_py.oart.diagram_2008 import el
    >>> el.cNvGrpSpPr()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.main import (
    CTGroupShapeProperties,
    CTNonVisualDrawingProps,
    CTNonVisualDrawingShapeProps,
    CTNonVisualGroupDrawingShapeProps,
    CTOfficeArtExtensionList,
    CTShapeProperties,
    CTShapeStyle,
    CTTextBody,
    CTTransform2D,
)
from docx4j_py.oart.diagram_2008 import (
    CTGroupShape,
    CTGroupShapeNonVisual,
    CTShape,
    CTShapeNonVisual,
    DataModelExt,
    Drawing,
)

__NAMESPACE__ = "http://schemas.microsoft.com/office/drawing/2008/diagram"

def cNvGrpSpPr(**kwargs: Any) -> CTNonVisualGroupDrawingShapeProps:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}cNvGrpSpPr`` -> :class:`docx4j_py.dml.main.CTNonVisualGroupDrawingShapeProps`."""
    return CTNonVisualGroupDrawingShapeProps(**kwargs)

def cNvPr(**kwargs: Any) -> CTNonVisualDrawingProps:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}cNvPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingProps`."""
    return CTNonVisualDrawingProps(**kwargs)

def cNvSpPr(**kwargs: Any) -> CTNonVisualDrawingShapeProps:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}cNvSpPr`` -> :class:`docx4j_py.dml.main.CTNonVisualDrawingShapeProps`."""
    return CTNonVisualDrawingShapeProps(**kwargs)

def dataModelExt(**kwargs: Any) -> DataModelExt:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}dataModelExt`` -> :class:`docx4j_py.oart.diagram_2008.DataModelExt`."""
    return DataModelExt(**kwargs)

def drawing(**kwargs: Any) -> Drawing:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}drawing`` -> :class:`docx4j_py.oart.diagram_2008.Drawing`."""
    return Drawing(**kwargs)

def extLst(**kwargs: Any) -> CTOfficeArtExtensionList:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}extLst`` -> :class:`docx4j_py.dml.main.CTOfficeArtExtensionList`."""
    return CTOfficeArtExtensionList(**kwargs)

def grpSp(**kwargs: Any) -> CTGroupShape:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}grpSp`` -> :class:`docx4j_py.oart.diagram_2008.CTGroupShape`."""
    return CTGroupShape(**kwargs)

def grpSpPr(**kwargs: Any) -> CTGroupShapeProperties:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}grpSpPr`` -> :class:`docx4j_py.dml.main.CTGroupShapeProperties`."""
    return CTGroupShapeProperties(**kwargs)

def nvGrpSpPr(**kwargs: Any) -> CTGroupShapeNonVisual:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}nvGrpSpPr`` -> :class:`docx4j_py.oart.diagram_2008.CTGroupShapeNonVisual`."""
    return CTGroupShapeNonVisual(**kwargs)

def nvSpPr(**kwargs: Any) -> CTShapeNonVisual:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}nvSpPr`` -> :class:`docx4j_py.oart.diagram_2008.CTShapeNonVisual`."""
    return CTShapeNonVisual(**kwargs)

def sp(**kwargs: Any) -> CTShape:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}sp`` -> :class:`docx4j_py.oart.diagram_2008.CTShape`."""
    return CTShape(**kwargs)

def spPr(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}spPr`` -> :class:`docx4j_py.dml.main.CTShapeProperties`."""
    return CTShapeProperties(**kwargs)

def spTree(**kwargs: Any) -> CTGroupShape:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}spTree`` -> :class:`docx4j_py.oart.diagram_2008.CTGroupShape`."""
    return CTGroupShape(**kwargs)

def style(**kwargs: Any) -> CTShapeStyle:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}style`` -> :class:`docx4j_py.dml.main.CTShapeStyle`."""
    return CTShapeStyle(**kwargs)

def txBody(**kwargs: Any) -> CTTextBody:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}txBody`` -> :class:`docx4j_py.dml.main.CTTextBody`."""
    return CTTextBody(**kwargs)

def txXfrm(**kwargs: Any) -> CTTransform2D:
    """``{http://schemas.microsoft.com/office/drawing/2008/diagram}txXfrm`` -> :class:`docx4j_py.dml.main.CTTransform2D`."""
    return CTTransform2D(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}cNvGrpSpPr": CTNonVisualGroupDrawingShapeProps,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}cNvPr": CTNonVisualDrawingProps,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}cNvSpPr": CTNonVisualDrawingShapeProps,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}dataModelExt": DataModelExt,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}drawing": Drawing,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}extLst": CTOfficeArtExtensionList,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}grpSp": CTGroupShape,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}grpSpPr": CTGroupShapeProperties,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}nvGrpSpPr": CTGroupShapeNonVisual,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}nvSpPr": CTShapeNonVisual,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}sp": CTShape,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}spPr": CTShapeProperties,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}spTree": CTGroupShape,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}style": CTShapeStyle,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}txBody": CTTextBody,
    "{http://schemas.microsoft.com/office/drawing/2008/diagram}txXfrm": CTTransform2D,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "cNvGrpSpPr": CTNonVisualGroupDrawingShapeProps,
    "cNvPr": CTNonVisualDrawingProps,
    "cNvSpPr": CTNonVisualDrawingShapeProps,
    "dataModelExt": DataModelExt,
    "drawing": Drawing,
    "extLst": CTOfficeArtExtensionList,
    "grpSp": CTGroupShape,
    "grpSpPr": CTGroupShapeProperties,
    "nvGrpSpPr": CTGroupShapeNonVisual,
    "nvSpPr": CTShapeNonVisual,
    "sp": CTShape,
    "spPr": CTShapeProperties,
    "spTree": CTGroupShape,
    "style": CTShapeStyle,
    "txBody": CTTextBody,
    "txXfrm": CTTransform2D,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTGroupShapeNonVisual: "{http://schemas.microsoft.com/office/drawing/2008/diagram}nvGrpSpPr",
    CTGroupShapeProperties: "{http://schemas.microsoft.com/office/drawing/2008/diagram}grpSpPr",
    CTNonVisualDrawingProps: "{http://schemas.microsoft.com/office/drawing/2008/diagram}cNvPr",
    CTNonVisualDrawingShapeProps: "{http://schemas.microsoft.com/office/drawing/2008/diagram}cNvSpPr",
    CTNonVisualGroupDrawingShapeProps: "{http://schemas.microsoft.com/office/drawing/2008/diagram}cNvGrpSpPr",
    CTOfficeArtExtensionList: "{http://schemas.microsoft.com/office/drawing/2008/diagram}extLst",
    CTShape: "{http://schemas.microsoft.com/office/drawing/2008/diagram}sp",
    CTShapeNonVisual: "{http://schemas.microsoft.com/office/drawing/2008/diagram}nvSpPr",
    CTShapeProperties: "{http://schemas.microsoft.com/office/drawing/2008/diagram}spPr",
    CTShapeStyle: "{http://schemas.microsoft.com/office/drawing/2008/diagram}style",
    CTTextBody: "{http://schemas.microsoft.com/office/drawing/2008/diagram}txBody",
    CTTransform2D: "{http://schemas.microsoft.com/office/drawing/2008/diagram}txXfrm",
    DataModelExt: "{http://schemas.microsoft.com/office/drawing/2008/diagram}dataModelExt",
    Drawing: "{http://schemas.microsoft.com/office/drawing/2008/diagram}drawing",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "cNvGrpSpPr",
    "cNvPr",
    "cNvSpPr",
    "dataModelExt",
    "drawing",
    "extLst",
    "grpSp",
    "grpSpPr",
    "nvGrpSpPr",
    "nvSpPr",
    "sp",
    "spPr",
    "spTree",
    "style",
    "txBody",
    "txXfrm",
]
