"""``el`` for the http://schemas.openxmlformats.org/drawingml/2006/chart namespace.

Generated by ``codegen/generate_el.py`` from the ``XmlContext`` class metadata;
do not edit. The naming rules, the collisions and the class each name resolves
to are in ``codegen/el_tables/dml_chart.json``, which a human reviews.

    >>> from docx4j_py.dml.chart import el
    >>> el.applyToEnd()  # doctest: +SKIP

Every function takes the dataclass's own keyword arguments and passes them
straight through. A class that carries text (``w:t``, ``w:delText``,
``w:instrText``: anything whose metadata has a text value field) also takes the
text as the one positional argument, and sets ``xml:space="preserve"`` when the
text begins or ends with whitespace or holds two in a row, which is what
docx4j's ``t()`` does.
"""

from __future__ import annotations

from typing import Any

from docx4j_py.runtime import text_element

from docx4j_py.dml.chart import (
    CTArea3DChart,
    CTAreaChart,
    CTAreaSer,
    CTAxDataSource,
    CTAxPos,
    CTAxisUnit,
    CTBandFmt,
    CTBandFmts,
    CTBar3DChart,
    CTBarChart,
    CTBarDir,
    CTBarGrouping,
    CTBarSer,
    CTBoolean,
    CTBubbleChart,
    CTBubbleScale,
    CTBubbleSer,
    CTBuiltInUnit,
    CTCatAx,
    CTChart,
    CTChartLines,
    CTCrossBetween,
    CTCrosses,
    CTCustSplit,
    CTDLbl,
    CTDLblPos,
    CTDLbls,
    CTDPt,
    CTDTable,
    CTDateAx,
    CTDepthPercent,
    CTDispBlanksAs,
    CTDispUnits,
    CTDispUnitsLbl,
    CTDouble,
    CTDoughnutChart,
    CTDrawing,
    CTErrBarType,
    CTErrBars,
    CTErrDir,
    CTErrValType,
    CTExtension,
    CTExtensionList,
    CTExternalData,
    CTFirstSliceAng,
    CTGapAmount,
    CTGrouping,
    CTHPercent,
    CTHeaderFooter,
    CTHoleSize,
    CTLayout,
    CTLayoutMode,
    CTLayoutTarget,
    CTLblAlgn,
    CTLblOffset,
    CTLegend,
    CTLegendEntry,
    CTLegendPos,
    CTLine3DChart,
    CTLineChart,
    CTLineSer,
    CTLogBase,
    CTLvl,
    CTManualLayout,
    CTMarker,
    CTMarkerSize,
    CTMarkerStyle,
    CTMultiLvlStrData,
    CTMultiLvlStrRef,
    CTNumData,
    CTNumDataSource,
    CTNumFmt,
    CTNumRef,
    CTNumVal,
    CTOfPieChart,
    CTOfPieType,
    CTOrder,
    CTOrientation,
    CTOverlap,
    CTPageMargins,
    CTPageSetup,
    CTPeriod,
    CTPerspective,
    CTPictureFormat,
    CTPictureOptions,
    CTPictureStackUnit,
    CTPie3DChart,
    CTPieChart,
    CTPieSer,
    CTPivotFmt,
    CTPivotFmts,
    CTPivotSource,
    CTPlotArea,
    CTPrintSettings,
    CTProtection,
    CTRadarChart,
    CTRadarSer,
    CTRadarStyle,
    CTRelId,
    CTRotX,
    CTRotY,
    CTScaling,
    CTScatterChart,
    CTScatterSer,
    CTScatterStyle,
    CTSecondPieSize,
    CTSerAx,
    CTSerTx,
    CTShape,
    CTSizeRepresents,
    CTSkip,
    CTSplitType,
    CTStockChart,
    CTStrData,
    CTStrRef,
    CTStrVal,
    CTStyle,
    CTSurface,
    CTSurface3DChart,
    CTSurfaceChart,
    CTSurfaceSer,
    CTTextLanguageID,
    CTTickLblPos,
    CTTickMark,
    CTTimeUnit,
    CTTitle,
    CTTrendline,
    CTTrendlineLbl,
    CTTrendlineType,
    CTTx,
    CTUnsignedInt,
    CTUpDownBar,
    CTUpDownBars,
    CTValAx,
    CTView3D,
    Chart,
    ChartSpace,
    Delete,
    ShowBubbleSize,
    ShowCatName,
    ShowLeaderLines,
    ShowLegendKey,
    ShowPercent,
    ShowSerName,
    ShowVal,
)
from docx4j_py.dml.main import (
    CTColorMapping,
    CTShapeProperties,
    CTTextBody,
)

__NAMESPACE__ = "http://schemas.openxmlformats.org/drawingml/2006/chart"

def applyToEnd(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}applyToEnd`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def applyToFront(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}applyToFront`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def applyToSides(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}applyToSides`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def area3DChart(**kwargs: Any) -> CTArea3DChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}area3DChart`` -> :class:`docx4j_py.dml.chart.CTArea3DChart`."""
    return CTArea3DChart(**kwargs)

def areaChart(**kwargs: Any) -> CTAreaChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}areaChart`` -> :class:`docx4j_py.dml.chart.CTAreaChart`."""
    return CTAreaChart(**kwargs)

def auto(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}auto`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def autoTitleDeleted(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}autoTitleDeleted`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def autoUpdate(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}autoUpdate`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def axId(**kwargs: Any) -> CTUnsignedInt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}axId`` -> :class:`docx4j_py.dml.chart.CTUnsignedInt`."""
    return CTUnsignedInt(**kwargs)

def axPos(**kwargs: Any) -> CTAxPos:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}axPos`` -> :class:`docx4j_py.dml.chart.CTAxPos`."""
    return CTAxPos(**kwargs)

def backWall(**kwargs: Any) -> CTSurface:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}backWall`` -> :class:`docx4j_py.dml.chart.CTSurface`."""
    return CTSurface(**kwargs)

def backward(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}backward`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def bandFmt(**kwargs: Any) -> CTBandFmt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}bandFmt`` -> :class:`docx4j_py.dml.chart.CTBandFmt`."""
    return CTBandFmt(**kwargs)

def bandFmts(**kwargs: Any) -> CTBandFmts:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}bandFmts`` -> :class:`docx4j_py.dml.chart.CTBandFmts`."""
    return CTBandFmts(**kwargs)

def bar3DChart(**kwargs: Any) -> CTBar3DChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}bar3DChart`` -> :class:`docx4j_py.dml.chart.CTBar3DChart`."""
    return CTBar3DChart(**kwargs)

def barChart(**kwargs: Any) -> CTBarChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}barChart`` -> :class:`docx4j_py.dml.chart.CTBarChart`."""
    return CTBarChart(**kwargs)

def barDir(**kwargs: Any) -> CTBarDir:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}barDir`` -> :class:`docx4j_py.dml.chart.CTBarDir`."""
    return CTBarDir(**kwargs)

def baseTimeUnit(**kwargs: Any) -> CTTimeUnit:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}baseTimeUnit`` -> :class:`docx4j_py.dml.chart.CTTimeUnit`."""
    return CTTimeUnit(**kwargs)

def bubble3D(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}bubble3D`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def bubbleChart(**kwargs: Any) -> CTBubbleChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}bubbleChart`` -> :class:`docx4j_py.dml.chart.CTBubbleChart`."""
    return CTBubbleChart(**kwargs)

def bubbleScale(**kwargs: Any) -> CTBubbleScale:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}bubbleScale`` -> :class:`docx4j_py.dml.chart.CTBubbleScale`."""
    return CTBubbleScale(**kwargs)

def bubbleSize(**kwargs: Any) -> CTNumDataSource:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}bubbleSize`` -> :class:`docx4j_py.dml.chart.CTNumDataSource`."""
    return CTNumDataSource(**kwargs)

def builtInUnit(**kwargs: Any) -> CTBuiltInUnit:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}builtInUnit`` -> :class:`docx4j_py.dml.chart.CTBuiltInUnit`."""
    return CTBuiltInUnit(**kwargs)

def cat(**kwargs: Any) -> CTAxDataSource:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}cat`` -> :class:`docx4j_py.dml.chart.CTAxDataSource`."""
    return CTAxDataSource(**kwargs)

def catAx(**kwargs: Any) -> CTCatAx:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}catAx`` -> :class:`docx4j_py.dml.chart.CTCatAx`."""
    return CTCatAx(**kwargs)

def chart(**kwargs: Any) -> Chart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}chart`` -> :class:`docx4j_py.dml.chart.Chart`, the global element declaration of 2 classes this name takes; see ``chart_chart``."""
    return Chart(**kwargs)

def chart_chart(**kwargs: Any) -> CTChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}chart`` -> :class:`docx4j_py.dml.chart.CTChart`, the CTChart form."""
    return CTChart(**kwargs)

def chartObject(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}chartObject`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def chartSpace(**kwargs: Any) -> ChartSpace:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}chartSpace`` -> :class:`docx4j_py.dml.chart.ChartSpace`."""
    return ChartSpace(**kwargs)

def clrMapOvr(**kwargs: Any) -> CTColorMapping:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}clrMapOvr`` -> :class:`docx4j_py.dml.main.CTColorMapping`."""
    return CTColorMapping(**kwargs)

def crossAx(**kwargs: Any) -> CTUnsignedInt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}crossAx`` -> :class:`docx4j_py.dml.chart.CTUnsignedInt`."""
    return CTUnsignedInt(**kwargs)

def crossBetween(**kwargs: Any) -> CTCrossBetween:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}crossBetween`` -> :class:`docx4j_py.dml.chart.CTCrossBetween`."""
    return CTCrossBetween(**kwargs)

def crosses(**kwargs: Any) -> CTCrosses:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}crosses`` -> :class:`docx4j_py.dml.chart.CTCrosses`."""
    return CTCrosses(**kwargs)

def crossesAt(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}crossesAt`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def custSplit(**kwargs: Any) -> CTCustSplit:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}custSplit`` -> :class:`docx4j_py.dml.chart.CTCustSplit`."""
    return CTCustSplit(**kwargs)

def custUnit(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}custUnit`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def dLbl(**kwargs: Any) -> CTDLbl:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dLbl`` -> :class:`docx4j_py.dml.chart.CTDLbl`."""
    return CTDLbl(**kwargs)

def dLblPos(**kwargs: Any) -> CTDLblPos:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dLblPos`` -> :class:`docx4j_py.dml.chart.CTDLblPos`."""
    return CTDLblPos(**kwargs)

def dLbls(**kwargs: Any) -> CTDLbls:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dLbls`` -> :class:`docx4j_py.dml.chart.CTDLbls`."""
    return CTDLbls(**kwargs)

def dPt(**kwargs: Any) -> CTDPt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dPt`` -> :class:`docx4j_py.dml.chart.CTDPt`."""
    return CTDPt(**kwargs)

def dTable(**kwargs: Any) -> CTDTable:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dTable`` -> :class:`docx4j_py.dml.chart.CTDTable`."""
    return CTDTable(**kwargs)

def data(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}data`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def date1904(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}date1904`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def dateAx(**kwargs: Any) -> CTDateAx:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dateAx`` -> :class:`docx4j_py.dml.chart.CTDateAx`."""
    return CTDateAx(**kwargs)

def delete(**kwargs: Any) -> Delete:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}delete`` -> :class:`docx4j_py.dml.chart.Delete`, the most reachable scope of 2 classes this name takes; see ``delete_boolean``."""
    return Delete(**kwargs)

def delete_boolean(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}delete`` -> :class:`docx4j_py.dml.chart.CTBoolean`, the CTBoolean form."""
    return CTBoolean(**kwargs)

def depthPercent(**kwargs: Any) -> CTDepthPercent:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}depthPercent`` -> :class:`docx4j_py.dml.chart.CTDepthPercent`."""
    return CTDepthPercent(**kwargs)

def dispBlanksAs(**kwargs: Any) -> CTDispBlanksAs:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dispBlanksAs`` -> :class:`docx4j_py.dml.chart.CTDispBlanksAs`."""
    return CTDispBlanksAs(**kwargs)

def dispEq(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dispEq`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def dispRSqr(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dispRSqr`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def dispUnits(**kwargs: Any) -> CTDispUnits:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dispUnits`` -> :class:`docx4j_py.dml.chart.CTDispUnits`."""
    return CTDispUnits(**kwargs)

def dispUnitsLbl(**kwargs: Any) -> CTDispUnitsLbl:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dispUnitsLbl`` -> :class:`docx4j_py.dml.chart.CTDispUnitsLbl`."""
    return CTDispUnitsLbl(**kwargs)

def doughnutChart(**kwargs: Any) -> CTDoughnutChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}doughnutChart`` -> :class:`docx4j_py.dml.chart.CTDoughnutChart`."""
    return CTDoughnutChart(**kwargs)

def downBars(**kwargs: Any) -> CTUpDownBar:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}downBars`` -> :class:`docx4j_py.dml.chart.CTUpDownBar`."""
    return CTUpDownBar(**kwargs)

def dropLines(**kwargs: Any) -> CTChartLines:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}dropLines`` -> :class:`docx4j_py.dml.chart.CTChartLines`."""
    return CTChartLines(**kwargs)

def errBarType(**kwargs: Any) -> CTErrBarType:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}errBarType`` -> :class:`docx4j_py.dml.chart.CTErrBarType`."""
    return CTErrBarType(**kwargs)

def errBars(**kwargs: Any) -> CTErrBars:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}errBars`` -> :class:`docx4j_py.dml.chart.CTErrBars`."""
    return CTErrBars(**kwargs)

def errDir(**kwargs: Any) -> CTErrDir:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}errDir`` -> :class:`docx4j_py.dml.chart.CTErrDir`."""
    return CTErrDir(**kwargs)

def errValType(**kwargs: Any) -> CTErrValType:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}errValType`` -> :class:`docx4j_py.dml.chart.CTErrValType`."""
    return CTErrValType(**kwargs)

def explosion(**kwargs: Any) -> CTUnsignedInt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}explosion`` -> :class:`docx4j_py.dml.chart.CTUnsignedInt`."""
    return CTUnsignedInt(**kwargs)

def ext(**kwargs: Any) -> CTExtension:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ext`` -> :class:`docx4j_py.dml.chart.CTExtension`."""
    return CTExtension(**kwargs)

def extLst(**kwargs: Any) -> CTExtensionList:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}extLst`` -> :class:`docx4j_py.dml.chart.CTExtensionList`."""
    return CTExtensionList(**kwargs)

def externalData(**kwargs: Any) -> CTExternalData:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}externalData`` -> :class:`docx4j_py.dml.chart.CTExternalData`."""
    return CTExternalData(**kwargs)

def firstSliceAng(**kwargs: Any) -> CTFirstSliceAng:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}firstSliceAng`` -> :class:`docx4j_py.dml.chart.CTFirstSliceAng`."""
    return CTFirstSliceAng(**kwargs)

def floor(**kwargs: Any) -> CTSurface:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}floor`` -> :class:`docx4j_py.dml.chart.CTSurface`."""
    return CTSurface(**kwargs)

def fmtId(**kwargs: Any) -> CTUnsignedInt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}fmtId`` -> :class:`docx4j_py.dml.chart.CTUnsignedInt`."""
    return CTUnsignedInt(**kwargs)

def formatting(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}formatting`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def forward(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}forward`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def gapDepth(**kwargs: Any) -> CTGapAmount:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}gapDepth`` -> :class:`docx4j_py.dml.chart.CTGapAmount`."""
    return CTGapAmount(**kwargs)

def gapWidth(**kwargs: Any) -> CTGapAmount:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}gapWidth`` -> :class:`docx4j_py.dml.chart.CTGapAmount`."""
    return CTGapAmount(**kwargs)

def grouping(**kwargs: Any) -> CTGrouping:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}grouping`` -> :class:`docx4j_py.dml.chart.CTGrouping`, the most reachable scope of 2 classes this name takes; see ``bar_grouping``."""
    return CTGrouping(**kwargs)

def bar_grouping(**kwargs: Any) -> CTBarGrouping:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}grouping`` -> :class:`docx4j_py.dml.chart.CTBarGrouping`, the CTBarGrouping form."""
    return CTBarGrouping(**kwargs)

def h(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}h`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def hMode(**kwargs: Any) -> CTLayoutMode:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}hMode`` -> :class:`docx4j_py.dml.chart.CTLayoutMode`."""
    return CTLayoutMode(**kwargs)

def hPercent(**kwargs: Any) -> CTHPercent:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}hPercent`` -> :class:`docx4j_py.dml.chart.CTHPercent`."""
    return CTHPercent(**kwargs)

def headerFooter(**kwargs: Any) -> CTHeaderFooter:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}headerFooter`` -> :class:`docx4j_py.dml.chart.CTHeaderFooter`."""
    return CTHeaderFooter(**kwargs)

def hiLowLines(**kwargs: Any) -> CTChartLines:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}hiLowLines`` -> :class:`docx4j_py.dml.chart.CTChartLines`."""
    return CTChartLines(**kwargs)

def holeSize(**kwargs: Any) -> CTHoleSize:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}holeSize`` -> :class:`docx4j_py.dml.chart.CTHoleSize`."""
    return CTHoleSize(**kwargs)

def idx(**kwargs: Any) -> CTUnsignedInt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}idx`` -> :class:`docx4j_py.dml.chart.CTUnsignedInt`."""
    return CTUnsignedInt(**kwargs)

def intercept(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}intercept`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def invertIfNegative(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}invertIfNegative`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def lang(**kwargs: Any) -> CTTextLanguageID:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}lang`` -> :class:`docx4j_py.dml.chart.CTTextLanguageID`."""
    return CTTextLanguageID(**kwargs)

def layout(**kwargs: Any) -> CTLayout:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}layout`` -> :class:`docx4j_py.dml.chart.CTLayout`."""
    return CTLayout(**kwargs)

def layoutTarget(**kwargs: Any) -> CTLayoutTarget:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}layoutTarget`` -> :class:`docx4j_py.dml.chart.CTLayoutTarget`."""
    return CTLayoutTarget(**kwargs)

def lblAlgn(**kwargs: Any) -> CTLblAlgn:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}lblAlgn`` -> :class:`docx4j_py.dml.chart.CTLblAlgn`."""
    return CTLblAlgn(**kwargs)

def lblOffset(**kwargs: Any) -> CTLblOffset:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}lblOffset`` -> :class:`docx4j_py.dml.chart.CTLblOffset`."""
    return CTLblOffset(**kwargs)

def leaderLines(**kwargs: Any) -> CTChartLines:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}leaderLines`` -> :class:`docx4j_py.dml.chart.CTChartLines`."""
    return CTChartLines(**kwargs)

def legacyDrawingHF(**kwargs: Any) -> CTRelId:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}legacyDrawingHF`` -> :class:`docx4j_py.dml.chart.CTRelId`."""
    return CTRelId(**kwargs)

def legend(**kwargs: Any) -> CTLegend:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}legend`` -> :class:`docx4j_py.dml.chart.CTLegend`."""
    return CTLegend(**kwargs)

def legendEntry(**kwargs: Any) -> CTLegendEntry:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}legendEntry`` -> :class:`docx4j_py.dml.chart.CTLegendEntry`."""
    return CTLegendEntry(**kwargs)

def legendPos(**kwargs: Any) -> CTLegendPos:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}legendPos`` -> :class:`docx4j_py.dml.chart.CTLegendPos`."""
    return CTLegendPos(**kwargs)

def line3DChart(**kwargs: Any) -> CTLine3DChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}line3DChart`` -> :class:`docx4j_py.dml.chart.CTLine3DChart`."""
    return CTLine3DChart(**kwargs)

def lineChart(**kwargs: Any) -> CTLineChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}lineChart`` -> :class:`docx4j_py.dml.chart.CTLineChart`."""
    return CTLineChart(**kwargs)

def logBase(**kwargs: Any) -> CTLogBase:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}logBase`` -> :class:`docx4j_py.dml.chart.CTLogBase`."""
    return CTLogBase(**kwargs)

def lvl(**kwargs: Any) -> CTLvl:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}lvl`` -> :class:`docx4j_py.dml.chart.CTLvl`."""
    return CTLvl(**kwargs)

def majorGridlines(**kwargs: Any) -> CTChartLines:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}majorGridlines`` -> :class:`docx4j_py.dml.chart.CTChartLines`."""
    return CTChartLines(**kwargs)

def majorTickMark(**kwargs: Any) -> CTTickMark:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}majorTickMark`` -> :class:`docx4j_py.dml.chart.CTTickMark`."""
    return CTTickMark(**kwargs)

def majorTimeUnit(**kwargs: Any) -> CTTimeUnit:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}majorTimeUnit`` -> :class:`docx4j_py.dml.chart.CTTimeUnit`."""
    return CTTimeUnit(**kwargs)

def majorUnit(**kwargs: Any) -> CTAxisUnit:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}majorUnit`` -> :class:`docx4j_py.dml.chart.CTAxisUnit`."""
    return CTAxisUnit(**kwargs)

def manualLayout(**kwargs: Any) -> CTManualLayout:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}manualLayout`` -> :class:`docx4j_py.dml.chart.CTManualLayout`."""
    return CTManualLayout(**kwargs)

def marker(**kwargs: Any) -> CTMarker:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}marker`` -> :class:`docx4j_py.dml.chart.CTMarker`, the most reachable scope of 2 classes this name takes; see ``marker_boolean``."""
    return CTMarker(**kwargs)

def marker_boolean(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}marker`` -> :class:`docx4j_py.dml.chart.CTBoolean`, the CTBoolean form."""
    return CTBoolean(**kwargs)

def max_(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}max`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def min_(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}min`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def minorGridlines(**kwargs: Any) -> CTChartLines:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}minorGridlines`` -> :class:`docx4j_py.dml.chart.CTChartLines`."""
    return CTChartLines(**kwargs)

def minorTickMark(**kwargs: Any) -> CTTickMark:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}minorTickMark`` -> :class:`docx4j_py.dml.chart.CTTickMark`."""
    return CTTickMark(**kwargs)

def minorTimeUnit(**kwargs: Any) -> CTTimeUnit:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}minorTimeUnit`` -> :class:`docx4j_py.dml.chart.CTTimeUnit`."""
    return CTTimeUnit(**kwargs)

def minorUnit(**kwargs: Any) -> CTAxisUnit:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}minorUnit`` -> :class:`docx4j_py.dml.chart.CTAxisUnit`."""
    return CTAxisUnit(**kwargs)

def minus(**kwargs: Any) -> CTNumDataSource:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}minus`` -> :class:`docx4j_py.dml.chart.CTNumDataSource`."""
    return CTNumDataSource(**kwargs)

def multiLvlStrCache(**kwargs: Any) -> CTMultiLvlStrData:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}multiLvlStrCache`` -> :class:`docx4j_py.dml.chart.CTMultiLvlStrData`."""
    return CTMultiLvlStrData(**kwargs)

def multiLvlStrRef(**kwargs: Any) -> CTMultiLvlStrRef:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}multiLvlStrRef`` -> :class:`docx4j_py.dml.chart.CTMultiLvlStrRef`."""
    return CTMultiLvlStrRef(**kwargs)

def noEndCap(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}noEndCap`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def noMultiLvlLbl(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}noMultiLvlLbl`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def numCache(**kwargs: Any) -> CTNumData:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}numCache`` -> :class:`docx4j_py.dml.chart.CTNumData`."""
    return CTNumData(**kwargs)

def numFmt(**kwargs: Any) -> CTNumFmt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}numFmt`` -> :class:`docx4j_py.dml.chart.CTNumFmt`."""
    return CTNumFmt(**kwargs)

def numLit(**kwargs: Any) -> CTNumData:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}numLit`` -> :class:`docx4j_py.dml.chart.CTNumData`."""
    return CTNumData(**kwargs)

def numRef(**kwargs: Any) -> CTNumRef:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}numRef`` -> :class:`docx4j_py.dml.chart.CTNumRef`."""
    return CTNumRef(**kwargs)

def ofPieChart(**kwargs: Any) -> CTOfPieChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ofPieChart`` -> :class:`docx4j_py.dml.chart.CTOfPieChart`."""
    return CTOfPieChart(**kwargs)

def ofPieType(**kwargs: Any) -> CTOfPieType:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ofPieType`` -> :class:`docx4j_py.dml.chart.CTOfPieType`."""
    return CTOfPieType(**kwargs)

def order(**kwargs: Any) -> CTUnsignedInt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}order`` -> :class:`docx4j_py.dml.chart.CTUnsignedInt`, the most reachable scope of 2 classes this name takes; see ``order_order``."""
    return CTUnsignedInt(**kwargs)

def order_order(**kwargs: Any) -> CTOrder:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}order`` -> :class:`docx4j_py.dml.chart.CTOrder`, the CTOrder form."""
    return CTOrder(**kwargs)

def orientation(**kwargs: Any) -> CTOrientation:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}orientation`` -> :class:`docx4j_py.dml.chart.CTOrientation`."""
    return CTOrientation(**kwargs)

def overlap(**kwargs: Any) -> CTOverlap:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}overlap`` -> :class:`docx4j_py.dml.chart.CTOverlap`."""
    return CTOverlap(**kwargs)

def overlay(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}overlay`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def pageMargins(**kwargs: Any) -> CTPageMargins:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pageMargins`` -> :class:`docx4j_py.dml.chart.CTPageMargins`."""
    return CTPageMargins(**kwargs)

def pageSetup(**kwargs: Any) -> CTPageSetup:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pageSetup`` -> :class:`docx4j_py.dml.chart.CTPageSetup`."""
    return CTPageSetup(**kwargs)

def period(**kwargs: Any) -> CTPeriod:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}period`` -> :class:`docx4j_py.dml.chart.CTPeriod`."""
    return CTPeriod(**kwargs)

def perspective(**kwargs: Any) -> CTPerspective:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}perspective`` -> :class:`docx4j_py.dml.chart.CTPerspective`."""
    return CTPerspective(**kwargs)

def pictureFormat(**kwargs: Any) -> CTPictureFormat:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pictureFormat`` -> :class:`docx4j_py.dml.chart.CTPictureFormat`."""
    return CTPictureFormat(**kwargs)

def pictureOptions(**kwargs: Any) -> CTPictureOptions:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pictureOptions`` -> :class:`docx4j_py.dml.chart.CTPictureOptions`."""
    return CTPictureOptions(**kwargs)

def pictureStackUnit(**kwargs: Any) -> CTPictureStackUnit:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pictureStackUnit`` -> :class:`docx4j_py.dml.chart.CTPictureStackUnit`."""
    return CTPictureStackUnit(**kwargs)

def pie3DChart(**kwargs: Any) -> CTPie3DChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pie3DChart`` -> :class:`docx4j_py.dml.chart.CTPie3DChart`."""
    return CTPie3DChart(**kwargs)

def pieChart(**kwargs: Any) -> CTPieChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pieChart`` -> :class:`docx4j_py.dml.chart.CTPieChart`."""
    return CTPieChart(**kwargs)

def pivotFmt(**kwargs: Any) -> CTPivotFmt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pivotFmt`` -> :class:`docx4j_py.dml.chart.CTPivotFmt`."""
    return CTPivotFmt(**kwargs)

def pivotFmts(**kwargs: Any) -> CTPivotFmts:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pivotFmts`` -> :class:`docx4j_py.dml.chart.CTPivotFmts`."""
    return CTPivotFmts(**kwargs)

def pivotSource(**kwargs: Any) -> CTPivotSource:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pivotSource`` -> :class:`docx4j_py.dml.chart.CTPivotSource`."""
    return CTPivotSource(**kwargs)

def plotArea(**kwargs: Any) -> CTPlotArea:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}plotArea`` -> :class:`docx4j_py.dml.chart.CTPlotArea`."""
    return CTPlotArea(**kwargs)

def plotVisOnly(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}plotVisOnly`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def plus(**kwargs: Any) -> CTNumDataSource:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}plus`` -> :class:`docx4j_py.dml.chart.CTNumDataSource`."""
    return CTNumDataSource(**kwargs)

def printSettings(**kwargs: Any) -> CTPrintSettings:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}printSettings`` -> :class:`docx4j_py.dml.chart.CTPrintSettings`."""
    return CTPrintSettings(**kwargs)

def protection(**kwargs: Any) -> CTProtection:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}protection`` -> :class:`docx4j_py.dml.chart.CTProtection`."""
    return CTProtection(**kwargs)

def pt(**kwargs: Any) -> CTStrVal:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pt`` -> :class:`docx4j_py.dml.chart.CTStrVal`, the most reachable scope of 2 classes this name takes; see ``num_val``."""
    return CTStrVal(**kwargs)

def num_val(**kwargs: Any) -> CTNumVal:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}pt`` -> :class:`docx4j_py.dml.chart.CTNumVal`, the CTNumVal form."""
    return CTNumVal(**kwargs)

def ptCount(**kwargs: Any) -> CTUnsignedInt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ptCount`` -> :class:`docx4j_py.dml.chart.CTUnsignedInt`."""
    return CTUnsignedInt(**kwargs)

def rAngAx(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}rAngAx`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def radarChart(**kwargs: Any) -> CTRadarChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}radarChart`` -> :class:`docx4j_py.dml.chart.CTRadarChart`."""
    return CTRadarChart(**kwargs)

def radarStyle(**kwargs: Any) -> CTRadarStyle:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}radarStyle`` -> :class:`docx4j_py.dml.chart.CTRadarStyle`."""
    return CTRadarStyle(**kwargs)

def rich(**kwargs: Any) -> CTTextBody:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}rich`` -> :class:`docx4j_py.dml.main.CTTextBody`."""
    return CTTextBody(**kwargs)

def rotX(**kwargs: Any) -> CTRotX:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}rotX`` -> :class:`docx4j_py.dml.chart.CTRotX`."""
    return CTRotX(**kwargs)

def rotY(**kwargs: Any) -> CTRotY:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}rotY`` -> :class:`docx4j_py.dml.chart.CTRotY`."""
    return CTRotY(**kwargs)

def roundedCorners(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}roundedCorners`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def scaling(**kwargs: Any) -> CTScaling:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}scaling`` -> :class:`docx4j_py.dml.chart.CTScaling`."""
    return CTScaling(**kwargs)

def scatterChart(**kwargs: Any) -> CTScatterChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}scatterChart`` -> :class:`docx4j_py.dml.chart.CTScatterChart`."""
    return CTScatterChart(**kwargs)

def scatterStyle(**kwargs: Any) -> CTScatterStyle:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}scatterStyle`` -> :class:`docx4j_py.dml.chart.CTScatterStyle`."""
    return CTScatterStyle(**kwargs)

def secondPiePt(**kwargs: Any) -> CTUnsignedInt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}secondPiePt`` -> :class:`docx4j_py.dml.chart.CTUnsignedInt`."""
    return CTUnsignedInt(**kwargs)

def secondPieSize(**kwargs: Any) -> CTSecondPieSize:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}secondPieSize`` -> :class:`docx4j_py.dml.chart.CTSecondPieSize`."""
    return CTSecondPieSize(**kwargs)

def selection(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}selection`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def ser(**kwargs: Any) -> CTPieSer:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ser`` -> :class:`docx4j_py.dml.chart.CTPieSer`, the most reachable scope of 8 classes this name takes; see ``area_ser``, ``bar_ser``, ``bubble_ser``, ``line_ser``, ``radar_ser``, ``scatter_ser``, ``surface_ser``."""
    return CTPieSer(**kwargs)

def area_ser(**kwargs: Any) -> CTAreaSer:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ser`` -> :class:`docx4j_py.dml.chart.CTAreaSer`, the CTAreaSer form."""
    return CTAreaSer(**kwargs)

def bar_ser(**kwargs: Any) -> CTBarSer:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ser`` -> :class:`docx4j_py.dml.chart.CTBarSer`, the CTBarSer form."""
    return CTBarSer(**kwargs)

def bubble_ser(**kwargs: Any) -> CTBubbleSer:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ser`` -> :class:`docx4j_py.dml.chart.CTBubbleSer`, the CTBubbleSer form."""
    return CTBubbleSer(**kwargs)

def line_ser(**kwargs: Any) -> CTLineSer:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ser`` -> :class:`docx4j_py.dml.chart.CTLineSer`, the CTLineSer form."""
    return CTLineSer(**kwargs)

def radar_ser(**kwargs: Any) -> CTRadarSer:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ser`` -> :class:`docx4j_py.dml.chart.CTRadarSer`, the CTRadarSer form."""
    return CTRadarSer(**kwargs)

def scatter_ser(**kwargs: Any) -> CTScatterSer:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ser`` -> :class:`docx4j_py.dml.chart.CTScatterSer`, the CTScatterSer form."""
    return CTScatterSer(**kwargs)

def surface_ser(**kwargs: Any) -> CTSurfaceSer:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}ser`` -> :class:`docx4j_py.dml.chart.CTSurfaceSer`, the CTSurfaceSer form."""
    return CTSurfaceSer(**kwargs)

def serAx(**kwargs: Any) -> CTSerAx:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}serAx`` -> :class:`docx4j_py.dml.chart.CTSerAx`."""
    return CTSerAx(**kwargs)

def serLines(**kwargs: Any) -> CTChartLines:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}serLines`` -> :class:`docx4j_py.dml.chart.CTChartLines`."""
    return CTChartLines(**kwargs)

def shape(**kwargs: Any) -> CTShape:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}shape`` -> :class:`docx4j_py.dml.chart.CTShape`."""
    return CTShape(**kwargs)

def showBubbleSize(**kwargs: Any) -> ShowBubbleSize:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showBubbleSize`` -> :class:`docx4j_py.dml.chart.ShowBubbleSize`."""
    return ShowBubbleSize(**kwargs)

def showCatName(**kwargs: Any) -> ShowCatName:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showCatName`` -> :class:`docx4j_py.dml.chart.ShowCatName`."""
    return ShowCatName(**kwargs)

def showDLblsOverMax(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showDLblsOverMax`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def showHorzBorder(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showHorzBorder`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def showKeys(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showKeys`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def showLeaderLines(**kwargs: Any) -> ShowLeaderLines:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showLeaderLines`` -> :class:`docx4j_py.dml.chart.ShowLeaderLines`."""
    return ShowLeaderLines(**kwargs)

def showLegendKey(**kwargs: Any) -> ShowLegendKey:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showLegendKey`` -> :class:`docx4j_py.dml.chart.ShowLegendKey`."""
    return ShowLegendKey(**kwargs)

def showNegBubbles(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showNegBubbles`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def showOutline(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showOutline`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def showPercent(**kwargs: Any) -> ShowPercent:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showPercent`` -> :class:`docx4j_py.dml.chart.ShowPercent`."""
    return ShowPercent(**kwargs)

def showSerName(**kwargs: Any) -> ShowSerName:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showSerName`` -> :class:`docx4j_py.dml.chart.ShowSerName`."""
    return ShowSerName(**kwargs)

def showVal(**kwargs: Any) -> ShowVal:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showVal`` -> :class:`docx4j_py.dml.chart.ShowVal`."""
    return ShowVal(**kwargs)

def showVertBorder(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}showVertBorder`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def sideWall(**kwargs: Any) -> CTSurface:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}sideWall`` -> :class:`docx4j_py.dml.chart.CTSurface`."""
    return CTSurface(**kwargs)

def size(**kwargs: Any) -> CTMarkerSize:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}size`` -> :class:`docx4j_py.dml.chart.CTMarkerSize`."""
    return CTMarkerSize(**kwargs)

def sizeRepresents(**kwargs: Any) -> CTSizeRepresents:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}sizeRepresents`` -> :class:`docx4j_py.dml.chart.CTSizeRepresents`."""
    return CTSizeRepresents(**kwargs)

def smooth(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}smooth`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def spPr(**kwargs: Any) -> CTShapeProperties:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}spPr`` -> :class:`docx4j_py.dml.main.CTShapeProperties`."""
    return CTShapeProperties(**kwargs)

def splitPos(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}splitPos`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def splitType(**kwargs: Any) -> CTSplitType:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}splitType`` -> :class:`docx4j_py.dml.chart.CTSplitType`."""
    return CTSplitType(**kwargs)

def stockChart(**kwargs: Any) -> CTStockChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}stockChart`` -> :class:`docx4j_py.dml.chart.CTStockChart`."""
    return CTStockChart(**kwargs)

def strCache(**kwargs: Any) -> CTStrData:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}strCache`` -> :class:`docx4j_py.dml.chart.CTStrData`."""
    return CTStrData(**kwargs)

def strLit(**kwargs: Any) -> CTStrData:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}strLit`` -> :class:`docx4j_py.dml.chart.CTStrData`."""
    return CTStrData(**kwargs)

def strRef(**kwargs: Any) -> CTStrRef:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}strRef`` -> :class:`docx4j_py.dml.chart.CTStrRef`."""
    return CTStrRef(**kwargs)

def style(**kwargs: Any) -> CTStyle:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}style`` -> :class:`docx4j_py.dml.chart.CTStyle`."""
    return CTStyle(**kwargs)

def surface3DChart(**kwargs: Any) -> CTSurface3DChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}surface3DChart`` -> :class:`docx4j_py.dml.chart.CTSurface3DChart`."""
    return CTSurface3DChart(**kwargs)

def surfaceChart(**kwargs: Any) -> CTSurfaceChart:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}surfaceChart`` -> :class:`docx4j_py.dml.chart.CTSurfaceChart`."""
    return CTSurfaceChart(**kwargs)

def symbol(**kwargs: Any) -> CTMarkerStyle:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}symbol`` -> :class:`docx4j_py.dml.chart.CTMarkerStyle`."""
    return CTMarkerStyle(**kwargs)

def thickness(**kwargs: Any) -> CTUnsignedInt:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}thickness`` -> :class:`docx4j_py.dml.chart.CTUnsignedInt`."""
    return CTUnsignedInt(**kwargs)

def tickLblPos(**kwargs: Any) -> CTTickLblPos:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}tickLblPos`` -> :class:`docx4j_py.dml.chart.CTTickLblPos`."""
    return CTTickLblPos(**kwargs)

def tickLblSkip(**kwargs: Any) -> CTSkip:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}tickLblSkip`` -> :class:`docx4j_py.dml.chart.CTSkip`."""
    return CTSkip(**kwargs)

def tickMarkSkip(**kwargs: Any) -> CTSkip:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}tickMarkSkip`` -> :class:`docx4j_py.dml.chart.CTSkip`."""
    return CTSkip(**kwargs)

def title(**kwargs: Any) -> CTTitle:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}title`` -> :class:`docx4j_py.dml.chart.CTTitle`."""
    return CTTitle(**kwargs)

def trendline(**kwargs: Any) -> CTTrendline:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}trendline`` -> :class:`docx4j_py.dml.chart.CTTrendline`."""
    return CTTrendline(**kwargs)

def trendlineLbl(**kwargs: Any) -> CTTrendlineLbl:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}trendlineLbl`` -> :class:`docx4j_py.dml.chart.CTTrendlineLbl`."""
    return CTTrendlineLbl(**kwargs)

def trendlineType(**kwargs: Any) -> CTTrendlineType:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}trendlineType`` -> :class:`docx4j_py.dml.chart.CTTrendlineType`."""
    return CTTrendlineType(**kwargs)

def tx(**kwargs: Any) -> CTSerTx:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}tx`` -> :class:`docx4j_py.dml.chart.CTSerTx`, the most reachable scope of 2 classes this name takes; see ``tx_tx``."""
    return CTSerTx(**kwargs)

def tx_tx(**kwargs: Any) -> CTTx:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}tx`` -> :class:`docx4j_py.dml.chart.CTTx`, the CTTx form."""
    return CTTx(**kwargs)

def txPr(**kwargs: Any) -> CTTextBody:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}txPr`` -> :class:`docx4j_py.dml.main.CTTextBody`."""
    return CTTextBody(**kwargs)

def upBars(**kwargs: Any) -> CTUpDownBar:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}upBars`` -> :class:`docx4j_py.dml.chart.CTUpDownBar`."""
    return CTUpDownBar(**kwargs)

def upDownBars(**kwargs: Any) -> CTUpDownBars:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}upDownBars`` -> :class:`docx4j_py.dml.chart.CTUpDownBars`."""
    return CTUpDownBars(**kwargs)

def userInterface(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}userInterface`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def userShapes(**kwargs: Any) -> CTDrawing:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}userShapes`` -> :class:`docx4j_py.dml.chart.CTDrawing`, the global element declaration of 2 classes this name takes; see ``rel_id``."""
    return CTDrawing(**kwargs)

def rel_id(**kwargs: Any) -> CTRelId:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}userShapes`` -> :class:`docx4j_py.dml.chart.CTRelId`, the CTRelId form."""
    return CTRelId(**kwargs)

def val(**kwargs: Any) -> CTNumDataSource:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}val`` -> :class:`docx4j_py.dml.chart.CTNumDataSource`, the most reachable scope of 2 classes this name takes; see ``double``."""
    return CTNumDataSource(**kwargs)

def double(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}val`` -> :class:`docx4j_py.dml.chart.CTDouble`, the CTDouble form."""
    return CTDouble(**kwargs)

def valAx(**kwargs: Any) -> CTValAx:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}valAx`` -> :class:`docx4j_py.dml.chart.CTValAx`."""
    return CTValAx(**kwargs)

def varyColors(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}varyColors`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def view3D(**kwargs: Any) -> CTView3D:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}view3D`` -> :class:`docx4j_py.dml.chart.CTView3D`."""
    return CTView3D(**kwargs)

def w(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}w`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def wMode(**kwargs: Any) -> CTLayoutMode:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}wMode`` -> :class:`docx4j_py.dml.chart.CTLayoutMode`."""
    return CTLayoutMode(**kwargs)

def wireframe(**kwargs: Any) -> CTBoolean:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}wireframe`` -> :class:`docx4j_py.dml.chart.CTBoolean`."""
    return CTBoolean(**kwargs)

def x(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}x`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def xMode(**kwargs: Any) -> CTLayoutMode:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}xMode`` -> :class:`docx4j_py.dml.chart.CTLayoutMode`."""
    return CTLayoutMode(**kwargs)

def xVal(**kwargs: Any) -> CTAxDataSource:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}xVal`` -> :class:`docx4j_py.dml.chart.CTAxDataSource`."""
    return CTAxDataSource(**kwargs)

def y(**kwargs: Any) -> CTDouble:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}y`` -> :class:`docx4j_py.dml.chart.CTDouble`."""
    return CTDouble(**kwargs)

def yMode(**kwargs: Any) -> CTLayoutMode:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}yMode`` -> :class:`docx4j_py.dml.chart.CTLayoutMode`."""
    return CTLayoutMode(**kwargs)

def yVal(**kwargs: Any) -> CTNumDataSource:
    """``{http://schemas.openxmlformats.org/drawingml/2006/chart}yVal`` -> :class:`docx4j_py.dml.chart.CTNumDataSource`."""
    return CTNumDataSource(**kwargs)

#: Element qualified name -> the class ``el.<name>`` builds.
QNAME_TO_CLASS: dict[str, type] = {
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}applyToEnd": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}applyToFront": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}applyToSides": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}area3DChart": CTArea3DChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}areaChart": CTAreaChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}auto": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}autoTitleDeleted": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}autoUpdate": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}axId": CTUnsignedInt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}axPos": CTAxPos,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}backWall": CTSurface,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}backward": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}bandFmt": CTBandFmt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}bandFmts": CTBandFmts,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}bar3DChart": CTBar3DChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}barChart": CTBarChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}barDir": CTBarDir,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}baseTimeUnit": CTTimeUnit,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}bubble3D": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}bubbleChart": CTBubbleChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}bubbleScale": CTBubbleScale,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}bubbleSize": CTNumDataSource,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}builtInUnit": CTBuiltInUnit,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}cat": CTAxDataSource,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}catAx": CTCatAx,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}chart": Chart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}chartObject": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}chartSpace": ChartSpace,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}clrMapOvr": CTColorMapping,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}crossAx": CTUnsignedInt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}crossBetween": CTCrossBetween,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}crosses": CTCrosses,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}crossesAt": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}custSplit": CTCustSplit,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}custUnit": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dLbl": CTDLbl,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dLblPos": CTDLblPos,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dLbls": CTDLbls,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dPt": CTDPt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dTable": CTDTable,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}data": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}date1904": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dateAx": CTDateAx,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}delete": Delete,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}depthPercent": CTDepthPercent,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dispBlanksAs": CTDispBlanksAs,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dispEq": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dispRSqr": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dispUnits": CTDispUnits,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dispUnitsLbl": CTDispUnitsLbl,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}doughnutChart": CTDoughnutChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}downBars": CTUpDownBar,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}dropLines": CTChartLines,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}errBarType": CTErrBarType,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}errBars": CTErrBars,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}errDir": CTErrDir,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}errValType": CTErrValType,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}explosion": CTUnsignedInt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}ext": CTExtension,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}extLst": CTExtensionList,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}externalData": CTExternalData,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}firstSliceAng": CTFirstSliceAng,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}floor": CTSurface,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}fmtId": CTUnsignedInt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}formatting": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}forward": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}gapDepth": CTGapAmount,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}gapWidth": CTGapAmount,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}grouping": CTGrouping,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}h": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}hMode": CTLayoutMode,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}hPercent": CTHPercent,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}headerFooter": CTHeaderFooter,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}hiLowLines": CTChartLines,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}holeSize": CTHoleSize,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}idx": CTUnsignedInt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}intercept": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}invertIfNegative": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}lang": CTTextLanguageID,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}layout": CTLayout,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}layoutTarget": CTLayoutTarget,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}lblAlgn": CTLblAlgn,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}lblOffset": CTLblOffset,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}leaderLines": CTChartLines,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}legacyDrawingHF": CTRelId,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}legend": CTLegend,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}legendEntry": CTLegendEntry,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}legendPos": CTLegendPos,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}line3DChart": CTLine3DChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}lineChart": CTLineChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}logBase": CTLogBase,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}lvl": CTLvl,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}majorGridlines": CTChartLines,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}majorTickMark": CTTickMark,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}majorTimeUnit": CTTimeUnit,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}majorUnit": CTAxisUnit,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}manualLayout": CTManualLayout,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}marker": CTMarker,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}max": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}min": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}minorGridlines": CTChartLines,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}minorTickMark": CTTickMark,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}minorTimeUnit": CTTimeUnit,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}minorUnit": CTAxisUnit,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}minus": CTNumDataSource,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}multiLvlStrCache": CTMultiLvlStrData,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}multiLvlStrRef": CTMultiLvlStrRef,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}noEndCap": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}noMultiLvlLbl": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}numCache": CTNumData,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}numFmt": CTNumFmt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}numLit": CTNumData,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}numRef": CTNumRef,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}ofPieChart": CTOfPieChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}ofPieType": CTOfPieType,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}order": CTUnsignedInt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}orientation": CTOrientation,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}overlap": CTOverlap,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}overlay": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pageMargins": CTPageMargins,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pageSetup": CTPageSetup,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}period": CTPeriod,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}perspective": CTPerspective,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pictureFormat": CTPictureFormat,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pictureOptions": CTPictureOptions,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pictureStackUnit": CTPictureStackUnit,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pie3DChart": CTPie3DChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pieChart": CTPieChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pivotFmt": CTPivotFmt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pivotFmts": CTPivotFmts,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pivotSource": CTPivotSource,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}plotArea": CTPlotArea,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}plotVisOnly": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}plus": CTNumDataSource,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}printSettings": CTPrintSettings,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}protection": CTProtection,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}pt": CTStrVal,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}ptCount": CTUnsignedInt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}rAngAx": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}radarChart": CTRadarChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}radarStyle": CTRadarStyle,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}rich": CTTextBody,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}rotX": CTRotX,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}rotY": CTRotY,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}roundedCorners": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}scaling": CTScaling,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}scatterChart": CTScatterChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}scatterStyle": CTScatterStyle,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}secondPiePt": CTUnsignedInt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}secondPieSize": CTSecondPieSize,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}selection": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}ser": CTPieSer,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}serAx": CTSerAx,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}serLines": CTChartLines,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}shape": CTShape,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showBubbleSize": ShowBubbleSize,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showCatName": ShowCatName,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showDLblsOverMax": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showHorzBorder": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showKeys": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showLeaderLines": ShowLeaderLines,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showLegendKey": ShowLegendKey,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showNegBubbles": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showOutline": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showPercent": ShowPercent,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showSerName": ShowSerName,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showVal": ShowVal,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}showVertBorder": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}sideWall": CTSurface,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}size": CTMarkerSize,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}sizeRepresents": CTSizeRepresents,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}smooth": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}spPr": CTShapeProperties,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}splitPos": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}splitType": CTSplitType,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}stockChart": CTStockChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}strCache": CTStrData,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}strLit": CTStrData,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}strRef": CTStrRef,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}style": CTStyle,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}surface3DChart": CTSurface3DChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}surfaceChart": CTSurfaceChart,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}symbol": CTMarkerStyle,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}thickness": CTUnsignedInt,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}tickLblPos": CTTickLblPos,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}tickLblSkip": CTSkip,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}tickMarkSkip": CTSkip,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}title": CTTitle,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}trendline": CTTrendline,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}trendlineLbl": CTTrendlineLbl,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}trendlineType": CTTrendlineType,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}tx": CTSerTx,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}txPr": CTTextBody,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}upBars": CTUpDownBar,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}upDownBars": CTUpDownBars,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}userInterface": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}userShapes": CTDrawing,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}val": CTNumDataSource,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}valAx": CTValAx,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}varyColors": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}view3D": CTView3D,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}w": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}wMode": CTLayoutMode,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}wireframe": CTBoolean,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}x": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}xMode": CTLayoutMode,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}xVal": CTAxDataSource,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}y": CTDouble,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}yMode": CTLayoutMode,
    "{http://schemas.openxmlformats.org/drawingml/2006/chart}yVal": CTNumDataSource,
}

#: Local element name -> the class ``el.<name>`` builds.
ELEMENTS: dict[str, type] = {
    "applyToEnd": CTBoolean,
    "applyToFront": CTBoolean,
    "applyToSides": CTBoolean,
    "area3DChart": CTArea3DChart,
    "areaChart": CTAreaChart,
    "auto": CTBoolean,
    "autoTitleDeleted": CTBoolean,
    "autoUpdate": CTBoolean,
    "axId": CTUnsignedInt,
    "axPos": CTAxPos,
    "backWall": CTSurface,
    "backward": CTDouble,
    "bandFmt": CTBandFmt,
    "bandFmts": CTBandFmts,
    "bar3DChart": CTBar3DChart,
    "barChart": CTBarChart,
    "barDir": CTBarDir,
    "baseTimeUnit": CTTimeUnit,
    "bubble3D": CTBoolean,
    "bubbleChart": CTBubbleChart,
    "bubbleScale": CTBubbleScale,
    "bubbleSize": CTNumDataSource,
    "builtInUnit": CTBuiltInUnit,
    "cat": CTAxDataSource,
    "catAx": CTCatAx,
    "chart": Chart,
    "chartObject": CTBoolean,
    "chartSpace": ChartSpace,
    "clrMapOvr": CTColorMapping,
    "crossAx": CTUnsignedInt,
    "crossBetween": CTCrossBetween,
    "crosses": CTCrosses,
    "crossesAt": CTDouble,
    "custSplit": CTCustSplit,
    "custUnit": CTDouble,
    "dLbl": CTDLbl,
    "dLblPos": CTDLblPos,
    "dLbls": CTDLbls,
    "dPt": CTDPt,
    "dTable": CTDTable,
    "data": CTBoolean,
    "date1904": CTBoolean,
    "dateAx": CTDateAx,
    "delete": Delete,
    "depthPercent": CTDepthPercent,
    "dispBlanksAs": CTDispBlanksAs,
    "dispEq": CTBoolean,
    "dispRSqr": CTBoolean,
    "dispUnits": CTDispUnits,
    "dispUnitsLbl": CTDispUnitsLbl,
    "doughnutChart": CTDoughnutChart,
    "downBars": CTUpDownBar,
    "dropLines": CTChartLines,
    "errBarType": CTErrBarType,
    "errBars": CTErrBars,
    "errDir": CTErrDir,
    "errValType": CTErrValType,
    "explosion": CTUnsignedInt,
    "ext": CTExtension,
    "extLst": CTExtensionList,
    "externalData": CTExternalData,
    "firstSliceAng": CTFirstSliceAng,
    "floor": CTSurface,
    "fmtId": CTUnsignedInt,
    "formatting": CTBoolean,
    "forward": CTDouble,
    "gapDepth": CTGapAmount,
    "gapWidth": CTGapAmount,
    "grouping": CTGrouping,
    "h": CTDouble,
    "hMode": CTLayoutMode,
    "hPercent": CTHPercent,
    "headerFooter": CTHeaderFooter,
    "hiLowLines": CTChartLines,
    "holeSize": CTHoleSize,
    "idx": CTUnsignedInt,
    "intercept": CTDouble,
    "invertIfNegative": CTBoolean,
    "lang": CTTextLanguageID,
    "layout": CTLayout,
    "layoutTarget": CTLayoutTarget,
    "lblAlgn": CTLblAlgn,
    "lblOffset": CTLblOffset,
    "leaderLines": CTChartLines,
    "legacyDrawingHF": CTRelId,
    "legend": CTLegend,
    "legendEntry": CTLegendEntry,
    "legendPos": CTLegendPos,
    "line3DChart": CTLine3DChart,
    "lineChart": CTLineChart,
    "logBase": CTLogBase,
    "lvl": CTLvl,
    "majorGridlines": CTChartLines,
    "majorTickMark": CTTickMark,
    "majorTimeUnit": CTTimeUnit,
    "majorUnit": CTAxisUnit,
    "manualLayout": CTManualLayout,
    "marker": CTMarker,
    "max": CTDouble,
    "min": CTDouble,
    "minorGridlines": CTChartLines,
    "minorTickMark": CTTickMark,
    "minorTimeUnit": CTTimeUnit,
    "minorUnit": CTAxisUnit,
    "minus": CTNumDataSource,
    "multiLvlStrCache": CTMultiLvlStrData,
    "multiLvlStrRef": CTMultiLvlStrRef,
    "noEndCap": CTBoolean,
    "noMultiLvlLbl": CTBoolean,
    "numCache": CTNumData,
    "numFmt": CTNumFmt,
    "numLit": CTNumData,
    "numRef": CTNumRef,
    "ofPieChart": CTOfPieChart,
    "ofPieType": CTOfPieType,
    "order": CTUnsignedInt,
    "orientation": CTOrientation,
    "overlap": CTOverlap,
    "overlay": CTBoolean,
    "pageMargins": CTPageMargins,
    "pageSetup": CTPageSetup,
    "period": CTPeriod,
    "perspective": CTPerspective,
    "pictureFormat": CTPictureFormat,
    "pictureOptions": CTPictureOptions,
    "pictureStackUnit": CTPictureStackUnit,
    "pie3DChart": CTPie3DChart,
    "pieChart": CTPieChart,
    "pivotFmt": CTPivotFmt,
    "pivotFmts": CTPivotFmts,
    "pivotSource": CTPivotSource,
    "plotArea": CTPlotArea,
    "plotVisOnly": CTBoolean,
    "plus": CTNumDataSource,
    "printSettings": CTPrintSettings,
    "protection": CTProtection,
    "pt": CTStrVal,
    "ptCount": CTUnsignedInt,
    "rAngAx": CTBoolean,
    "radarChart": CTRadarChart,
    "radarStyle": CTRadarStyle,
    "rich": CTTextBody,
    "rotX": CTRotX,
    "rotY": CTRotY,
    "roundedCorners": CTBoolean,
    "scaling": CTScaling,
    "scatterChart": CTScatterChart,
    "scatterStyle": CTScatterStyle,
    "secondPiePt": CTUnsignedInt,
    "secondPieSize": CTSecondPieSize,
    "selection": CTBoolean,
    "ser": CTPieSer,
    "serAx": CTSerAx,
    "serLines": CTChartLines,
    "shape": CTShape,
    "showBubbleSize": ShowBubbleSize,
    "showCatName": ShowCatName,
    "showDLblsOverMax": CTBoolean,
    "showHorzBorder": CTBoolean,
    "showKeys": CTBoolean,
    "showLeaderLines": ShowLeaderLines,
    "showLegendKey": ShowLegendKey,
    "showNegBubbles": CTBoolean,
    "showOutline": CTBoolean,
    "showPercent": ShowPercent,
    "showSerName": ShowSerName,
    "showVal": ShowVal,
    "showVertBorder": CTBoolean,
    "sideWall": CTSurface,
    "size": CTMarkerSize,
    "sizeRepresents": CTSizeRepresents,
    "smooth": CTBoolean,
    "spPr": CTShapeProperties,
    "splitPos": CTDouble,
    "splitType": CTSplitType,
    "stockChart": CTStockChart,
    "strCache": CTStrData,
    "strLit": CTStrData,
    "strRef": CTStrRef,
    "style": CTStyle,
    "surface3DChart": CTSurface3DChart,
    "surfaceChart": CTSurfaceChart,
    "symbol": CTMarkerStyle,
    "thickness": CTUnsignedInt,
    "tickLblPos": CTTickLblPos,
    "tickLblSkip": CTSkip,
    "tickMarkSkip": CTSkip,
    "title": CTTitle,
    "trendline": CTTrendline,
    "trendlineLbl": CTTrendlineLbl,
    "trendlineType": CTTrendlineType,
    "tx": CTSerTx,
    "txPr": CTTextBody,
    "upBars": CTUpDownBar,
    "upDownBars": CTUpDownBars,
    "userInterface": CTBoolean,
    "userShapes": CTDrawing,
    "val": CTNumDataSource,
    "valAx": CTValAx,
    "varyColors": CTBoolean,
    "view3D": CTView3D,
    "w": CTDouble,
    "wMode": CTLayoutMode,
    "wireframe": CTBoolean,
    "x": CTDouble,
    "xMode": CTLayoutMode,
    "xVal": CTAxDataSource,
    "y": CTDouble,
    "yMode": CTLayoutMode,
    "yVal": CTNumDataSource,
}

#: Class -> the one element qualified name it stands for, where there is one.
CLASS_TO_QNAME: dict[type, str] = {
    CTArea3DChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}area3DChart",
    CTAreaChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}areaChart",
    CTAreaSer: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ser",
    CTAxPos: "{http://schemas.openxmlformats.org/drawingml/2006/chart}axPos",
    CTBandFmt: "{http://schemas.openxmlformats.org/drawingml/2006/chart}bandFmt",
    CTBandFmts: "{http://schemas.openxmlformats.org/drawingml/2006/chart}bandFmts",
    CTBar3DChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}bar3DChart",
    CTBarChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}barChart",
    CTBarDir: "{http://schemas.openxmlformats.org/drawingml/2006/chart}barDir",
    CTBarGrouping: "{http://schemas.openxmlformats.org/drawingml/2006/chart}grouping",
    CTBarSer: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ser",
    CTBubbleChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}bubbleChart",
    CTBubbleScale: "{http://schemas.openxmlformats.org/drawingml/2006/chart}bubbleScale",
    CTBubbleSer: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ser",
    CTBuiltInUnit: "{http://schemas.openxmlformats.org/drawingml/2006/chart}builtInUnit",
    CTCatAx: "{http://schemas.openxmlformats.org/drawingml/2006/chart}catAx",
    CTChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}chart",
    CTColorMapping: "{http://schemas.openxmlformats.org/drawingml/2006/chart}clrMapOvr",
    CTCrossBetween: "{http://schemas.openxmlformats.org/drawingml/2006/chart}crossBetween",
    CTCrosses: "{http://schemas.openxmlformats.org/drawingml/2006/chart}crosses",
    CTCustSplit: "{http://schemas.openxmlformats.org/drawingml/2006/chart}custSplit",
    CTDLbl: "{http://schemas.openxmlformats.org/drawingml/2006/chart}dLbl",
    CTDLblPos: "{http://schemas.openxmlformats.org/drawingml/2006/chart}dLblPos",
    CTDLbls: "{http://schemas.openxmlformats.org/drawingml/2006/chart}dLbls",
    CTDPt: "{http://schemas.openxmlformats.org/drawingml/2006/chart}dPt",
    CTDTable: "{http://schemas.openxmlformats.org/drawingml/2006/chart}dTable",
    CTDateAx: "{http://schemas.openxmlformats.org/drawingml/2006/chart}dateAx",
    CTDepthPercent: "{http://schemas.openxmlformats.org/drawingml/2006/chart}depthPercent",
    CTDispBlanksAs: "{http://schemas.openxmlformats.org/drawingml/2006/chart}dispBlanksAs",
    CTDispUnits: "{http://schemas.openxmlformats.org/drawingml/2006/chart}dispUnits",
    CTDispUnitsLbl: "{http://schemas.openxmlformats.org/drawingml/2006/chart}dispUnitsLbl",
    CTDoughnutChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}doughnutChart",
    CTDrawing: "{http://schemas.openxmlformats.org/drawingml/2006/chart}userShapes",
    CTErrBarType: "{http://schemas.openxmlformats.org/drawingml/2006/chart}errBarType",
    CTErrBars: "{http://schemas.openxmlformats.org/drawingml/2006/chart}errBars",
    CTErrDir: "{http://schemas.openxmlformats.org/drawingml/2006/chart}errDir",
    CTErrValType: "{http://schemas.openxmlformats.org/drawingml/2006/chart}errValType",
    CTExtension: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ext",
    CTExtensionList: "{http://schemas.openxmlformats.org/drawingml/2006/chart}extLst",
    CTExternalData: "{http://schemas.openxmlformats.org/drawingml/2006/chart}externalData",
    CTFirstSliceAng: "{http://schemas.openxmlformats.org/drawingml/2006/chart}firstSliceAng",
    CTGrouping: "{http://schemas.openxmlformats.org/drawingml/2006/chart}grouping",
    CTHPercent: "{http://schemas.openxmlformats.org/drawingml/2006/chart}hPercent",
    CTHeaderFooter: "{http://schemas.openxmlformats.org/drawingml/2006/chart}headerFooter",
    CTHoleSize: "{http://schemas.openxmlformats.org/drawingml/2006/chart}holeSize",
    CTLayout: "{http://schemas.openxmlformats.org/drawingml/2006/chart}layout",
    CTLayoutTarget: "{http://schemas.openxmlformats.org/drawingml/2006/chart}layoutTarget",
    CTLblAlgn: "{http://schemas.openxmlformats.org/drawingml/2006/chart}lblAlgn",
    CTLblOffset: "{http://schemas.openxmlformats.org/drawingml/2006/chart}lblOffset",
    CTLegend: "{http://schemas.openxmlformats.org/drawingml/2006/chart}legend",
    CTLegendEntry: "{http://schemas.openxmlformats.org/drawingml/2006/chart}legendEntry",
    CTLegendPos: "{http://schemas.openxmlformats.org/drawingml/2006/chart}legendPos",
    CTLine3DChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}line3DChart",
    CTLineChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}lineChart",
    CTLineSer: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ser",
    CTLogBase: "{http://schemas.openxmlformats.org/drawingml/2006/chart}logBase",
    CTLvl: "{http://schemas.openxmlformats.org/drawingml/2006/chart}lvl",
    CTManualLayout: "{http://schemas.openxmlformats.org/drawingml/2006/chart}manualLayout",
    CTMarker: "{http://schemas.openxmlformats.org/drawingml/2006/chart}marker",
    CTMarkerSize: "{http://schemas.openxmlformats.org/drawingml/2006/chart}size",
    CTMarkerStyle: "{http://schemas.openxmlformats.org/drawingml/2006/chart}symbol",
    CTMultiLvlStrData: "{http://schemas.openxmlformats.org/drawingml/2006/chart}multiLvlStrCache",
    CTMultiLvlStrRef: "{http://schemas.openxmlformats.org/drawingml/2006/chart}multiLvlStrRef",
    CTNumFmt: "{http://schemas.openxmlformats.org/drawingml/2006/chart}numFmt",
    CTNumRef: "{http://schemas.openxmlformats.org/drawingml/2006/chart}numRef",
    CTNumVal: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pt",
    CTOfPieChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ofPieChart",
    CTOfPieType: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ofPieType",
    CTOrder: "{http://schemas.openxmlformats.org/drawingml/2006/chart}order",
    CTOrientation: "{http://schemas.openxmlformats.org/drawingml/2006/chart}orientation",
    CTOverlap: "{http://schemas.openxmlformats.org/drawingml/2006/chart}overlap",
    CTPageMargins: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pageMargins",
    CTPageSetup: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pageSetup",
    CTPeriod: "{http://schemas.openxmlformats.org/drawingml/2006/chart}period",
    CTPerspective: "{http://schemas.openxmlformats.org/drawingml/2006/chart}perspective",
    CTPictureFormat: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pictureFormat",
    CTPictureOptions: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pictureOptions",
    CTPictureStackUnit: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pictureStackUnit",
    CTPie3DChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pie3DChart",
    CTPieChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pieChart",
    CTPieSer: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ser",
    CTPivotFmt: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pivotFmt",
    CTPivotFmts: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pivotFmts",
    CTPivotSource: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pivotSource",
    CTPlotArea: "{http://schemas.openxmlformats.org/drawingml/2006/chart}plotArea",
    CTPrintSettings: "{http://schemas.openxmlformats.org/drawingml/2006/chart}printSettings",
    CTProtection: "{http://schemas.openxmlformats.org/drawingml/2006/chart}protection",
    CTRadarChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}radarChart",
    CTRadarSer: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ser",
    CTRadarStyle: "{http://schemas.openxmlformats.org/drawingml/2006/chart}radarStyle",
    CTRotX: "{http://schemas.openxmlformats.org/drawingml/2006/chart}rotX",
    CTRotY: "{http://schemas.openxmlformats.org/drawingml/2006/chart}rotY",
    CTScaling: "{http://schemas.openxmlformats.org/drawingml/2006/chart}scaling",
    CTScatterChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}scatterChart",
    CTScatterSer: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ser",
    CTScatterStyle: "{http://schemas.openxmlformats.org/drawingml/2006/chart}scatterStyle",
    CTSecondPieSize: "{http://schemas.openxmlformats.org/drawingml/2006/chart}secondPieSize",
    CTSerAx: "{http://schemas.openxmlformats.org/drawingml/2006/chart}serAx",
    CTSerTx: "{http://schemas.openxmlformats.org/drawingml/2006/chart}tx",
    CTShape: "{http://schemas.openxmlformats.org/drawingml/2006/chart}shape",
    CTShapeProperties: "{http://schemas.openxmlformats.org/drawingml/2006/chart}spPr",
    CTSizeRepresents: "{http://schemas.openxmlformats.org/drawingml/2006/chart}sizeRepresents",
    CTSplitType: "{http://schemas.openxmlformats.org/drawingml/2006/chart}splitType",
    CTStockChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}stockChart",
    CTStrRef: "{http://schemas.openxmlformats.org/drawingml/2006/chart}strRef",
    CTStrVal: "{http://schemas.openxmlformats.org/drawingml/2006/chart}pt",
    CTStyle: "{http://schemas.openxmlformats.org/drawingml/2006/chart}style",
    CTSurface3DChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}surface3DChart",
    CTSurfaceChart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}surfaceChart",
    CTSurfaceSer: "{http://schemas.openxmlformats.org/drawingml/2006/chart}ser",
    CTTextLanguageID: "{http://schemas.openxmlformats.org/drawingml/2006/chart}lang",
    CTTickLblPos: "{http://schemas.openxmlformats.org/drawingml/2006/chart}tickLblPos",
    CTTitle: "{http://schemas.openxmlformats.org/drawingml/2006/chart}title",
    CTTrendline: "{http://schemas.openxmlformats.org/drawingml/2006/chart}trendline",
    CTTrendlineLbl: "{http://schemas.openxmlformats.org/drawingml/2006/chart}trendlineLbl",
    CTTrendlineType: "{http://schemas.openxmlformats.org/drawingml/2006/chart}trendlineType",
    CTTx: "{http://schemas.openxmlformats.org/drawingml/2006/chart}tx",
    CTUpDownBars: "{http://schemas.openxmlformats.org/drawingml/2006/chart}upDownBars",
    CTValAx: "{http://schemas.openxmlformats.org/drawingml/2006/chart}valAx",
    CTView3D: "{http://schemas.openxmlformats.org/drawingml/2006/chart}view3D",
    Chart: "{http://schemas.openxmlformats.org/drawingml/2006/chart}chart",
    ChartSpace: "{http://schemas.openxmlformats.org/drawingml/2006/chart}chartSpace",
    Delete: "{http://schemas.openxmlformats.org/drawingml/2006/chart}delete",
    ShowBubbleSize: "{http://schemas.openxmlformats.org/drawingml/2006/chart}showBubbleSize",
    ShowCatName: "{http://schemas.openxmlformats.org/drawingml/2006/chart}showCatName",
    ShowLeaderLines: "{http://schemas.openxmlformats.org/drawingml/2006/chart}showLeaderLines",
    ShowLegendKey: "{http://schemas.openxmlformats.org/drawingml/2006/chart}showLegendKey",
    ShowPercent: "{http://schemas.openxmlformats.org/drawingml/2006/chart}showPercent",
    ShowSerName: "{http://schemas.openxmlformats.org/drawingml/2006/chart}showSerName",
    ShowVal: "{http://schemas.openxmlformats.org/drawingml/2006/chart}showVal",
}

__all__ = [
    "CLASS_TO_QNAME",
    "ELEMENTS",
    "QNAME_TO_CLASS",
    "applyToEnd",
    "applyToFront",
    "applyToSides",
    "area3DChart",
    "areaChart",
    "area_ser",
    "auto",
    "autoTitleDeleted",
    "autoUpdate",
    "axId",
    "axPos",
    "backWall",
    "backward",
    "bandFmt",
    "bandFmts",
    "bar3DChart",
    "barChart",
    "barDir",
    "bar_grouping",
    "bar_ser",
    "baseTimeUnit",
    "bubble3D",
    "bubbleChart",
    "bubbleScale",
    "bubbleSize",
    "bubble_ser",
    "builtInUnit",
    "cat",
    "catAx",
    "chart",
    "chartObject",
    "chartSpace",
    "chart_chart",
    "clrMapOvr",
    "crossAx",
    "crossBetween",
    "crosses",
    "crossesAt",
    "custSplit",
    "custUnit",
    "dLbl",
    "dLblPos",
    "dLbls",
    "dPt",
    "dTable",
    "data",
    "date1904",
    "dateAx",
    "delete",
    "delete_boolean",
    "depthPercent",
    "dispBlanksAs",
    "dispEq",
    "dispRSqr",
    "dispUnits",
    "dispUnitsLbl",
    "double",
    "doughnutChart",
    "downBars",
    "dropLines",
    "errBarType",
    "errBars",
    "errDir",
    "errValType",
    "explosion",
    "ext",
    "extLst",
    "externalData",
    "firstSliceAng",
    "floor",
    "fmtId",
    "formatting",
    "forward",
    "gapDepth",
    "gapWidth",
    "grouping",
    "h",
    "hMode",
    "hPercent",
    "headerFooter",
    "hiLowLines",
    "holeSize",
    "idx",
    "intercept",
    "invertIfNegative",
    "lang",
    "layout",
    "layoutTarget",
    "lblAlgn",
    "lblOffset",
    "leaderLines",
    "legacyDrawingHF",
    "legend",
    "legendEntry",
    "legendPos",
    "line3DChart",
    "lineChart",
    "line_ser",
    "logBase",
    "lvl",
    "majorGridlines",
    "majorTickMark",
    "majorTimeUnit",
    "majorUnit",
    "manualLayout",
    "marker",
    "marker_boolean",
    "max_",
    "min_",
    "minorGridlines",
    "minorTickMark",
    "minorTimeUnit",
    "minorUnit",
    "minus",
    "multiLvlStrCache",
    "multiLvlStrRef",
    "noEndCap",
    "noMultiLvlLbl",
    "numCache",
    "numFmt",
    "numLit",
    "numRef",
    "num_val",
    "ofPieChart",
    "ofPieType",
    "order",
    "order_order",
    "orientation",
    "overlap",
    "overlay",
    "pageMargins",
    "pageSetup",
    "period",
    "perspective",
    "pictureFormat",
    "pictureOptions",
    "pictureStackUnit",
    "pie3DChart",
    "pieChart",
    "pivotFmt",
    "pivotFmts",
    "pivotSource",
    "plotArea",
    "plotVisOnly",
    "plus",
    "printSettings",
    "protection",
    "pt",
    "ptCount",
    "rAngAx",
    "radarChart",
    "radarStyle",
    "radar_ser",
    "rel_id",
    "rich",
    "rotX",
    "rotY",
    "roundedCorners",
    "scaling",
    "scatterChart",
    "scatterStyle",
    "scatter_ser",
    "secondPiePt",
    "secondPieSize",
    "selection",
    "ser",
    "serAx",
    "serLines",
    "shape",
    "showBubbleSize",
    "showCatName",
    "showDLblsOverMax",
    "showHorzBorder",
    "showKeys",
    "showLeaderLines",
    "showLegendKey",
    "showNegBubbles",
    "showOutline",
    "showPercent",
    "showSerName",
    "showVal",
    "showVertBorder",
    "sideWall",
    "size",
    "sizeRepresents",
    "smooth",
    "spPr",
    "splitPos",
    "splitType",
    "stockChart",
    "strCache",
    "strLit",
    "strRef",
    "style",
    "surface3DChart",
    "surfaceChart",
    "surface_ser",
    "symbol",
    "thickness",
    "tickLblPos",
    "tickLblSkip",
    "tickMarkSkip",
    "title",
    "trendline",
    "trendlineLbl",
    "trendlineType",
    "tx",
    "txPr",
    "tx_tx",
    "upBars",
    "upDownBars",
    "userInterface",
    "userShapes",
    "val",
    "valAx",
    "varyColors",
    "view3D",
    "w",
    "wMode",
    "wireframe",
    "x",
    "xMode",
    "xVal",
    "y",
    "yMode",
    "yVal",
]
